import type { IndustryPage } from "@/lib/backlinks/types";

export const INDUSTRY_PAGES: IndustryPage[] = [
  {
    slug: "saas",
    name: "SaaS",
    icon: "layers",
    metaTitle: "SaaS Backlinks | Link Building for Software Companies",
    metaDescription: "SaaS backlinks from software directories, review platforms, technology media and integration partners. Link building built around product-led search.",
    h1: "SaaS Backlinks for Product-Led Search Growth",
    summary: "Review platforms, tool directories, integration partners and technology editorial, combined into one programme.",
    keywords: ["saas backlinks", "software link building", "saas seo links"],
    intro: [
      "SaaS search is won on comparison, integration and alternative queries long before anyone reaches your homepage. Links need to reach those templates, not just your brand page, and they need to come from sources a software buyer would actually consult.",
      "That means working the parts of the ecosystem most teams neglect: partner directories from tools you already integrate with, category listings, developer communities, and trade publications whose readers evaluate software for a living.",
    ],
    publisherTypes: ["Software review and comparison platforms", "Category and tool directories", "Integration partner listings", "Startup and venture media", "Developer and product communities"],
    opportunities: [
      { title: "Integration partner pages", body: "Every tool you connect to may maintain a partner directory. These are relevant, usually followed and cost nothing beyond the request." },
      { title: "Comparison and alternative pages", body: "Sites publishing category comparisons often accept product submissions, putting you in front of buyers mid-evaluation." },
      { title: "Technical documentation references", body: "Developer-facing guides cite tools when explaining implementation, which produces durable contextual links." },
    ],
    anchorGuidance: "Lead with brand and product names. Software buyers search by tool name, and exact-match feature anchors from directory sources look engineered. Reserve descriptive anchors for editorial placements where the sentence supports them.",
    qualityNote: "Traffic quality matters more than volume in SaaS. A niche developer publication with 8,000 monthly readers who evaluate tooling is worth more than a general business site with 200,000 casual visitors.",
    recommendedServices: ["saas-software-backlinks", "guest-post-backlinks", "competitor-link-building", "digital-pr-backlinks"],
    faqs: [
      { question: "Should SaaS links point at the homepage or feature pages?", answer: "Mostly feature, integration and comparison pages. Those templates carry commercial intent and typically have far fewer references than the homepage, so each link moves the needle more." },
      { question: "Are review site links worth it if they are nofollow?", answer: "Yes, for traffic and category visibility rather than authority. Buyers use those platforms directly, and their listings shape how your category is described elsewhere, including in AI summaries." },
      { question: "How many links does a new SaaS product need?", answer: "There is no fixed number. What matters is closing the gap to the products currently ranking for your priority terms, which is why we start with a competitor gap analysis rather than selling a package blind." },
    ],
    reviews: [],
  },
  {
    slug: "finance",
    name: "Finance",
    icon: "wallet",
    metaTitle: "Finance Backlinks | Link Building for Financial Services",
    metaDescription: "Finance backlinks from regulated-aware publishers, trade press and comparison media. Compliance-conscious link building for financial services brands.",
    h1: "Finance Backlinks Built for a Regulated Environment",
    summary: "Placements on financial trade press and comparison media, with compliance awareness built into every brief.",
    keywords: ["finance backlinks", "financial services link building", "fintech backlinks"],
    intro: [
      "Financial search results are dominated by institutions with decades of accumulated trust, and the content bar is correspondingly high. A placement that would pass unnoticed in another sector gets scrutinised here, by editors and by readers making consequential decisions.",
      "We brief every finance placement with the regulatory context in mind: no promised returns, no advice framed as guidance unless you are authorised to give it, and clear separation between educational content and product promotion.",
    ],
    publisherTypes: ["Financial trade publications", "Personal finance and comparison media", "Accounting and tax resources", "Business and economics press", "Professional association journals"],
    opportunities: [
      { title: "Methodology and data transparency", body: "Comparison sites and journalists cite providers who publish clear scoring methodologies, which turns a compliance document into a link asset." },
      { title: "Market data commentary", body: "Finance journalists need informed comment on rate changes and regulation, and named spokespeople get quoted repeatedly." },
      { title: "Professional body listings", body: "Membership and accreditation directories carry genuine relevance and are often overlooked in favour of generic placements." },
    ],
    anchorGuidance: "Keep anchors descriptive and conservative. Exact-match commercial anchors such as product-plus-rate phrases attract scrutiny in a sector where regulators and competitors both pay attention. Brand and topic anchors carry the work.",
    qualityNote: "Publisher credibility is non-negotiable here. We decline sites that publish unattributed financial advice or accept placements from unregulated lenders, because association with those sources damages more than it helps.",
    recommendedServices: ["editorial-backlinks", "digital-pr-backlinks", "authority-backlinks", "premium-link-building"],
    faqs: [
      { question: "Can you place links for regulated financial products?", answer: "Yes, with care. We work to your compliance team's requirements, avoid performance claims, and flag any publisher whose existing content suggests weak editorial standards. Where a claim needs approval we build that step into the timeline." },
      { question: "Why is finance link building more expensive?", answer: "Because the publishers are more selective, the content requires subject expertise and often legal review, and fewer sites accept financial placements at all. Cheap finance links almost always come from sites that will accept anything." },
      { question: "Do you work with crypto or high-risk lenders?", answer: "Crypto is handled as a separate category with its own publisher set. We decline payday and unregulated lending outright, as most quality publishers will not accept those placements regardless of budget." },
    ],
    reviews: [],
  },
  {
    slug: "crypto",
    name: "Crypto",
    icon: "spark",
    metaTitle: "Crypto Backlinks | Link Building for Blockchain Projects",
    metaDescription: "Crypto backlinks from blockchain media, research publications and technology press. Careful publisher screening in a sector full of low-quality inventory.",
    h1: "Crypto Backlinks With Serious Publisher Screening",
    summary: "Placements on blockchain and technology publications that have survived more than one market cycle.",
    keywords: ["crypto backlinks", "blockchain link building", "web3 backlinks"],
    intro: [
      "Crypto has more low-quality link inventory than almost any other sector. Hundreds of sites exist purely to sell placements to token projects, and many disappear within a year, taking your links with them.",
      "Our screening is deliberately harsh here. We look for publications that were operating before the last cycle, have editorial staff rather than anonymous contributors, and cover the sector critically rather than acting as paid promotion channels.",
    ],
    publisherTypes: ["Established blockchain news publications", "Technology and fintech press", "Developer and protocol documentation", "Research and analysis platforms", "Business media covering digital assets"],
    opportunities: [
      { title: "Technical explainers", body: "Protocol and infrastructure documentation attracts durable references from developers, independent of market sentiment." },
      { title: "On-chain data analysis", body: "Original data drawn from public chains is genuinely citable and gets picked up by journalists covering market movements." },
      { title: "Regulatory commentary", body: "Informed comment on evolving rules is in constant demand and positions your team as a credible source." },
    ],
    anchorGuidance: "Favour brand and project names heavily. Token-name and exchange-listing anchors repeated across many sources form an obvious pattern, and the sector already attracts scrutiny without adding to it.",
    qualityNote: "Longevity is the key screening criterion. A publication that has operated through a full market cycle with the same editorial team is far more likely to keep your link live than one launched during the current cycle.",
    recommendedServices: ["editorial-backlinks", "digital-pr-backlinks", "premium-link-building", "brand-entity-link-building"],
    faqs: [
      { question: "Why do you reject so many crypto publishers?", answer: "Because a large share are placement farms that will not exist in eighteen months. We prioritise sites with editorial history, named staff and genuine readership, which removes most of the inventory typically offered in this sector." },
      { question: "Can you help with exchange listing announcements?", answer: "We can distribute and pitch genuine announcements, but we avoid the coordinated placement bursts common around listings. That pattern is recognisable and rarely holds value once the news cycle passes." },
      { question: "Are crypto links riskier than other sectors?", answer: "The sector itself is not the risk; the inventory quality is. Careful screening produces links that behave like any other technology placement. Bulk crypto packages are where the problems appear." },
    ],
    reviews: [],
  },
  {
    slug: "technology",
    name: "Technology",
    icon: "gauge",
    metaTitle: "Technology Backlinks | Link Building for Tech Companies",
    metaDescription: "Technology backlinks from trade press, developer publications and industry analysis sites. Link building for hardware, IT services and technology brands.",
    h1: "Technology Backlinks From Publications Engineers Read",
    summary: "Trade press, developer publications and analyst coverage across hardware, infrastructure and IT services.",
    keywords: ["technology backlinks", "tech link building", "IT services backlinks"],
    intro: [
      "Technology buyers are sceptical readers. They check sources, they notice when an article is thinly disguised promotion, and they trust a small set of publications that have earned credibility over years.",
      "Link building here works best when the content genuinely teaches something. Implementation detail, benchmark data and honest trade-off discussion get accepted by editors who reject standard marketing pitches immediately.",
    ],
    publisherTypes: ["Technology trade publications", "Developer and engineering blogs", "Industry analyst platforms", "Enterprise IT media", "Open source project documentation"],
    opportunities: [
      { title: "Benchmark and performance data", body: "Independent testing results are widely cited because so few companies publish them transparently." },
      { title: "Implementation case detail", body: "Technical write-ups explaining how something was actually built earn references from engineers solving the same problem." },
      { title: "Standards and compatibility guides", body: "Reference material on protocols and interoperability tends to accumulate links steadily for years." },
    ],
    anchorGuidance: "Technical audiences respond to descriptive anchors that say what the page covers. Product-name anchors work for brand references; keyword-stuffed commercial anchors are conspicuous in a sector where writers link precisely.",
    qualityNote: "Editorial independence is the main quality marker. Publications that review products critically carry weight; those that publish only positive coverage are recognised as promotional by the audience you are trying to reach.",
    recommendedServices: ["guest-post-backlinks", "editorial-backlinks", "resource-link-building", "saas-software-backlinks"],
    faqs: [
      { question: "Will technical publications accept vendor content?", answer: "Many will, provided it teaches rather than sells. The fastest rejection is a piece that mentions your product in every section. We write around the problem and reference the product once, where it genuinely belongs." },
      { question: "Do open source references count as backlinks?", answer: "They do, and they are often overlooked. Documentation, README files and project wikis frequently link to tools and guides, and those references are durable and highly relevant." },
      { question: "Which pages should technology links point to?", answer: "Documentation, technical guides and solution pages generally outperform the homepage. Those are the pages engineers actually need, which makes the link look natural to both readers and search engines." },
    ],
    reviews: [],
  },
  {
    slug: "gaming",
    name: "Gaming",
    icon: "play",
    metaTitle: "Gaming Backlinks | Link Building for Games and Esports",
    metaDescription: "Gaming backlinks from games media, esports coverage and community publications. Link building for studios, platforms and gaming brands.",
    h1: "Gaming Backlinks From Media Players Actually Read",
    summary: "Games media, esports outlets and community publications with genuinely engaged audiences.",
    keywords: ["gaming backlinks", "games media link building", "esports backlinks"],
    intro: [
      "Gaming audiences detect marketing instantly and react badly to it. Coverage has to come from writers who understand the space, on outlets readers already trust, or the placement generates hostility rather than interest.",
      "The upside is that gaming media covers a huge volume of stories and is unusually open to data, community trends and behind-the-scenes development detail.",
    ],
    publisherTypes: ["Games news and review outlets", "Esports and competitive coverage", "Game development publications", "Streaming and creator media", "Community and fan platforms"],
    opportunities: [
      { title: "Player behaviour data", body: "Aggregate statistics about how people actually play are reliably covered because studios rarely release them." },
      { title: "Development process stories", body: "Technical and design write-ups from developers get strong engagement and are cited by other studios." },
      { title: "Esports and tournament coverage", body: "Sponsorships and event participation produce natural references from competitive coverage." },
    ],
    anchorGuidance: "Game titles and studio names dominate naturally. Commercial anchors around purchase terms look out of place in editorial gaming coverage, where writers link to store pages and press kits by name.",
    qualityNote: "Check whether an outlet has an engaged audience or simply high traffic from aggregation. Community response is a better quality signal in gaming than raw visitor numbers.",
    recommendedServices: ["digital-pr-backlinks", "guest-post-backlinks", "forum-community-backlinks", "image-infographic-link-building"],
    faqs: [
      { question: "Do gaming outlets accept sponsored content?", answer: "Some do and label it clearly, which is fine when the content is genuinely interesting. Others accept only editorial pitches. We separate the two so you know what you are buying and how it will be presented to readers." },
      { question: "How important are community platforms?", answer: "Very, for reach and sentiment, though many apply nofollow. We treat them as audience channels first and link sources second, and we never post promotional material in communities that prohibit it." },
      { question: "What works best for indie studios with small budgets?", answer: "Development stories and data. They cost nothing beyond your team's time to explain, and gaming press covers them readily because most studios never share that detail." },
    ],
    reviews: [],
  },
  {
    slug: "travel",
    name: "Travel",
    icon: "globe",
    metaTitle: "Travel Backlinks | Link Building for Travel Brands",
    metaDescription: "Travel backlinks from destination media, travel blogs and tourism resources. Seasonal link building for hotels, tour operators and booking platforms.",
    h1: "Travel Backlinks Across Destination and Tourism Media",
    summary: "Destination guides, travel publications and tourism bodies, planned around booking seasonality.",
    keywords: ["travel backlinks", "tourism link building", "destination backlinks"],
    intro: [
      "Travel search runs on a calendar. Interest in a destination builds months before the season, which means links need to be live well before the traffic arrives, not during it.",
      "The sector also has an unusually rich set of legitimate link sources: tourism boards, regional guides, transport resources and a large community of independent travel writers who genuinely want good material.",
    ],
    publisherTypes: ["Destination and city guides", "Independent travel publications", "Tourism boards and regional bodies", "Transport and logistics resources", "Accommodation and review platforms"],
    opportunities: [
      { title: "Practical destination guides", body: "Detailed local information gets referenced by other travel writers for years, particularly transport and seasonal timing detail." },
      { title: "Tourism board partnerships", body: "Regional tourism organisations maintain operator listings and partner pages that are relevant and rarely claimed." },
      { title: "Seasonal data stories", body: "Booking trends, pricing patterns and weather-linked demand data get picked up reliably by travel desks." },
    ],
    anchorGuidance: "Destination and brand anchors read naturally; commercial booking anchors repeated across guides do not. Point links at destination and experience pages rather than checkout templates.",
    qualityNote: "Many travel sites accept any placement for a fee and host large volumes of unrelated commercial content. We screen for genuine editorial focus and whether the site's traffic is concentrated in real destination content.",
    recommendedServices: ["guest-post-backlinks", "local-backlinks", "digital-pr-backlinks", "image-infographic-link-building"],
    faqs: [
      { question: "When should travel link building start?", answer: "Three to six months before your booking season. Links need time to be discovered and to influence rankings, and arriving during peak season means competing for attention you should already have earned." },
      { question: "Are travel blogger placements worth it?", answer: "The good ones are. An independent writer with a loyal readership in your destination is valuable; a blog that publishes fifteen sponsored posts a month is not. The difference is visible in their archive." },
      { question: "Can you get tourism board links?", answer: "Often, if you operate legitimately in the region. Many boards maintain operator directories with a formal application process that most businesses never complete." },
    ],
    reviews: [],
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    icon: "pin",
    metaTitle: "Real Estate Backlinks | Property Link Building",
    metaDescription: "Real estate backlinks from property media, regional press and local resources. Location-focused link building for agents, developers and property platforms.",
    h1: "Real Estate Backlinks Anchored to Location",
    summary: "Property media, regional press and local institutional sources tied to the areas you actually serve.",
    keywords: ["real estate backlinks", "property link building", "estate agent backlinks"],
    intro: [
      "Property search is inherently local. Someone searching for homes in a specific district is not served by a national link with a city keyword attached, and search engines have become good at telling the difference.",
      "Effective property link building concentrates on sources rooted in the area: regional newspapers, local business groups, community organisations and property publications that cover specific markets rather than the country as a whole.",
    ],
    publisherTypes: ["Property and housing publications", "Regional newspapers and city media", "Local business and community organisations", "Mortgage and finance resources", "Architecture and development media"],
    opportunities: [
      { title: "Local market data", body: "Price and transaction trends for specific areas are covered reliably by regional press because national data misses local nuance." },
      { title: "Neighbourhood guides", body: "Detailed area guides earn references from relocation resources, schools and employers in the region." },
      { title: "Development and planning coverage", body: "New projects generate legitimate local news interest well before completion." },
    ],
    anchorGuidance: "Combine brand with location naturally. Repeating a commercial phrase such as a property-type-plus-city keyword across many regional sources is one of the most recognisable patterns in this sector.",
    qualityNote: "Prioritise sources with genuine local footprint over national property portals that offer paid placements. A regional paper's property section carries more relevance for a city-level query than a national directory page.",
    recommendedServices: ["local-backlinks", "citation-directory-backlinks", "press-release-news-backlinks", "guest-post-backlinks"],
    faqs: [
      { question: "Should links point to listing pages?", answer: "Rarely, because individual listings expire and the link dies with them. Point to area guides, market reports and service pages that remain live, then link internally to current listings from there." },
      { question: "How do we build links for multiple branches?", answer: "Each branch gets its own local prospect set and its own landing page target. Sending every regional link to one head office page wastes the geographic signal entirely." },
      { question: "Is local press realistically reachable?", answer: "Yes, more than most sectors, because regional newsrooms cover property closely and are short of data. Local transaction analysis is usually enough to open the conversation." },
    ],
    reviews: [],
  },
  {
    slug: "automotive",
    name: "Automotive",
    icon: "compass",
    metaTitle: "Automotive Backlinks | Link Building for Car and EV Brands",
    metaDescription: "Automotive backlinks from motoring media, EV publications and trade resources. Link building for dealerships, manufacturers and automotive services.",
    h1: "Automotive Backlinks Across Motoring and EV Media",
    summary: "Motoring publications, EV specialists and trade resources covering manufacturers, dealers and services.",
    keywords: ["automotive backlinks", "car dealership link building", "EV backlinks"],
    intro: [
      "Automotive covers two quite different search worlds: national interest in vehicles and reviews, and intensely local interest in where to buy or service one. A single link strategy rarely serves both well.",
      "We split the work accordingly, pairing motoring and EV publications for brand-level authority with regional sources for dealership and service visibility.",
    ],
    publisherTypes: ["Motoring news and review publications", "Electric vehicle specialist media", "Automotive trade and fleet resources", "Regional motoring and classifieds", "Insurance and finance comparison sites"],
    opportunities: [
      { title: "Ownership cost analysis", body: "Real running-cost and depreciation data is widely cited because manufacturer figures are treated with suspicion." },
      { title: "EV infrastructure content", body: "Charging, range and grid content attracts steady references as the transition continues." },
      { title: "Maintenance and technical guides", body: "Practical repair and servicing information earns links from forums and owner communities." },
    ],
    anchorGuidance: "Model names and brand terms dominate naturally in motoring coverage. For dealerships, combine brand with location rather than repeating purchase-intent keywords.",
    qualityNote: "Motoring has a large network of sites that exist to sell placements around vehicle keywords. Check whether a publication runs genuine reviews with named journalists or simply republishes manufacturer material.",
    recommendedServices: ["guest-post-backlinks", "local-backlinks", "digital-pr-backlinks", "competitor-link-building"],
    faqs: [
      { question: "Do dealerships need national links?", answer: "Some, for overall domain credibility, but the majority of value comes from regional sources. A link from a national motoring title helps the brand; a link from the local paper helps the showroom." },
      { question: "Is EV content a genuine opportunity?", answer: "Yes. Editorial demand still outstrips supply on charging infrastructure, real-world range and grid impact, and well-researched content is accepted readily." },
      { question: "What about owner forums?", answer: "Valuable for referral traffic and community credibility, provided contributions are genuinely helpful. Automotive forums are among the most hostile to obvious marketing, so restraint matters." },
    ],
    reviews: [],
  },
  {
    slug: "ecommerce",
    name: "E-commerce",
    icon: "wallet",
    metaTitle: "E-commerce Backlinks | Link Building for Online Stores",
    metaDescription: "E-commerce backlinks from product media, gift guides and review publications. Category-focused link building for online retailers and marketplaces.",
    h1: "E-commerce Backlinks That Reach Category Pages",
    summary: "Product media, gift guides and buying advice, directed at the category pages that actually convert.",
    keywords: ["ecommerce backlinks", "online store link building", "product page backlinks"],
    intro: [
      "The hardest problem in retail link building is that nobody wants to link to a product page. Editorial sources link to guides, comparisons and roundups, which is why so many stores end up with links pointing only at their homepage.",
      "We solve that by building links to category and buying-guide templates, then using internal linking to pass that value to the products that need it. Gift guides and seasonal roundups provide the editorial route in.",
    ],
    publisherTypes: ["Product review and buying guide media", "Lifestyle and consumer publications", "Gift guide and seasonal roundups", "Deal and comparison platforms", "Niche enthusiast blogs"],
    opportunities: [
      { title: "Seasonal gift guides", body: "Editors assemble these months ahead and actively seek products to feature, making them one of the most reliable retail link routes." },
      { title: "Buying guides on your own site", body: "A genuinely useful category guide is linkable in a way a product listing never is." },
      { title: "Materials and sourcing transparency", body: "Detail about how products are made attracts references from sustainability and consumer advice writers." },
    ],
    anchorGuidance: "Use brand and category descriptors. Product-name anchors are fine in roundups where the writer names the item. Avoid repeating exact commercial phrases such as buy-plus-product across multiple sources.",
    qualityNote: "Be wary of coupon and deal sites offering paid placements at volume; many carry little editorial weight and large outbound link counts. A single genuine roundup placement typically outperforms dozens of them.",
    recommendedServices: ["guest-post-backlinks", "image-infographic-link-building", "digital-pr-backlinks", "monthly-link-building"],
    faqs: [
      { question: "How do we get links to product pages?", answer: "Usually indirectly. Editorial sources link to guides and roundups, so we target those templates and strengthen products through internal linking. Direct product-page links mainly come from gift guides and reviews." },
      { question: "When should seasonal outreach begin?", answer: "Gift guide pitching starts three to four months before the season. Editors finalise selections early, and approaching them in the same month the content publishes is far too late." },
      { question: "Are affiliate roundups useful?", answer: "They send buyers and often carry followed links, but they are commercial placements rather than editorial endorsements. We balance them with genuine editorial coverage rather than relying on them." },
    ],
    reviews: [],
  },
  {
    slug: "fashion",
    name: "Fashion",
    icon: "badge",
    metaTitle: "Fashion Backlinks | Link Building for Fashion Brands",
    metaDescription: "Fashion backlinks from style publications, sustainability media and editorial roundups. Visual-led link building for clothing and accessory brands.",
    h1: "Fashion Backlinks Through Editorial and Visual Coverage",
    summary: "Style publications, sustainability media and seasonal editorial, supported by strong visual assets.",
    keywords: ["fashion backlinks", "clothing brand link building", "style media backlinks"],
    intro: [
      "Fashion coverage is driven by imagery and narrative. Editors need visuals they can publish and a story that fits the season, the trend cycle or a wider cultural conversation.",
      "That makes photography and provenance unusually valuable as link assets. Brands with strong imagery and a genuine story about materials or manufacturing have far more to work with than those relying on product descriptions.",
    ],
    publisherTypes: ["Fashion and style publications", "Sustainability and ethical consumer media", "Lifestyle and culture magazines", "Independent style blogs", "Retail trade press"],
    opportunities: [
      { title: "Supply chain transparency", body: "Detailed sourcing and manufacturing information is in demand from sustainability writers and difficult for competitors to fake." },
      { title: "Seasonal editorial features", body: "Trend roundups need products and imagery, and editors work to schedules that reward early contact." },
      { title: "Image attribution recovery", body: "Fashion photography is reused constantly without credit, making attribution recovery particularly productive here." },
    ],
    anchorGuidance: "Brand names carry fashion coverage almost entirely. Descriptive anchors work in sustainability and materials contexts. Commercial anchors look obviously placed in editorial style writing.",
    qualityNote: "Distinguish genuine style publications from sites that publish paid product roundups exclusively. Readership engagement and editorial voice are better indicators than domain metrics in this sector.",
    recommendedServices: ["image-infographic-link-building", "digital-pr-backlinks", "guest-post-backlinks", "brand-entity-link-building"],
    faqs: [
      { question: "Why is image attribution so effective for fashion?", answer: "Because product and campaign photography is widely republished by blogs and smaller publications without credit. A polite attribution request converts a substantial share of those uses into links at very low cost." },
      { question: "Do we need a sustainability angle?", answer: "Not necessarily, but if you have genuine provenance detail it is one of the strongest available angles, because editors covering the topic struggle to find brands willing to share specifics." },
      { question: "How far ahead do fashion editors plan?", answer: "Typically two to four months for seasonal features, longer for print. Outreach timed to the season itself has already missed the window." },
    ],
    reviews: [],
  },
  {
    slug: "education",
    name: "Education",
    icon: "document",
    metaTitle: "Education Backlinks | Link Building for Education Providers",
    metaDescription: "Education backlinks from academic resources, teaching publications and institutional guides. Resource-led link building for schools, courses and edtech.",
    h1: "Education Backlinks Built on Genuinely Useful Resources",
    summary: "Institutional guides, teaching publications and academic resources that reference material worth using.",
    keywords: ["education backlinks", "edtech link building", "academic resource links"],
    intro: [
      "Education has the strongest resource-link culture of any sector. Librarians, teachers and course leaders maintain curated lists and actively look for material worth adding to them.",
      "The requirement is simply that your resource is genuinely useful without a purchase. Free tools, lesson material, research summaries and accessible explainers get listed; course sales pages do not.",
    ],
    publisherTypes: ["University library and subject guides", "Teaching and pedagogy publications", "Academic and research platforms", "Education technology media", "Parent and student advice resources"],
    opportunities: [
      { title: "Free teaching materials", body: "Lesson plans, worksheets and classroom tools get shared between educators and added to institutional lists repeatedly." },
      { title: "Research summaries", body: "Plain-language summaries of academic work are referenced by both students and journalists covering education." },
      { title: "Accessibility resources", body: "Material supporting learners with additional needs is actively sought and under-supplied." },
    ],
    anchorGuidance: "Institutions choose their own anchor text, usually the resource title. Requesting specific anchors is inappropriate and undermines credibility with curators, so we do not ask.",
    qualityNote: "Judge institutional pages on maintenance and reachability, not the domain extension. An actively curated library guide is valuable; a forgotten page on the same university domain is not.",
    recommendedServices: ["edu-gov-resource-links", "resource-link-building", "broken-link-building", "guest-post-backlinks"],
    faqs: [
      { question: "Does our course page count as a resource?", answer: "Almost never. Curators list material students can use immediately without paying. A free tool, guide or dataset connected to your subject is the realistic route, with the course linked from it." },
      { question: "How long does education outreach take?", answer: "Longer than commercial outreach. Academic and institutional staff respond on their own schedule, often three to six weeks. Campaigns here are planned across a term rather than a month." },
      { question: "Is edtech treated differently?", answer: "Somewhat. Edtech products can appear in teaching technology roundups and review platforms as well as resource lists, which gives more routes than a traditional education provider has." },
    ],
    reviews: [],
  },
  {
    slug: "legal",
    name: "Legal",
    icon: "shield",
    metaTitle: "Legal Backlinks | Link Building for Law Firms",
    metaDescription: "Legal backlinks from law publications, professional directories and regional press. Compliance-aware link building for firms and legal services.",
    h1: "Legal Backlinks With Professional Standards in Mind",
    summary: "Law publications, professional bodies and regional press, briefed with professional conduct rules in mind.",
    keywords: ["legal backlinks", "law firm link building", "attorney backlinks"],
    intro: [
      "Legal marketing operates under professional conduct rules that vary by jurisdiction. Claims about outcomes, comparative superiority and specialisation are restricted in many regions, and publishers in this space know it.",
      "We write to those constraints from the outset. Content explains the law clearly without promising results, and placements favour professional publications and regional press over generic guest post inventory.",
    ],
    publisherTypes: ["Legal trade publications", "Bar association and professional directories", "Regional business and news press", "Consumer rights and advice resources", "Academic law commentary"],
    opportunities: [
      { title: "Legislative change commentary", body: "Journalists need practitioners who can explain new rules quickly, and those quotes are consistently attributed." },
      { title: "Plain-language legal guides", body: "Accessible explanations of common processes earn references from advice organisations and community resources." },
      { title: "Professional body listings", body: "Association and accreditation directories carry genuine relevance and verify practising status." },
    ],
    anchorGuidance: "Firm name and descriptive practice-area anchors only. Exact-match commercial anchors combining service and city across many sources are conspicuous and may conflict with advertising rules in some jurisdictions.",
    qualityNote: "Avoid legal directories that accept any listing for payment and host large volumes of unrelated content. Professional bodies, genuine trade press and regional news carry the credibility that matters here.",
    recommendedServices: ["local-backlinks", "editorial-backlinks", "citation-directory-backlinks", "press-release-news-backlinks"],
    faqs: [
      { question: "Can you work within advertising rules for law firms?", answer: "Yes. We brief content to avoid outcome claims and comparative superiority statements, and we submit drafts for your compliance review before publication. Rules differ by jurisdiction, so we work to yours specifically." },
      { question: "Are legal directories worth paying for?", answer: "Professional bodies and accreditation directories, yes. Generic paid legal directories that list any firm willing to pay, generally not. The distinction is whether inclusion requires verification." },
      { question: "What is the strongest angle for a small firm?", answer: "Local expertise and legislative commentary. Regional journalists need practitioners who will explain a change in plain terms on a deadline, and that access is genuinely valuable to them." },
    ],
    reviews: [],
  },
  {
    slug: "business",
    name: "Business",
    icon: "chart",
    metaTitle: "Business Backlinks | B2B Link Building Services",
    metaDescription: "Business backlinks from B2B publications, trade press and professional resources. Link building for consultancies, agencies and business service providers.",
    h1: "B2B Business Backlinks From Trade and Professional Media",
    summary: "Business publications, trade press and professional resources reaching decision-makers rather than consumers.",
    keywords: ["business backlinks", "B2B link building", "corporate backlinks"],
    intro: [
      "B2B audiences are small, specific and reachable. You are not trying to attract general interest; you are trying to appear in front of a few thousand people who make purchasing decisions in your category.",
      "That changes the calculation entirely. A trade publication with modest traffic but the right readership outperforms a large general business site, and we prioritise accordingly.",
    ],
    publisherTypes: ["Industry trade publications", "Business and management media", "Professional association resources", "Consultancy and research platforms", "Regional business press"],
    opportunities: [
      { title: "Sector benchmark data", body: "Operational and salary benchmarks are consistently cited because few companies publish them openly." },
      { title: "Practitioner commentary", body: "Trade editors need working professionals who can explain sector developments credibly." },
      { title: "Association membership", body: "Trade body directories provide relevant, verified links that generic directories cannot match." },
    ],
    anchorGuidance: "Company name and descriptive service anchors. B2B editorial rarely uses commercial phrasing, so exact-match anchors stand out immediately in this context.",
    qualityNote: "Readership relevance beats traffic volume. Ask whether the publication's audience contains your buyers; if not, a high metric score is irrelevant to your commercial outcome.",
    recommendedServices: ["editorial-backlinks", "guest-post-backlinks", "brand-entity-link-building", "monthly-link-building"],
    faqs: [
      { question: "Is a small trade publication worth the same as a big business site?", answer: "For commercial outcomes, often more. Two thousand readers who all work in your sector are worth more than two hundred thousand general visitors, and the topical relevance is far stronger." },
      { question: "What content works for B2B placements?", answer: "Operational detail and data. Trade editors reject strategy platitudes but accept practical material about how something is actually done, particularly with numbers attached." },
      { question: "How do we compete with larger consultancies?", answer: "By being more specific. Large firms publish general thought leadership; a focused practitioner view on a narrow problem is easier to place and more useful to readers." },
    ],
    reviews: [],
  },
  {
    slug: "marketing",
    name: "Marketing",
    icon: "megaphone",
    metaTitle: "Marketing Backlinks | Link Building for Marketing Agencies",
    metaDescription: "Marketing backlinks from industry publications, agency resources and practitioner media. Link building for agencies, martech and marketing consultants.",
    h1: "Marketing Backlinks in a Sector That Recognises Tactics",
    summary: "Industry publications and practitioner media where readers are marketers themselves and notice weak content.",
    keywords: ["marketing backlinks", "agency link building", "martech backlinks"],
    intro: [
      "Marketing is the hardest sector to place content in, because every reader does this for a living. Thin articles get called out publicly, and editors are unusually strict as a result.",
      "What works is original data and genuinely contrarian experience. Campaign results, test outcomes and honest accounts of what failed get accepted where generic best-practice pieces are rejected immediately.",
    ],
    publisherTypes: ["Marketing industry publications", "Practitioner blogs and newsletters", "Martech review platforms", "Advertising and media trade press", "Professional marketing associations"],
    opportunities: [
      { title: "Campaign result transparency", body: "Actual numbers from real campaigns, including the disappointing ones, are rare and widely shared." },
      { title: "Original industry research", body: "Surveys of practitioners get cited for years because so much sector commentary is opinion without data." },
      { title: "Tool testing and comparison", body: "Independent hands-on evaluations earn references from buyers and from the vendors themselves." },
    ],
    anchorGuidance: "Brand and descriptive anchors. This is the one sector where readers will actively notice an over-optimised anchor and mention it, so restraint protects credibility as well as the profile.",
    qualityNote: "Assess whether a marketing publication has genuine practitioner readership or exists primarily to sell guest posts to other agencies. The comment activity and author roster usually reveal it quickly.",
    recommendedServices: ["editorial-backlinks", "digital-pr-backlinks", "guest-post-backlinks", "competitor-link-building"],
    faqs: [
      { question: "Why is marketing so competitive for placements?", answer: "Because every agency is pitching the same publications with similar content. The way through is data or genuine experience, not another article restating well-known principles." },
      { question: "Should agencies build links to their own site?", answer: "Yes, and many neglect it entirely while serving clients. Your own profile is the strongest proof of capability a prospect can check, and they do check." },
      { question: "Do case studies work as link assets?", answer: "Only with real numbers and enough methodological detail to be credible. Vague success stories without figures get ignored by editors and prospects alike." },
    ],
    reviews: [],
  },
  {
    slug: "health",
    name: "Health",
    icon: "shield",
    metaTitle: "Health Backlinks | Link Building for Health and Medical Sites",
    metaDescription: "Health backlinks from medical publications, wellness media and health resources. Evidence-led link building with appropriate review for health content.",
    h1: "Health Backlinks Built on Evidence and Review",
    summary: "Medical publications, health resources and wellness media, with evidence standards applied to every placement.",
    keywords: ["health backlinks", "medical link building", "healthcare backlinks"],
    intro: [
      "Health content affects decisions people make about their wellbeing, and both publishers and search engines treat it accordingly. Sources are checked, author credentials matter, and unsupported claims are rejected outright.",
      "Every health placement we produce is written against cited evidence and, where the subject requires it, reviewed by a qualified professional before submission. That slows the process and it is the only responsible way to work in this sector.",
    ],
    publisherTypes: ["Medical and clinical publications", "Health information platforms", "Wellness and nutrition media", "Professional healthcare associations", "Patient advocacy organisations"],
    opportunities: [
      { title: "Clinically reviewed explainers", body: "Accurate, accessible condition and treatment information earns references from patient organisations and health resources." },
      { title: "Practitioner commentary", body: "Qualified professionals willing to comment on health stories are in constant demand from journalists." },
      { title: "Public health data", body: "Anonymised service data and outcome statistics are cited readily where methodology is transparent." },
    ],
    anchorGuidance: "Descriptive, clinical language rather than commercial phrasing. Treatment-plus-location keyword anchors repeated across sources are inappropriate in a sector where accuracy signals matter most.",
    qualityNote: "Publisher standards are the main screen. Sites publishing unsupported health claims or promoting unproven treatments are excluded entirely, regardless of their metrics, because association with them carries real risk.",
    recommendedServices: ["editorial-backlinks", "authority-backlinks", "edu-gov-resource-links", "premium-link-building"],
    faqs: [
      { question: "Do health articles need medical review?", answer: "For anything clinical, yes. We arrange qualified review before submission because reputable publishers require it and because publishing unreviewed health guidance is irresponsible regardless of SEO considerations." },
      { question: "Can you work with supplement or wellness brands?", answer: "Where claims are evidence-supported and legally compliant in your market, yes. We decline work promoting unproven treatments, and reputable health publishers would reject those placements anyway." },
      { question: "Why are health placements more expensive?", answer: "Because of the review step, the writer expertise required and the smaller pool of publishers that meet the standard. Cheap health links almost always come from sites that publish anything." },
    ],
    reviews: [],
  },
  {
    slug: "fitness",
    name: "Fitness",
    icon: "target",
    metaTitle: "Fitness Backlinks | Link Building for Fitness Brands",
    metaDescription: "Fitness backlinks from training publications, sports media and coaching resources. Evidence-aware link building for gyms, coaches and fitness products.",
    h1: "Fitness Backlinks Across Training and Sports Media",
    summary: "Training publications, coaching resources and sports media, with claims kept to what evidence supports.",
    keywords: ["fitness backlinks", "gym link building", "sports nutrition backlinks"],
    intro: [
      "Fitness sits between health and lifestyle. Training and nutrition claims attract the same scrutiny as medical content, while the audience engages more like a consumer market, driven by community and results.",
      "We work both sides: evidence-supported content for publications that check sources, and practical training material for coaching and community outlets where credibility is earned through usefulness.",
    ],
    publisherTypes: ["Training and strength publications", "Sports science resources", "Nutrition and supplement media", "Coaching and certification bodies", "Community and club platforms"],
    opportunities: [
      { title: "Programming and technique content", body: "Detailed training material from qualified coaches is referenced widely and keeps earning links over time." },
      { title: "Participation and performance data", body: "Aggregate member or athlete data makes strong stories for sports desks and fitness media." },
      { title: "Certification and club directories", body: "Professional bodies and club listings provide relevant, verified references for coaches and facilities." },
    ],
    anchorGuidance: "Descriptive training terminology and brand names. Avoid repeated commercial anchors around purchase or supplement keywords, which are heavily used by low-quality operators in this space.",
    qualityNote: "The sector contains a large volume of sites publishing unsupported supplement and transformation claims. We screen those out because proximity to them damages credibility with both readers and reviewers.",
    recommendedServices: ["guest-post-backlinks", "local-backlinks", "digital-pr-backlinks", "forum-community-backlinks"],
    faqs: [
      { question: "Are supplement claims a problem for placements?", answer: "They can be. Reputable publishers reject unsupported performance claims, and advertising regulators take an interest. We write to what the evidence supports, which usually improves acceptance rates as well as compliance." },
      { question: "What works for a single-location gym?", answer: "Local sources and community involvement. Regional press, club listings, event sponsorship and coaching directories outperform national fitness placements for a business serving one catchment area." },
      { question: "Is athlete or member data usable?", answer: "Yes, when properly anonymised and aggregated. Participation trends and performance patterns make genuinely interesting stories that fitness and sports desks cover readily." },
    ],
    reviews: [],
  },
  {
    slug: "food",
    name: "Food",
    icon: "spark",
    metaTitle: "Food Backlinks | Link Building for Food and Drink Brands",
    metaDescription: "Food backlinks from culinary publications, recipe platforms and hospitality media. Visual and seasonal link building for food and beverage brands.",
    h1: "Food and Drink Backlinks Through Culinary Media",
    summary: "Recipe platforms, culinary publications and hospitality media, supported by strong photography and seasonality.",
    keywords: ["food backlinks", "restaurant link building", "beverage brand backlinks"],
    intro: [
      "Food content is visual, seasonal and endlessly republished. Recipes get shared, adapted and cited, and photography circulates widely, which creates both link opportunities and uncredited use worth recovering.",
      "For hospitality businesses the picture shifts local: reviews, regional guides and event listings matter far more than national food media.",
    ],
    publisherTypes: ["Recipe and culinary platforms", "Food and drink publications", "Hospitality trade media", "Regional dining guides", "Producer and sourcing directories"],
    opportunities: [
      { title: "Original recipes and methods", body: "Well-tested recipes with proper photography get cited and adapted by other food writers continuously." },
      { title: "Sourcing and producer stories", body: "Provenance detail attracts coverage from food writers and sustainability-focused publications alike." },
      { title: "Seasonal and event content", body: "Food media plans around seasons and festivals, creating predictable windows for well-timed outreach." },
    ],
    anchorGuidance: "Brand, dish and ingredient names read naturally. For restaurants, brand plus location. Avoid commercial booking anchors repeated across dining guides.",
    qualityNote: "Recipe aggregators that republish content at scale carry little editorial weight. Prioritise publications with original photography, named writers and genuine testing behind their content.",
    recommendedServices: ["image-infographic-link-building", "local-backlinks", "guest-post-backlinks", "citation-directory-backlinks"],
    faqs: [
      { question: "How do restaurants build links?", answer: "Locally, mostly. Regional dining guides, event listings, supplier pages, local press and community involvement outperform national food publications for a business serving one city." },
      { question: "Is food photography a link asset?", answer: "One of the strongest. Food images are reused constantly without credit, so attribution recovery is unusually productive, and offering images for editorial use opens doors that text pitches do not." },
      { question: "Do recipe links still carry value?", answer: "Yes, when the recipe is genuinely original and tested. Republished aggregator content does not, but a properly developed recipe with original photography gets cited by writers for years." },
    ],
    reviews: [],
  },
  {
    slug: "home-garden",
    name: "Home & Garden",
    icon: "pin",
    metaTitle: "Home & Garden Backlinks | Link Building for Home Brands",
    metaDescription: "Home and garden backlinks from interiors media, DIY resources and trade publications. Seasonal, visual link building for home improvement and garden brands.",
    h1: "Home and Garden Backlinks From Interiors and DIY Media",
    summary: "Interiors publications, DIY resources and trade media, planned around strong seasonal demand cycles.",
    keywords: ["home improvement backlinks", "garden link building", "interiors backlinks"],
    intro: [
      "Home and garden search follows the weather and the calendar. Interest in specific projects rises and falls predictably, so links need to be established before each season rather than during it.",
      "The sector is also strongly visual and instructional. Clear project guides and before-and-after imagery get referenced by interiors publications and DIY communities that constantly need illustrative material.",
    ],
    publisherTypes: ["Interiors and design publications", "DIY and home improvement resources", "Gardening and horticulture media", "Trade and building publications", "Regional property and lifestyle press"],
    opportunities: [
      { title: "Project guides with real photography", body: "Step-by-step material illustrated with genuine project images is referenced by writers who lack their own visuals." },
      { title: "Cost and material data", body: "Renovation and landscaping cost breakdowns are cited constantly because homeowners search for them and publishers rarely have current figures." },
      { title: "Seasonal maintenance content", body: "Predictable annual demand creates reliable windows for planned outreach." },
    ],
    anchorGuidance: "Descriptive project and material anchors work naturally. Installer and service businesses should combine brand with location rather than repeating service-plus-city keywords across sources.",
    qualityNote: "Distinguish genuine interiors and DIY publications from content farms producing high volumes of thin project articles. Original photography and named contributors are the clearest indicators.",
    recommendedServices: ["image-infographic-link-building", "guest-post-backlinks", "local-backlinks", "monthly-link-building"],
    faqs: [
      { question: "When should seasonal outreach start?", answer: "Two to three months before demand rises. Garden content pitched in spring is late; interiors features for autumn are planned in summer. Publishers work ahead and reward those who do the same." },
      { question: "Do trade publications matter for consumer brands?", answer: "More than most expect. Builders, landscapers and installers influence purchasing decisions, and trade titles are far less crowded with marketing pitches than consumer media." },
      { question: "What is the strongest asset in this sector?", answer: "Real project photography with cost and material detail attached. Publishers need images and homeowners need numbers, and very few brands supply both together." },
    ],
    reviews: [],
  },
];
