import type { BacklinkService } from "@/lib/backlinks/types";

export const SERVICES_A: BacklinkService[] = [
  {
    slug: "guest-post-backlinks",
    group: "Placement Services",
    nav: "Guest Post Backlinks",
    icon: "quill",
    accent: "brand",
    h1: "Guest Post Backlinks on Publications That Actually Publish",
    metaTitle: "Guest Post Backlinks | Niche-Relevant Editorial Placements",
    metaDescription:
      "Order niche-relevant guest post backlinks on screened publications. Original articles, editorial approval, dofollow in-content links and full URL reporting.",
    summary:
      "Original articles placed on vetted blogs and magazines in your niche, with the link sitting naturally inside the body copy.",
    keywords: ["guest post backlinks", "niche relevant guest posts", "dofollow guest posts", "sponsored guest posts", "permanent guest posts"],
    variants: [
      "High authority guest posts",
      "Niche relevant guest posts",
      "DoFollow guest posts",
      "Permanent guest posts",
      "Editorial guest posts",
      "Sponsored guest posts",
      "Multi-niche guest posts",
    ],
    intro: [
      "A guest post backlink is earned by writing something a publication wants to put in front of its readers. We research sites that already cover your subject, agree a topic with the editor, write the article to their brief, and place one contextual link to the page you are trying to grow.",
      "Every site we pitch is checked by hand before it reaches your shortlist. We look at whether organic traffic is spread across the archive or trapped in two old posts, whether the outbound linking pattern looks editorial or commercial, and whether a real person is running the publishing calendar. Sites that fail those checks are removed, not quietly discounted.",
    ],
    included: [
      "Prospect shortlist with organic traffic, authority and topical-fit notes",
      "Topic pitching and editorial approval before writing begins",
      "Original article written for the publisher's audience, 900–1,600 words",
      "One contextual in-content link to your chosen target URL",
      "Anchor text recommendation based on your current link profile",
      "Live URL log, publication date and post-indexing check",
    ],
    benefits: [
      { title: "Relevance decides the value", body: "A mid-authority site that covers your exact subject usually moves rankings more reliably than a large general blog with no topical connection to your product." },
      { title: "You keep editorial control", body: "You approve the topic, the angle and the anchor before anything is submitted, so the article supports your positioning rather than contradicting it." },
      { title: "Content that earns its place", body: "Articles are written to be genuinely readable. Publishers keep them live because they serve their audience, not because of a contract clause." },
      { title: "No mystery inventory", body: "You see the domain before you pay. There are no blind bundles where the sites are revealed only after the invoice clears." },
    ],
    process: [
      { title: "Brief and target mapping", body: "You share the URL you want to strengthen, your market and any sites to avoid. We map the anchor and destination before prospecting." },
      { title: "Manual prospecting", body: "We build a shortlist from publications already ranking for related topics, then verify traffic patterns, editorial history and outbound behaviour." },
      { title: "Pitch and approval", body: "Topics are agreed with each editor first. You approve the shortlist and the proposed angles before a single word is written." },
      { title: "Write, place, report", body: "Our writers produce the draft, the editor publishes it, and the live URL lands in your workspace with its metrics and date." },
    ],
    placement: "Links are placed inside the body of the article, surrounded by text that explains why the reference is useful. We avoid author bios, footers and sidebars because those positions carry far less weight and are the first thing a publisher strips during a cleanup.",
    quality: "We assess publications on topical overlap with your subject, organic visibility spread across many URLs, evidence of a working editorial process, author transparency and a sane ratio of commercial to editorial outbound links. Authority scores are used as a filter, never as the deciding factor.",
    useCases: [
      "Strengthening a commercial page that has good content but few references",
      "Building topical coverage around a newly launched category",
      "Diversifying a profile that leans too heavily on directories",
      "Supporting a market entry where you have no local citations yet",
    ],
    stats: [
      { label: "Average publisher traffic", value: "18k+/mo" },
      { label: "Sites rejected at review", value: "34%" },
      { label: "Typical placement window", value: "10–21 days" },
    ],
    packages: [
      { tier: "starter", name: "Single Placement", price: 210, deliveryDays: 14, revisions: 1, volume: "1 guest post", summary: "One article on one vetted publication in your niche.", features: ["1 niche-relevant placement", "900+ word original article", "1 contextual dofollow link", "Shortlist approval before writing", "Live URL and metrics report"] },
      { tier: "growth", name: "Campaign of Five", price: 940, deliveryDays: 24, revisions: 2, volume: "5 guest posts", summary: "A spread of placements across different publishers and anchors.", features: ["5 placements across distinct domains", "1,200+ word articles", "Anchor and target-page distribution plan", "Priority editor scheduling", "Monthly progress summary"], recommended: true },
      { tier: "scale", name: "Quarterly Programme", price: 3280, deliveryDays: 45, revisions: 3, volume: "18 guest posts", summary: "A sustained quarter of placements across several target pages.", features: ["18 placements over one quarter", "Multi-page target mapping", "Competitor overlap reporting", "Dedicated outreach strategist", "90-day link monitoring"] },
    ],
    faqs: [
      { question: "Do you write the article or do I?", answer: "We write it by default, using a brief agreed with the editor. If you would rather supply your own draft we will review it against the publisher's guidelines and tell you what needs changing before submission." },
      { question: "Will the link be dofollow?", answer: "In almost all cases yes, and we confirm the attribution before you approve the shortlist. A small number of strong publications mark commercial links as sponsored. We flag those clearly so you can decide whether the audience and relevance still make the placement worthwhile." },
      { question: "How long do the posts stay live?", answer: "Placements are intended to be permanent, and our publishers agree to that when they join the network. We monitor every URL for twelve months and arrange a replacement on a comparable site if a post is removed in that window." },
      { question: "Can I choose the exact websites?", answer: "Yes. Nothing is written until you approve the shortlist, and you can reject any domain without giving a reason. We will then propose alternatives at the same relevance and traffic level." },
    ],
    reviews: [
      { name: "Petra Lindgren", role: "Head of SEO", country: "Sweden", rating: 5, date: "2026-02-19", tier: "Campaign of Five", text: "The shortlist arrived with notes on why each site was chosen, including two we had already been offered elsewhere at double the price. Articles read like the publication wrote them." },
      { name: "Dominic Ashford", role: "Founder", country: "United Kingdom", rating: 5, date: "2026-01-28", tier: "Single Placement", text: "I tested one placement before committing to anything bigger. The editor published on the agreed date and the link sits in the second paragraph where it makes sense." },
      { name: "Yuki Tanaka", role: "Content Lead", country: "Canada", rating: 4, date: "2026-03-06", tier: "Quarterly Programme", text: "Two topics needed reworking before the editors accepted them, which added about a week. Communication was clear throughout and the final spread of domains was strong." },
    ],
    related: ["editorial-backlinks", "niche-edit-backlinks", "contextual-backlinks", "monthly-link-building"],
    cta: { heading: "Place your first guest post this month", body: "Send us one target URL and we will return a shortlist of relevant publications with traffic data and pricing." },
  },

  {
    slug: "editorial-backlinks",
    group: "Placement Services",
    nav: "Editorial Backlinks",
    icon: "document",
    accent: "sky",
    h1: "Editorial Backlinks Earned Through Genuine Coverage",
    metaTitle: "Editorial Backlinks | Natural In-Content Authority Links",
    metaDescription:
      "Editorial backlinks placed by journalists and editors inside genuine coverage. Relevance-first outreach, in-content and homepage placements, transparent reporting.",
    summary:
      "Links given by an editor because your resource genuinely improves their article, not because a slot was purchased.",
    keywords: ["editorial backlinks", "natural editorial links", "in-content editorial links", "authority editorial links", "homepage editorial links"],
    variants: ["Contextual editorial links", "Authority editorial links", "Natural editorial links", "High-authority editorial links", "In-content editorial links", "Homepage editorial links"],
    intro: [
      "Editorial links are the ones an editor chooses to include. Somebody writing an article decides your page explains something better than the alternatives and points their readers to it. That decision is what makes the link durable and what makes it worth pursuing properly.",
      "Our work here is closer to media relations than to content ordering. We identify writers and sections already covering your topic, prepare a reason for them to cite you, and pitch it. Not every pitch lands, so we work to an agreed number of secured placements rather than an agreed number of emails sent.",
    ],
    included: [
      "Identification of writers and columns covering your subject",
      "Citation angle development based on your strongest existing asset",
      "Personalised pitching to named editorial contacts",
      "Placement inside published articles rather than sponsored sections",
      "Attribution and anchor negotiation where the editor allows input",
      "Coverage log with publication, section and live URL",
    ],
    benefits: [
      { title: "Durable by nature", body: "A link an editor chose to add is rarely audited out later, because it exists to serve the article rather than a commercial arrangement." },
      { title: "Strong surrounding context", body: "Editorial mentions sit inside relevant paragraphs, which helps search engines understand what your page should be associated with." },
      { title: "Secondary pickup", body: "Coverage on established titles is often syndicated or referenced by smaller publications, producing additional references you did not directly pitch." },
      { title: "Reputation as well as ranking", body: "Prospects read these articles. An editorial mention in a title your buyers respect does work that a directory listing never will." },
    ],
    process: [
      { title: "Asset review", body: "We look at what you already have that is genuinely citable — original data, a clear explainer, a tool, a methodology — and pick the strongest candidate." },
      { title: "Contact mapping", body: "We build a list of writers and sections that have covered adjacent subjects recently, with notes on what each of them tends to reference." },
      { title: "Pitching", body: "Each contact receives a short, specific message explaining the relevance. No mass sends, no templated subject lines." },
      { title: "Securing and reporting", body: "We follow up once, record every response, and report the placements that go live along with the ones that declined and why." },
    ],
    placement: "Placements appear in the running text of a published article, typically where the writer is explaining a concept or citing a figure. Where a publication maintains an evergreen hub page, a homepage or section-level reference is sometimes available and we will flag it because those positions carry unusually strong internal support.",
    quality: "We prioritise publications with an identifiable editorial team, a consistent publishing schedule and readership that overlaps with your market. A smaller trade title read by your buyers is treated as a better outcome than a large general site with no subject connection.",
    useCases: [
      "Brands with original data or research that has never been promoted",
      "Companies whose link profile is mostly self-created placements",
      "Businesses entering a category where credibility must be established quickly",
      "Teams that need references from titles their customers already read",
    ],
    stats: [
      { label: "Median secured per campaign", value: "6 placements" },
      { label: "Average contact response rate", value: "11%" },
      { label: "Typical campaign length", value: "4–6 weeks" },
    ],
    packages: [
      { tier: "starter", name: "Pitch Sprint", price: 690, deliveryDays: 21, revisions: 1, volume: "2 secured placements", summary: "A focused sprint around one citable asset.", features: ["1 asset reviewed and framed", "40 verified editorial contacts", "2 secured placements", "Response log with decline reasons", "Live URL reporting"] },
      { tier: "growth", name: "Coverage Campaign", price: 1980, deliveryDays: 35, revisions: 2, volume: "6 secured placements", summary: "A full campaign across multiple publications and angles.", features: ["2 angles developed", "120 verified contacts", "6 secured placements", "Anchor negotiation where permitted", "Syndication tracking"], recommended: true },
      { tier: "scale", name: "Authority Programme", price: 4850, deliveryDays: 60, revisions: 3, volume: "15 secured placements", summary: "A quarter of sustained editorial relationship building.", features: ["Rolling angle pipeline", "300+ verified contacts", "15 secured placements", "Named media strategist", "Quarterly coverage review"] },
    ],
    faqs: [
      { question: "How is this different from a guest post?", answer: "With a guest post you supply the article and the publication hosts it. With an editorial link, the publication's own writer produces the piece and decides to reference you inside it. Editorial links take longer to secure and cannot be guaranteed individually, which is why we sell them by secured outcome rather than by emails sent." },
      { question: "Can you guarantee a specific publication?", answer: "No, and you should be sceptical of anyone who does. Editors make their own decisions. What we can commit to is the number of secured placements at an agreed quality level, and we will keep working until that number is met." },
      { question: "What if I have nothing citable yet?", answer: "Then we start there. During the asset review we will tell you honestly whether anything on your site is pitchable. If it is not, a small original data piece or a clear methodology page is usually enough to make outreach viable." },
      { question: "Do you control the anchor text?", answer: "Sometimes. Many editors accept a suggested anchor if it reads naturally; others link on your brand name or the article title. We always ask, never insist, and report what was actually used." },
    ],
    reviews: [
      { name: "Marisol Vega", role: "Communications Manager", country: "Spain", rating: 5, date: "2026-02-04", tier: "Coverage Campaign", text: "They told us our original landing page was not pitchable and helped us reshape it first. That honesty saved a month of pointless outreach." },
      { name: "Arne Boersma", role: "Growth Director", country: "Netherlands", rating: 5, date: "2026-01-15", tier: "Authority Programme", text: "Six of the fifteen placements came from trade titles our sales team already mentions on calls. That is worth more to us than any metric score." },
      { name: "Fiona Mackay", role: "Marketing Lead", country: "United Kingdom", rating: 4, date: "2026-03-11", tier: "Pitch Sprint", text: "Slower than buying placements outright, exactly as they warned during the briefing call. The two links we secured are on sites that would never sell a post." },
    ],
    related: ["digital-pr-backlinks", "guest-post-backlinks", "brand-entity-link-building", "premium-link-building"],
    cta: { heading: "Find out whether your site is pitchable", body: "We will review your strongest page and tell you honestly what an editor would do with it." },
  },

  {
    slug: "contextual-backlinks",
    group: "Placement Services",
    nav: "Contextual Backlinks",
    icon: "link",
    accent: "brand",
    h1: "Contextual Backlinks Placed Inside Relevant Body Content",
    metaTitle: "Contextual Backlinks | In-Content Links on Relevant Pages",
    metaDescription:
      "Contextual backlinks placed inside topically relevant body content. Dofollow in-content links, natural anchor distribution and verified placement reporting.",
    summary:
      "Links surrounded by paragraphs that discuss your subject, placed on pages where the reference genuinely fits.",
    keywords: ["contextual backlinks", "in-content backlinks", "dofollow contextual backlinks", "relevant contextual links", "natural contextual links"],
    variants: ["High authority contextual links", "DoFollow contextual backlinks", "Relevant contextual backlinks", "In-content backlinks", "Natural contextual links", "Authority contextual links"],
    intro: [
      "Context is what separates a link that helps from one that sits inert. A contextual backlink appears inside the main body of a page, wrapped in sentences that discuss the same subject as your destination URL. Search engines read that surrounding language, and so do the people who click.",
      "We source contextual placements two ways: inside new articles we commission, and inside existing indexed pages that already rank for related terms. Both routes are priced separately so you can see exactly what you are buying rather than receiving an undifferentiated bundle.",
    ],
    included: [
      "Topic-matched page selection with the surrounding paragraph shown before approval",
      "Placement inside the main content area, never sidebars or footers",
      "Anchor text varied across brand, partial-match and descriptive phrasing",
      "Screenshot and live URL for every placement",
      "Attribution confirmation (dofollow, nofollow or sponsored)",
      "Twelve months of placement monitoring",
    ],
    benefits: [
      { title: "The paragraph does the work", body: "A link inside relevant prose passes clearer topical signals than the same link dropped into a list of unrelated resources." },
      { title: "Immediate context for readers", body: "Because the sentence explains why your page is worth visiting, referral clicks from contextual links convert noticeably better than profile or directory links." },
      { title: "Flexible anchor strategy", body: "Body copy gives room for natural phrasing, so you can build a varied anchor profile instead of repeating the same exact-match phrase." },
      { title: "Verifiable before purchase", body: "You see the exact page and the paragraph the link will sit in, so there is no argument later about what relevant actually meant." },
    ],
    process: [
      { title: "Destination analysis", body: "We read your target page and identify the topics a linking paragraph would need to discuss for the reference to look natural." },
      { title: "Page sourcing", body: "We search for existing indexed pages and commission-ready publishers covering those exact topics, then verify traffic and indexing." },
      { title: "Paragraph approval", body: "You see the proposed page, the surrounding copy and the anchor before anything is inserted or written." },
      { title: "Insertion and verification", body: "Once live, we confirm the link renders in the HTML, check attribution and log the URL with a dated screenshot." },
    ],
    placement: "Every link sits within the first two-thirds of the body copy, inside a sentence that references the subject of your destination page. We reject placements offered in comment sections, author boxes, sidebars or bulk resource lists at the bottom of a page, because those positions rarely reflect genuine editorial intent.",
    quality: "Relevance is judged at page level, not just domain level. A general news site with one strongly matched article can be a better home for your link than a niche site where the specific page has no topical connection. We check indexing status, page-level traffic and outbound link density on the exact URL before offering it.",
    useCases: [
      "Supporting commercial pages that need topical reinforcement",
      "Adding relevance to a profile built mostly from homepage links",
      "Balancing an anchor distribution that has become too exact-match heavy",
      "Reinforcing a specific cluster before a seasonal push",
    ],
    stats: [
      { label: "Page-level indexing verified", value: "100%" },
      { label: "Average outbound links on host page", value: "under 8" },
      { label: "Typical turnaround", value: "7–14 days" },
    ],
    packages: [
      { tier: "starter", name: "Context Test", price: 175, deliveryDays: 10, revisions: 1, volume: "1 placement", summary: "A single contextual link on an approved relevant page.", features: ["1 in-content placement", "Paragraph shown before approval", "Anchor recommendation", "Dated screenshot", "Indexing verification"] },
      { tier: "growth", name: "Relevance Cluster", price: 790, deliveryDays: 18, revisions: 2, volume: "5 placements", summary: "Five placements supporting a single topic cluster.", features: ["5 topically clustered placements", "Anchor variation plan", "Mixed new and existing pages", "Cluster relevance report", "12-month monitoring"], recommended: true },
      { tier: "scale", name: "Profile Build", price: 2790, deliveryDays: 40, revisions: 3, volume: "20 placements", summary: "A broad contextual build across multiple destination pages.", features: ["20 placements across your key pages", "Full anchor distribution modelling", "Duplicate-host prevention", "Competitor context comparison", "Quarterly placement audit"] },
    ],
    faqs: [
      { question: "What counts as contextual in practice?", answer: "The link must be inside the main article body, in a sentence that discusses the same subject as the page it points to. If the only connection is that both pages exist on the internet, we do not call it contextual and we will not sell it as such." },
      { question: "Do you use new articles or existing pages?", answer: "Both, and we tell you which is which. Existing aged pages sometimes carry accumulated authority, while new articles let us control the topic precisely. Most balanced campaigns use a mix." },
      { question: "How do you decide anchor text?", answer: "We look at your existing anchor distribution first. If exact-match phrases already dominate, we lean on brand and descriptive anchors. The aim is a profile that looks like it accumulated naturally over time." },
      { question: "Can two links point to the same page?", answer: "Yes, but we space them across different domains and vary the anchor. Repeating an identical anchor from several hosts in a short window is one of the clearest artificial patterns there is." },
    ],
    reviews: [
      { name: "Emeka Nwosu", role: "SEO Manager", country: "Ireland", rating: 5, date: "2026-02-26", tier: "Relevance Cluster", text: "Being shown the actual paragraph before approving each placement is the detail that sold me. Two suggestions were swapped because the surrounding copy was too thin." },
      { name: "Clara Beaumont", role: "Digital Strategist", country: "France", rating: 5, date: "2026-01-09", tier: "Profile Build", text: "They pushed back when we asked for the same anchor twenty times and explained why. The revised distribution looks far more natural in our audit tool." },
      { name: "Owen Pritchard", role: "Ecommerce Manager", country: "Australia", rating: 4, date: "2026-03-02", tier: "Context Test", text: "Single link, no drama, delivered in nine days with a screenshot. I would have liked slightly more traffic on the host page for the price." },
    ],
    related: ["niche-edit-backlinks", "guest-post-backlinks", "authority-backlinks", "editorial-backlinks"],
    cta: { heading: "See the paragraph before you buy the link", body: "Send one destination URL and we will return contextual placement options with the surrounding copy attached." },
  },

  {
    slug: "niche-edit-backlinks",
    group: "Placement Services",
    nav: "Niche Edit Backlinks",
    icon: "search",
    accent: "violet",
    h1: "Niche Edit Backlinks Added to Established, Indexed Pages",
    metaTitle: "Niche Edit Backlinks | Contextual Links on Aged Pages",
    metaDescription:
      "Niche edit backlinks inserted into existing indexed articles with real traffic. Aged page placements, contextual anchors and transparent host-page metrics.",
    summary:
      "Your link added to an article that already exists, already ranks and already has readers.",
    keywords: ["niche edit backlinks", "contextual niche edits", "dofollow niche edits", "aged page niche edits", "premium niche edits"],
    variants: ["Contextual niche edits", "DoFollow niche edits", "Relevant niche edits", "High authority niche edits", "Aged page niche edits", "Premium niche edits"],
    intro: [
      "A niche edit places your link inside an article that was published months or years ago and has been accumulating signals ever since. Nothing new needs to be written, which is why placements move faster than guest posts, often inside a week.",
      "The trade-off is that the host page has to be genuinely worth being on. Plenty of sellers insert links into abandoned posts with no visitors and no indexing. We check page-level traffic, confirm the URL is indexed, count the existing outbound links and read the surrounding paragraph before we offer anything.",
    ],
    included: [
      "Host page URL, page-level traffic estimate and indexing status",
      "The paragraph your link will be added to, supplied for approval",
      "Existing outbound link count on the host page",
      "Natural anchor integrated into the current sentence flow",
      "Publisher confirmation that the edit is permanent",
      "Post-placement crawl to verify the link renders server-side",
    ],
    benefits: [
      { title: "Faster than commissioning content", body: "Because the article already exists, most niche edits go live within five to ten days instead of the three weeks a guest post typically needs." },
      { title: "Inherited page signals", body: "An aged page that already attracts visits and internal links passes value your link can benefit from immediately." },
      { title: "Lower cost per placement", body: "No writing, no editorial calendar slot. You pay for the placement and the relevance rather than for article production." },
      { title: "Precise topical targeting", body: "We can find pages that rank for the exact terms surrounding your product, which is difficult to guarantee when commissioning a new article." },
    ],
    process: [
      { title: "Topic and page hunting", body: "We search for indexed articles that already discuss your subject and rank for related queries in your target market." },
      { title: "Page-level vetting", body: "Each candidate is checked for traffic, indexing, outbound density and whether the content has been maintained or abandoned." },
      { title: "Insertion proposal", body: "You receive the URL, the current paragraph and the proposed edited sentence. Nothing changes until you approve it." },
      { title: "Edit and confirmation", body: "The publisher makes the edit, we re-crawl the page to confirm the link is present in the raw HTML and log the placement." },
    ],
    placement: "The link is woven into an existing sentence or a lightly expanded one so the paragraph still reads naturally. We do not accept placements where the publisher bolts an unrelated sentence onto the end of a post, because that pattern is obvious to both readers and reviewers.",
    quality: "We decline host pages that are orphaned, deindexed, stuffed with existing outbound commercial links, or maintained purely as link inventory. A page with modest traffic and genuine topical alignment is accepted ahead of a high-metric page with no relevance to your subject.",
    useCases: [
      "Campaigns that need placements live before a quarter closes",
      "Supporting pages that already have content but lack references",
      "Adding aged-domain diversity to a profile built from new posts",
      "Topic clusters where a matching article already ranks well",
    ],
    stats: [
      { label: "Average host page age", value: "2.5 years" },
      { label: "Minimum page-level traffic", value: "150/mo" },
      { label: "Typical turnaround", value: "5–10 days" },
    ],
    packages: [
      { tier: "starter", name: "Single Edit", price: 165, deliveryDays: 8, revisions: 1, volume: "1 niche edit", summary: "One insertion on an approved aged page.", features: ["1 contextual insertion", "Host page metrics supplied", "Paragraph approval", "Permanence confirmation", "HTML verification"] },
      { tier: "growth", name: "Edit Pack", price: 740, deliveryDays: 15, revisions: 2, volume: "5 niche edits", summary: "Five insertions across separate aged domains.", features: ["5 insertions on distinct domains", "Minimum 2-year page age", "Anchor variation", "Outbound density screening", "12-month monitoring"], recommended: true },
      { tier: "scale", name: "Premium Edit Programme", price: 2640, deliveryDays: 35, revisions: 3, volume: "18 niche edits", summary: "A large placement run weighted towards higher-traffic hosts.", features: ["18 insertions", "Priority on pages above 1k monthly visits", "Multi-page target distribution", "Duplicate-host prevention", "Quarterly re-crawl audit"] },
    ],
    faqs: [
      { question: "What is the real difference between a niche edit and a guest post?", answer: "A guest post is a brand-new article written for the publication, so you control the entire page but must wait for it to be written, approved and indexed. A niche edit adds your link to an article that already exists and already performs, so it is faster and cheaper, but you only control one sentence rather than the whole page." },
      { question: "Are niche edits safe to use?", answer: "They are as safe as the page they sit on. An edit inside a maintained, relevant, trafficked article reads exactly like any other citation. An edit inside an abandoned post that suddenly sprouted fifteen outbound commercial links does not, which is why we screen outbound density before offering anything." },
      { question: "Will the publisher remove it later?", answer: "Our publishers agree to permanent placement and we monitor each URL for twelve months. If a link is removed inside that period we arrange a replacement on a page of comparable age, traffic and relevance at no extra cost." },
      { question: "Can you edit a page that mentions my competitor?", answer: "Sometimes, and those are often the strongest opportunities because the topical fit is already proven. We will never ask a publisher to remove a competitor's link, only to add yours where it genuinely adds something for the reader." },
    ],
    reviews: [
      { name: "Ingrid Halvorsen", role: "Performance Marketer", country: "Norway", rating: 5, date: "2026-02-12", tier: "Edit Pack", text: "Three of the five host pages were already ranking for terms adjacent to our product. That level of matching is what we were paying for." },
      { name: "Rafael Dominguez", role: "SEO Consultant", country: "Mexico", rating: 4, date: "2026-01-22", tier: "Premium Edit Programme", text: "Delivery on two placements slipped past the estimate because the publishers were slow. They kept me updated and discounted the late items without being asked." },
      { name: "Anneke Visser", role: "Head of Digital", country: "Netherlands", rating: 5, date: "2026-03-14", tier: "Single Edit", text: "They rejected the first page I picked myself and explained the outbound link count was too high. Appreciated the honesty when it would have been easier to take the order." },
    ],
    related: ["contextual-backlinks", "guest-post-backlinks", "authority-backlinks", "resource-link-building"],
    cta: { heading: "Get aged page options for your target URL", body: "Tell us the page you want to strengthen and we will find indexed articles that already discuss the subject." },
  },

  {
    slug: "web-2-0-backlinks",
    group: "Foundation Links",
    nav: "Web 2.0 Backlinks",
    icon: "layers",
    accent: "sky",
    h1: "Web 2.0 Backlinks Built as Maintained Supporting Properties",
    metaTitle: "Web 2.0 Backlinks | Managed Supporting Blog Properties",
    metaDescription:
      "Web 2.0 backlinks built on maintained blog properties with original articles, contextual links and honest positioning as a supporting layer, not a core strategy.",
    summary:
      "Properly written blog properties on established platforms, used as a supporting layer around your stronger links.",
    keywords: ["web 2.0 backlinks", "web 2.0 link building", "dofollow web 2.0", "web 2.0 contextual links", "aged web 2.0 backlinks"],
    variants: ["High authority Web 2.0", "DoFollow Web 2.0", "Web 2.0 contextual links", "Web 2.0 blog posts", "Aged Web 2.0 backlinks"],
    intro: [
      "Web 2.0 properties are blogs you create on established publishing platforms. They are not a substitute for editorial coverage, and we will say that plainly: their value lies in diversifying a profile and giving you controlled properties where you can reference your own content sensibly.",
      "The difference between a useful Web 2.0 layer and a worthless one is whether the property looks like a real blog. Ours are built with a theme, an about page, several genuinely written articles on the subject, and outbound links to third-party sources as well as to you.",
    ],
    included: [
      "Property setup on established platforms with a completed profile",
      "Three to five original articles per property, not spun text",
      "One contextual link to your site inside relevant body copy",
      "Outbound references to independent third-party sources",
      "Basic on-page structure, categories and internal linking",
      "Login credentials handed over so you own the property outright",
    ],
    benefits: [
      { title: "Controlled supporting layer", body: "You own these properties, so they are useful for reinforcing a page without needing a publisher's permission every time." },
      { title: "Profile diversification", body: "A profile made entirely of paid placements looks unusual. A sensible layer of self-published properties broadens the mix." },
      { title: "Genuinely written content", body: "Every article is written by a person and is readable. Spun or auto-generated text is the fastest way to make these properties worthless." },
      { title: "Honest positioning", body: "We tell you upfront that these support a strategy rather than driving it, so your budget goes where it produces the most movement." },
    ],
    process: [
      { title: "Platform selection", body: "We choose established platforms appropriate to your subject and market, avoiding networks that exist only for link building." },
      { title: "Property build", body: "Each blog is set up with a theme, profile details, an about page and category structure so it reads like a genuine project." },
      { title: "Content publishing", body: "Original articles are published over a short schedule rather than all at once, with one contextual link to your target page." },
      { title: "Handover", body: "You receive the URLs and credentials, so the properties remain yours and can be updated later if you wish." },
    ],
    placement: "Your link appears inside an article body, in a paragraph that discusses the topic it relates to. Each property also links out to unrelated authoritative sources, because a blog whose only outbound link points at one commercial site is obviously not a real blog.",
    quality: "We use platforms with genuine public use and reject anything that resembles a private network. Content is written to be readable; we do not spin articles or generate filler. Because these are self-published, we are explicit that they carry less weight than editorial placements and we will steer you elsewhere if your budget is limited.",
    useCases: [
      "Diversifying a profile weighted heavily towards one link type",
      "Supporting a new domain that has almost no references at all",
      "Holding controlled properties for long-term content reuse",
      "Reinforcing a cluster alongside editorial and contextual work",
    ],
    stats: [
      { label: "Articles per property", value: "3–5" },
      { label: "Written by humans", value: "100%" },
      { label: "Typical build time", value: "10–18 days" },
    ],
    packages: [
      { tier: "starter", name: "Foundation Three", price: 180, deliveryDays: 12, revisions: 1, volume: "3 properties", summary: "Three maintained properties with original content.", features: ["3 properties built", "3 articles each", "1 contextual link per property", "Third-party outbound references", "Credentials handed over"] },
      { tier: "growth", name: "Support Layer", price: 420, deliveryDays: 18, revisions: 2, volume: "8 properties", summary: "A broader supporting layer across multiple platforms.", features: ["8 properties across varied platforms", "4 articles each", "Staggered publishing schedule", "Anchor variation", "Indexing check on every property"], recommended: true },
      { tier: "scale", name: "Managed Network", price: 980, deliveryDays: 30, revisions: 3, volume: "20 properties", summary: "A maintained set of properties refreshed over three months.", features: ["20 properties", "5 articles each", "Quarterly content refresh", "Cross-topic distribution", "Full URL and credential inventory"] },
    ],
    faqs: [
      { question: "Are Web 2.0 links still worth building in 2026?", answer: "As a supporting layer, yes; as your main strategy, no. They help diversify a profile and give you controlled properties, but they will not carry a competitive commercial term on their own. If you only have budget for one thing, put it into editorial or contextual placements instead." },
      { question: "Is this the same as a PBN?", answer: "No, and we do not offer private blog networks under any name. These are public properties on mainstream platforms, built openly and handed to you with full credentials. There is no attempt to disguise ownership or simulate independent editorial endorsement." },
      { question: "Will the links be dofollow?", answer: "It depends on the platform, and we tell you which is which before purchase. Several major platforms apply nofollow by default. Those properties still contribute diversity and referral context, but we never bill a nofollow placement as though it were dofollow." },
      { question: "Do I own the properties afterwards?", answer: "Yes. Credentials are handed over on delivery. You can keep publishing on them, update the articles, or leave them as they are." },
    ],
    reviews: [
      { name: "Tobias Wenger", role: "Startup Founder", country: "Switzerland", rating: 4, date: "2026-02-08", tier: "Support Layer", text: "They talked me down from twenty properties to eight and suggested putting the difference into niche edits. Unusual advice from someone selling the service." },
      { name: "Sana Qureshi", role: "Freelance SEO", country: "United Kingdom", rating: 5, date: "2026-01-30", tier: "Foundation Three", text: "The articles are actually readable, which is not what I expected at this price. Each blog has a proper about page and outbound citations." },
      { name: "Lukas Brandt", role: "Agency Owner", country: "Germany", rating: 4, date: "2026-03-08", tier: "Managed Network", text: "Solid supporting layer for new client domains. Clear reporting on which platforms apply nofollow, which saved an awkward client conversation." },
    ],
    related: ["contextual-backlinks", "social-bookmarking-backlinks", "citation-directory-backlinks", "monthly-link-building"],
    cta: { heading: "Not sure Web 2.0 is right for you?", body: "Tell us your budget and current profile and we will say honestly whether this layer is worth funding." },
  },

  {
    slug: "authority-backlinks",
    group: "Authority & Metrics",
    nav: "Authority Backlinks",
    icon: "badge",
    accent: "amber",
    h1: "High Authority Backlinks Filtered by Metrics, Chosen by Relevance",
    metaTitle: "High Authority Backlinks | DA, DR and Trust Flow Filtering",
    metaDescription:
      "High authority backlinks from DA 30+ to DR 70+ publishers. Metric thresholds combined with manual relevance and traffic checks, not metrics alone.",
    summary:
      "Placements that meet the authority thresholds you specify, then pass a manual relevance and traffic review before we offer them.",
    keywords: ["high authority backlinks", "DA 50 backlinks", "DR 70 backlinks", "high trust flow backlinks", "premium authority backlinks"],
    variants: ["DA 30+ backlinks", "DA 50+ backlinks", "DA 70+ backlinks", "DR 30+ backlinks", "DR 50+ backlinks", "DR 70+ backlinks", "High Trust Flow backlinks", "High Citation Flow backlinks"],
    intro: [
      "Most buyers arrive with a metric threshold in mind, usually a DA or DR number. We work to those thresholds because they are a practical filter, but we are direct about what they are: third-party estimates produced by tools that do not have access to the ranking systems they are approximating.",
      "So we treat metrics as the first gate and relevance as the deciding one. A DR 40 site that covers your exact subject and has readers is offered ahead of a DR 75 domain with inflated scores, no topical connection and traffic concentrated in a single viral post from four years ago.",
    ],
    included: [
      "Placements meeting your specified DA, DR, TF or CF threshold",
      "Independent traffic verification separate from the authority score",
      "Metric manipulation screening, including link velocity and referring-domain quality",
      "Topical relevance assessment against your destination page",
      "Full metric snapshot recorded at the time of placement",
      "Contextual in-content link with anchor guidance",
    ],
    benefits: [
      { title: "Thresholds you control", body: "Specify DA 30+, DR 50+, a Trust Flow floor or a combination, and we filter inventory to match before the manual review begins." },
      { title: "Manipulation screening", body: "We check whether a domain's score is supported by a genuine referring-domain profile or has been inflated through purchased links and expired-domain tricks." },
      { title: "Traffic sanity checks", body: "A high score with negligible organic visitors is a warning sign. We verify traffic independently and report both figures side by side." },
      { title: "Honest metric context", body: "You get a clear explanation of what each score does and does not indicate, so internal reporting stays accurate." },
    ],
    process: [
      { title: "Threshold setting", body: "We agree which metrics matter to you and at what level, including any minimum traffic and maximum spam-signal tolerance." },
      { title: "Inventory filtering", body: "Our marketplace is filtered to the threshold, then each candidate is queued for manual review rather than being sold automatically." },
      { title: "Manual verification", body: "An analyst checks relevance, traffic distribution, referring-domain quality and outbound behaviour, and removes anything that looks engineered." },
      { title: "Placement and snapshot", body: "The link goes live and we record a dated snapshot of every metric so you can evidence what you bought." },
    ],
    placement: "Links are placed in-content on a topically appropriate page. On very large publications we prioritise section pages and evergreen articles over news items that will be buried within days, because internal linking on a strong domain determines how much of that domain authority actually reaches your link.",
    quality: "We reject domains whose scores are supported by obviously purchased referring domains, sites with sharp unexplained authority spikes, and expired domains rebuilt purely to sell links. Relevance and genuine readership outrank raw metric values in every decision we make.",
    useCases: [
      "Agencies working to a client-mandated metric threshold",
      "Competitive niches where reference quality is the differentiator",
      "Profiles that need stronger domains alongside existing mid-tier links",
      "Reporting environments where metric evidence is required",
    ],
    stats: [
      { label: "Metric-qualified domains", value: "12,400+" },
      { label: "Rejected after manual review", value: "29%" },
      { label: "Minimum organic traffic", value: "2,000/mo" },
    ],
    packages: [
      { tier: "starter", name: "DA 30+ Entry", price: 240, deliveryDays: 14, revisions: 1, volume: "1 placement", summary: "One placement on a verified DA 30+ or DR 30+ domain.", features: ["DA/DR 30+ threshold", "Traffic verification", "Relevance review", "In-content placement", "Dated metric snapshot"] },
      { tier: "growth", name: "DA 50+ Campaign", price: 1650, deliveryDays: 25, revisions: 2, volume: "5 placements", summary: "Five placements on stronger domains with mixed anchors.", features: ["DA/DR 50+ threshold", "Minimum 5k monthly traffic", "Manipulation screening", "Anchor distribution plan", "Full metric reporting"], recommended: true },
      { tier: "scale", name: "DR 70+ Premium", price: 5400, deliveryDays: 45, revisions: 3, volume: "8 placements", summary: "A small number of genuinely strong, relevant publishers.", features: ["DA/DR 70+ threshold", "Minimum 25k monthly traffic", "Editorial-only placements", "Competitor overlap analysis", "Named account strategist"] },
    ],
    faqs: [
      { question: "Does a high DA or DR guarantee a good backlink?", answer: "No. DA, DR, Trust Flow and Citation Flow are third-party estimates created by tool vendors, not signals used by search engines. They are useful for filtering out obviously weak sites, but a high score tells you nothing about whether the page is relevant to your subject or whether anybody reads it. We use them as a gate and then judge relevance, traffic and editorial quality separately." },
      { question: "Can metrics be manipulated?", answer: "Easily, and it happens constantly. Buying a few hundred cheap links can lift a domain score within weeks. That is why we examine the referring-domain profile behind the number and reject domains whose authority appeared suddenly without matching traffic growth." },
      { question: "Should I always buy the highest metric I can afford?", answer: "Usually not. Five relevant DR 45 placements in your subject area typically outperform one DR 80 link from an unrelated site, and cost less. We will tell you when a threshold is pushing your budget into diminishing returns." },
      { question: "Which metric should I report internally?", answer: "Report referring-domain growth and organic visibility movement, and use DA or DR only as a supporting quality indicator. We supply all of them so your reporting does not depend on a single vendor's estimate." },
    ],
    reviews: [
      { name: "Gabriel Okonkwo", role: "Head of Acquisition", country: "United States", rating: 5, date: "2026-02-21", tier: "DA 50+ Campaign", text: "They rejected two domains that met our DR floor because traffic did not support the score. Our previous vendor would have invoiced them without a word." },
      { name: "Helena Novotna", role: "SEO Lead", country: "Czech Republic", rating: 5, date: "2026-01-18", tier: "DR 70+ Premium", text: "Eight links instead of the twenty we asked for, with an explanation of why the remaining budget was better spent on relevance. Rankings moved anyway." },
      { name: "Callum Frazier", role: "Agency Director", country: "Australia", rating: 4, date: "2026-03-17", tier: "DA 30+ Entry", text: "Straightforward entry-level placement and the metric snapshot made client reporting easy. Delivery took the full fourteen days." },
    ],
    related: ["premium-link-building", "guest-post-backlinks", "niche-edit-backlinks", "competitor-link-building"],
    cta: { heading: "Set your threshold, we will apply the judgement", body: "Tell us your metric requirements and we will show you what passes both the filter and the manual review." },
  },

  {
    slug: "local-backlinks",
    group: "Local & Directories",
    nav: "Local Backlinks",
    icon: "pin",
    accent: "brand",
    h1: "Local Backlinks That Tie Your Business to a Real Place",
    metaTitle: "Local Backlinks | City-Specific and Geo-Targeted Link Building",
    metaDescription:
      "Local backlinks from regional publications, community organisations and city-specific sources. Geo-targeted link building with consistent business information.",
    summary:
      "References from regional media, community organisations and local institutions that connect your business to the area you serve.",
    keywords: ["local backlinks", "city specific backlinks", "geo targeted backlinks", "local news backlinks", "local authority links"],
    variants: ["Local citation backlinks", "Local business directory links", "Local guest posts", "Local news backlinks", "City-specific backlinks", "Geo-targeted backlinks", "NAP citations", "Local authority links"],
    intro: [
      "Local link building answers a different question from national SEO. You are not trying to be the biggest site in your industry; you are trying to look like an established part of a specific place. Regional newspapers, chambers of commerce, community groups, local event listings and area-specific blogs all contribute to that picture.",
      "These links are usually cheaper than national placements and considerably harder to fake, because the organisations issuing them tend to know the businesses in their area. That is exactly what makes them useful for map visibility and localised organic results.",
    ],
    included: [
      "Location audit covering your existing local references and inconsistencies",
      "Regional publication and community organisation prospecting",
      "Placements or listings carrying consistent name, address and phone details",
      "City and neighbourhood-level anchor and landing page mapping",
      "Sponsorship and event opportunity identification where relevant",
      "Per-location reporting for multi-branch businesses",
    ],
    benefits: [
      { title: "Signals tied to geography", body: "Links from sources rooted in your area reinforce where you operate far more clearly than a national link with a city word in the anchor." },
      { title: "Harder for competitors to copy", body: "Relationships with local organisations and sponsorships are not available to buy in bulk, which makes them more defensible." },
      { title: "Supports map and organic together", body: "Consistent local references help both your listing visibility and the ranking of the location pages on your own site." },
      { title: "Works for multi-location brands", body: "Each branch gets its own prospect set and landing page target rather than every link pointing at one head-office homepage." },
    ],
    process: [
      { title: "Location and consistency audit", body: "We record how your business details currently appear across the web and identify conflicting addresses, old phone numbers and duplicate entries." },
      { title: "Local prospecting", body: "We build a list per location: regional press, community sites, industry associations, event calendars and genuinely local directories." },
      { title: "Outreach and submission", body: "We pitch stories to regional press, apply to relevant organisations and complete listings by hand with identical business details." },
      { title: "Verification and reporting", body: "Each live reference is checked and logged against the correct location, with a note on whether the link is followed." },
    ],
    placement: "Links point to the relevant location page rather than the homepage wherever one exists, because that is what a reader looking for your nearest branch actually needs. Anchors lean on the business name and city, since exact-match service anchors from local sources look unnatural and rarely help.",
    quality: "We prioritise sources with a genuine local footprint: publications with regional newsrooms, organisations with real membership and directories that local people actually use. Nationwide listing farms with a city subpage are excluded regardless of their metrics.",
    useCases: [
      "Service businesses competing for city-level search visibility",
      "Multi-branch retailers needing per-location authority",
      "Franchise operators consolidating inconsistent business information",
      "New locations that need regional references quickly",
    ],
    stats: [
      { label: "Markets covered", value: "38 countries" },
      { label: "Average references per location", value: "14" },
      { label: "Detail consistency achieved", value: "96%" },
    ],
    packages: [
      { tier: "starter", name: "Single Location", price: 290, deliveryDays: 18, revisions: 1, volume: "1 location, 12 references", summary: "A focused local build for one address.", features: ["Consistency audit", "12 local references", "Regional directory submissions", "Location page targeting", "Detail accuracy report"] },
      { tier: "growth", name: "City Authority", price: 780, deliveryDays: 28, revisions: 2, volume: "1 location, 30 references", summary: "A deeper build including regional press outreach.", features: ["30 local references", "2 regional press pitches", "Community and association outreach", "Neighbourhood anchor mapping", "Duplicate listing cleanup"], recommended: true },
      { tier: "scale", name: "Multi-Location", price: 2150, deliveryDays: 45, revisions: 3, volume: "5 locations, 20 each", summary: "Coordinated local link building across several branches.", features: ["Up to 5 locations", "20 references per location", "Per-branch reporting", "Cross-location duplicate prevention", "Quarterly consistency re-audit"] },
    ],
    faqs: [
      { question: "Do local links need to be dofollow to help?", answer: "Not always. Many chamber of commerce and community listings apply nofollow, yet they still contribute to how consistently your business details appear across the web, which matters for local visibility. We report attribution honestly and balance nofollow listings with followed editorial placements." },
      { question: "What if my business details have changed?", answer: "Tell us during the audit and we will find and correct the outdated entries we can access, then submit the new details consistently everywhere else. Conflicting addresses and phone numbers are one of the most common local visibility problems we see." },
      { question: "Can you get coverage in the local newspaper?", answer: "We pitch regional press where you have something genuinely newsworthy: an expansion, a hire, a community initiative, local data. We cannot buy editorial coverage, and any provider claiming guaranteed local news placement is either paying for advertorial or misleading you." },
      { question: "How does this work for service-area businesses without a shopfront?", answer: "We focus on regional press, trade associations and community organisations covering the areas you serve, and we avoid address-based directories that require a physical location you do not have." },
    ],
    reviews: [
      { name: "Bridget Kavanagh", role: "Operations Manager", country: "Ireland", rating: 5, date: "2026-02-16", tier: "City Authority", text: "The audit found three old phone numbers still listed from before we moved premises. Fixing those probably mattered as much as the new links." },
      { name: "Hugo Ferreira", role: "Franchise Owner", country: "Portugal", rating: 5, date: "2026-01-24", tier: "Multi-Location", text: "Each branch got its own set of references pointing at its own page. Our previous agency sent everything to the homepage and wondered why nothing moved." },
      { name: "Nadia Rahim", role: "Clinic Director", country: "Canada", rating: 4, date: "2026-03-04", tier: "Single Location", text: "Good value and careful work. The regional press pitch did not land, which they had flagged as uncertain from the start." },
    ],
    related: ["citation-directory-backlinks", "guest-post-backlinks", "brand-entity-link-building", "press-release-news-backlinks"],
    cta: { heading: "Audit your local footprint first", body: "We will map how your business currently appears locally and where the gaps are before recommending any spend." },
  },

  {
    slug: "citation-directory-backlinks",
    group: "Local & Directories",
    nav: "Citation & Directory Backlinks",
    icon: "check",
    accent: "sky",
    h1: "Citations and Directory Backlinks Worth Actually Having",
    metaTitle: "Citation & Directory Backlinks | Curated Business Listings",
    metaDescription:
      "Business directory backlinks and local citations on curated, genuinely used platforms. Consistent NAP details, niche directories and duplicate cleanup.",
    summary:
      "Listings on directories people genuinely use, submitted by hand with consistent business details.",
    keywords: ["business directory backlinks", "local citations", "niche directory backlinks", "NAP citations", "industry directory links"],
    variants: ["Business directory backlinks", "Local citations", "Niche directory backlinks", "Industry directory links", "Regional directory links", "Business listings", "Map and citation links"],
    intro: [
      "Directory submissions earned a bad reputation because for years they were sold by the thousand, dumped into link farms nobody visited. We only work with directories that meet one test: would a real person plausibly use this to find a business like yours?",
      "That cuts the available inventory dramatically, and it should. A curated set of forty relevant listings with identical business details does more for consistency and discovery than two thousand automated submissions that search engines have long since stopped counting.",
    ],
    included: [
      "Existing citation audit with duplicate and conflict detection",
      "Manual submission to curated general, niche and regional directories",
      "Identical name, address, phone and website details across every listing",
      "Category selection and business description written per platform",
      "Verification handling, including postcard and phone confirmations where required",
      "Login credentials and a full listing inventory on completion",
    ],
    benefits: [
      { title: "Consistency over volume", body: "Search engines cross-reference your details across sources. Forty identical listings build confidence; four hundred inconsistent ones create doubt." },
      { title: "Genuinely used platforms", body: "We maintain a curated directory list and remove platforms that become abandoned, spam-ridden or deindexed." },
      { title: "Duplicate cleanup included", body: "Old, partial or competitor-created listings are found and corrected or suppressed, which is often the highest-impact part of the work." },
      { title: "Niche directories that matter", body: "Industry association listings and trade directories carry real relevance and are frequently missed entirely by generic citation packages." },
    ],
    process: [
      { title: "Audit", body: "We scan for existing listings, record how your details appear on each, and flag duplicates and conflicts." },
      { title: "Platform selection", body: "We assemble a shortlist of general, regional and industry-specific directories appropriate to your business and market." },
      { title: "Manual submission", body: "Each listing is created by hand with a platform-appropriate description, correct category and identical contact details." },
      { title: "Verification and handover", body: "We complete the verification steps each platform requires, then hand over credentials with a full inventory spreadsheet." },
    ],
    placement: "Listings link to your homepage or the relevant location page, with your business name as the anchor in almost all cases. Directory listings are one of the few contexts where a branded anchor is unquestionably correct, and using keyword anchors here looks manipulative.",
    quality: "We exclude directories that accept every submission automatically, charge for guaranteed followed links regardless of relevance, or exist purely to host outbound links. Industry associations, regional business bodies and established platforms with genuine consumer traffic are prioritised.",
    useCases: [
      "New businesses establishing baseline online presence",
      "Companies that have moved premises or rebranded",
      "Multi-location operators with inconsistent legacy listings",
      "Local service providers competing for map visibility",
    ],
    stats: [
      { label: "Curated directory list", value: "340 platforms" },
      { label: "Removed from our list last year", value: "62" },
      { label: "Submissions made manually", value: "100%" },
    ],
    packages: [
      { tier: "starter", name: "Core Citations", price: 120, deliveryDays: 12, revisions: 1, volume: "25 listings", summary: "Essential listings with consistent details.", features: ["Existing citation audit", "25 manual submissions", "Consistent NAP details", "Category optimisation", "Listing inventory"] },
      { tier: "growth", name: "Citation Cleanup", price: 340, deliveryDays: 20, revisions: 2, volume: "50 listings + cleanup", summary: "Full cleanup plus an expanded listing set.", features: ["Duplicate detection and suppression", "50 manual submissions", "Niche directory inclusion", "Verification handling", "Before and after consistency report"], recommended: true },
      { tier: "scale", name: "Industry Coverage", price: 890, deliveryDays: 32, revisions: 3, volume: "100 listings", summary: "Comprehensive coverage including trade bodies.", features: ["100 curated listings", "Industry association applications", "Regional directory coverage", "Multi-location support", "Annual re-audit included"] },
    ],
    faqs: [
      { question: "Are directory links still worth paying for?", answer: "Curated ones, yes, for consistency and discovery. Bulk ones, no. The difference is whether the directory has genuine users and editorial standards. We deliberately offer fewer listings than most providers because padding the count with worthless platforms helps nobody." },
      { question: "What is a NAP citation?", answer: "It refers to your business Name, Address and Phone number appearing together on another website. Search engines use these mentions to confirm your business details, so the aim is for every instance to match exactly, including abbreviations and formatting." },
      { question: "Will these links improve my rankings directly?", answer: "Individually they carry modest weight. Their value is cumulative and confirmatory rather than dramatic, and they matter most for local visibility. Anyone promising ranking jumps from directory submissions alone is overselling." },
      { question: "What happens to listings competitors created for my business?", answer: "We find them during the audit and start the claim or correction process. Incorrect third-party listings are surprisingly common and can send customers to an old address for years." },
    ],
    reviews: [
      { name: "Martin Szabo", role: "Restaurant Owner", country: "Hungary", rating: 5, date: "2026-02-02", tier: "Citation Cleanup", text: "Found eleven duplicate listings, two with a competitor's phone number attached. The cleanup alone justified the cost." },
      { name: "Priyanka Menon", role: "Marketing Manager", country: "India", rating: 4, date: "2026-01-12", tier: "Core Citations", text: "Twenty-five listings rather than the five hundred another provider promised. Explained clearly why fewer is better, and I believe them." },
      { name: "Stefan Koch", role: "Logistics Director", country: "Germany", rating: 5, date: "2026-03-19", tier: "Industry Coverage", text: "The trade association listings were the valuable part. Nobody else we spoke to even mentioned them as an option." },
    ],
    related: ["local-backlinks", "brand-entity-link-building", "web-2-0-backlinks", "edu-gov-resource-links"],
    cta: { heading: "Start with a citation audit", body: "We will show you every listing we can find, including the ones with the wrong details." },
  },

  {
    slug: "forum-community-backlinks",
    group: "Community Links",
    nav: "Forum & Community Backlinks",
    icon: "users",
    accent: "violet",
    h1: "Forum and Community Backlinks From Genuine Participation",
    metaTitle: "Forum & Community Backlinks | Genuine Niche Participation",
    metaDescription:
      "Forum and community backlinks earned through real participation in niche discussions and Q&A threads. Contextual answers, no automated posting or signature spam.",
    summary:
      "Links earned by answering questions properly in communities where your audience already spends time.",
    keywords: ["forum backlinks", "niche forum links", "community links", "Q&A backlinks", "contextual forum links"],
    variants: ["Contextual forum links", "Niche forum links", "Relevant forum links", "Community links", "Q&A backlinks"],
    intro: [
      "Forum links work when the contribution stands on its own. Somebody asks a question, a knowledgeable answer is posted, and a link appears because it genuinely helps the reader. Nothing about that process can be automated without producing something worthless.",
      "We write substantive answers in communities relevant to your subject, and we only include a link where it adds something the answer cannot. Many of our contributions carry no link at all, because a profile of thirty forum posts that all point at the same commercial site is the clearest spam signal available.",
    ],
    included: [
      "Community research to find active forums and Q&A threads in your subject",
      "Established accounts with genuine posting history where required",
      "Detailed answers written by someone who understands the topic",
      "Contextual links included only where directly relevant",
      "A proportion of link-free contributions to keep the profile natural",
      "Thread URLs, dates and engagement notes in a single report",
    ],
    benefits: [
      { title: "Real referral traffic", body: "Good answers in active communities send visitors for years, and those visitors arrive with a specific problem your page can solve." },
      { title: "Hard-to-replicate signals", body: "A genuinely helpful presence in a niche community cannot be bought in bulk, which is precisely why it carries weight." },
      { title: "Audience insight", body: "The questions people actually ask become useful input for your content roadmap, and we pass them on." },
      { title: "Conservative link ratio", body: "We deliberately post without links a large share of the time, because restraint is what keeps the account and the links useful." },
    ],
    process: [
      { title: "Community mapping", body: "We identify forums, subreddits, Q&A sites and professional communities where your subject is actively discussed." },
      { title: "Account preparation", body: "Where a community requires standing, we use accounts with genuine history or build participation before any link is posted." },
      { title: "Answer writing", body: "A subject-literate writer produces a full answer to the actual question, not a paragraph engineered around an anchor." },
      { title: "Selective linking", body: "A link is added only where your page is the best available reference. Everything is logged, including the contributions posted without links." },
    ],
    placement: "Links sit inside the body of an answer, referenced as a source for a specific claim. We do not use signature links, profile-field links or one-line replies with a URL attached, because moderators remove them and they contribute nothing.",
    quality: "We only work in communities with active moderation and genuine discussion volume. Forums that exist to host promotional posts are excluded. If a community's rules prohibit commercial links, we either contribute without one or skip it entirely rather than risk a ban on your brand name.",
    useCases: [
      "Technical products where buyers research in specialist communities",
      "Brands wanting referral traffic alongside link equity",
      "Profiles that need non-commercial link diversity",
      "Companies with genuine subject expertise to demonstrate",
    ],
    stats: [
      { label: "Contributions without a link", value: "around 55%" },
      { label: "Communities actively monitored", value: "220+" },
      { label: "Average answer length", value: "180 words" },
    ],
    packages: [
      { tier: "starter", name: "Community Starter", price: 145, deliveryDays: 14, revisions: 1, volume: "10 contributions", summary: "Ten genuine contributions with selective linking.", features: ["Community research", "10 written contributions", "3–4 contextual links", "Thread URL reporting", "Moderation-safe approach"] },
      { tier: "growth", name: "Active Presence", price: 480, deliveryDays: 28, revisions: 2, volume: "35 contributions", summary: "A sustained presence across several communities.", features: ["35 contributions over a month", "10–12 contextual links", "Multi-community coverage", "Question insight summary", "Engagement tracking"], recommended: true },
      { tier: "scale", name: "Managed Community", price: 1290, deliveryDays: 45, revisions: 3, volume: "90 contributions", summary: "Ongoing managed participation across a quarter.", features: ["90 contributions", "25–30 contextual links", "Dedicated topic specialist", "Audience question reporting", "Reputation monitoring"] },
    ],
    faqs: [
      { question: "Will my posts get removed by moderators?", answer: "Rarely, because we follow each community's rules and post answers that would be acceptable with or without the link. If a moderator does remove a post we replace it, but the bigger risk we protect against is your brand name being associated with promotional spam." },
      { question: "Do you use signature links?", answer: "No. Signature and profile links are ignored almost everywhere and are the first thing associated with forum spam. Every link we place is inside the body of a relevant answer." },
      { question: "Why do you post without links so often?", answer: "Because an account whose every contribution contains a commercial link is obviously promotional, to moderators and to search engines. Mixing in genuinely helpful link-free answers is what keeps the linked contributions credible." },
      { question: "Can you post in communities that ban promotion?", answer: "We will contribute there without links if the audience is valuable, and we will tell you upfront that no link is possible. We will not break a community's rules using your brand name." },
    ],
    reviews: [
      { name: "Aleksandr Petrov", role: "Product Manager", country: "Estonia", rating: 5, date: "2026-02-14", tier: "Active Presence", text: "The referral traffic surprised us more than the links. Two threads still send signups nine weeks later." },
      { name: "Chloe Rousseau", role: "Growth Marketer", country: "France", rating: 4, date: "2026-01-26", tier: "Community Starter", text: "Only three links from ten posts, which felt light until they explained the ratio. The answers themselves are genuinely good." },
      { name: "Darren Whitlock", role: "Technical Director", country: "United Kingdom", rating: 5, date: "2026-03-21", tier: "Managed Community", text: "They asked our engineers for input before answering the harder questions. That is why the posts do not read like marketing." },
    ],
    related: ["blog-comment-backlinks", "brand-entity-link-building", "social-bookmarking-backlinks", "saas-software-backlinks"],
    cta: { heading: "Find out where your buyers ask questions", body: "We will map the active communities in your subject and show you what a genuine presence would look like." },
  },

  {
    slug: "blog-comment-backlinks",
    group: "Community Links",
    nav: "Blog Comment Backlinks",
    icon: "quote",
    accent: "amber",
    h1: "Blog Comment Backlinks Written by People Who Read the Article",
    metaTitle: "Blog Comment Backlinks | Manual Comments on Relevant Blogs",
    metaDescription:
      "Manual blog comment backlinks on relevant, moderated blogs. Genuine responses to published articles, positioned honestly as a supporting link-building method.",
    summary:
      "Thoughtful comments on relevant, moderated blogs — a supporting tactic, and we position it as exactly that.",
    keywords: ["blog comment backlinks", "manual blog comment links", "niche blog comment links", "relevant blog comment backlinks"],
    variants: ["Relevant blog comment backlinks", "Niche blog comment links", "Manual blog comment backlinks", "High-quality blog comment links"],
    intro: [
      "Let us set expectations before you spend anything. Blog comment links are a minor supporting tactic. Most are nofollow, they carry limited ranking weight, and no serious strategy is built on them. If a provider is pitching comments as a primary authority solution, walk away.",
      "Used correctly they still have a place: modest profile diversity, occasional referral traffic and visibility with bloggers in your space. We write comments that respond to the specific article, get through moderation, and stay live because they add to the discussion.",
    ],
    included: [
      "Relevant, recently published articles selected in your subject area",
      "Comments written after reading the article, referencing its actual content",
      "Consistent commenter name and profile details across placements",
      "Links included only where the article's subject makes them relevant",
      "Moderation tracking with replacement of anything not approved",
      "Attribution reporting showing which links are nofollow",
    ],
    benefits: [
      { title: "Honest positioning", body: "We tell you plainly where this sits in a strategy, so budget goes to comments only after the work that moves rankings is funded." },
      { title: "Moderation survival", body: "Comments are written to be approved and kept. Generic praise gets deleted within days and helps nobody." },
      { title: "Blogger visibility", body: "Consistent, useful commenting puts your name in front of publishers who may later accept a guest contribution." },
      { title: "Profile diversity", body: "A natural link profile contains a mix of link types. A small number of comment links contributes to that mix." },
    ],
    process: [
      { title: "Article sourcing", body: "We find recently published, actively moderated articles in your subject where a comment would reasonably appear." },
      { title: "Reading and writing", body: "A writer reads the article and responds to a specific point in it, adding an observation, a caveat or relevant experience." },
      { title: "Selective linking", body: "A link is included only where it directly supports the point being made. Otherwise the comment is posted without one." },
      { title: "Approval tracking", body: "We monitor each comment through moderation and replace any that are not approved within two weeks." },
    ],
    placement: "Links appear either in the comment body where directly relevant or in the commenter name field, depending on the platform. We report attribution accurately and never present a nofollow comment link as though it carries the weight of an editorial placement.",
    quality: "We only comment on moderated blogs with genuine readership and existing discussion. Sites with hundreds of unmoderated spam comments are excluded; appearing alongside that material does more harm than the link could ever do good.",
    useCases: [
      "Adding small-scale diversity to an otherwise narrow profile",
      "Building familiarity with bloggers before pitching guest posts",
      "Supplementing a broader campaign at low cost",
      "New sites establishing a minimal baseline presence",
    ],
    stats: [
      { label: "Moderation approval rate", value: "82%" },
      { label: "Typically nofollow", value: "most placements" },
      { label: "Average comment length", value: "70 words" },
    ],
    packages: [
      { tier: "starter", name: "Comment Ten", price: 65, deliveryDays: 10, revisions: 1, volume: "10 comments", summary: "Ten manual comments on relevant moderated blogs.", features: ["10 manual comments", "Article-specific responses", "Moderation tracking", "Attribution reporting", "Replacement if rejected"] },
      { tier: "growth", name: "Comment Thirty", price: 165, deliveryDays: 18, revisions: 2, volume: "30 comments", summary: "A broader spread across more blogs.", features: ["30 manual comments", "Consistent commenter identity", "Mixed linked and unlinked", "Blog relevance report", "Approval monitoring"], recommended: true },
      { tier: "scale", name: "Ongoing Commenting", price: 420, deliveryDays: 30, revisions: 2, volume: "90 comments", summary: "Sustained monthly commenting activity.", features: ["90 comments across a month", "Blogger relationship notes", "Guest post opportunity flagging", "Full URL log", "Monthly summary"] },
    ],
    faqs: [
      { question: "Are blog comment links worth buying at all?", answer: "Only as a small supporting layer, and only after your budget covers editorial or contextual placements. They provide modest diversity and occasional referral traffic. If someone tells you comments will lift competitive rankings, they are not being straight with you." },
      { question: "Are the links dofollow?", answer: "Most are not. The majority of blog platforms apply nofollow to comment links by default. We report the attribution for every placement and price the service accordingly rather than charging dofollow rates for nofollow links." },
      { question: "How do you get comments approved?", answer: "By writing something the blogger wants published: a specific response to a specific point, in reasonable English, without a sales pitch. Our approval rate sits around 82%, and anything rejected is replaced." },
      { question: "Could this harm my site?", answer: "Done at this scale and quality, no. Harm comes from automated commenting at volume across irrelevant blogs, which is exactly what we do not do. We also cap volumes deliberately rather than selling thousand-comment packages." },
    ],
    reviews: [
      { name: "Marek Zielinski", role: "Blog Owner", country: "Poland", rating: 4, date: "2026-02-06", tier: "Comment Thirty", text: "Realistic expectations set on the first call, which I respected. Comments are clearly written by someone who read the posts." },
      { name: "Tess Van Dijk", role: "Small Business Owner", country: "Netherlands", rating: 4, date: "2026-01-20", tier: "Comment Ten", text: "Cheap, honest, no overselling. They told me to spend elsewhere first and I ignored them, which was my mistake not theirs." },
      { name: "Julian Okafor", role: "SEO Executive", country: "United Kingdom", rating: 5, date: "2026-03-12", tier: "Ongoing Commenting", text: "Two bloggers we commented on regularly later accepted guest posts. That secondary benefit was worth more than the links." },
    ],
    related: ["forum-community-backlinks", "social-bookmarking-backlinks", "guest-post-backlinks", "web-2-0-backlinks"],
    cta: { heading: "Only buy this if it fits your plan", body: "Tell us your current profile and budget and we will say whether comments deserve any of it." },
  },

  {
    slug: "social-bookmarking-backlinks",
    group: "Community Links",
    nav: "Social Bookmarking",
    icon: "spark",
    accent: "sky",
    h1: "Social Bookmarking Backlinks on Platforms People Still Use",
    metaTitle: "Social Bookmarking Backlinks | Manual Submissions & Sharing",
    metaDescription:
      "Manual social bookmarking backlinks on active platforms. Curated submissions with proper titles and descriptions, positioned as a discovery and diversity layer.",
    summary:
      "Manual submissions to bookmarking and content-sharing platforms that still have active users and crawlers.",
    keywords: ["social bookmarking backlinks", "manual social bookmarking", "social sharing links", "niche social bookmarking"],
    variants: ["High-quality social bookmarks", "Niche social bookmarking", "Manual social bookmarking", "Social sharing links"],
    intro: [
      "Social bookmarking is a discovery and indexing layer rather than an authority strategy. Submitting a new page to active bookmarking platforms helps crawlers find it quickly and occasionally brings genuine visitors. That is the honest scope of the benefit.",
      "The reason most bookmarking packages are worthless is that they target hundreds of dead platforms nobody has visited since 2014. We maintain a working list of active sites, remove ones that decay, and submit by hand with a proper title and description for each.",
    ],
    included: [
      "Submissions to a curated list of active bookmarking and sharing platforms",
      "Unique title and description written for each platform's format",
      "Relevant tags and category selection",
      "Profile completion where the platform supports it",
      "Attribution reporting for every submission",
      "Indexing check on submitted URLs",
    ],
    benefits: [
      { title: "Faster discovery", body: "Bookmarking a newly published page gives crawlers an additional path to it, which can shorten the time to indexing." },
      { title: "Active platforms only", body: "Our list is reviewed quarterly and dead or deindexed platforms are removed rather than left in to inflate package numbers." },
      { title: "Written, not automated", body: "Each submission gets its own title and description, because identical text across fifty platforms is duplicate spam." },
      { title: "Sensible expectations", body: "We explain exactly what this does and does not achieve so it stays a small supporting line in your budget." },
    ],
    process: [
      { title: "Page selection", body: "We choose which URLs benefit most, usually newly published content or pages that are slow to index." },
      { title: "Copywriting", body: "A unique title, description and tag set is written for each platform, matching its conventions and character limits." },
      { title: "Manual submission", body: "Submissions are made by hand from established accounts, spaced out rather than fired off simultaneously." },
      { title: "Indexing verification", body: "We check whether submitted URLs are picked up and report which platforms produced followed links." },
    ],
    placement: "Links appear on your submission's page and, on some platforms, within category listings. We complete profile information where available so the account looks like a genuine user rather than a submission bot.",
    quality: "Platforms must be indexed, actively used and free of overwhelming spam to stay on our list. We removed a significant number of platforms last year for exactly those reasons. Where a platform applies nofollow, we say so rather than quietly counting it towards a dofollow total.",
    useCases: [
      "Speeding up discovery of newly published content",
      "Adding low-cost diversity to a link profile",
      "Supporting a content launch alongside stronger placements",
      "Sites with indexing delays on new pages",
    ],
    stats: [
      { label: "Active platforms on our list", value: "48" },
      { label: "Platforms removed last review", value: "17" },
      { label: "Unique copy per submission", value: "always" },
    ],
    packages: [
      { tier: "starter", name: "Launch Push", price: 55, deliveryDays: 7, revisions: 1, volume: "1 URL, 20 platforms", summary: "A quick discovery push for one new page.", features: ["20 manual submissions", "Unique copy per platform", "Tag optimisation", "Attribution report", "Indexing check"] },
      { tier: "growth", name: "Content Support", price: 150, deliveryDays: 14, revisions: 2, volume: "5 URLs, 20 platforms each", summary: "Support for a batch of new content.", features: ["5 URLs submitted", "100 total submissions", "Staggered scheduling", "Profile completion", "Full URL log"], recommended: true },
      { tier: "scale", name: "Monthly Sharing", price: 390, deliveryDays: 30, revisions: 2, volume: "15 URLs monthly", summary: "Ongoing submission of new content each month.", features: ["15 URLs per month", "Priority on slow-indexing pages", "Platform performance reporting", "Quarterly platform list review", "Monthly summary"] },
    ],
    faqs: [
      { question: "Does social bookmarking still work?", answer: "For discovery and a small amount of diversity, yes. For building authority, no. Treat it as a cheap way to help new pages get found, not as something that will move a competitive keyword." },
      { question: "Why only 48 platforms when others offer 500?", answer: "Because roughly 450 of those are dead, deindexed or pure spam. Submitting to them produces nothing except a longer report. We would rather hand you a short list that works." },
      { question: "Do bookmarking platforms give followed links?", answer: "Some are, many are not. We report attribution per platform. The indexing and discovery benefit applies either way, which is the main reason to use this service." },
      { question: "Can this hurt my site?", answer: "Not at this scale with unique copy on active platforms. Harm comes from automated submission of identical text to thousands of spam directories, which is a different service entirely and one we do not offer." },
    ],
    reviews: [
      { name: "Ravi Deshmukh", role: "Content Manager", country: "India", rating: 4, date: "2026-02-24", tier: "Content Support", text: "Pages that used to take a week to appear in search were showing up within two days. That was the whole reason I bought it." },
      { name: "Erika Lindholm", role: "Publisher", country: "Finland", rating: 4, date: "2026-01-17", tier: "Launch Push", text: "Modest service, modest price, described accurately. Refreshing after being offered five hundred bookmarks for the same money elsewhere." },
      { name: "Antoine Girard", role: "Digital Lead", country: "Belgium", rating: 5, date: "2026-03-25", tier: "Monthly Sharing", text: "The quarterly platform review matters. They dropped several sites mid-contract and replaced them without changing the price." },
    ],
    related: ["web-2-0-backlinks", "blog-comment-backlinks", "image-infographic-link-building", "brand-entity-link-building"],
    cta: { heading: "Help new pages get found faster", body: "Send us your latest URLs and we will handle discovery submissions across active platforms." },
  },
];
