import type { BacklinkService } from "@/lib/backlinks/types";

export const SERVICES_B: BacklinkService[] = [
  {
    slug: "press-release-news-backlinks",
    group: "PR & News",
    nav: "Press Release & News Backlinks",
    icon: "megaphone",
    accent: "amber",
    h1: "Press Release and News Backlinks Built Around Real Announcements",
    metaTitle: "Press Release & News Backlinks | Distribution and Pickup",
    metaDescription:
      "Press release backlinks and news website placements built around genuine announcements. Written releases, syndication and honest reporting on link attribution.",
    summary:
      "Distribution and news coverage for announcements that are genuinely worth announcing.",
    keywords: ["press release backlinks", "news backlinks", "press release distribution", "online newspaper backlinks", "news website backlinks"],
    variants: ["Press release distribution", "News backlinks", "News website backlinks", "Online newspaper backlinks", "Media coverage backlinks"],
    intro: [
      "Press releases work when there is news. A funding round, a product launch, a significant hire, an acquisition, original research, an expansion into a new market. Without one of those, a release is just an advert that journalists ignore and syndication networks duplicate.",
      "We write the release properly, distribute it through networks that place on genuine news sites, and tell you exactly what to expect: a burst of syndicated copies, some of which carry followed links, plus a smaller number of genuine pickups if the story merits attention.",
    ],
    included: [
      "Newsworthiness assessment before anything is written",
      "Professionally written release in standard news format",
      "Approved quote drafting for a named spokesperson",
      "Distribution through networks with genuine news-site placement",
      "Pickup report listing every publication that carried the release",
      "Attribution breakdown separating followed from nofollow placements",
    ],
    benefits: [
      { title: "Volume of references quickly", body: "A distributed release produces many syndicated copies within days, which is useful for brand-name visibility and entity confirmation." },
      { title: "Genuine news pickup potential", body: "Where the story merits it, journalists cover it independently, and those articles are considerably more valuable than the syndicated copies." },
      { title: "Written to be read", body: "Releases follow news conventions with a real angle in the first paragraph, not a marketing paragraph dressed as news." },
      { title: "No inflated claims", body: "We tell you in advance that most syndicated copies carry nofollow links. You buy the visibility knowingly." },
    ],
    process: [
      { title: "Angle assessment", body: "We review what you want to announce and tell you honestly whether it will interest anybody outside your company." },
      { title: "Writing and approval", body: "A journalist-trained writer produces the release with headline, lede, body and quotes, and you approve before distribution." },
      { title: "Distribution", body: "The release goes out through networks selected for your sector and region, scheduled for a sensible day and time." },
      { title: "Pickup reporting", body: "We track and report every placement, separating syndicated copies from independent coverage and noting link attribution." },
    ],
    placement: "Links appear in the release body and boilerplate. We recommend one link to the most relevant page and one to your homepage, which is what most distribution networks allow. Independent pickups may or may not include a link depending on the publication's policy.",
    quality: "We only distribute releases with a genuine announcement behind them. If your news does not clear that bar we will say so and suggest a digital PR campaign instead, where a story is built rather than announced. Networks that place exclusively on low-quality duplicate sites are not used.",
    useCases: [
      "Funding rounds, acquisitions and corporate milestones",
      "Product or feature launches with a genuine market angle",
      "Original research or survey findings being published",
      "Market expansions, new offices and significant hires",
    ],
    stats: [
      { label: "Average syndicated pickups", value: "40–90" },
      { label: "Typically followed links", value: "3–8" },
      { label: "Distribution to live", value: "3–5 days" },
    ],
    packages: [
      { tier: "starter", name: "Single Release", price: 390, deliveryDays: 8, revisions: 1, volume: "1 release", summary: "One written and distributed announcement.", features: ["Newsworthiness review", "Professionally written release", "Standard network distribution", "Pickup report", "Attribution breakdown"] },
      { tier: "growth", name: "Release Plus Outreach", price: 1180, deliveryDays: 18, revisions: 2, volume: "1 release + 30 pitches", summary: "Distribution combined with direct journalist pitching.", features: ["Written release", "Premium distribution network", "30 targeted journalist pitches", "Follow-up handling", "Coverage and link report"], recommended: true },
      { tier: "scale", name: "Quarterly News Programme", price: 3200, deliveryDays: 90, revisions: 3, volume: "4 releases + outreach", summary: "A planned announcement calendar across a quarter.", features: ["4 releases across the quarter", "Announcement calendar planning", "120 journalist pitches total", "Spokesperson quote library", "Quarterly coverage review"] },
    ],
    faqs: [
      { question: "Do press release links actually pass value?", answer: "Syndicated copies mostly carry nofollow links and duplicate content, so their direct ranking contribution is limited. Their real value is brand-name visibility, entity confirmation and the chance of genuine journalist pickup. We are explicit about this split in every report." },
      { question: "What if I do not have real news?", answer: "Then a press release is the wrong product and we will tell you. Manufactured announcements get ignored and can make a brand look thin. A digital PR campaign that builds a story around data is usually the better route." },
      { question: "How many links can the release contain?", answer: "Typically two: one contextual link to the most relevant page and one in the boilerplate. Networks reject releases stuffed with links, and journalists ignore them, so restraint here is practical rather than cautious." },
      { question: "Will a major newspaper cover my announcement?", answer: "Possibly, if the story genuinely warrants it, but nobody can promise national coverage and you should be wary of anyone who does. We pitch honestly and report exactly what landed." },
    ],
    reviews: [
      { name: "Katarzyna Wojcik", role: "Communications Director", country: "Poland", rating: 5, date: "2026-02-11", tier: "Release Plus Outreach", text: "The release was rewritten twice before they were happy with the opening line. Two trade publications covered it independently, which is what we actually wanted." },
      { name: "Samuel Adeyemi", role: "Founder", country: "United States", rating: 4, date: "2026-01-31", tier: "Single Release", text: "Clear that most pickups would be nofollow syndication, so no surprises in the report. Good value for brand visibility around our funding news." },
      { name: "Linnea Bergstrom", role: "Head of Brand", country: "Sweden", rating: 5, date: "2026-03-16", tier: "Quarterly News Programme", text: "Planning four announcements across the quarter forced us to think about what was genuinely newsworthy. The calendar was as useful as the coverage." },
    ],
    related: ["digital-pr-backlinks", "brand-entity-link-building", "editorial-backlinks", "premium-link-building"],
    cta: { heading: "Tell us what you want to announce", body: "We will assess honestly whether it is newsworthy and recommend distribution or a different approach." },
  },

  {
    slug: "digital-pr-backlinks",
    group: "PR & News",
    nav: "Digital PR Backlinks",
    icon: "target",
    accent: "violet",
    h1: "Digital PR Backlinks From Stories Journalists Want to Cover",
    metaTitle: "Digital PR Backlinks | Data-Led Campaigns and Media Coverage",
    metaDescription:
      "Digital PR backlinks earned through data-led campaigns. Original research, story development, journalist outreach and coverage reporting with link attribution.",
    summary:
      "Original research and story development pitched to newsrooms, earning coverage that carries links and reach.",
    keywords: ["digital PR backlinks", "media coverage backlinks", "data led PR campaign", "journalist outreach links"],
    variants: ["Digital PR campaigns", "Data journalism outreach", "Expert commentary placement", "Media coverage backlinks", "Brand mention campaigns"],
    intro: [
      "Digital PR earns links by giving journalists something they need: a statistic, a study, an expert who can explain something quickly, or a story with a genuine angle. The link is a by-product of coverage, which is why the results tend to be strong and difficult for competitors to replicate.",
      "Campaigns start with the angle, not the link target. We develop something defensible, usually from original data, then pitch it to the reporters who cover that beat. Expect a spread of outcomes: some followed links, some brand mentions without links, and secondary pickups you did not pitch.",
    ],
    included: [
      "Campaign concept development with two or three competing angles",
      "Original data work: survey design, dataset analysis or internal data anonymisation",
      "Press asset production, including a methodology note and charts",
      "Tiered journalist outreach with exclusive windows for priority titles",
      "Reactive commentary placement when related news breaks",
      "Coverage report listing publications, reach, links and mentions",
    ],
    benefits: [
      { title: "Links you cannot buy", body: "Coverage on national and major trade titles is not purchasable. Earning it through a story is the only realistic route." },
      { title: "Multiplier effect", body: "Strong campaigns get syndicated and referenced by other writers for months, producing links long after outreach ends." },
      { title: "Brand and entity value", body: "Being quoted as a source shapes how your company is described across the web, which increasingly affects how AI systems summarise you." },
      { title: "Defensible methodology", body: "Every statistic can be traced to a stated method, so a sceptical journalist gets an answer rather than a dead end." },
    ],
    process: [
      { title: "Angle development", body: "We workshop several concepts against what your target publications have actually covered in the last year, then pick the strongest." },
      { title: "Data and asset build", body: "We run the survey or analysis, write the methodology, produce visuals and build the landing page brief for the asset." },
      { title: "Tiered outreach", body: "Priority titles are approached first with a short exclusive window, followed by a wider regional and trade push." },
      { title: "Coverage and reporting", body: "We track every placement, chase unlinked mentions for attribution and report reach alongside link quality." },
    ],
    placement: "Links usually appear where the journalist cites your data or names your company as the source. We push for a link to the research page rather than the homepage, because that is where the citation logically belongs and it keeps the placement natural.",
    quality: "Success is measured in secured coverage on relevant titles, not emails sent. We prioritise publications your buyers actually read over vanity placements, and we report unlinked mentions honestly rather than hiding them, because they still shape brand perception and entity signals.",
    useCases: [
      "Brands with access to interesting internal or industry data",
      "Companies needing coverage on titles that never sell placements",
      "Businesses building entity strength for AI and brand search",
      "Competitive niches where bought links are no longer differentiating",
    ],
    stats: [
      { label: "Median coverage per campaign", value: "14 outlets" },
      { label: "Share carrying followed links", value: "about 60%" },
      { label: "Campaign duration", value: "4–8 weeks" },
    ],
    packages: [
      { tier: "starter", name: "Reactive Commentary", price: 980, deliveryDays: 30, revisions: 1, volume: "Ongoing pitching, 1 month", summary: "Expert commentary pitched against breaking stories.", features: ["Spokesperson positioning", "Daily source-request monitoring", "Unlimited reactive pitches for a month", "Quote writing", "Coverage report"] },
      { tier: "growth", name: "Data Campaign", price: 3400, deliveryDays: 45, revisions: 2, volume: "1 full campaign", summary: "A complete research-led campaign from concept to coverage.", features: ["Angle development workshop", "Original data collection", "Press assets and visuals", "Tiered journalist outreach", "Full coverage and link report"], recommended: true },
      { tier: "scale", name: "Always-On PR", price: 8900, deliveryDays: 90, revisions: 3, volume: "2 campaigns + reactive", summary: "Two campaigns plus continuous reactive commentary.", features: ["2 data campaigns per quarter", "Continuous reactive pitching", "Journalist relationship building", "Syndication tracking", "Named PR strategist"] },
    ],
    faqs: [
      { question: "How many links will a campaign produce?", answer: "A well-executed campaign typically earns coverage across ten to twenty outlets, of which roughly six in ten include a followed link. We give a range rather than a guarantee because editorial decisions are not ours to make, and any agency quoting an exact number is guessing." },
      { question: "What if we have no data to work with?", answer: "Most companies have more than they think: product usage patterns, pricing trends, customer survey responses, operational statistics. Where nothing usable exists we can commission a survey, which is built into the Data Campaign package." },
      { question: "Are unlinked mentions a failure?", answer: "No. They still build brand recognition and strengthen how your company is described across the web, which matters for entity recognition and increasingly for AI-generated summaries. We also pursue attribution afterwards where the publication allows it." },
      { question: "How is this different from a press release?", answer: "A release announces something you did. Digital PR builds a story a journalist wants to tell, usually grounded in data about the wider market rather than about your company. Releases are faster and cheaper; PR campaigns earn stronger links." },
    ],
    reviews: [
      { name: "Isabelle Moreau", role: "CMO", country: "France", rating: 5, date: "2026-02-27", tier: "Data Campaign", text: "They killed our first two ideas with evidence that nobody had covered similar angles. The third concept ran in eleven outlets including two we had chased for years." },
      { name: "Ben Halvorsen", role: "Head of Content", country: "Denmark", rating: 5, date: "2026-01-14", tier: "Always-On PR", text: "The reactive commentary is the underrated part. Our CTO has been quoted six times this quarter simply because someone was watching the right feeds." },
      { name: "Adaeze Obi", role: "Marketing Director", country: "United States", rating: 4, date: "2026-03-23", tier: "Reactive Commentary", text: "Slower start than expected while they learned our sector, then three placements in the final fortnight. Honest weekly updates throughout." },
    ],
    related: ["press-release-news-backlinks", "editorial-backlinks", "brand-entity-link-building", "image-infographic-link-building"],
    cta: { heading: "Find out if you have a story", body: "Send us what data you have access to and we will tell you whether a campaign is viable." },
  },

  {
    slug: "resource-link-building",
    group: "Outreach Services",
    nav: "Resource Link Building",
    icon: "compass",
    accent: "brand",
    h1: "Resource Page Link Building Through Targeted Outreach",
    metaTitle: "Resource Page Link Building | Curated List Placements",
    metaDescription:
      "Resource page link building through manual prospecting and outreach. Placements on curated industry lists, library guides and genuinely maintained resource hubs.",
    summary:
      "Getting your best asset added to the curated lists that already send people to useful resources.",
    keywords: ["resource page backlinks", "resource link building", "curated list links", "resource page outreach"],
    variants: ["Resource page backlinks", "Curated list placements", "Library guide links", "Industry resource hubs", "Tool list placements"],
    intro: [
      "Resource pages exist because somebody decided to collect the best material on a subject and keep it updated. Getting onto one is straightforward in principle: have something genuinely worth listing, then tell the curator it exists.",
      "The work is in the qualification. Most pages returned by standard resource-page searches are abandoned, unmaintained or so stuffed with outbound links that another entry means nothing. We check when each page was last updated and whether it still sends traffic before spending your budget pitching to it.",
    ],
    included: [
      "Asset review to identify which of your pages is genuinely listable",
      "Resource page prospecting with last-updated and traffic checks",
      "Curator contact identification and verification",
      "Personalised outreach explaining the specific fit",
      "Suggestions for improving the asset where it falls short",
      "Placement log with page URL and position in the list",
    ],
    benefits: [
      { title: "Naturally relevant by design", body: "Resource pages are topic-specific by definition, so any placement you win carries strong topical alignment automatically." },
      { title: "Long-lived placements", body: "Curators maintain these pages deliberately. Once listed, entries tend to stay for years unless the resource itself goes offline." },
      { title: "Qualified referral clicks", body: "People browsing a curated list are actively looking for a solution, so the traffic converts better than most link sources." },
      { title: "Honest asset feedback", body: "If your page is not good enough to be listed, we say so and explain what would need to change rather than pitching it anyway." },
    ],
    process: [
      { title: "Asset qualification", body: "We assess which page you own could earn a listing, judged on usefulness rather than commercial intent." },
      { title: "Page prospecting", body: "We find resource pages in your subject, then filter out anything abandoned, deindexed or overloaded with existing links." },
      { title: "Curator outreach", body: "Each curator receives a specific message naming their page and explaining what your resource adds to their list." },
      { title: "Follow-up and logging", body: "One polite follow-up is sent where there is no reply, and every outcome is recorded including declines." },
    ],
    placement: "Your entry appears within the list itself, usually with your page title as the anchor and a short description. We ask for placement in the most relevant section rather than an appended miscellaneous category at the bottom, since position affects both clicks and crawl attention.",
    quality: "We only pitch to pages updated within the last eighteen months that still receive organic traffic and maintain a sensible number of outbound links. Pages that exist purely to host links, or that accept any submission for a fee, are excluded from prospecting entirely.",
    useCases: [
      "Free tools, calculators and templates that deserve wider distribution",
      "Comprehensive guides that outperform what is currently listed",
      "Original research that curators would want to reference",
      "Nonprofit and educational resources seeking legitimate visibility",
    ],
    stats: [
      { label: "Prospects rejected at qualification", value: "61%" },
      { label: "Average placement acceptance rate", value: "9%" },
      { label: "Typical campaign length", value: "3–5 weeks" },
    ],
    packages: [
      { tier: "starter", name: "Resource Sprint", price: 340, deliveryDays: 21, revisions: 1, volume: "3 secured placements", summary: "A focused push around one strong asset.", features: ["1 asset qualified", "60 pages prospected", "3 secured placements", "Asset improvement notes", "Outcome log"] },
      { tier: "growth", name: "Curated Campaign", price: 940, deliveryDays: 32, revisions: 2, volume: "9 secured placements", summary: "A wider campaign across multiple resource categories.", features: ["2 assets qualified", "180 pages prospected", "9 secured placements", "Section placement requests", "Traffic-weighted prioritisation"], recommended: true },
      { tier: "scale", name: "Resource Programme", price: 2480, deliveryDays: 55, revisions: 3, volume: "25 secured placements", summary: "A sustained programme across your full asset library.", features: ["Full asset library review", "500+ pages prospected", "25 secured placements", "Quarterly re-pitch of declines", "Placement retention monitoring"] },
    ],
    faqs: [
      { question: "What makes a page listable on a resource page?", answer: "It has to be useful without requiring a purchase. Free tools, detailed guides, original data and templates get listed. Product pages and pricing pages almost never do, regardless of how well written they are. We will tell you which of your pages qualifies before starting." },
      { question: "Why is the acceptance rate only around 9%?", answer: "Because curators are selective and many pages are no longer actively maintained. We price on secured placements rather than outreach volume, so the acceptance rate affects our workload rather than your cost." },
      { question: "Do you pay for these placements?", answer: "No. Resource page placements are earned by having something worth listing. If a page demands payment for inclusion we treat it as a paid directory and exclude it from this service." },
      { question: "Can you improve my asset first?", answer: "We will tell you exactly what is holding it back and can arrange the content work separately. Pitching a weak asset wastes outreach opportunities that are difficult to revisit later." },
    ],
    reviews: [
      { name: "Harriet Nolan", role: "Nonprofit Director", country: "Ireland", rating: 5, date: "2026-02-18", tier: "Curated Campaign", text: "They rewrote our pitch angle after realising the guide was stronger for practitioners than students. Nine placements from a resource we had never promoted." },
      { name: "Viktor Mihailov", role: "Product Lead", country: "Bulgaria", rating: 4, date: "2026-01-27", tier: "Resource Sprint", text: "Told us plainly our calculator needed a proper explanation page before pitching. Annoying to hear, correct in hindsight." },
      { name: "Nora Eriksen", role: "Head of SEO", country: "Norway", rating: 5, date: "2026-03-10", tier: "Resource Programme", text: "The retention monitoring caught two placements that were removed during site redesigns, and both were reinstated after they followed up." },
    ],
    related: ["broken-link-building", "edu-gov-resource-links", "image-infographic-link-building", "competitor-link-building"],
    cta: { heading: "Find out which of your pages is listable", body: "Send us your best free resource and we will assess its chances honestly." },
  },

  {
    slug: "broken-link-building",
    group: "Outreach Services",
    nav: "Broken Link Building",
    icon: "gauge",
    accent: "sky",
    h1: "Broken Link Building That Solves a Problem for the Publisher",
    metaTitle: "Broken Link Building | Dead Link Replacement Outreach",
    metaDescription:
      "Broken link building through dead link discovery and replacement outreach. We find broken references on relevant pages and offer your content as the fix.",
    summary:
      "Finding dead links on relevant pages and offering your content as the replacement.",
    keywords: ["broken link building", "dead link replacement", "link reclamation outreach", "404 link building"],
    variants: ["Dead link replacement", "404 resource recovery", "Broken resource outreach", "Link reclamation"],
    intro: [
      "Broken link building is one of the few outreach approaches where you are genuinely doing the publisher a favour. Their page contains a link to something that no longer exists, which is bad for their readers. You point it out and offer a working alternative.",
      "The catch is that your replacement has to actually replace the dead resource. If the original was a detailed statistics page and you offer a product page, the answer will be no. We match replacements carefully and, where nothing suitable exists, we tell you what would need creating.",
    ],
    included: [
      "Broken link discovery across relevant pages in your subject",
      "Verification that each dead URL genuinely returns an error",
      "Assessment of what the original resource contained",
      "Matching of your existing pages as replacements",
      "Outreach identifying the broken link and proposing the fix",
      "Report showing fixes accepted, declined and unanswered",
    ],
    benefits: [
      { title: "A reason to reply", body: "Publishers respond to broken link emails far more often than to generic link requests, because the message is useful to them regardless of the offer." },
      { title: "Established placement context", body: "The dead link was already in a relevant position on the page, so your replacement inherits that context exactly." },
      { title: "Genuinely goodwill-based", body: "Even when a publisher chooses a different replacement, you have made a helpful contact rather than burned one." },
      { title: "Compounding prospect lists", body: "Pages with one broken link often have several, and the same publishers reappear across future campaigns." },
    ],
    process: [
      { title: "Target mapping", body: "We identify the kinds of resources in your subject that commonly go offline, then find pages still linking to them." },
      { title: "Verification", body: "Every candidate URL is checked to confirm it genuinely fails, and we look at archived copies to see what the original contained." },
      { title: "Replacement matching", body: "We match your pages to each dead resource and flag gaps where you have nothing comparable to offer." },
      { title: "Outreach and tracking", body: "Publishers are contacted with the specific broken URL and the proposed fix, and every outcome is recorded." },
    ],
    placement: "Your link takes the position of the broken one, inside the same paragraph or list entry. That is the cleanest possible placement because the context was written before anybody knew your page existed.",
    quality: "We only pursue broken links on pages that are indexed, maintained and receiving traffic. A dead link on an abandoned page is not worth fixing for anybody. We also verify that the linking page itself has not been deindexed, which is a common waste of outreach effort.",
    useCases: [
      "Sites with strong evergreen guides and reference content",
      "Businesses in sectors where older resources frequently disappear",
      "Teams wanting outreach with a higher-than-average response rate",
      "Campaigns needing placements on established, aged pages",
    ],
    stats: [
      { label: "Average response rate", value: "23%" },
      { label: "Broken links verified per campaign", value: "200+" },
      { label: "Typical campaign length", value: "3–4 weeks" },
    ],
    packages: [
      { tier: "starter", name: "Broken Link Test", price: 320, deliveryDays: 21, revisions: 1, volume: "3 secured replacements", summary: "A trial campaign on one topic area.", features: ["100 broken links verified", "Replacement matching", "3 secured placements", "Archive analysis of dead pages", "Content gap notes"] },
      { tier: "growth", name: "Replacement Campaign", price: 880, deliveryDays: 30, revisions: 2, volume: "8 secured replacements", summary: "A full campaign across several topic clusters.", features: ["300 broken links verified", "8 secured placements", "Multi-topic coverage", "Publisher relationship notes", "Decline reason reporting"], recommended: true },
      { tier: "scale", name: "Recovery Programme", price: 2340, deliveryDays: 50, revisions: 3, volume: "22 secured replacements", summary: "A large-scale programme including repeat publisher outreach.", features: ["800+ broken links verified", "22 secured placements", "Repeat publisher targeting", "Content creation recommendations", "Quarterly re-scan"] },
    ],
    faqs: [
      { question: "What if I do not have a suitable replacement page?", answer: "We flag it during the matching stage and tell you what the dead resource contained. Often a modest new page is enough to unlock dozens of prospects, and we would rather tell you that than pitch a mismatched URL and burn the contacts." },
      { question: "Why is the response rate higher than normal outreach?", answer: "Because the email is useful even if the publisher ignores your suggestion. You are reporting a fault on their page. That framing gets replies from people who delete standard link requests unread." },
      { question: "Do publishers always use my link as the replacement?", answer: "No. Sometimes they pick a different resource or simply remove the dead link. We only charge for secured placements, so those outcomes cost you nothing beyond the campaign fee structure we agree upfront." },
      { question: "Is this the same as link reclamation?", answer: "They are related but distinct. Broken link building targets dead links pointing at other people's resources. Reclamation recovers links that once pointed at your site and have since broken or been removed, which we handle within our competitor and brand services." },
    ],
    reviews: [
      { name: "Callie Brennan", role: "SEO Specialist", country: "United States", rating: 5, date: "2026-02-09", tier: "Replacement Campaign", text: "They found a discontinued industry report that forty sites still linked to. We published a replacement and eight of them switched over." },
      { name: "Jasper Vandenberg", role: "Web Manager", country: "Belgium", rating: 4, date: "2026-01-19", tier: "Broken Link Test", text: "Three placements from a hundred verified links felt low until I saw the decline reasons. Most pages had simply removed the link entirely." },
      { name: "Meera Krishnan", role: "Digital Manager", country: "India", rating: 5, date: "2026-03-27", tier: "Recovery Programme", text: "The content gap recommendations were the unexpected value. We built two pages specifically to serve broken link opportunities they identified." },
    ],
    related: ["resource-link-building", "competitor-link-building", "niche-edit-backlinks", "brand-entity-link-building"],
    cta: { heading: "See how many broken links point at gaps you could fill", body: "We will run a discovery scan on your subject area and show you the opportunity volume." },
  },

  {
    slug: "image-infographic-link-building",
    group: "Outreach Services",
    nav: "Image & Infographic Link Building",
    icon: "layers",
    accent: "violet",
    h1: "Image and Infographic Link Building Through Attribution",
    metaTitle: "Image & Infographic Backlinks | Visual Attribution Links",
    metaDescription:
      "Image and infographic link building through visual asset creation, outreach and reverse image attribution recovery. Earn links from publishers using your visuals.",
    summary:
      "Visual assets worth embedding, plus recovery of links from publishers already using your images without credit.",
    keywords: ["infographic backlinks", "image backlinks", "visual content link building", "image attribution links", "reverse image link building"],
    variants: ["Infographic outreach", "Image attribution links", "Visual content link building", "Reverse image link building", "Data visualisation outreach"],
    intro: [
      "Publishers need visuals and most cannot produce them. A clear chart, a well-designed process diagram or a genuinely useful infographic gives writers something they can embed, and the embed comes with a credit link.",
      "There is a second, often overlooked opportunity: images you already own that other sites are using without attribution. A reverse image search frequently surfaces dozens of uncredited uses, and a polite request converts a surprising number of them into links.",
    ],
    included: [
      "Concept development based on data your audience actually wants visualised",
      "Professional design of the infographic or chart set",
      "Embed code generation with correct attribution markup",
      "Outreach to publishers covering the subject",
      "Reverse image search across your existing visual library",
      "Attribution requests for uncredited uses already in the wild",
    ],
    benefits: [
      { title: "Assets publishers actively want", body: "Writers under deadline pressure will embed a clear visual rather than commission one, and the credit link is standard practice." },
      { title: "Recovers value you already created", body: "Uncredited image use is extremely common. Converting those uses into links costs nothing to create, only to pursue." },
      { title: "Repeated over time", body: "A good visual gets embedded for years, producing links long after the outreach campaign has finished." },
      { title: "Works alongside PR", body: "Charts produced for a digital PR campaign can be repurposed here, so one data set supports two link routes." },
    ],
    process: [
      { title: "Concept and data", body: "We pick a subject where a visual genuinely explains something faster than text, and assemble the underlying data." },
      { title: "Design and embed setup", body: "A designer produces the asset, and we create a copy-paste embed snippet that includes the attribution link." },
      { title: "Publisher outreach", body: "We pitch writers who have covered the topic and would benefit from the visual, offering free use with credit." },
      { title: "Attribution recovery", body: "In parallel we reverse-search your existing images, identify uncredited uses and request attribution." },
    ],
    placement: "Links appear in the image credit line beneath or beside the visual, or inside the embed code itself. Where a publisher prefers, we accept a text citation in the body copy instead, which often sits in a more prominent position anyway.",
    quality: "The asset has to earn its place. We decline to produce infographics that simply restate widely known facts, because nobody embeds those. Outreach is limited to publishers who genuinely cover the subject, and we never scrape contact lists.",
    useCases: [
      "Companies sitting on data that would visualise well",
      "Brands with existing photography or diagrams being reused online",
      "Technical subjects where a process diagram aids explanation",
      "Campaigns needing assets that keep earning links passively",
    ],
    stats: [
      { label: "Average embeds per asset", value: "11" },
      { label: "Uncredited uses found per audit", value: "24 median" },
      { label: "Attribution request success", value: "38%" },
    ],
    packages: [
      { tier: "starter", name: "Attribution Audit", price: 260, deliveryDays: 14, revisions: 1, volume: "Existing images", summary: "Recover links from images already being used.", features: ["Reverse image search across your library", "Uncredited use report", "Attribution outreach to 40 sites", "Response tracking", "Recovered link log"] },
      { tier: "growth", name: "Infographic Campaign", price: 1240, deliveryDays: 32, revisions: 2, volume: "1 asset + outreach", summary: "One designed asset with a full outreach push.", features: ["Concept and data research", "Professional design", "Embed code with attribution", "80 publisher pitches", "Ongoing embed monitoring"], recommended: true },
      { tier: "scale", name: "Visual Asset Programme", price: 3100, deliveryDays: 60, revisions: 3, volume: "3 assets + audits", summary: "A series of visuals plus recurring attribution recovery.", features: ["3 designed assets", "Quarterly reverse image audits", "240 publisher pitches", "Asset refresh recommendations", "Embed performance reporting"] },
    ],
    faqs: [
      { question: "Do infographics still earn links in 2026?", answer: "Generic ones do not. Clear data visualisations that explain something specific still get embedded regularly, particularly charts journalists can drop into an article. We focus on that end of the spectrum rather than the decorative posters that were common a decade ago." },
      { question: "How does reverse image attribution work?", answer: "We search for copies of your existing images across the web, identify pages using them without a credit link, and contact the publisher asking for attribution. Most comply because using an image without credit is a licensing issue they would rather resolve quickly and politely." },
      { question: "Who owns the asset you design?", answer: "You do, completely. Source files are handed over on delivery and you can reuse the visual anywhere, including in paid campaigns or print." },
      { question: "What if publishers embed the image but strip the link?", answer: "It happens, and we monitor for it. A short follow-up asking for the credit to be restored resolves most cases, and the embed code is structured to make removing the attribution deliberate rather than accidental." },
    ],
    reviews: [
      { name: "Felix Andersson", role: "Data Analyst", country: "Sweden", rating: 5, date: "2026-02-22", tier: "Infographic Campaign", text: "The chart they designed from our internal figures has been embedded by fourteen sites so far, including two we pitched unsuccessfully last year." },
      { name: "Rosa Iglesias", role: "Brand Manager", country: "Spain", rating: 5, date: "2026-01-08", tier: "Attribution Audit", text: "Thirty-one sites were using our product photography with no credit. Eleven added links within a fortnight of being asked politely." },
      { name: "Graham Sutherland", role: "Marketing Head", country: "United Kingdom", rating: 4, date: "2026-03-29", tier: "Visual Asset Programme", text: "The second asset underperformed and they said so directly rather than burying it in the report, then adjusted the third concept accordingly." },
    ],
    related: ["digital-pr-backlinks", "resource-link-building", "brand-entity-link-building", "social-bookmarking-backlinks"],
    cta: { heading: "Check who is using your images already", body: "We will run a reverse image audit and show you the uncredited uses worth pursuing." },
  },

  {
    slug: "saas-software-backlinks",
    group: "Specialist Programmes",
    nav: "SaaS & Software Backlinks",
    icon: "gauge",
    accent: "brand",
    h1: "SaaS and Software Backlinks Across Reviews, Directories and Editorial",
    metaTitle: "SaaS Backlinks | Software Directory & Review Link Building",
    metaDescription:
      "SaaS and software backlinks from review platforms, software directories, startup media and technology publications. Product-led link building for tools and platforms.",
    summary:
      "The full mix software companies need: review platforms, tool directories, startup media and technology editorial.",
    keywords: ["SaaS backlinks", "software directory backlinks", "startup backlinks", "product review backlinks", "tool listing backlinks"],
    variants: ["SaaS guest posts", "Software directory backlinks", "Startup backlinks", "Product review backlinks", "SaaS resource links", "Tool listing backlinks"],
    intro: [
      "Software companies have link opportunities that other businesses do not. Review platforms, comparison sites, tool directories, integration partner pages, alternative-to listings, startup databases and developer communities all exist specifically to catalogue products like yours.",
      "Most SaaS teams work through a handful of these and stop. We work the full surface systematically, then add editorial placements on technology publications where the buying audience actually reads, so the profile is not made up entirely of listings.",
    ],
    included: [
      "Software directory and review platform audit covering existing listings",
      "Submission to relevant tool directories and comparison sites",
      "Integration and partner page link opportunities with your existing vendors",
      "Alternative-to and comparison listing placement where permitted",
      "Guest placements on technology and SaaS publications",
      "Developer and product community participation where appropriate",
    ],
    benefits: [
      { title: "Purchase-intent traffic", body: "Directory and review listings send visitors who are actively comparing tools, which is the highest-intent traffic in the mix." },
      { title: "Partner links are free", body: "Your existing integration partners often have listing pages you have never claimed. We find them and get you added." },
      { title: "Category visibility", body: "Being present across the standard comparison sources shapes how buyers and AI assistants describe your category position." },
      { title: "Editorial balance", body: "Listings alone make a thin profile, so we pair them with genuine technology publication placements." },
    ],
    process: [
      { title: "Ecosystem audit", body: "We map every directory, review site, marketplace and partner page where a product like yours could legitimately appear." },
      { title: "Gap identification", body: "We compare your presence against two or three direct competitors and list the sources they appear on and you do not." },
      { title: "Submission and outreach", body: "Listings are completed by hand with accurate product details, and editorial placements are pitched separately." },
      { title: "Maintenance", body: "Listings are reviewed quarterly so descriptions, pricing and feature details stay current rather than drifting out of date." },
    ],
    placement: "Directory listings link to your homepage or a category-relevant landing page. Editorial placements use in-content links to feature pages or documentation, because those are the pages buyers actually need when the article mentions a capability.",
    quality: "We only submit to directories with genuine traffic and editorial standards, and we avoid paid listing farms that exist purely to sell placements. Review platform submissions follow each platform's rules precisely; we never generate or incentivise fake reviews.",
    useCases: [
      "Early-stage SaaS building initial category presence",
      "Established tools whose listings have gone stale",
      "Products entering a new category or vertical",
      "Companies whose competitors dominate comparison sources",
    ],
    stats: [
      { label: "Relevant SaaS directories tracked", value: "180+" },
      { label: "Average partner links found", value: "7 per audit" },
      { label: "Typical programme length", value: "6–10 weeks" },
    ],
    packages: [
      { tier: "starter", name: "Directory Foundation", price: 420, deliveryDays: 20, revisions: 1, volume: "30 listings", summary: "Core software directory and review presence.", features: ["Ecosystem audit", "30 curated listings", "Accurate product descriptions", "Screenshot and asset upload", "Listing inventory"] },
      { tier: "growth", name: "SaaS Link Mix", price: 1680, deliveryDays: 35, revisions: 2, volume: "40 listings + 4 editorial", summary: "Directory coverage combined with technology editorial.", features: ["Full ecosystem coverage", "Competitor gap analysis", "Partner page outreach", "4 technology publication placements", "Quarterly listing refresh"], recommended: true },
      { tier: "scale", name: "Category Leadership", price: 4200, deliveryDays: 70, revisions: 3, volume: "60 listings + 12 editorial", summary: "Comprehensive presence across the category.", features: ["60 listings and marketplaces", "12 editorial placements", "Alternative-to page targeting", "Integration partner programme", "Named SaaS strategist"] },
    ],
    faqs: [
      { question: "Do you write or buy reviews on review platforms?", answer: "Never. Fabricated reviews violate every major platform's terms and can get your profile removed entirely. We create and optimise the listing itself, then advise on how to request reviews from genuine customers through the platform's own mechanisms." },
      { question: "Are software directory links nofollow?", answer: "Many are, particularly the largest review platforms. Those listings still matter because they drive high-intent traffic and shape category perception. We report attribution clearly and balance them with followed editorial placements." },
      { question: "What are integration partner links?", answer: "If your product integrates with other tools, those vendors usually maintain partner or integration directories. Many companies never claim their entry. These links are relevant, followed and free, which makes them the first thing we look for." },
      { question: "Can you help with alternative-to pages?", answer: "Where the site accepts submissions or updates, yes. We will not attempt to manipulate independent comparison content, but many of these pages have a formal process for adding products that nobody bothers to use." },
    ],
    reviews: [
      { name: "Dimitri Volkov", role: "Head of Growth", country: "Estonia", rating: 5, date: "2026-02-05", tier: "SaaS Link Mix", text: "The partner page audit found nine integration directories we were entitled to be in and had never claimed. Free links we had left sitting there for three years." },
      { name: "Amelia Foster", role: "VP Marketing", country: "United States", rating: 5, date: "2026-01-23", tier: "Category Leadership", text: "They refused to touch review generation and explained exactly why. Then they showed us how to ask customers properly, which worked better anyway." },
      { name: "Kenji Nakamura", role: "Founder", country: "Canada", rating: 4, date: "2026-03-13", tier: "Directory Foundation", text: "Thirty solid listings with accurate descriptions. Would have liked faster turnaround, though the detail on each submission explains the time." },
    ],
    related: ["guest-post-backlinks", "citation-directory-backlinks", "competitor-link-building", "monthly-link-building"],
    cta: { heading: "See which directories your competitors are in", body: "We will run a gap audit across the software ecosystem and show you what you are missing." },
  },

  {
    slug: "edu-gov-resource-links",
    group: "Specialist Programmes",
    nav: "EDU & GOV Resource Links",
    icon: "shield",
    accent: "amber",
    h1: "EDU and GOV Resource Links Earned Through Legitimate Relevance",
    metaTitle: "EDU & GOV Resource Links | Institutional Resource Placements",
    metaDescription:
      "EDU and GOV resource links earned through legitimate relevance on university guides and public sector resource pages. No domain-extension myths, no manipulation.",
    summary:
      "Placements on university guides and public sector resource pages, earned because the resource genuinely belongs there.",
    keywords: ["edu backlinks", "gov backlinks", "university resource links", "educational resource links", "scholarship resource backlinks"],
    variants: ["EDU resource backlinks", "University resource links", "Educational resource links", "GOV resource backlinks", "Government resource links", "Scholarship resource backlinks"],
    intro: [
      "First, the correction that matters most: a link is not valuable because the domain ends in .edu or .gov. That myth has sold a lot of worthless placements. A forgotten student profile page on a university subdomain carries almost nothing, while a maintained library guide on the same domain can be genuinely strong.",
      "What makes these placements worth pursuing is that institutional resource pages are heavily curated, rarely sell links, and are maintained by librarians and public sector staff who only add resources that serve their users. Earning a place is slow, and that is precisely the point.",
    ],
    included: [
      "Assessment of whether your resource plausibly belongs on an institutional page",
      "Prospecting across university library guides and departmental resource lists",
      "Public sector and local authority resource page identification",
      "Outreach to named librarians, faculty or department contacts",
      "Guidance on scholarship programmes where you intend to run one genuinely",
      "Placement reporting with page purpose and maintenance status",
    ],
    benefits: [
      { title: "Curated by people, not algorithms", body: "Institutional pages are maintained by staff with a duty to their users, so inclusion signals genuine usefulness." },
      { title: "Rarely purchasable", body: "Because these placements cannot be bought, they are difficult for competitors to replicate at any budget." },
      { title: "Extremely durable", body: "Library guides and public resource pages are maintained for years, and entries are removed only when the resource itself fails." },
      { title: "Honest about the myth", body: "We assess each page on its merits rather than charging a premium for a domain extension." },
    ],
    process: [
      { title: "Eligibility review", body: "We look at what you offer and determine honestly whether an institution would have reason to reference it." },
      { title: "Institutional prospecting", body: "We identify relevant library guides, course resource lists and public sector pages, checking each is actively maintained." },
      { title: "Named contact outreach", body: "Emails go to the specific librarian or department contact responsible for the page, explaining the relevance in plain terms." },
      { title: "Follow-through", body: "Institutional response cycles are slow, so we maintain polite follow-up over weeks and report every outcome." },
    ],
    placement: "Placements appear within curated resource lists, reading lists or guidance pages, usually with a descriptive anchor set by the institution. We do not request specific anchor text here because doing so is inappropriate and damages credibility with the contact.",
    quality: "We assess each page individually: is it maintained, is it reachable from the site's navigation, does it serve actual students or citizens, and is our resource genuinely relevant to its purpose. Abandoned pages and open-submission subdomains are excluded regardless of the domain extension.",
    useCases: [
      "Free tools and calculators with genuine educational value",
      "Original research relevant to academic or public interest",
      "Nonprofit and public interest organisations",
      "Companies running legitimate, properly administered scholarship programmes",
    ],
    stats: [
      { label: "Average acceptance rate", value: "4–7%" },
      { label: "Typical response window", value: "3–6 weeks" },
      { label: "Placement retention", value: "very high" },
    ],
    packages: [
      { tier: "starter", name: "Eligibility Review", price: 290, deliveryDays: 25, revisions: 1, volume: "1 secured placement", summary: "An honest assessment plus a focused first attempt.", features: ["Resource eligibility assessment", "50 institutional pages prospected", "1 secured placement", "Named contact outreach", "Outcome reporting"] },
      { tier: "growth", name: "Institutional Outreach", price: 1150, deliveryDays: 45, revisions: 2, volume: "4 secured placements", summary: "A sustained campaign across universities and public bodies.", features: ["200 institutional pages prospected", "4 secured placements", "Library guide targeting", "Multi-department outreach", "Maintenance status reporting"], recommended: true },
      { tier: "scale", name: "Resource Recognition", price: 2950, deliveryDays: 80, revisions: 3, volume: "10 secured placements", summary: "A long-horizon programme including asset guidance.", features: ["500+ pages prospected", "10 secured placements", "Asset improvement guidance", "Scholarship programme advice", "Two-quarter follow-up cycle"] },
    ],
    faqs: [
      { question: "Are .edu and .gov links automatically high quality?", answer: "No, and this is the most persistent myth in link building. Search engines do not apply a bonus based on a domain suffix. Value comes from whether the specific page is relevant, maintained and genuinely referenced. A neglected page on a university subdomain is worth very little." },
      { question: "Can you guarantee an .edu link?", answer: "No. Institutional curators make independent decisions and often take weeks to respond. We commit to secured placements over a longer timeframe, and we will tell you upfront if your resource has little realistic chance." },
      { question: "What about scholarship link building?", answer: "It only works if you actually run the scholarship, fund it, administer it and award it. Universities increasingly check. A fake scholarship page built purely for links gets removed and damages your credibility with contacts you may want later." },
      { question: "Why is the acceptance rate so low?", answer: "Because these pages are genuinely selective and institutional staff are busy. We price accordingly and focus effort on the pages where your resource has a real chance rather than mass-mailing every university in the country." },
    ],
    reviews: [
      { name: "Dr. Alistair Finch", role: "Research Lead", country: "United Kingdom", rating: 5, date: "2026-02-01", tier: "Institutional Outreach", text: "They told us our commercial pages had no chance and focused entirely on the open dataset instead. Four library guides now reference it." },
      { name: "Mariana Duarte", role: "Nonprofit Manager", country: "Portugal", rating: 5, date: "2026-01-11", tier: "Eligibility Review", text: "The eligibility assessment alone was worth it. They explained precisely why a .gov suffix means nothing on its own, which changed how we brief agencies." },
      { name: "Thomas Reinhardt", role: "Education Director", country: "Germany", rating: 4, date: "2026-03-07", tier: "Resource Recognition", text: "Slow, as promised repeatedly during onboarding. Ten placements over nearly three months, all on pages that are clearly maintained." },
    ],
    related: ["resource-link-building", "broken-link-building", "citation-directory-backlinks", "brand-entity-link-building"],
    cta: { heading: "Find out if your resource qualifies", body: "We will assess honestly whether an institution would have any reason to link to you." },
  },

  {
    slug: "competitor-link-building",
    group: "Strategy Services",
    nav: "Competitor Link Building",
    icon: "chart",
    accent: "sky",
    h1: "Competitor Link Building Based on Gaps Worth Closing",
    metaTitle: "Competitor Link Building | Backlink Gap Analysis & Replication",
    metaDescription:
      "Competitor backlink analysis and link gap building. We identify which competitor links are replicable and worth pursuing, then run the outreach to win them.",
    summary:
      "Analysis of where competitors earn links, filtered down to the opportunities you can realistically win.",
    keywords: ["competitor backlink analysis", "competitor link building", "link gap analysis", "lost backlink recovery", "backlink replication"],
    variants: ["Competitor backlink analysis", "Competitor backlink replication", "Link gap building", "Lost backlink recovery", "Competitor guest post research"],
    intro: [
      "Competitor link analysis is useful and frequently misused. Exporting every referring domain a rival has and chasing all of them wastes months, because a large share are unrepeatable: acquisitions, personal relationships, historical coverage and links from sites that will never accept an approach.",
      "Our job is the filtering. We classify every competitor link by whether it can be replicated, how, and whether it is worth the effort, then run outreach on the ones that survive that test.",
    ],
    included: [
      "Backlink profile export for up to five named competitors",
      "Link gap analysis showing domains linking to rivals but not to you",
      "Classification of each opportunity by replicability and method",
      "Priority scoring based on relevance, traffic and realistic win probability",
      "Outreach execution on the qualified shortlist",
      "Lost link recovery for references you previously held",
    ],
    benefits: [
      { title: "Proven relevance", body: "A site that already links to a competitor has demonstrated willingness to reference companies like yours, which removes most of the guesswork." },
      { title: "Effort spent where it counts", body: "Classifying opportunities before outreach means your budget goes to winnable links rather than unrepeatable ones." },
      { title: "Strategic visibility", body: "The gap analysis often reveals entire link types you had not considered, such as association memberships or partner directories." },
      { title: "Recovers your own losses", body: "Most sites have lost links they never noticed. Recovering them is usually faster and cheaper than earning new ones." },
    ],
    process: [
      { title: "Competitor selection", body: "We agree which rivals actually compete with you in search, which is often not the same list as your commercial competitors." },
      { title: "Export and deduplication", body: "Profiles are exported, merged and cleaned so you see referring domains rather than thousands of duplicate page-level links." },
      { title: "Classification", body: "Each domain is tagged: replicable by outreach, purchasable placement, partner relationship, unrepeatable, or not worth pursuing." },
      { title: "Execution", body: "We run outreach against the qualified list and report wins, declines and the reasons behind them." },
    ],
    placement: "Placement type depends on what the competitor link actually is. A guest post gap is closed with a guest post, a resource listing with a resource pitch, a directory entry with a submission. We match the method to the opportunity rather than forcing everything through one channel.",
    quality: "We exclude competitor links that come from obvious link schemes, expired-domain networks or paid networks we would not use ourselves. Replicating a rival's low-quality links inherits their risk, and we will point out where a competitor's profile looks engineered rather than earned.",
    useCases: [
      "Teams that need a defensible plan before committing budget",
      "Sites that have plateaued while rivals continue to gain ground",
      "Agencies building a first-quarter roadmap for a new client",
      "Businesses that have migrated domains and lost references",
    ],
    stats: [
      { label: "Competitor links typically replicable", value: "18–25%" },
      { label: "Average gap domains identified", value: "340" },
      { label: "Lost links recovered per audit", value: "12 median" },
    ],
    packages: [
      { tier: "starter", name: "Gap Analysis", price: 340, deliveryDays: 10, revisions: 1, volume: "Analysis only", summary: "The full analysis and prioritised opportunity list.", features: ["Up to 3 competitors analysed", "Deduplicated gap report", "Replicability classification", "Priority scoring", "90-day action plan"] },
      { tier: "growth", name: "Analysis + Outreach", price: 1420, deliveryDays: 35, revisions: 2, volume: "Analysis + 8 links", summary: "Analysis followed by execution on the best opportunities.", features: ["Up to 5 competitors analysed", "8 secured placements", "Mixed acquisition methods", "Lost link recovery included", "Progress reporting"], recommended: true },
      { tier: "scale", name: "Gap Closing Programme", price: 3960, deliveryDays: 70, revisions: 3, volume: "Analysis + 24 links", summary: "A sustained programme to close the gap systematically.", features: ["Ongoing competitor monitoring", "24 secured placements", "New competitor link alerts", "Quarterly re-analysis", "Named strategist"] },
    ],
    faqs: [
      { question: "Should I try to replicate every competitor link?", answer: "Definitely not. Typically only a fifth of a competitor's referring domains are realistically winnable, and some of the rest you would not want. Chasing everything is how teams spend a quarter on outreach and secure almost nothing." },
      { question: "What counts as an unrepeatable link?", answer: "Coverage of a funding announcement, links from an acquired company, personal relationships, sponsorships that have ended, and historical press from years ago. We tag these clearly so you understand which parts of a rival's profile you cannot copy." },
      { question: "How do you find lost backlinks?", answer: "We compare historical referring domain data against current links and identify references that disappeared, then determine whether the page was removed, redirected badly or simply edited. Many are recoverable with a short email." },
      { question: "What if a competitor's profile looks manipulated?", answer: "We will tell you. Sometimes the honest finding is that a rival is ranking partly on links we would not recommend replicating. In that case we focus on the legitimate portion and explain the risk in the report." },
    ],
    reviews: [
      { name: "Sinead O'Halloran", role: "Marketing Manager", country: "Ireland", rating: 5, date: "2026-02-13", tier: "Analysis + Outreach", text: "The classification saved us chasing ninety domains that were never going to link to us. Eight placements from the qualified list in five weeks." },
      { name: "Andreas Papadopoulos", role: "Ecommerce Director", country: "Greece", rating: 4, date: "2026-01-29", tier: "Gap Analysis", text: "Analysis only, and it was thorough enough that we executed in-house. They offered to help with outreach but did not push it." },
      { name: "Whitney Barnes", role: "SEO Director", country: "United States", rating: 5, date: "2026-03-20", tier: "Gap Closing Programme", text: "Recovered nineteen links lost during a migration two years ago. Nobody on our side had realised they were gone." },
    ],
    related: ["broken-link-building", "authority-backlinks", "monthly-link-building", "brand-entity-link-building"],
    cta: { heading: "See the gap before you spend", body: "Name three competitors and we will show you which of their links you could realistically win." },
  },

  {
    slug: "brand-entity-link-building",
    group: "Strategy Services",
    nav: "Brand & Entity Link Building",
    icon: "badge",
    accent: "violet",
    h1: "Brand and Entity Link Building for Consistent Recognition",
    metaTitle: "Brand & Entity Link Building | Mentions, Profiles and Attribution",
    metaDescription:
      "Brand and entity link building through mention recovery, brand profile links, founder authority and consistent descriptions across the web.",
    summary:
      "Making sure the web describes your company consistently, and that mentions of it point somewhere.",
    keywords: ["brand mention backlinks", "entity link building", "unlinked brand mention recovery", "brand profile links", "founder authority links"],
    variants: ["Brand mention backlinks", "Brand profile links", "Brand citation links", "Founder and author links", "Entity-based link building", "Unlinked brand mention recovery"],
    intro: [
      "Search engines and AI systems build a picture of who you are from how independent sources describe you. If five publications describe your company three different ways, that picture is muddled. If your name is mentioned frequently but never linked, the association is weaker than it should be.",
      "This service addresses both. We recover unlinked mentions, standardise how your business is described across profiles and databases, and build the founder and author signals that connect people to the organisation.",
    ],
    included: [
      "Brand mention monitoring across news, blogs, forums and databases",
      "Unlinked mention discovery with contact details for each publisher",
      "Attribution requests written individually rather than templated",
      "Brand profile creation and cleanup on relevant platforms and databases",
      "Founder and author profile consistency across bylines and bios",
      "Standardised company description library for consistent use",
    ],
    benefits: [
      { title: "Recovers value already earned", body: "Mentions without links represent coverage you have already generated. Converting them is cheaper than earning new coverage." },
      { title: "Clearer entity signals", body: "Consistent naming, descriptions and category placement help systems associate your brand with the right subject reliably." },
      { title: "Better AI summaries", body: "When independent sources describe you in similar terms, generative systems reproduce that description more accurately." },
      { title: "Author credibility", body: "Consistent founder and author profiles connect individual expertise to the company, strengthening both." },
    ],
    process: [
      { title: "Mention sweep", body: "We search news, blogs, forums, databases and social sources for every reference to your brand, product and founders." },
      { title: "Classification", body: "Mentions are sorted into linked, unlinked-and-recoverable, and unlinked-but-inappropriate to pursue." },
      { title: "Attribution outreach", body: "Each recoverable mention gets an individual message to the writer or editor requesting a link where it helps the reader." },
      { title: "Profile standardisation", body: "We align your descriptions, categories and founder bios across profiles so every source tells the same story." },
    ],
    placement: "Recovered links appear exactly where your brand is already mentioned, which is the most natural placement available. Profile links point to your homepage, while founder profiles link to a relevant about or author page depending on the platform.",
    quality: "We do not pursue attribution on negative coverage or on sites where a link would look forced. Profiles are created only on platforms with genuine use. The aim is a coherent, accurate picture of your organisation rather than the maximum possible number of profile links.",
    useCases: [
      "Companies that generate press coverage but rarely get linked",
      "Brands with inconsistent descriptions across the web",
      "Founders building personal authority alongside the company",
      "Businesses concerned about how AI systems summarise them",
    ],
    stats: [
      { label: "Unlinked mentions found per sweep", value: "31 median" },
      { label: "Attribution conversion rate", value: "34%" },
      { label: "Description consistency achieved", value: "92%" },
    ],
    packages: [
      { tier: "starter", name: "Mention Recovery", price: 310, deliveryDays: 18, revisions: 1, volume: "1 sweep + outreach", summary: "Find and convert existing unlinked mentions.", features: ["Full brand mention sweep", "Unlinked mention report", "Attribution outreach", "Conversion tracking", "Recovered link log"] },
      { tier: "growth", name: "Entity Foundation", price: 980, deliveryDays: 32, revisions: 2, volume: "Recovery + profiles", summary: "Mention recovery plus profile standardisation.", features: ["Mention recovery included", "25 brand profiles created or corrected", "Description library", "Founder profile alignment", "Consistency audit report"], recommended: true },
      { tier: "scale", name: "Entity Programme", price: 2680, deliveryDays: 60, revisions: 3, volume: "Ongoing, 1 quarter", summary: "Continuous monitoring and entity strengthening.", features: ["Continuous mention monitoring", "Monthly attribution outreach", "50+ profiles maintained", "Author authority building", "Quarterly entity review"] },
    ],
    faqs: [
      { question: "What exactly is an unlinked brand mention?", answer: "It is any place your company or product name appears in text without a hyperlink to your site. It happens constantly in news coverage, roundups and blog posts. The writer has already decided you are worth mentioning, so asking for attribution is a low-friction request." },
      { question: "Do publishers actually add links when asked?", answer: "Around a third do, in our experience. The key is asking the right person politely, explaining that readers looking for the company would benefit, and not demanding specific anchor text. Aggressive requests get ignored." },
      { question: "Why do consistent descriptions matter?", answer: "Because systems that summarise companies rely on repetition across independent sources. If your positioning is described differently everywhere, the summary becomes vague or wrong. Alignment is a low-cost way to influence how you are represented." },
      { question: "Should we build founder profiles as well as company ones?", answer: "If a named person is publicly associated with your expertise, yes. Author and founder signals reinforce organisational credibility, particularly in subjects where readers reasonably want to know who is behind the advice." },
    ],
    reviews: [
      { name: "Cecilia Marchetti", role: "Head of Comms", country: "Italy", rating: 5, date: "2026-02-25", tier: "Entity Foundation", text: "We were described four different ways across major databases. Fixing that was unglamorous work but our brand search results look coherent now." },
      { name: "Joel Lindqvist", role: "Co-founder", country: "Finland", rating: 5, date: "2026-01-16", tier: "Mention Recovery", text: "Forty-three unlinked mentions found, sixteen converted within a month. All from coverage we had already paid for in other ways." },
      { name: "Priya Anand", role: "Brand Lead", country: "United Kingdom", rating: 4, date: "2026-03-18", tier: "Entity Programme", text: "The monthly monitoring catches mentions we would never spot ourselves. Attribution rate is lower than the headline figure in our sector, which they explained upfront." },
    ],
    related: ["digital-pr-backlinks", "press-release-news-backlinks", "citation-directory-backlinks", "forum-community-backlinks"],
    cta: { heading: "Find out who mentions you without linking", body: "We will run a mention sweep and show you exactly how much coverage is going unattributed." },
  },

  {
    slug: "monthly-link-building",
    group: "Campaign Programmes",
    nav: "Monthly Link Building",
    icon: "clock",
    accent: "brand",
    h1: "Monthly Link Building Managed as an Ongoing Campaign",
    metaTitle: "Monthly Link Building | Managed Recurring Link Campaigns",
    metaDescription:
      "Monthly link building packages with managed strategy, mixed placement types, consistent velocity and transparent reporting. Recurring guest posts and niche edits.",
    summary:
      "A managed programme with a steady monthly output, a mix of link types and reporting you can present internally.",
    keywords: ["monthly link building", "monthly backlink packages", "managed link building", "recurring guest posts", "off-page SEO packages"],
    variants: ["Monthly backlink packages", "Monthly off-page link building", "Managed link building", "Recurring guest posts", "Recurring niche edits", "Monthly authority backlinks", "Custom monthly campaigns"],
    intro: [
      "One-off placements rarely change much. Link building works when it is sustained, when the mix of link types changes over time, and when somebody is watching the profile as a whole rather than fulfilling individual orders.",
      "A monthly programme gives you that continuity. We agree the target pages and the monthly output, then vary the methods across guest posts, niche edits, resource placements and outreach depending on what the profile needs that month. Velocity stays steady rather than arriving in unnatural bursts.",
    ],
    included: [
      "Quarterly strategy with agreed target pages and anchor distribution",
      "A fixed number of placements each month across mixed link types",
      "Ongoing profile monitoring, including new competitor links",
      "Anchor ratio management to prevent over-optimisation",
      "Monthly report with live URLs, metrics and visibility movement",
      "A named strategist on a recurring review call",
    ],
    benefits: [
      { title: "Natural acquisition pattern", body: "Consistent monthly output looks like an organic growth pattern rather than a sudden spike followed by silence." },
      { title: "Strategy adapts monthly", body: "If one target page starts moving and another stalls, the following month's allocation shifts accordingly." },
      { title: "Mixed link types by default", body: "Programmes blend editorial, contextual, niche edit and outreach placements so the profile does not look one-dimensional." },
      { title: "Reporting built for stakeholders", body: "Monthly summaries explain what changed and what it means, not just how many links were delivered." },
    ],
    process: [
      { title: "Onboarding and audit", body: "We review your current profile, anchor distribution, competitor position and target pages before the first placement is planned." },
      { title: "Quarterly planning", body: "Objectives are set for the quarter, broken into monthly allocations across pages and link types." },
      { title: "Monthly execution", body: "Placements are produced and delivered across the month rather than clustered at the end of a billing cycle." },
      { title: "Review and adjust", body: "Each month ends with a report and a call where the following month's allocation is confirmed or changed." },
    ],
    placement: "Placements are distributed across several target pages rather than concentrated on one, and anchors are rotated deliberately. Where a page has received several links recently, we deprioritise it the following month even if it is your commercial favourite.",
    quality: "Every placement passes the same screening as our individual services. We cap monthly volume at a level we can deliver without dropping standards, and we will decline to increase a programme if it would mean accepting weaker publishers to hit a number.",
    useCases: [
      "In-house teams needing predictable ongoing output",
      "Agencies outsourcing fulfilment while keeping client strategy",
      "Competitive niches where consistency matters more than bursts",
      "Businesses that have tried one-off buying without results",
    ],
    stats: [
      { label: "Average programme length", value: "11 months" },
      { label: "Link types per programme", value: "3–5" },
      { label: "Reporting cadence", value: "monthly" },
    ],
    packages: [
      { tier: "starter", name: "Steady", price: 890, deliveryDays: 30, revisions: 2, volume: "4 links / month", summary: "A consistent baseline for smaller sites.", features: ["4 placements monthly", "2 link types", "Anchor distribution management", "Monthly report", "Email support"] },
      { tier: "growth", name: "Momentum", price: 2350, deliveryDays: 30, revisions: 3, volume: "11 links / month", summary: "The standard programme for competitive niches.", features: ["11 placements monthly", "4 link types blended", "Quarterly strategy sessions", "Competitor link monitoring", "Named strategist and monthly call"], recommended: true },
      { tier: "scale", name: "Authority", price: 5600, deliveryDays: 30, revisions: 4, volume: "28 links / month", summary: "A full programme with PR and strategy included.", features: ["28 placements monthly", "All link types including digital PR", "Multi-page target distribution", "Weekly progress access", "Quarterly executive review"] },
    ],
    faqs: [
      { question: "How long before I see movement?", answer: "For most sites, meaningful change appears between the third and sixth month. Anyone promising results in week four is either lucky or not being straight with you. We report leading indicators like referring domain growth from month one so you can see progress before rankings shift." },
      { question: "Can I change the target pages mid-programme?", answer: "Yes, at any monthly review. In fact we often recommend it, because priorities change and there is little point pushing links at a page you have deprioritised commercially." },
      { question: "What happens if I pause?", answer: "You can pause before the next cycle begins and any unused allocation stays on your account for three months. Placements already commissioned with publishers will complete, since editors have scheduled them." },
      { question: "Is the link velocity safe?", answer: "We set volumes relative to your existing profile size rather than applying a fixed number. A site with 80 referring domains gets a different pace from one with 8,000, because what looks natural depends entirely on the baseline." },
    ],
    reviews: [
      { name: "Vanessa Hartley", role: "Head of Digital", country: "United Kingdom", rating: 5, date: "2026-02-28", tier: "Momentum", text: "Eight months in. The monthly call is short and useful, and they moved allocation away from a page we had stopped caring about without being asked twice." },
      { name: "Ricardo Alves", role: "Ecommerce Manager", country: "Brazil", rating: 4, date: "2026-01-21", tier: "Steady", text: "Modest volume but consistent. They refused to double the output when I asked, explaining it would outpace our profile growth. Frustrating then, sensible now." },
      { name: "Sophie Leclerc", role: "Agency Partner", country: "Canada", rating: 5, date: "2026-03-24", tier: "Authority", text: "We white-label this for three clients. Reporting is clean enough to forward with our logo on it and the strategist joins our client calls when needed." },
    ],
    related: ["premium-link-building", "guest-post-backlinks", "competitor-link-building", "niche-edit-backlinks"],
    cta: { heading: "Build a programme around your profile", body: "Send us your domain and we will propose a monthly volume and mix that suits where you are now." },
  },

  {
    slug: "premium-link-building",
    group: "Campaign Programmes",
    nav: "Premium Link Building",
    icon: "spark",
    accent: "amber",
    h1: "Premium Link Building on Publications With Genuine Readership",
    metaTitle: "Premium Link Building | High-Traffic Publisher Placements",
    metaDescription:
      "Premium backlinks from high-traffic publications with genuine editorial standards. Fewer placements, stronger publishers, judged on readership not inflated metrics.",
    summary:
      "A small number of placements on publications with real audiences, real editors and real editorial standards.",
    keywords: ["premium backlinks", "premium guest posts", "high traffic publisher links", "premium editorial links", "high authority publisher links"],
    variants: ["Premium guest posts", "Premium editorial links", "Premium contextual links", "High-traffic publisher links", "High-authority publisher links", "Premium campaigns"],
    intro: [
      "Premium means something specific here. It is not a higher DR number attached to the same inventory. It means publications with substantial genuine readership, staffed editorial teams, and standards strict enough that most placement requests are declined.",
      "You get fewer links for your money, and each one takes longer to secure. For competitive commercial terms where everybody has already bought the mid-tier placements, that trade is usually the right one.",
    ],
    included: [
      "Publisher selection based on verified traffic and editorial staffing",
      "Editorial-standard content written by senior subject writers",
      "Editor negotiation including topic, angle and attribution",
      "In-content placement on pages with genuine internal support",
      "Full traffic, audience and readership data for each publication",
      "Twelve-month monitoring with replacement guarantee",
    ],
    benefits: [
      { title: "Audiences that actually exist", body: "Every publication is verified for genuine readership, so placements generate referral visits as well as ranking value." },
      { title: "Difficult to replicate", body: "These publishers decline most approaches, which means competitors cannot simply buy the same placement next week." },
      { title: "Editorial-grade content", body: "Writing is produced by senior writers who can meet a real editor's standards, because anything less gets rejected." },
      { title: "Assessed on substance", body: "We judge publishers on traffic, staffing and standards rather than pricing them purely off a third-party authority score." },
    ],
    process: [
      { title: "Target and publisher matching", body: "We identify which premium publications genuinely reach your buyers and would consider your subject." },
      { title: "Angle negotiation", body: "Topics are proposed and negotiated with editors before commissioning, since these publishers reject generic pitches immediately." },
      { title: "Senior content production", body: "An experienced writer produces the piece to the publication's standard, with fact-checking and source citations." },
      { title: "Placement and verification", body: "The article publishes, and we supply full publication data alongside the live URL and a monitoring schedule." },
    ],
    placement: "Links sit in the body of substantive articles on publications with strong internal linking, so the page receives ongoing crawl attention rather than being buried after a week. We avoid sponsored hubs that are siloed away from the main editorial structure.",
    quality: "Publications must demonstrate verified organic traffic at scale, a named editorial team, consistent publishing standards and an audience that overlaps with your market. A high authority score with thin traffic does not qualify, and neither does a large site whose commercial section is walled off from its editorial content.",
    useCases: [
      "Competitive commercial terms where mid-tier links have stalled",
      "Brands needing placements that carry reputational weight",
      "Companies whose buyers read a specific set of trade titles",
      "Profiles that need a small number of genuinely strong references",
    ],
    stats: [
      { label: "Minimum publisher traffic", value: "50k+/mo" },
      { label: "Publisher acceptance rate", value: "under 20%" },
      { label: "Typical placement window", value: "3–6 weeks" },
    ],
    packages: [
      { tier: "starter", name: "Single Premium", price: 940, deliveryDays: 30, revisions: 2, volume: "1 placement", summary: "One placement on a verified premium publication.", features: ["50k+ monthly traffic publisher", "Senior writer content", "Editor-negotiated angle", "Full audience data", "12-month monitoring"] },
      { tier: "growth", name: "Premium Three", price: 2640, deliveryDays: 45, revisions: 3, volume: "3 placements", summary: "Three placements across distinct premium titles.", features: ["3 premium publications", "100k+ traffic priority", "Multi-angle development", "Referral traffic reporting", "Replacement guarantee"], recommended: true },
      { tier: "scale", name: "Premium Campaign", price: 7200, deliveryDays: 75, revisions: 4, volume: "9 placements", summary: "A quarter-long premium acquisition campaign.", features: ["9 premium placements", "Tier-one publisher targeting", "Dedicated senior writer", "Editor relationship management", "Quarterly performance review"] },
    ],
    faqs: [
      { question: "What makes a placement premium rather than just expensive?", answer: "Verified traffic at scale, a named editorial team, genuine editorial standards and an audience that matches your market. Price alone means nothing. We show you the traffic and audience data for every publication so you can judge whether the premium is justified." },
      { question: "Why so few links for the budget?", answer: "Because these publishers decline most approaches and the content has to meet a real editorial bar. If volume is your priority, our monthly programme delivers considerably more placements for the same spend, and we will say so during the consultation." },
      { question: "Do premium placements guarantee rankings?", answer: "No. Nothing guarantees rankings, and we would not work with anyone who claims otherwise. What premium placements provide is references that are genuinely difficult for competitors to obtain, on pages that real people read." },
      { question: "Can I see the publication list before committing?", answer: "You see the specific proposed publications with their traffic and audience data before any content is commissioned, and you can reject any of them." },
    ],
    reviews: [
      { name: "Julian Ashworth", role: "Marketing Director", country: "United Kingdom", rating: 5, date: "2026-02-17", tier: "Premium Three", text: "Three links in six weeks, which felt slow until the first one sent more referral traffic in a month than our previous twenty placements combined." },
      { name: "Elena Rossi", role: "Head of SEO", country: "Italy", rating: 5, date: "2026-01-13", tier: "Premium Campaign", text: "They talked us out of two publications on our wish list because the audience did not match, despite those being the most expensive options available." },
      { name: "Marcus Delgado", role: "Founder", country: "United States", rating: 4, date: "2026-03-28", tier: "Single Premium", text: "Expensive for one link and they were upfront about that. The editor required two rewrites, which explains why competitors have not got the same placement." },
    ],
    related: ["authority-backlinks", "editorial-backlinks", "digital-pr-backlinks", "monthly-link-building"],
    cta: { heading: "See which premium titles reach your buyers", body: "We will identify the publications worth pursuing and show you their audience data before you commit." },
  },
];
