export type SeoToolCategory =
  | "Technical SEO"
  | "XML Sitemaps"
  | "Structured Data"
  | "On-Page SEO"
  | "Social & SERP";

export type SeoToolMode = "url" | "text" | "generator" | "preview";

export type SeoToolDefinition = {
  slug: string;
  name: string;
  category: SeoToolCategory;
  mode: SeoToolMode;
  summary: string;
  metaDescription: string;
  primaryEntity: string;
  relatedEntities: string[];
  actionLabel: string;
  inputLabel: string;
  placeholder: string;
  related: string[];
};

export const SEO_TOOL_CATEGORIES: SeoToolCategory[] = [
  "Technical SEO",
  "XML Sitemaps",
  "Structured Data",
  "On-Page SEO",
  "Social & SERP",
];

export const SEO_TOOLS: SeoToolDefinition[] = [
  {
    slug: "robots-txt-tester",
    name: "Robots.txt Tester",
    category: "Technical SEO",
    mode: "url",
    summary: "Test whether a specific URL is allowed or blocked for a crawler and see the robots.txt rule that controls the decision.",
    metaDescription: "Test robots.txt rules for any URL and crawler. See matched directives, crawl permission and practical technical SEO guidance.",
    primaryEntity: "robots.txt",
    relatedEntities: ["user-agent", "Disallow", "Allow", "crawler", "crawlability", "Googlebot", "path matching"],
    actionLabel: "Test robots.txt",
    inputLabel: "URL to test",
    placeholder: "https://example.com/private/page",
    related: ["robots-txt-validator", "robots-txt-generator", "noindex-checker", "x-robots-tag-checker", "indexability-checker"],
  },
  {
    slug: "robots-txt-validator",
    name: "Robots.txt Validator",
    category: "Technical SEO",
    mode: "url",
    summary: "Fetch and validate a site's robots.txt file for directive syntax, formatting problems and crawl-control mistakes.",
    metaDescription: "Validate a live robots.txt file for syntax, unsupported directives, formatting problems and common crawl configuration mistakes.",
    primaryEntity: "robots.txt validation",
    relatedEntities: ["robots.txt syntax", "User-agent", "Disallow", "Allow", "Sitemap", "crawl directives", "Googlebot"],
    actionLabel: "Validate robots.txt",
    inputLabel: "Website URL",
    placeholder: "https://example.com",
    related: ["robots-txt-tester", "robots-txt-generator", "sitemap-validator", "indexability-checker"],
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Build a clean robots.txt file from crawler rules, blocked paths and sitemap locations without hand-writing directives.",
    metaDescription: "Generate a valid robots.txt file with user-agent, Allow, Disallow and Sitemap directives, then copy the finished file.",
    primaryEntity: "robots.txt generation",
    relatedEntities: ["User-agent", "Disallow", "Allow", "Sitemap", "crawl rules", "Googlebot"],
    actionLabel: "Generate robots.txt",
    inputLabel: "Rules",
    placeholder: "Disallow paths, one per line",
    related: ["robots-txt-tester", "robots-txt-validator", "sitemap-generator", "indexability-checker"],
  },
  {
    slug: "canonical-url-checker",
    name: "Canonical URL Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect a webpage's rel=canonical implementation, resolve the declared canonical URL and flag common conflicts.",
    metaDescription: "Check a page's canonical tag, preferred URL, status and common canonicalization conflicts with clear recommendations.",
    primaryEntity: "canonical URL",
    relatedEntities: ["rel=canonical", "canonical tag", "duplicate URLs", "preferred URL", "indexing", "redirects", "HTTPS"],
    actionLabel: "Check canonical",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["canonical-tag-generator", "redirect-checker", "indexability-checker", "url-structure-checker"],
  },
  {
    slug: "canonical-tag-generator",
    name: "Canonical Tag Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Generate a correctly formatted rel=canonical link element for the preferred version of a page.",
    metaDescription: "Create a valid rel=canonical HTML tag for your preferred URL and avoid common canonical formatting mistakes.",
    primaryEntity: "canonical tag",
    relatedEntities: ["rel=canonical", "preferred URL", "duplicate content", "HTML head", "absolute URL"],
    actionLabel: "Generate canonical tag",
    inputLabel: "Preferred URL",
    placeholder: "https://example.com/preferred-page",
    related: ["canonical-url-checker", "url-structure-checker", "indexability-checker"],
  },
  {
    slug: "hreflang-checker",
    name: "Hreflang Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect hreflang tags, language-region codes, duplicate entries and reciprocal references on multilingual pages.",
    metaDescription: "Check hreflang implementation, language and region codes, x-default, duplicates and return-link issues on a live page.",
    primaryEntity: "hreflang",
    relatedEntities: ["hreflang attribute", "language code", "region code", "x-default", "international SEO", "return link"],
    actionLabel: "Check hreflang",
    inputLabel: "Page URL",
    placeholder: "https://example.com/en/page",
    related: ["hreflang-generator", "canonical-url-checker", "sitemap-validator"],
  },
  {
    slug: "hreflang-generator",
    name: "Hreflang Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Create valid hreflang link elements for language and regional page variants, including optional x-default markup.",
    metaDescription: "Generate valid hreflang tags for multilingual or multi-region pages using language-region codes and absolute URLs.",
    primaryEntity: "hreflang tag",
    relatedEntities: ["language code", "region code", "x-default", "alternate URL", "international SEO"],
    actionLabel: "Generate hreflang tags",
    inputLabel: "Language and URL pairs",
    placeholder: "en-US | https://example.com/us/page",
    related: ["hreflang-checker", "canonical-url-checker", "sitemap-generator"],
  },
  {
    slug: "redirect-checker",
    name: "Redirect Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Follow a URL request and show each HTTP redirect until the final destination, including response status at every hop.",
    metaDescription: "Check URL redirects, status codes and final destination with a clear redirect path and practical SEO interpretation.",
    primaryEntity: "HTTP redirect",
    relatedEntities: ["301", "302", "307", "308", "Location header", "final URL", "HTTP status"],
    actionLabel: "Check redirects",
    inputLabel: "URL",
    placeholder: "https://example.com/old-page",
    related: ["redirect-chain-checker", "redirect-loop-checker", "http-status-code-checker", "canonical-url-checker"],
  },
  {
    slug: "redirect-chain-checker",
    name: "Redirect Chain Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Reveal multi-hop redirect chains so you can find unnecessary hops, mixed protocols and inefficient destination paths.",
    metaDescription: "Find redirect chains and view every URL and HTTP status in the sequence from the starting URL to the final page.",
    primaryEntity: "redirect chain",
    relatedEntities: ["redirect hop", "301", "302", "HTTP status", "Location header", "crawl efficiency"],
    actionLabel: "Check redirect chain",
    inputLabel: "Starting URL",
    placeholder: "https://example.com/old-url",
    related: ["redirect-checker", "redirect-loop-checker", "http-status-code-checker"],
  },
  {
    slug: "redirect-loop-checker",
    name: "Redirect Loop Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Detect circular redirect behavior and identify the URLs involved before browsers or crawlers hit a redirect limit.",
    metaDescription: "Detect redirect loops, inspect repeated URLs and identify where a redirect path becomes circular or fails to resolve.",
    primaryEntity: "redirect loop",
    relatedEntities: ["too many redirects", "HTTP redirect", "301", "302", "Location header", "circular redirect"],
    actionLabel: "Check redirect loop",
    inputLabel: "URL",
    placeholder: "https://example.com/page",
    related: ["redirect-checker", "redirect-chain-checker", "http-status-code-checker"],
  },
  {
    slug: "http-status-code-checker",
    name: "HTTP Status Code Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Request a URL, report its HTTP response status and explain what the result means for users and search crawlers.",
    metaDescription: "Check HTTP status codes for a URL, follow redirects safely and understand 2xx, 3xx, 4xx and 5xx responses.",
    primaryEntity: "HTTP status code",
    relatedEntities: ["200", "301", "404", "410", "500", "response header", "crawlability"],
    actionLabel: "Check status code",
    inputLabel: "URL",
    placeholder: "https://example.com/page",
    related: ["redirect-checker", "redirect-chain-checker", "indexability-checker"],
  },
  {
    slug: "indexability-checker",
    name: "Indexability Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Review the technical signals that influence whether a page is eligible for indexing without pretending to know Google's live index state.",
    metaDescription: "Analyze indexability signals including HTTP status, robots directives, canonical tags and crawl controls on a live webpage.",
    primaryEntity: "indexability",
    relatedEntities: ["meta robots", "X-Robots-Tag", "canonical", "HTTP status", "crawlability", "noindex", "robots.txt"],
    actionLabel: "Check indexability",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["noindex-checker", "meta-robots-checker", "x-robots-tag-checker", "canonical-url-checker", "robots-txt-tester"],
  },
  {
    slug: "noindex-checker",
    name: "Noindex Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Detect noindex directives in meta robots markup and relevant HTTP response headers on a live URL.",
    metaDescription: "Check whether a webpage declares noindex through meta robots or X-Robots-Tag headers and see the exact directive found.",
    primaryEntity: "noindex",
    relatedEntities: ["meta robots", "X-Robots-Tag", "indexing directive", "robots", "HTML head"],
    actionLabel: "Check noindex",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-robots-checker", "x-robots-tag-checker", "indexability-checker", "robots-txt-tester"],
  },
  {
    slug: "meta-robots-checker",
    name: "Meta Robots Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Read the page's meta robots directives and explain how index, noindex, follow and related instructions are being declared.",
    metaDescription: "Analyze meta robots tags on a webpage and understand index, noindex, follow, nofollow and snippet-related directives.",
    primaryEntity: "meta robots",
    relatedEntities: ["index", "noindex", "follow", "nofollow", "max-snippet", "HTML meta tag"],
    actionLabel: "Check meta robots",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["noindex-checker", "x-robots-tag-checker", "meta-robots-generator", "indexability-checker"],
  },
  {
    slug: "x-robots-tag-checker",
    name: "X-Robots-Tag Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect X-Robots-Tag response headers and explain indexing directives delivered outside the HTML document.",
    metaDescription: "Check X-Robots-Tag HTTP headers for noindex and other indexing directives that may not appear in page source.",
    primaryEntity: "X-Robots-Tag",
    relatedEntities: ["HTTP header", "noindex", "indexing directive", "robots", "PDF indexing"],
    actionLabel: "Check X-Robots-Tag",
    inputLabel: "URL",
    placeholder: "https://example.com/document.pdf",
    related: ["noindex-checker", "meta-robots-checker", "indexability-checker"],
  },
  {
    slug: "url-structure-checker",
    name: "URL Structure Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Review URL length, readability, parameters, path depth and characters that can make addresses harder to understand or maintain.",
    metaDescription: "Analyze URL structure for readability, length, parameters, path depth and common SEO or usability issues.",
    primaryEntity: "URL structure",
    relatedEntities: ["URL slug", "query parameter", "path depth", "HTTPS", "readability", "percent encoding"],
    actionLabel: "Analyze URL",
    inputLabel: "URL",
    placeholder: "https://example.com/category/product?ref=123",
    related: ["seo-slug-checker", "canonical-url-checker", "redirect-checker"],
  },
  {
    slug: "sitemap-validator",
    name: "XML Sitemap Validator",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Fetch an XML sitemap, verify its root structure and inspect loc entries for common formatting and protocol mistakes.",
    metaDescription: "Validate an XML sitemap's structure, namespace, URL entries and common formatting problems with clear error messages.",
    primaryEntity: "XML sitemap",
    relatedEntities: ["urlset", "loc", "lastmod", "XML namespace", "sitemap protocol", "indexing discovery"],
    actionLabel: "Validate sitemap",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-url-checker", "sitemap-index-checker", "sitemap-lastmod-checker", "sitemap-generator"],
  },
  {
    slug: "sitemap-url-checker",
    name: "Sitemap URL Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Inspect URLs listed in a sitemap and sample their HTTP responses to surface broken or redirected entries.",
    metaDescription: "Check URLs contained in an XML sitemap and review sampled HTTP status, redirects and indexability-related signals.",
    primaryEntity: "sitemap URLs",
    relatedEntities: ["XML sitemap", "loc", "HTTP status", "redirect", "indexable URL", "crawl discovery"],
    actionLabel: "Check sitemap URLs",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-validator", "http-status-code-checker", "indexability-checker"],
  },
  {
    slug: "sitemap-index-checker",
    name: "Sitemap Index Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Analyze a sitemap index file, list referenced child sitemaps and identify malformed or duplicate sitemap entries.",
    metaDescription: "Check XML sitemap index files, referenced child sitemaps, duplicate entries and structural issues.",
    primaryEntity: "sitemap index",
    relatedEntities: ["sitemapindex", "sitemap", "loc", "lastmod", "child sitemap", "XML"],
    actionLabel: "Check sitemap index",
    inputLabel: "Sitemap index URL",
    placeholder: "https://example.com/sitemap_index.xml",
    related: ["sitemap-validator", "sitemap-url-checker", "sitemap-lastmod-checker"],
  },
  {
    slug: "sitemap-lastmod-checker",
    name: "Sitemap Lastmod Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Review lastmod values inside a sitemap and flag missing, invalid, future-dated or inconsistent timestamps.",
    metaDescription: "Analyze XML sitemap lastmod dates for valid ISO formatting, future dates and consistency issues.",
    primaryEntity: "sitemap lastmod",
    relatedEntities: ["lastmod", "ISO 8601", "XML sitemap", "modification date", "crawl scheduling"],
    actionLabel: "Check lastmod values",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-validator", "sitemap-index-checker", "sitemap-generator"],
  },
  {
    slug: "sitemap-generator",
    name: "XML Sitemap Generator",
    category: "XML Sitemaps",
    mode: "generator",
    summary: "Turn a list of absolute URLs into a standards-compliant XML sitemap you can save as sitemap.xml.",
    metaDescription: "Generate a clean XML sitemap from your URL list with valid loc elements and optional lastmod dates.",
    primaryEntity: "XML sitemap generation",
    relatedEntities: ["urlset", "loc", "lastmod", "XML namespace", "sitemap.xml"],
    actionLabel: "Generate sitemap",
    inputLabel: "URLs",
    placeholder: "https://example.com/\nhttps://example.com/about/",
    related: ["sitemap-validator", "sitemap-url-checker", "robots-txt-generator"],
  },
  {
    slug: "schema-validator",
    name: "Schema Markup Validator",
    category: "Structured Data",
    mode: "text",
    summary: "Parse JSON-LD structured data, identify syntax or basic structural issues and show the detected Schema.org types.",
    metaDescription: "Validate JSON-LD schema markup for JSON syntax, @context, @type and basic structured data structure.",
    primaryEntity: "Schema.org structured data",
    relatedEntities: ["JSON-LD", "@context", "@type", "Schema.org", "structured data", "rich results"],
    actionLabel: "Validate schema",
    inputLabel: "JSON-LD markup",
    placeholder: "Paste JSON-LD here",
    related: ["json-ld-validator", "schema-markup-generator", "article-schema-generator", "faq-schema-generator", "organization-schema-generator"],
  },
  {
    slug: "json-ld-validator",
    name: "JSON-LD Validator",
    category: "Structured Data",
    mode: "text",
    summary: "Check whether JSON-LD parses as valid JSON and whether common linked-data fields are shaped correctly.",
    metaDescription: "Validate JSON-LD syntax and inspect @context, @type and nested objects before publishing structured data.",
    primaryEntity: "JSON-LD",
    relatedEntities: ["JSON", "linked data", "@context", "@type", "Schema.org", "script type application/ld+json"],
    actionLabel: "Validate JSON-LD",
    inputLabel: "JSON-LD",
    placeholder: "{\n  \"@context\": \"https://schema.org\", ...\n}",
    related: ["schema-validator", "schema-markup-generator", "faq-schema-generator"],
  },
  {
    slug: "schema-markup-generator",
    name: "Schema Markup Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate a clean JSON-LD starting point for common Schema.org types using information you provide.",
    metaDescription: "Create Schema.org JSON-LD markup from your own page or business information with valid JSON formatting.",
    primaryEntity: "schema markup generation",
    relatedEntities: ["Schema.org", "JSON-LD", "structured data", "@type", "WebPage", "Organization"],
    actionLabel: "Generate schema",
    inputLabel: "Schema details",
    placeholder: "Enter the fields for your selected schema type",
    related: ["schema-validator", "json-ld-validator", "article-schema-generator", "organization-schema-generator"],
  },
  {
    slug: "faq-schema-generator",
    name: "FAQ Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Convert visible questions and answers into FAQPage JSON-LD without inventing FAQ content.",
    metaDescription: "Generate FAQPage JSON-LD from your real questions and answers, ready to add to a qualifying FAQ section.",
    primaryEntity: "FAQPage schema",
    relatedEntities: ["Question", "Answer", "JSON-LD", "FAQPage", "structured data"],
    actionLabel: "Generate FAQ schema",
    inputLabel: "Questions and answers",
    placeholder: "Question | Answer",
    related: ["schema-validator", "json-ld-validator", "schema-markup-generator"],
  },
  {
    slug: "article-schema-generator",
    name: "Article Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Create Article JSON-LD with headline, URL, author and publication information supplied by you.",
    metaDescription: "Generate Article structured data in JSON-LD format using your real headline, author, URL and publication dates.",
    primaryEntity: "Article schema",
    relatedEntities: ["Article", "headline", "author", "datePublished", "dateModified", "JSON-LD"],
    actionLabel: "Generate Article schema",
    inputLabel: "Article details",
    placeholder: "Headline and page details",
    related: ["schema-validator", "json-ld-validator", "organization-schema-generator"],
  },
  {
    slug: "organization-schema-generator",
    name: "Organization Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Build Organization JSON-LD from a real organization name, website, logo and contact details.",
    metaDescription: "Generate Organization Schema.org JSON-LD with your real name, URL, logo and contact information.",
    primaryEntity: "Organization schema",
    relatedEntities: ["Organization", "logo", "url", "contactPoint", "sameAs", "JSON-LD"],
    actionLabel: "Generate Organization schema",
    inputLabel: "Organization details",
    placeholder: "Organization name and URL",
    related: ["schema-validator", "website-schema-generator", "local-business-schema-generator"],
  },
  {
    slug: "breadcrumb-schema-generator",
    name: "Breadcrumb Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Create BreadcrumbList JSON-LD from an ordered set of visible breadcrumb labels and destination URLs.",
    metaDescription: "Generate valid BreadcrumbList JSON-LD from your page hierarchy with ordered names, URLs and positions.",
    primaryEntity: "BreadcrumbList schema",
    relatedEntities: ["BreadcrumbList", "ListItem", "position", "item", "JSON-LD", "site hierarchy"],
    actionLabel: "Generate breadcrumb schema",
    inputLabel: "Breadcrumb items",
    placeholder: "Home | https://example.com/",
    related: ["schema-validator", "json-ld-validator", "website-schema-generator"],
  },
  {
    slug: "local-business-schema-generator",
    name: "Local Business Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Create LocalBusiness JSON-LD from real business details such as name, address, phone and website.",
    metaDescription: "Generate LocalBusiness structured data with your real business name, address, phone, website and business type.",
    primaryEntity: "LocalBusiness schema",
    relatedEntities: ["LocalBusiness", "PostalAddress", "telephone", "openingHours", "geo", "JSON-LD"],
    actionLabel: "Generate LocalBusiness schema",
    inputLabel: "Business details",
    placeholder: "Business name, URL, phone and address",
    related: ["organization-schema-generator", "schema-validator", "website-schema-generator"],
  },
  {
    slug: "website-schema-generator",
    name: "WebSite Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate WebSite JSON-LD for a website name and canonical homepage URL, with optional search action details.",
    metaDescription: "Create WebSite Schema.org JSON-LD with your site name, URL and optional site-search action.",
    primaryEntity: "WebSite schema",
    relatedEntities: ["WebSite", "url", "name", "SearchAction", "potentialAction", "JSON-LD"],
    actionLabel: "Generate WebSite schema",
    inputLabel: "Website details",
    placeholder: "Website name and homepage URL",
    related: ["organization-schema-generator", "breadcrumb-schema-generator", "schema-validator"],
  },
  {
    slug: "video-schema-generator",
    name: "Video Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Build VideoObject JSON-LD from a real video's title, description, thumbnail, upload date and playback URL.",
    metaDescription: "Generate VideoObject structured data with video name, description, thumbnail, upload date and content or embed URL.",
    primaryEntity: "VideoObject schema",
    relatedEntities: ["VideoObject", "thumbnailUrl", "uploadDate", "contentUrl", "embedUrl", "duration"],
    actionLabel: "Generate Video schema",
    inputLabel: "Video details",
    placeholder: "Video title, thumbnail and URL",
    related: ["schema-validator", "json-ld-validator", "article-schema-generator"],
  },
  {
    slug: "internal-link-checker",
    name: "Internal Link Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Extract internal links from a webpage and review destination URLs, anchor text and common linking issues.",
    metaDescription: "Check internal links on a webpage, inspect anchors and destinations and identify structural internal linking issues.",
    primaryEntity: "internal links",
    relatedEntities: ["anchor text", "internal URL", "site architecture", "crawl path", "navigation", "nofollow"],
    actionLabel: "Check internal links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-analyzer", "anchor-text-analyzer", "broken-link-checker"],
  },
  {
    slug: "internal-link-analyzer",
    name: "Internal Link Analyzer",
    category: "On-Page SEO",
    mode: "url",
    summary: "Take a deeper look at internal anchor patterns, repeated destinations, link counts and distribution on a single page.",
    metaDescription: "Analyze internal linking structure, anchor text, destination frequency and distribution on a webpage.",
    primaryEntity: "internal link analysis",
    relatedEntities: ["anchor text", "link distribution", "crawl depth", "site architecture", "destination URL"],
    actionLabel: "Analyze internal links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-checker", "anchor-text-analyzer", "seo-page-analyzer"],
  },
  {
    slug: "external-link-checker",
    name: "External Link Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "List outbound links from a webpage and show destination, anchor and rel attributes that affect link behavior.",
    metaDescription: "Check external links on a webpage and review outbound destinations, anchor text, rel attributes and protocols.",
    primaryEntity: "external links",
    relatedEntities: ["outbound link", "nofollow", "sponsored", "ugc", "anchor text", "external domain"],
    actionLabel: "Check external links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["broken-link-checker", "anchor-text-analyzer", "internal-link-checker"],
  },
  {
    slug: "broken-link-checker",
    name: "Broken Link Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Extract page links and safely sample their HTTP responses to identify destinations that fail or return error status codes.",
    metaDescription: "Find broken links on a webpage by checking linked destinations for 4xx, 5xx and request failures with clear limits.",
    primaryEntity: "broken links",
    relatedEntities: ["404", "410", "5xx", "link rot", "HTTP status", "outbound link", "internal link"],
    actionLabel: "Find broken links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-checker", "external-link-checker", "http-status-code-checker"],
  },
  {
    slug: "anchor-text-analyzer",
    name: "Anchor Text Analyzer",
    category: "On-Page SEO",
    mode: "url",
    summary: "Review anchor text used on a webpage and group common patterns such as URL, generic, branded-looking and descriptive anchors.",
    metaDescription: "Analyze anchor text on a webpage and inspect generic, URL, repeated and descriptive linking patterns.",
    primaryEntity: "anchor text",
    relatedEntities: ["link text", "generic anchor", "URL anchor", "exact match", "descriptive link", "internal linking"],
    actionLabel: "Analyze anchor text",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-analyzer", "external-link-checker", "internal-link-checker"],
  },
  {
    slug: "heading-checker",
    name: "Heading Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Extract H1–H6 elements in document order so you can review page hierarchy, missing H1s and abrupt level changes.",
    metaDescription: "Check H1, H2, H3, H4, H5 and H6 structure on a webpage and identify common heading hierarchy issues.",
    primaryEntity: "HTML headings",
    relatedEntities: ["H1", "H2", "H3", "document outline", "heading hierarchy", "accessibility"],
    actionLabel: "Check headings",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-title-checker", "seo-page-analyzer", "internal-link-analyzer"],
  },
  {
    slug: "image-alt-checker",
    name: "Image Alt Text Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Inspect img alt attributes and flag missing, empty or unusually long alternative text for manual review.",
    metaDescription: "Find images with missing, empty or excessively long alt attributes and review alt text in page context.",
    primaryEntity: "image alt text",
    relatedEntities: ["alt attribute", "img", "accessibility", "image SEO", "decorative image", "screen reader"],
    actionLabel: "Check image alt text",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["image-seo-checker", "seo-page-analyzer", "meta-tag-checker"],
  },
  {
    slug: "image-seo-checker",
    name: "Image SEO Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Review image filenames, alt attributes, width and height declarations, lazy-loading hints and source URLs on a page.",
    metaDescription: "Analyze image SEO signals including alt text, filenames, width and height attributes, lazy loading and image source URLs.",
    primaryEntity: "image SEO",
    relatedEntities: ["alt text", "filename", "width", "height", "loading=lazy", "img src", "CLS"],
    actionLabel: "Analyze images",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["image-alt-checker", "seo-page-analyzer", "heading-checker"],
  },
  {
    slug: "meta-title-checker",
    name: "Meta Title Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Read a page's HTML title, measure its text length and highlight missing or unusually short or long title tags.",
    metaDescription: "Check a webpage title tag for presence and length, then review practical title optimization guidance.",
    primaryEntity: "title tag",
    relatedEntities: ["HTML title", "SERP title", "title length", "search snippet", "head element"],
    actionLabel: "Check title tag",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["serp-title-pixel-checker", "seo-snippet-preview", "meta-description-checker", "meta-tag-checker"],
  },
  {
    slug: "meta-description-checker",
    name: "Meta Description Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Inspect a page's meta description, report its text length and flag missing or unusually sized descriptions.",
    metaDescription: "Check a webpage meta description for presence and length and get practical guidance without promising search-engine display.",
    primaryEntity: "meta description",
    relatedEntities: ["description meta tag", "search snippet", "SERP", "snippet rewrite", "HTML head"],
    actionLabel: "Check meta description",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-description-pixel-checker", "seo-snippet-preview", "meta-title-checker", "meta-tag-checker"],
  },
  {
    slug: "meta-tag-checker",
    name: "Meta Tag Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Inspect important head metadata in one place, including title, description, canonical, robots and social tags.",
    metaDescription: "Check important HTML meta tags including title, description, canonical, robots, Open Graph and Twitter/X metadata.",
    primaryEntity: "HTML metadata",
    relatedEntities: ["title", "meta description", "canonical", "robots", "Open Graph", "Twitter Card"],
    actionLabel: "Check meta tags",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-title-checker", "meta-description-checker", "meta-robots-checker", "og-tag-checker"],
  },
  {
    slug: "seo-slug-checker",
    name: "SEO URL Slug Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Review the final path segment of a URL for readability, excessive length, separators, encoding and unnecessary complexity.",
    metaDescription: "Analyze a URL slug for readability, length, separators, characters and common structure issues.",
    primaryEntity: "URL slug",
    relatedEntities: ["slug", "URL path", "hyphen", "readability", "keyword", "percent encoding"],
    actionLabel: "Check URL slug",
    inputLabel: "URL",
    placeholder: "https://example.com/category/my-page-slug",
    related: ["url-structure-checker", "canonical-url-checker", "seo-page-analyzer"],
  },
  {
    slug: "og-tag-checker",
    name: "Open Graph Tag Checker",
    category: "Social & SERP",
    mode: "url",
    summary: "Inspect Open Graph metadata and build a practical sharing preview from the title, description, image and URL found on the page.",
    metaDescription: "Check Open Graph tags including og:title, og:description, og:image and og:url and preview social sharing data.",
    primaryEntity: "Open Graph metadata",
    relatedEntities: ["og:title", "og:description", "og:image", "og:url", "social preview", "Facebook"],
    actionLabel: "Check Open Graph tags",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["twitter-card-checker", "meta-tag-checker", "seo-snippet-preview"],
  },
  {
    slug: "twitter-card-checker",
    name: "Twitter/X Card Checker",
    category: "Social & SERP",
    mode: "url",
    summary: "Inspect Twitter/X Card metadata and preview the title, description, image and card type declared by the page.",
    metaDescription: "Check Twitter/X Card tags such as twitter:card, title, description and image and review the resulting metadata.",
    primaryEntity: "Twitter Card metadata",
    relatedEntities: ["twitter:card", "twitter:title", "twitter:description", "twitter:image", "X", "social sharing"],
    actionLabel: "Check Twitter/X Card",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["og-tag-checker", "meta-tag-checker", "seo-snippet-preview"],
  },
  {
    slug: "meta-robots-generator",
    name: "Meta Robots Generator",
    category: "Social & SERP",
    mode: "generator",
    summary: "Build a robots meta tag from explicit indexing, following and snippet-control choices.",
    metaDescription: "Generate a valid robots meta tag using index, noindex, follow, nofollow and snippet-related directives.",
    primaryEntity: "robots meta tag",
    relatedEntities: ["index", "noindex", "follow", "nofollow", "max-snippet", "meta robots"],
    actionLabel: "Generate meta robots tag",
    inputLabel: "Robots directives",
    placeholder: "Choose indexing and link-following directives",
    related: ["meta-robots-checker", "noindex-checker", "indexability-checker"],
  },
  {
    slug: "seo-snippet-preview",
    name: "SEO Search Snippet Preview",
    category: "Social & SERP",
    mode: "preview",
    summary: "Preview a title, URL and description in a search-style layout while keeping clear that search engines may rewrite snippets.",
    metaDescription: "Preview how a title, URL and description could look in search results. Search engines may rewrite displayed snippets.",
    primaryEntity: "search snippet",
    relatedEntities: ["SERP", "title tag", "meta description", "URL", "snippet rewrite", "search result"],
    actionLabel: "Update preview",
    inputLabel: "Snippet fields",
    placeholder: "Enter title, URL and description",
    related: ["meta-title-checker", "meta-description-checker", "serp-title-pixel-checker", "meta-description-pixel-checker"],
  },
  {
    slug: "serp-title-pixel-checker",
    name: "SERP Title Pixel Checker",
    category: "Social & SERP",
    mode: "preview",
    summary: "Estimate rendered title width in pixels and compare it with a practical display range without claiming a guaranteed Google cutoff.",
    metaDescription: "Estimate SERP title pixel width and review practical display guidance without claiming a fixed Google title limit.",
    primaryEntity: "SERP title width",
    relatedEntities: ["title pixels", "title tag", "SERP", "font width", "title rewrite", "Google Search"],
    actionLabel: "Measure title width",
    inputLabel: "Title text",
    placeholder: "Enter a title tag",
    related: ["meta-title-checker", "seo-snippet-preview", "meta-description-pixel-checker"],
  },
  {
    slug: "meta-description-pixel-checker",
    name: "Meta Description Pixel Checker",
    category: "Social & SERP",
    mode: "preview",
    summary: "Estimate the rendered width of a description and explain why search engines may shorten or replace snippet text.",
    metaDescription: "Estimate meta description pixel width and review practical snippet guidance while accounting for search-engine rewrites.",
    primaryEntity: "meta description width",
    relatedEntities: ["description pixels", "meta description", "SERP", "snippet rewrite", "rendered width"],
    actionLabel: "Measure description width",
    inputLabel: "Description text",
    placeholder: "Enter a meta description",
    related: ["meta-description-checker", "seo-snippet-preview", "serp-title-pixel-checker"],
  },
  {
    slug: "seo-page-analyzer",
    name: "SEO Page Analyzer",
    category: "Social & SERP",
    mode: "url",
    summary: "Run a consolidated review of major on-page and technical signals available from a webpage without inventing rankings or authority scores.",
    metaDescription: "Analyze title, description, canonical, robots, headings, links, images and social metadata from a live webpage in one report.",
    primaryEntity: "on-page SEO analysis",
    relatedEntities: ["title tag", "meta description", "canonical", "robots", "headings", "internal links", "images", "Open Graph"],
    actionLabel: "Analyze page",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["indexability-checker", "meta-tag-checker", "heading-checker", "internal-link-analyzer", "image-seo-checker"],
  },
];

export const SEO_TOOL_BY_SLUG = new Map(SEO_TOOLS.map((tool) => [tool.slug, tool]));

export function getSeoTool(slug: string) {
  return SEO_TOOL_BY_SLUG.get(slug);
}

export function toolsByCategory(category: SeoToolCategory) {
  return SEO_TOOLS.filter((tool) => tool.category === category);
}
