type SeoToolDefinition = {
  slug: string;
  name: string;
  category: string;
  mode: string;
  summary: string;
  metaDescription: string;
  primaryEntity: string;
  relatedEntities: string[];
  actionLabel: string;
  inputLabel: string;
  placeholder: string;
  related: string[];
};

export const EXTRA_SEO_TOOLS_1: SeoToolDefinition[] = [
  {
    slug: "keyword-density-checker",
    name: "Keyword Density Checker",
    category: "Keyword & Content",
    mode: "text",
    summary: "Measure how often target keywords appear in text and interpret density without over-optimization.",
    metaDescription: "Measure how often target keywords appear in text and interpret density without over-optimization.",
    primaryEntity: "keyword density",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "readability-score-checker",
    name: "Readability Score Checker",
    category: "Keyword & Content",
    mode: "text",
    summary: "Estimate reading ease of content so users and search engines can understand the page more easily.",
    metaDescription: "Estimate reading ease of content so users and search engines can understand the page more easily.",
    primaryEntity: "readability",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "word-count-analyzer",
    name: "Word Count Analyzer",
    category: "Keyword & Content",
    mode: "text",
    summary: "Count words and summarize length context for blog posts, product pages and guides.",
    metaDescription: "Count words and summarize length context for blog posts, product pages and guides.",
    primaryEntity: "word count",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "content-length-checker",
    name: "Content Length Checker",
    category: "Keyword & Content",
    mode: "url",
    summary: "Compare a page's visible content length against practical ranges for its page type.",
    metaDescription: "Compare a page's visible content length against practical ranges for its page type.",
    primaryEntity: "content length",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "heading-keyword-alignment-checker",
    name: "Heading Keyword Alignment Checker",
    category: "Keyword & Content",
    mode: "url",
    summary: "Check whether primary topics appear naturally in H1 and supporting headings.",
    metaDescription: "Check whether primary topics appear naturally in H1 and supporting headings.",
    primaryEntity: "heading keyword alignment",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "keyword-in-title-checker",
    name: "Keyword in Title Checker",
    category: "Keyword & Content",
    mode: "url",
    summary: "See if target terms appear in the title tag without forced stuffing.",
    metaDescription: "See if target terms appear in the title tag without forced stuffing.",
    primaryEntity: "keyword in title",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "keyword-in-url-checker",
    name: "Keyword in URL Checker",
    category: "Keyword & Content",
    mode: "url",
    summary: "Evaluate whether the URL slug reflects the main topic in a readable way.",
    metaDescription: "Evaluate whether the URL slug reflects the main topic in a readable way.",
    primaryEntity: "keyword in URL",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "content-to-html-ratio-checker",
    name: "Content-to-HTML Ratio Checker",
    category: "Keyword & Content",
    mode: "url",
    summary: "Estimate how much of the response is visible text versus markup noise.",
    metaDescription: "Estimate how much of the response is visible text versus markup noise.",
    primaryEntity: "content to HTML ratio",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "paragraph-length-analyzer",
    name: "Paragraph Length Analyzer",
    category: "Keyword & Content",
    mode: "text",
    summary: "Flag very long paragraphs that can hurt readability on mobile and desktop.",
    metaDescription: "Flag very long paragraphs that can hurt readability on mobile and desktop.",
    primaryEntity: "paragraph length",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "sentence-complexity-checker",
    name: "Sentence Complexity Checker",
    category: "Keyword & Content",
    mode: "text",
    summary: "Highlight dense sentences that may reduce clarity for general audiences.",
    metaDescription: "Highlight dense sentences that may reduce clarity for general audiences.",
    primaryEntity: "sentence complexity",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "passive-voice-detector",
    name: "Passive Voice Detector",
    category: "Keyword & Content",
    mode: "text",
    summary: "Find passive constructions that can make content less direct and harder to scan.",
    metaDescription: "Find passive constructions that can make content less direct and harder to scan.",
    primaryEntity: "passive voice",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "transition-words-checker",
    name: "Transition Words Checker",
    category: "Keyword & Content",
    mode: "text",
    summary: "Check whether transitions support flow between ideas in longer articles.",
    metaDescription: "Check whether transitions support flow between ideas in longer articles.",
    primaryEntity: "transition words",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "thin-content-signals-checker",
    name: "Thin Content Signals Checker",
    category: "Keyword & Content",
    mode: "url",
    summary: "Surface signals of thin pages such as low word count and weak unique value.",
    metaDescription: "Surface signals of thin pages such as low word count and weak unique value.",
    primaryEntity: "thin content",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "content-structure-analyzer",
    name: "Content Structure Analyzer",
    category: "Keyword & Content",
    mode: "url",
    summary: "Review headings, lists and section balance for clearer topical structure.",
    metaDescription: "Review headings, lists and section balance for clearer topical structure.",
    primaryEntity: "content structure",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "duplicate-content-text-checker",
    name: "Duplicate Content Text Checker",
    category: "Keyword & Content",
    mode: "text",
    summary: "Compare two text samples for similarity that may indicate duplication risk.",
    metaDescription: "Compare two text samples for similarity that may indicate duplication risk.",
    primaryEntity: "duplicate content",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
  {
    slug: "content-outline-generator",
    name: "Content Outline Generator",
    category: "Keyword & Content",
    mode: "generator",
    summary: "Generate a semantic outline for a topic with user-focused sections and entities.",
    metaDescription: "Generate a semantic outline for a topic with user-focused sections and entities.",
    primaryEntity: "content outline",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Generate",
    inputLabel: "Topic or keywords",
    placeholder: "Topic or keywords",
    related: [],
  },
  {
    slug: "faq-section-generator",
    name: "FAQ Section Generator",
    category: "Keyword & Content",
    mode: "generator",
    summary: "Create practical FAQ questions and answers aligned to real user intents.",
    metaDescription: "Create practical FAQ questions and answers aligned to real user intents.",
    primaryEntity: "FAQ section",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Generate",
    inputLabel: "Topic or keywords",
    placeholder: "Topic or keywords",
    related: [],
  },
  {
    slug: "howto-outline-generator",
    name: "HowTo Outline Generator",
    category: "Keyword & Content",
    mode: "generator",
    summary: "Build a step-by-step HowTo outline suitable for guides and schema-ready content.",
    metaDescription: "Build a step-by-step HowTo outline suitable for guides and schema-ready content.",
    primaryEntity: "HowTo outline",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Generate",
    inputLabel: "Topic or keywords",
    placeholder: "Topic or keywords",
    related: [],
  },
  {
    slug: "comparison-page-outline-generator",
    name: "Comparison Page Outline Generator",
    category: "Keyword & Content",
    mode: "generator",
    summary: "Outline comparison pages with fair criteria and decision-focused sections.",
    metaDescription: "Outline comparison pages with fair criteria and decision-focused sections.",
    primaryEntity: "comparison outline",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Generate",
    inputLabel: "Topic or keywords",
    placeholder: "Topic or keywords",
    related: [],
  },
  {
    slug: "semantic-entity-checklist",
    name: "Semantic Entity Checklist",
    category: "Keyword & Content",
    mode: "text",
    summary: "List entities and attributes that high-quality content on a topic should cover.",
    metaDescription: "List entities and attributes that high-quality content on a topic should cover.",
    primaryEntity: "semantic entities",
    relatedEntities: ["semantic SEO", "content quality", "user intent"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste content...",
    related: [],
  },
];
