// Core SEO tools part A
export const SEO_TOOLS_CORE_A = [
  {
    slug: "robots-txt-tester",
    name: "Robots.txt Tester",
    category: "Technical SEO",
    mode: "url",
    summary: "Test whether a specific URL is allowed or blocked for a crawler and see the robots.txt rule that controls the decision.",
    metaDescription: "Test robots.txt rules for any URL and crawler. See matched directives, crawl permission and practical technical SEO guidance.",
    primaryEntity: "robots.txt",
    relatedEntities: ["user-agent", "Disallow", "Allow", "crawler", "crawlability", "Googlebot", "path matching"],
    actionLabel: "Test robots.txt",
    inputLabel: "URL to test",
    placeholder: "https://example.com/private/page",
    related: ["robots-txt-validator", "robots-txt-generator", "noindex-checker", "x-robots-tag-checker", "indexability-checker"],
  },
  {
    slug: "robots-txt-validator",
    name: "Robots.txt Validator",
    category: "Technical SEO",
    mode: "url",
    summary: "Fetch and validate a site's robots.txt file for directive syntax, formatting problems and crawl-control mistakes.",
    metaDescription: "Validate a live robots.txt file for syntax, unsupported directives, formatting problems and common crawl configuration mistakes.",
    primaryEntity: "robots.txt validation",
    relatedEntities: ["robots.txt syntax", "User-agent", "Disallow", "Allow", "Sitemap", "crawl directives", "Googlebot"],
    actionLabel: "Validate robots.txt",
    inputLabel: "Website URL",
    placeholder: "https://example.com",
    related: ["robots-txt-tester", "robots-txt-generator", "sitemap-validator", "indexability-checker"],
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Build a clean robots.txt file from crawler rules, blocked paths and sitemap locations without hand-writing directives.",
    metaDescription: "Generate a valid robots.txt file with user-agent, Allow, Disallow and Sitemap directives, then copy the finished file.",
    primaryEntity: "robots.txt generation",
    relatedEntities: ["User-agent", "Disallow", "Allow", "Sitemap", "crawl rules", "Googlebot"],
    actionLabel: "Generate robots.txt",
    inputLabel: "Rules",
    placeholder: "Disallow paths, one per line",
    related: ["robots-txt-tester", "robots-txt-validator", "sitemap-generator", "indexability-checker"],
  },
  {
    slug: "canonical-url-checker",
    name: "Canonical URL Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect a webpage's rel=canonical implementation, resolve the declared canonical URL and flag common conflicts.",
    metaDescription: "Check a page's canonical tag, preferred URL, status and common canonicalization conflicts with clear recommendations.",
    primaryEntity: "canonical URL",
    relatedEntities: ["rel=canonical", "canonical tag", "duplicate URLs", "preferred URL", "indexing", "redirects", "HTTPS"],
    actionLabel: "Check canonical",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["canonical-tag-generator", "redirect-checker", "indexability-checker", "url-structure-checker"],
  },
  {
    slug: "canonical-tag-generator",
    name: "Canonical Tag Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Generate a correctly formatted rel=canonical link element for the preferred version of a page.",
    metaDescription: "Create a valid rel=canonical HTML tag for your preferred URL and avoid common canonical formatting mistakes.",
    primaryEntity: "canonical tag",
    relatedEntities: ["rel=canonical", "preferred URL", "duplicate content", "HTML head", "absolute URL"],
    actionLabel: "Generate canonical tag",
    inputLabel: "Preferred URL",
    placeholder: "https://example.com/preferred-page",
    related: ["canonical-url-checker", "url-structure-checker", "indexability-checker"],
  },
  {
    slug: "hreflang-checker",
    name: "Hreflang Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect hreflang tags, language-region codes, duplicate entries and reciprocal references on multilingual pages.",
    metaDescription: "Check hreflang implementation, language and region codes, x-default, duplicates and return-link issues on a live page.",
    primaryEntity: "hreflang",
    relatedEntities: ["hreflang attribute", "language code", "region code", "x-default", "international SEO", "return link"],
    actionLabel: "Check hreflang",
    inputLabel: "Page URL",
    placeholder: "https://example.com/en/page",
    related: ["hreflang-generator", "canonical-url-checker", "sitemap-validator"],
  },
  {
    slug: "hreflang-generator",
    name: "Hreflang Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Create valid hreflang link elements for language and regional page variants, including optional x-default markup.",
    metaDescription: "Generate valid hreflang tags for multilingual or multi-region pages using language-region codes and absolute URLs.",
    primaryEntity: "hreflang tag",
    relatedEntities: ["language code", "region code", "x-default", "alternate URL", "international SEO"],
    actionLabel: "Generate hreflang tags",
    inputLabel: "Language and URL pairs",
    placeholder: "en-US | https://example.com/us/page",
    related: ["hreflang-checker", "canonical-url-checker", "sitemap-generator"],
  },
  {
    slug: "redirect-checker",
    name: "Redirect Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Follow a URL request and show each HTTP redirect until the final destination, including response status at every hop.",
    metaDescription: "Check URL redirects, status codes and final destination with a clear redirect path and practical SEO interpretation.",
    primaryEntity: "HTTP redirect",
    relatedEntities: ["301", "302", "307", "308", "Location header", "final URL", "HTTP status"],
    actionLabel: "Check redirects",
    inputLabel: "URL",
    placeholder: "https://example.com/old-page",
    related: ["redirect-chain-checker", "redirect-loop-checker", "http-status-code-checker", "canonical-url-checker"],
  },
  {
    slug: "redirect-chain-checker",
    name: "Redirect Chain Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Reveal multi-hop redirect chains so you can find unnecessary hops, mixed protocols and inefficient destination paths.",
    metaDescription: "Find redirect chains and view every URL and HTTP status in the sequence from the starting URL to the final page.",
    primaryEntity: "redirect chain",
    relatedEntities: ["redirect hop", "301", "302", "HTTP status", "Location header", "crawl efficiency"],
    actionLabel: "Check redirect chain",
    inputLabel: "Starting URL",
    placeholder: "https://example.com/old-url",
    related: ["redirect-checker", "redirect-loop-checker", "http-status-code-checker"],
  },
  {
    slug: "redirect-loop-checker",
    name: "Redirect Loop Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Detect circular redirect behavior and identify the URLs involved before browsers or crawlers hit a redirect limit.",
    metaDescription: "Detect redirect loops, inspect repeated URLs and identify where a redirect path becomes circular or fails to resolve.",
    primaryEntity: "redirect loop",
    relatedEntities: ["too many redirects", "HTTP redirect", "301", "302", "Location header", "circular redirect"],
    actionLabel: "Check redirect loop",
    inputLabel: "URL",
    placeholder: "https://example.com/page",
    related: ["redirect-checker", "redirect-chain-checker", "http-status-code-checker"],
  },
  {
    slug: "http-status-code-checker",
    name: "HTTP Status Code Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Request a URL, report its HTTP response status and explain what the result means for users and search crawlers.",
    metaDescription: "Check HTTP status codes for a URL, follow redirects safely and understand 2xx, 3xx, 4xx and 5xx responses.",
    primaryEntity: "HTTP status code",
    relatedEntities: ["200", "301", "404", "410", "500", "response header", "crawlability"],
    actionLabel: "Check status code",
    inputLabel: "URL",
    placeholder: "https://example.com/page",
    related: ["redirect-checker", "redirect-chain-checker", "indexability-checker"],
  },
  {
    slug: "indexability-checker",
    name: "Indexability Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Review the technical signals that influence whether a page is eligible for indexing without pretending to know Google's live index state.",
    metaDescription: "Analyze indexability signals including HTTP status, robots directives, canonical tags and crawl controls on a live webpage.",
    primaryEntity: "indexability",
    relatedEntities: ["meta robots", "X-Robots-Tag", "canonical", "HTTP status", "crawlability", "noindex", "robots.txt"],
    actionLabel: "Check indexability",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["noindex-checker", "meta-robots-checker", "x-robots-tag-checker", "canonical-url-checker", "robots-txt-tester"],
  },
  {
    slug: "noindex-checker",
    name: "Noindex Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Detect noindex directives in meta robots markup and relevant HTTP response headers on a live URL.",
    metaDescription: "Check whether a webpage declares noindex through meta robots or X-Robots-Tag headers and see the exact directive found.",
    primaryEntity: "noindex",
    relatedEntities: ["meta robots", "X-Robots-Tag", "indexing directive", "robots", "HTML head"],
    actionLabel: "Check noindex",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-robots-checker", "x-robots-tag-checker", "indexability-checker", "robots-txt-tester"],
  },
  {
    slug: "meta-robots-checker",
    name: "Meta Robots Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Read the page's meta robots directives and explain how index, noindex, follow and related instructions are being declared.",
    metaDescription: "Analyze meta robots tags on a webpage and understand index, noindex, follow, nofollow and snippet-related directives.",
    primaryEntity: "meta robots",
    relatedEntities: ["index", "noindex", "follow", "nofollow", "max-snippet", "HTML meta tag"],
    actionLabel: "Check meta robots",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["noindex-checker", "x-robots-tag-checker", "meta-robots-generator", "indexability-checker"],
  },
  {
    slug: "x-robots-tag-checker",
    name: "X-Robots-Tag Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect X-Robots-Tag response headers and explain indexing directives delivered outside the HTML document.",
    metaDescription: "Check X-Robots-Tag HTTP headers for noindex and other indexing directives that may not appear in page source.",
    primaryEntity: "X-Robots-Tag",
    relatedEntities: ["HTTP header", "noindex", "indexing directive", "robots", "PDF indexing"],
    actionLabel: "Check X-Robots-Tag",
    inputLabel: "URL",
    placeholder: "https://example.com/document.pdf",
    related: ["noindex-checker", "meta-robots-checker", "indexability-checker"],
  },
];
