export type SeoToolCategory =
  | "Technical SEO"
  | "XML Sitemaps"
  | "Structured Data"
  | "On-Page SEO"
  | "Social & SERP";

export type SeoToolMode = "url" | "text" | "generator" | "preview";

export type SeoToolDefinition = {
  slug: string;
  name: string;
  category: SeoToolCategory;
  mode: SeoToolMode;
  summary: string;
  metaDescription: string;
  primaryEntity: string;
  relatedEntities: string[];
  actionLabel: string;
  inputLabel: string;
  placeholder: string;
  related: string[];
};

export const SEO_TOOL_CATEGORIES: SeoToolCategory[] = [
  "Technical SEO",
  "XML Sitemaps",
  "Structured Data",
  "On-Page SEO",
  "Social & SERP",
];

export const SEO_TOOLS: SeoToolDefinition[] = [
  {
    slug: "robots-txt-tester",
    name: "Robots.txt Tester",
    category: "Technical SEO",
    mode: "url",
    summary: "Test whether a specific URL is allowed or blocked for a crawler and see the robots.txt rule that controls the decision.",
    metaDescription: "Test robots.txt rules for any URL and crawler. See matched directives, crawl permission and practical technical SEO guidance.",
    primaryEntity: "robots.txt",
    relatedEntities: ["user-agent", "Disallow", "Allow", "crawler", "crawlability", "Googlebot", "path matching"],
    actionLabel: "Test robots.txt",
    inputLabel: "URL to test",
    placeholder: "https://example.com/private/page",
    related: ["robots-txt-validator", "robots-txt-generator", "noindex-checker", "x-robots-tag-checker", "indexability-checker"],
  },
  {
    slug: "robots-txt-validator",
    name: "Robots.txt Validator",
    category: "Technical SEO",
    mode: "url",
    summary: "Fetch and validate a site's robots.txt file for directive syntax, formatting problems and crawl-control mistakes.",
    metaDescription: "Validate a live robots.txt file for syntax, unsupported directives, formatting problems and common crawl configuration mistakes.",
    primaryEntity: "robots.txt validation",
    relatedEntities: ["robots.txt syntax", "User-agent", "Disallow", "Allow", "Sitemap", "crawl directives", "Googlebot"],
    actionLabel: "Validate robots.txt",
    inputLabel: "Website URL",
    placeholder: "https://example.com",
    related: ["robots-txt-tester", "robots-txt-generator", "sitemap-validator", "indexability-checker"],
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Build a clean robots.txt file from crawler rules, blocked paths and sitemap locations without hand-writing directives.",
    metaDescription: "Generate a valid robots.txt file with user-agent, Allow, Disallow and Sitemap directives, then copy the finished file.",
    primaryEntity: "robots.txt generation",
    relatedEntities: ["User-agent", "Disallow", "Allow", "Sitemap", "crawl rules", "Googlebot"],
    actionLabel: "Generate robots.txt",
    inputLabel: "Rules",
    placeholder: "Disallow paths, one per line",
    related: ["robots-txt-tester", "robots-txt-validator", "sitemap-generator", "indexability-checker"],
  },
  {
    slug: "canonical-url-checker",
    name: "Canonical URL Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect a webpage's rel=canonical implementation, resolve the declared canonical URL and flag common conflicts.",
    metaDescription: "Check a page's canonical tag, preferred URL, status and common canonicalization conflicts with clear recommendations.",
    primaryEntity: "canonical URL",
    relatedEntities: ["rel=canonical", "canonical tag", "duplicate URLs", "preferred URL", "indexing", "redirects", "HTTPS"],
    actionLabel: "Check canonical",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["canonical-tag-generator", "redirect-checker", "indexability-checker", "url-structure-checker"],
  },
  {
    slug: "canonical-tag-generator",
    name: "Canonical Tag Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Generate a correctly formatted rel=canonical link element for the preferred version of a page.",
    metaDescription: "Create a valid rel=canonical HTML tag for your preferred URL and avoid common canonical formatting mistakes.",
    primaryEntity: "canonical tag",
    relatedEntities: ["rel=canonical", "preferred URL", "duplicate content", "HTML head", "absolute URL"],
    actionLabel: "Generate canonical tag",
    inputLabel: "Preferred URL",
    placeholder: "https://example.com/preferred-page",
    related: ["canonical-url-checker", "url-structure-checker", "indexability-checker"],
  },
  {
    slug: "hreflang-checker",
    name: "Hreflang Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect hreflang tags, language-region codes, duplicate entries and reciprocal references on multilingual pages.",
    metaDescription: "Check hreflang implementation, language and region codes, x-default, duplicates and return-link issues on a live page.",
    primaryEntity: "hreflang",
    relatedEntities: ["hreflang attribute", "language code", "region code", "x-default", "international SEO", "return link"],
    actionLabel: "Check hreflang",
    inputLabel: "Page URL",
    placeholder: "https://example.com/en/page",
    related: ["hreflang-generator", "canonical-url-checker", "sitemap-validator"],
  },
  {
    slug: "hreflang-generator",
    name: "Hreflang Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Create valid hreflang link elements for language and regional page variants, including optional x-default markup.",
    metaDescription: "Generate valid hreflang tags for multilingual or multi-region pages using language-region codes and absolute URLs.",
    primaryEntity: "hreflang tag",
    relatedEntities: ["language code", "region code", "x-default", "alternate URL", "international SEO"],
    actionLabel: "Generate hreflang tags",
    inputLabel: "Language and URL pairs",
    placeholder: "en-US | https://example.com/us/page",
    related: ["hreflang-checker", "canonical-url-checker", "sitemap-generator"],
  },
  {
    slug: "redirect-checker",
    name: "Redirect Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Follow a URL request and show each HTTP redirect until the final destination, including response status at every hop.",
    metaDescription: "Check URL redirects, status codes and final destination with a clear redirect path and practical SEO interpretation.",
    primaryEntity: "HTTP redirect",
    relatedEntities: ["301", "302", "307", "308", "Location header", "final URL", "HTTP status"],
    actionLabel: "Check redirects",
    inputLabel: "URL",
    placeholder: "https://example.com/old-page",
    related: ["redirect-chain-checker", "redirect-loop-checker", "http-status-code-checker", "canonical-url-checker"],
  },
  {
    slug: "redirect-chain-checker",
    name: "Redirect Chain Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Reveal multi-hop redirect chains so you can find unnecessary hops, mixed protocols and inefficient destination paths.",
    metaDescription: "Find redirect chains and view every URL and HTTP status in the sequence from the starting URL to the final page.",
    primaryEntity: "redirect chain",
    relatedEntities: ["redirect hop", "301", "302", "HTTP status", "Location header", "crawl efficiency"],
    actionLabel: "Check redirect chain",
    inputLabel: "Starting URL",
    placeholder: "https://example.com/old-url",
    related: ["redirect-checker", "redirect-loop-checker", "http-status-code-checker"],
  },
  {
    slug: "redirect-loop-checker",
    name: "Redirect Loop Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Detect circular redirect behavior and identify the URLs involved before browsers or crawlers hit a redirect limit.",
    metaDescription: "Detect redirect loops, inspect repeated URLs and identify where a redirect path becomes circular or fails to resolve.",
    primaryEntity: "redirect loop",
    relatedEntities: ["too many redirects", "HTTP redirect", "301", "302", "Location header", "circular redirect"],
    actionLabel: "Check redirect loop",
    inputLabel: "URL",
    placeholder: "https://example.com/page",
    related: ["redirect-checker", "redirect-chain-checker", "http-status-code-checker"],
  },
  {
    slug: "http-status-code-checker",
    name: "HTTP Status Code Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Request a URL, report its HTTP response status and explain what the result means for users and search crawlers.",
    metaDescription: "Check HTTP status codes for a URL, follow redirects safely and understand 2xx, 3xx, 4xx and 5xx responses.",
    primaryEntity: "HTTP status code",
    relatedEntities: ["200", "301", "404", "410", "500", "response header", "crawlability"],
    actionLabel: "Check status code",
    inputLabel: "URL",
    placeholder: "https://example.com/page",
    related: ["redirect-checker", "redirect-chain-checker", "indexability-checker"],
  },
  {
    slug: "indexability-checker",
    name: "Indexability Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Review the technical signals that influence whether a page is eligible for indexing without pretending to know Google's live index state.",
    metaDescription: "Analyze indexability signals including HTTP status, robots directives, canonical tags and crawl controls on a live webpage.",
    primaryEntity: "indexability",
    relatedEntities: ["meta robots", "X-Robots-Tag", "canonical", "HTTP status", "crawlability", "noindex", "robots.txt"],
    actionLabel: "Check indexability",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["noindex-checker", "meta-robots-checker", "x-robots-tag-checker", "canonical-url-checker", "robots-txt-tester"],
  },
  {
    slug: "noindex-checker",
    name: "Noindex Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Detect noindex directives in meta robots markup and relevant HTTP response headers on a live URL.",
    metaDescription: "Check whether a webpage declares noindex through meta robots or X-Robots-Tag headers and see the exact directive found.",
    primaryEntity: "noindex",
    relatedEntities: ["meta robots", "X-Robots-Tag", "indexing directive", "robots", "HTML head"],
    actionLabel: "Check noindex",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-robots-checker", "x-robots-tag-checker", "indexability-checker", "robots-txt-tester"],
  },
  {
    slug: "meta-robots-checker",
    name: "Meta Robots Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Read the page's meta robots directives and explain how index, noindex, follow and related instructions are being declared.",
    metaDescription: "Analyze meta robots tags on a webpage and understand index, noindex, follow, nofollow and snippet-related directives.",
    primaryEntity: "meta robots",
    relatedEntities: ["index", "noindex", "follow", "nofollow", "max-snippet", "HTML meta tag"],
    actionLabel: "Check meta robots",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["noindex-checker", "x-robots-tag-checker", "meta-robots-generator", "indexability-checker"],
  },
  {
    slug: "x-robots-tag-checker",
    name: "X-Robots-Tag Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Inspect X-Robots-Tag response headers and explain indexing directives delivered outside the HTML document.",
    metaDescription: "Check X-Robots-Tag HTTP headers for noindex and other indexing directives that may not appear in page source.",
    primaryEntity: "X-Robots-Tag",
    relatedEntities: ["HTTP header", "noindex", "indexing directive", "robots", "PDF indexing"],
    actionLabel: "Check X-Robots-Tag",
    inputLabel: "URL",
    placeholder: "https://example.com/document.pdf",
    related: ["noindex-checker", "meta-robots-checker", "indexability-checker"],
  },
  {
    slug: "url-structure-checker",
    name: "URL Structure Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Review URL length, readability, parameters, path depth and characters that can make addresses harder to understand or maintain.",
    metaDescription: "Analyze URL structure for readability, length, parameters, path depth and common SEO or usability issues.",
    primaryEntity: "URL structure",
    relatedEntities: ["URL slug", "query parameter", "path depth", "HTTPS", "readability", "percent encoding"],
    actionLabel: "Analyze URL",
    inputLabel: "URL",
    placeholder: "https://example.com/category/product?ref=123",
    related: ["seo-slug-checker", "canonical-url-checker", "redirect-checker"],
  },
  {
    slug: "sitemap-validator",
    name: "XML Sitemap Validator",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Fetch an XML sitemap, verify its root structure and inspect loc entries for common formatting and protocol mistakes.",
    metaDescription: "Validate an XML sitemap's structure, namespace, URL entries and common formatting problems with clear error messages.",
    primaryEntity: "XML sitemap",
    relatedEntities: ["urlset", "loc", "lastmod", "XML namespace", "sitemap protocol", "indexing discovery"],
    actionLabel: "Validate sitemap",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-url-checker", "sitemap-index-checker", "sitemap-lastmod-checker", "sitemap-generator"],
  },
  {
    slug: "sitemap-url-checker",
    name: "Sitemap URL Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Inspect URLs listed in a sitemap and sample their HTTP responses to surface broken or redirected entries.",
    metaDescription: "Check URLs contained in an XML sitemap and review sampled HTTP status, redirects and indexability-related signals.",
    primaryEntity: "sitemap URLs",
    relatedEntities: ["XML sitemap", "loc", "HTTP status", "redirect", "indexable URL", "crawl discovery"],
    actionLabel: "Check sitemap URLs",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-validator", "http-status-code-checker", "indexability-checker"],
  },
  {
    slug: "sitemap-index-checker",
    name: "Sitemap Index Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Analyze a sitemap index file, list referenced child sitemaps and identify malformed or duplicate sitemap entries.",
    metaDescription: "Check XML sitemap index files, referenced child sitemaps, duplicate entries and structural issues.",
    primaryEntity: "sitemap index",
    relatedEntities: ["sitemapindex", "sitemap", "loc", "lastmod", "child sitemap", "XML"],
    actionLabel: "Check sitemap index",
    inputLabel: "Sitemap index URL",
    placeholder: "https://example.com/sitemap_index.xml",
    related: ["sitemap-validator", "sitemap-url-checker", "sitemap-lastmod-checker"],
  },
  {
    slug: "sitemap-lastmod-checker",
    name: "Sitemap Lastmod Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Review lastmod values inside a sitemap and flag missing, invalid, future-dated or inconsistent timestamps.",
    metaDescription: "Analyze XML sitemap lastmod dates for valid ISO formatting, future dates and consistency issues.",
    primaryEntity: "sitemap lastmod",
    relatedEntities: ["lastmod", "ISO 8601", "XML sitemap", "modification date", "crawl scheduling"],
    actionLabel: "Check lastmod values",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-validator", "sitemap-index-checker", "sitemap-generator"],
  },
  {
    slug: "sitemap-generator",
    name: "XML Sitemap Generator",
    category: "XML Sitemaps",
    mode: "generator",
    summary: "Turn a list of absolute URLs into a standards-compliant XML sitemap that you can download or host on your site.",
    metaDescription: "Generate a valid XML sitemap from a list of URLs with optional lastmod values and clear formatting.",
    primaryEntity: "XML sitemap generation",
    relatedEntities: ["urlset", "loc", "lastmod", "sitemap protocol", "crawl discovery"],
    actionLabel: "Generate sitemap",
    inputLabel: "URLs (one per line)",
    placeholder: "https://example.com/\nhttps://example.com/about",
    related: ["sitemap-validator", "sitemap-url-checker", "robots-txt-generator"],
  },
  {
    slug: "schema-validator",
    name: "Schema Markup Validator",
    category: "Structured Data",
    mode: "url",
    summary: "Fetch a page and inspect structured data blocks for presence, basic validity and common implementation issues.",
    metaDescription: "Validate schema markup and structured data on a live page with practical SEO interpretation.",
    primaryEntity: "schema markup",
    relatedEntities: ["JSON-LD", "Microdata", "structured data", "Schema.org", "rich results"],
    actionLabel: "Validate schema",
    inputLabel: "Page URL",
    placeholder: "https://example.com/article",
    related: ["json-ld-validator", "schema-markup-generator", "faq-schema-generator"],
  },
  {
    slug: "json-ld-validator",
    name: "JSON-LD Validator",
    category: "Structured Data",
    mode: "url",
    summary: "Extract JSON-LD scripts from a page and check for parse errors, missing required fields and type issues.",
    metaDescription: "Validate JSON-LD structured data on a webpage for syntax and common Schema.org issues.",
    primaryEntity: "JSON-LD",
    relatedEntities: ["structured data", "Schema.org", "script type application/ld+json", "rich results"],
    actionLabel: "Validate JSON-LD",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["schema-validator", "schema-markup-generator"],
  },
  {
    slug: "schema-markup-generator",
    name: "Schema Markup Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate common Schema.org JSON-LD snippets for pages, articles, products and organizations.",
    metaDescription: "Generate Schema.org JSON-LD markup for common page types with clean, copy-ready output.",
    primaryEntity: "schema generation",
    relatedEntities: ["JSON-LD", "Schema.org", "Article", "Product", "Organization"],
    actionLabel: "Generate schema",
    inputLabel: "Page details",
    placeholder: "Type and key fields",
    related: ["schema-validator", "json-ld-validator", "faq-schema-generator"],
  },
  {
    slug: "faq-schema-generator",
    name: "FAQ Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Build FAQPage JSON-LD from question and answer pairs for eligible FAQ content.",
    metaDescription: "Generate FAQPage schema markup from questions and answers for structured data testing.",
    primaryEntity: "FAQ schema",
    relatedEntities: ["FAQPage", "JSON-LD", "Schema.org", "rich results"],
    actionLabel: "Generate FAQ schema",
    inputLabel: "Questions and answers",
    placeholder: "Q: ...\nA: ...",
    related: ["schema-validator", "schema-markup-generator", "howto-schema-generator"],
  },
  {
    slug: "howto-schema-generator",
    name: "HowTo Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Create HowTo JSON-LD from step-by-step instructions for eligible how-to content.",
    metaDescription: "Generate HowTo schema markup from ordered steps for structured data implementation.",
    primaryEntity: "HowTo schema",
    relatedEntities: ["HowTo", "JSON-LD", "Schema.org", "step markup"],
    actionLabel: "Generate HowTo schema",
    inputLabel: "Steps",
    placeholder: "Step 1: ...",
    related: ["faq-schema-generator", "schema-validator"],
  },
  {
    slug: "article-schema-generator",
    name: "Article Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate Article or BlogPosting JSON-LD with headline, author, date and publisher fields.",
    metaDescription: "Create Article schema markup with required and recommended fields for news and blog pages.",
    primaryEntity: "Article schema",
    relatedEntities: ["Article", "BlogPosting", "JSON-LD", "headline", "author"],
    actionLabel: "Generate Article schema",
    inputLabel: "Article details",
    placeholder: "Headline, author, date",
    related: ["schema-validator", "schema-markup-generator"],
  },
  {
    slug: "product-schema-generator",
    name: "Product Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Build Product JSON-LD with name, offers, brand and optional review fields for product pages.",
    metaDescription: "Generate Product schema markup for e-commerce pages with offers and brand details.",
    primaryEntity: "Product schema",
    relatedEntities: ["Product", "Offer", "Brand", "JSON-LD", "Schema.org"],
    actionLabel: "Generate Product schema",
    inputLabel: "Product details",
    placeholder: "Name, price, currency",
    related: ["schema-validator", "schema-markup-generator"],
  },
  {
    slug: "organization-schema-generator",
    name: "Organization Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate Organization JSON-LD for sitewide entity markup including name, URL and logo.",
    metaDescription: "Create Organization schema markup for brand and publisher entity signals.",
    primaryEntity: "Organization schema",
    relatedEntities: ["Organization", "logo", "sameAs", "JSON-LD"],
    actionLabel: "Generate Organization schema",
    inputLabel: "Organization details",
    placeholder: "Name, URL, logo URL",
    related: ["schema-validator", "breadcrumb-schema-generator"],
  },
  {
    slug: "breadcrumb-schema-generator",
    name: "Breadcrumb Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Create BreadcrumbList JSON-LD from a path of labels and URLs for navigation markup.",
    metaDescription: "Generate BreadcrumbList schema from navigation hierarchy for structured data.",
    primaryEntity: "BreadcrumbList",
    relatedEntities: ["BreadcrumbList", "ListItem", "JSON-LD", "navigation"],
    actionLabel: "Generate breadcrumb schema",
    inputLabel: "Breadcrumb path",
    placeholder: "Home > Category > Page",
    related: ["organization-schema-generator", "schema-validator"],
  },
];

export const SEO_TOOL_BY_SLUG = new Map(SEO_TOOLS.map((tool) => [tool.slug, tool]));

export function getSeoTool(slug: string) {
  return SEO_TOOL_BY_SLUG.get(slug);
}

export function toolsByCategory(category: SeoToolCategory) {
  return SEO_TOOLS.filter((tool) => tool.category === category);
}
