type SeoToolDefinition = {
  slug: string;
  name: string;
  category: string;
  mode: string;
  summary: string;
  metaDescription: string;
  primaryEntity: string;
  relatedEntities: string[];
  actionLabel: string;
  inputLabel: string;
  placeholder: string;
  related: string[];
};

export const REST_SEO_TOOLS: SeoToolDefinition[] = [
  {
    slug: "video-schema-generator",
    name: "Video Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate VideoObject JSON-LD with name, description, thumbnail and upload date for video pages.",
    metaDescription: "Create VideoObject schema markup for video content with key fields for rich results eligibility.",
    primaryEntity: "VideoObject schema",
    relatedEntities: ["VideoObject", "JSON-LD", "thumbnail", "Schema.org"],
    actionLabel: "Generate Video schema",
    inputLabel: "Video details",
    placeholder: "Title, description, thumbnail URL",
    related: ["schema-validator", "schema-markup-generator"],
  },
  {
    slug: "internal-link-checker",
    name: "Internal Link Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "List internal links on a page and review destination paths for structure and basic health signals.",
    metaDescription: "Analyze internal links on a webpage including anchors and destination URLs for on-page SEO.",
    primaryEntity: "internal links",
    relatedEntities: ["anchor text", "internal linking", "crawl path", "site architecture"],
    actionLabel: "Check internal links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-analyzer", "broken-link-checker", "anchor-text-analyzer"],
  },
  {
    slug: "internal-link-analyzer",
    name: "Internal Link Analyzer",
    category: "On-Page SEO",
    mode: "url",
    summary: "Analyze internal link distribution, anchor patterns and depth signals on a single page.",
    metaDescription: "Deep-dive internal link analysis for anchor text, path depth and linking patterns.",
    primaryEntity: "internal link analysis",
    relatedEntities: ["anchor text", "link equity", "site architecture", "crawl depth"],
    actionLabel: "Analyze internal links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-checker", "anchor-text-analyzer", "broken-link-checker"],
  },
  {
    slug: "external-link-checker",
    name: "External Link Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "List outbound links on a page and flag common issues such as nofollow usage and target attributes.",
    metaDescription: "Inspect external links on a webpage for destination domains, rel attributes and basic health.",
    primaryEntity: "external links",
    relatedEntities: ["outbound links", "nofollow", "sponsored", "ugc", "rel attribute"],
    actionLabel: "Check external links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["broken-link-checker", "internal-link-checker"],
  },
  {
    slug: "broken-link-checker",
    name: "Broken Link Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Sample links on a page and report HTTP status codes that indicate broken or redirected destinations.",
    metaDescription: "Find broken and redirected links on a webpage with status codes and destination URLs.",
    primaryEntity: "broken links",
    relatedEntities: ["404", "HTTP status", "dead links", "link health"],
    actionLabel: "Check broken links",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-checker", "external-link-checker", "http-status-code-checker"],
  },
  {
    slug: "anchor-text-analyzer",
    name: "Anchor Text Analyzer",
    category: "On-Page SEO",
    mode: "url",
    summary: "Extract anchor text used on a page and summarize patterns for internal and external links.",
    metaDescription: "Analyze anchor text distribution on a page for descriptive, generic and over-optimized patterns.",
    primaryEntity: "anchor text",
    relatedEntities: ["internal links", "link text", "over-optimization", "descriptive anchors"],
    actionLabel: "Analyze anchor text",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["internal-link-analyzer", "internal-link-checker"],
  },
  {
    slug: "heading-checker",
    name: "Heading Structure Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Inspect H1–H6 hierarchy, multiple H1s and skipped levels that affect content structure and accessibility.",
    metaDescription: "Check heading structure on a page for H1 usage, hierarchy order and common on-page SEO issues.",
    primaryEntity: "heading structure",
    relatedEntities: ["H1", "H2", "heading hierarchy", "on-page SEO", "accessibility"],
    actionLabel: "Check headings",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-title-checker", "seo-page-analyzer"],
  },
  {
    slug: "image-alt-checker",
    name: "Image Alt Text Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "List images on a page and report missing, empty or weak alt attributes for accessibility and image SEO.",
    metaDescription: "Audit image alt text on a webpage for missing and low-quality descriptions.",
    primaryEntity: "image alt text",
    relatedEntities: ["alt attribute", "accessibility", "image SEO", "descriptive alt"],
    actionLabel: "Check image alt text",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["image-seo-checker", "seo-page-analyzer"],
  },
  {
    slug: "image-seo-checker",
    name: "Image SEO Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Review images for alt text, file names, dimensions hints and basic on-page image SEO signals.",
    metaDescription: "Check image SEO factors including alt text, naming and basic optimization signals on a page.",
    primaryEntity: "image SEO",
    relatedEntities: ["alt text", "file name", "image optimization", "lazy loading"],
    actionLabel: "Check image SEO",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["image-alt-checker", "seo-page-analyzer"],
  },
  {
    slug: "meta-title-checker",
    name: "Meta Title Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Read the page title element and evaluate length, clarity and basic SERP presentation risks.",
    metaDescription: "Check meta title length, uniqueness signals and SERP-friendly wording on a live page.",
    primaryEntity: "meta title",
    relatedEntities: ["title tag", "SERP", "pixel width", "click-through rate"],
    actionLabel: "Check meta title",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-description-checker", "serp-title-pixel-checker", "seo-snippet-preview"],
  },
  {
    slug: "meta-description-checker",
    name: "Meta Description Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Inspect the meta description for presence, length and usefulness as a search result summary.",
    metaDescription: "Check meta description length and quality on a webpage for SERP snippet potential.",
    primaryEntity: "meta description",
    relatedEntities: ["SERP snippet", "CTR", "meta tag", "summary text"],
    actionLabel: "Check meta description",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-title-checker", "meta-description-pixel-checker", "seo-snippet-preview"],
  },
  {
    slug: "meta-tag-checker",
    name: "Meta Tag Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "List important meta tags on a page including robots, description, viewport and social tags.",
    metaDescription: "Audit common meta tags on a webpage for SEO and social sharing configuration.",
    primaryEntity: "meta tags",
    relatedEntities: ["meta robots", "viewport", "description", "Open Graph"],
    actionLabel: "Check meta tags",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-title-checker", "meta-description-checker", "og-tag-checker"],
  },
  {
    slug: "seo-slug-checker",
    name: "SEO Slug Checker",
    category: "On-Page SEO",
    mode: "url",
    summary: "Evaluate the URL slug for readability, length, separators and keyword-friendly structure.",
    metaDescription: "Check URL slug quality for SEO-friendly length, hyphens and readable wording.",
    primaryEntity: "URL slug",
    relatedEntities: ["permalink", "URL structure", "hyphen", "readability"],
    actionLabel: "Check SEO slug",
    inputLabel: "URL",
    placeholder: "https://example.com/my-page-slug",
    related: ["url-structure-checker", "canonical-url-checker"],
  },
  {
    slug: "og-tag-checker",
    name: "Open Graph Tag Checker",
    category: "Social & SERP",
    mode: "url",
    summary: "Inspect Open Graph tags for title, description, image and type used in social previews.",
    metaDescription: "Validate Open Graph meta tags for Facebook, LinkedIn and other social share previews.",
    primaryEntity: "Open Graph",
    relatedEntities: ["og:title", "og:description", "og:image", "social preview"],
    actionLabel: "Check OG tags",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["twitter-card-checker", "seo-snippet-preview", "meta-tag-checker"],
  },
  {
    slug: "twitter-card-checker",
    name: "Twitter Card Checker",
    category: "Social & SERP",
    mode: "url",
    summary: "Review Twitter Card meta tags for card type, title, description and image configuration.",
    metaDescription: "Check Twitter Card tags for proper social preview configuration on a webpage.",
    primaryEntity: "Twitter Card",
    relatedEntities: ["twitter:card", "twitter:title", "twitter:image", "social preview"],
    actionLabel: "Check Twitter Cards",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["og-tag-checker", "seo-snippet-preview"],
  },
  {
    slug: "meta-robots-generator",
    name: "Meta Robots Generator",
    category: "Technical SEO",
    mode: "generator",
    summary: "Generate a meta robots tag with index/noindex and follow/nofollow combinations for the page head.",
    metaDescription: "Create meta robots HTML tags with common indexing and snippet directives.",
    primaryEntity: "meta robots generation",
    relatedEntities: ["noindex", "nofollow", "max-snippet", "meta tag"],
    actionLabel: "Generate meta robots",
    inputLabel: "Directives",
    placeholder: "noindex, nofollow",
    related: ["meta-robots-checker", "noindex-checker"],
  },
  {
    slug: "seo-snippet-preview",
    name: "SEO Snippet Preview",
    category: "Social & SERP",
    mode: "preview",
    summary: "Preview how a title and description may appear in a typical search result snippet layout.",
    metaDescription: "Preview SERP-style title and description snippets before publishing page metadata.",
    primaryEntity: "SERP snippet",
    relatedEntities: ["title tag", "meta description", "CTR", "search result"],
    actionLabel: "Preview snippet",
    inputLabel: "Title and description",
    placeholder: "Title | Description",
    related: ["meta-title-checker", "meta-description-checker", "serp-title-pixel-checker"],
  },
  {
    slug: "serp-title-pixel-checker",
    name: "SERP Title Pixel Checker",
    category: "Social & SERP",
    mode: "text",
    summary: "Estimate title display width in pixels to reduce the chance of SERP truncation on desktop results.",
    metaDescription: "Check approximate pixel width of a title tag for Google SERP display limits.",
    primaryEntity: "title pixel width",
    relatedEntities: ["SERP", "title tag", "truncation", "CTR"],
    actionLabel: "Check title pixels",
    inputLabel: "Title text",
    placeholder: "Your page title here",
    related: ["meta-title-checker", "seo-snippet-preview", "meta-description-pixel-checker"],
  },
  {
    slug: "meta-description-pixel-checker",
    name: "Meta Description Pixel Checker",
    category: "Social & SERP",
    mode: "text",
    summary: "Estimate meta description display width to understand truncation risk in search results.",
    metaDescription: "Check approximate pixel width of a meta description for SERP snippet display.",
    primaryEntity: "description pixel width",
    relatedEntities: ["meta description", "SERP", "truncation", "snippet"],
    actionLabel: "Check description pixels",
    inputLabel: "Description text",
    placeholder: "Your meta description here",
    related: ["meta-description-checker", "seo-snippet-preview", "serp-title-pixel-checker"],
  },
  {
    slug: "seo-page-analyzer",
    name: "SEO Page Analyzer",
    category: "On-Page SEO",
    mode: "url",
    summary: "Run a combined on-page SEO check covering title, description, headings, links and basic technical signals.",
    metaDescription: "Analyze a page for core on-page SEO factors with a practical summary of strengths and issues.",
    primaryEntity: "on-page SEO audit",
    relatedEntities: ["title tag", "meta description", "headings", "internal links", "indexability"],
    actionLabel: "Analyze page",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: ["meta-title-checker", "heading-checker", "internal-link-analyzer", "indexability-checker"],
  },
];
