type SeoToolDefinition = {
  slug: string; name: string; category: string; mode: string;
  summary: string; metaDescription: string; primaryEntity: string;
  relatedEntities: string[]; actionLabel: string; inputLabel: string;
  placeholder: string; related: string[];
};

export const EXTRA_SEO_TOOLS_2: SeoToolDefinition[] = [
  {
    slug: "google-business-profile-checker",
    name: "Google Business Profile Checker",
    category: "Local SEO",
    mode: "url",
    summary: "Review common on-page signals that support a Google Business Profile listing for a local business URL.",
    metaDescription: "Review common on-page signals that support a Google Business Profile listing for a local business URL.",
    primaryEntity: "Google Business Profile",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "nap-consistency-checker",
    name: "NAP Consistency Checker",
    category: "Local SEO",
    mode: "text",
    summary: "Check name, address and phone formatting consistency for local SEO citations.",
    metaDescription: "Check name, address and phone formatting consistency for local SEO citations.",
    primaryEntity: "NAP consistency",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Text",
    placeholder: "Paste text...",
    related: [],
  },
  {
    slug: "local-schema-presence-checker",
    name: "Local Schema Presence Checker",
    category: "Local SEO",
    mode: "url",
    summary: "Detect LocalBusiness and related schema on a location or contact page.",
    metaDescription: "Detect LocalBusiness and related schema on a location or contact page.",
    primaryEntity: "local schema",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "local-landing-page-checker",
    name: "Local Landing Page Checker",
    category: "Local SEO",
    mode: "url",
    summary: "Audit a city or service-area landing page for local relevance and basic SEO signals.",
    metaDescription: "Audit a city or service-area landing page for local relevance and basic SEO signals.",
    primaryEntity: "local landing page",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "service-area-page-outline-generator",
    name: "Service Area Page Outline Generator",
    category: "Local SEO",
    mode: "generator",
    summary: "Generate a user-focused outline for a local service-area page without doorway spam patterns.",
    metaDescription: "Generate a user-focused outline for a local service-area page without doorway spam patterns.",
    primaryEntity: "service area page",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Generate",
    inputLabel: "Topic or details",
    placeholder: "Describe business or page type",
    related: [],
  },
  {
    slug: "local-citation-checklist",
    name: "Local Citation Checklist",
    category: "Local SEO",
    mode: "generator",
    summary: "Produce a practical checklist of citation and directory priorities for a local business.",
    metaDescription: "Produce a practical checklist of citation and directory priorities for a local business.",
    primaryEntity: "local citations",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Generate",
    inputLabel: "Topic or details",
    placeholder: "Describe business or page type",
    related: [],
  },
  {
    slug: "map-embed-checker",
    name: "Map Embed Checker",
    category: "Local SEO",
    mode: "url",
    summary: "Detect embedded maps and basic accessibility or crawl considerations on a contact page.",
    metaDescription: "Detect embedded maps and basic accessibility or crawl considerations on a contact page.",
    primaryEntity: "map embed",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "local-review-schema-checker",
    name: "Local Review Schema Checker",
    category: "Local SEO",
    mode: "url",
    summary: "Check for aggregate rating or review structured data on local business pages.",
    metaDescription: "Check for aggregate rating or review structured data on local business pages.",
    primaryEntity: "review schema",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "opening-hours-schema-checker",
    name: "Opening Hours Schema Checker",
    category: "Local SEO",
    mode: "url",
    summary: "Validate openingHours or OpeningHoursSpecification markup when present.",
    metaDescription: "Validate openingHours or OpeningHoursSpecification markup when present.",
    primaryEntity: "opening hours schema",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "local-faq-generator",
    name: "Local FAQ Generator",
    category: "Local SEO",
    mode: "generator",
    summary: "Create location-relevant FAQ ideas for service and city pages.",
    metaDescription: "Create location-relevant FAQ ideas for service and city pages.",
    primaryEntity: "local FAQ",
    relatedEntities: ["local SEO", "semantic SEO", "user experience"],
    actionLabel: "Generate",
    inputLabel: "Topic or details",
    placeholder: "Describe business or page type",
    related: [],
  },
  {
    slug: "page-weight-checker",
    name: "Page Weight Checker",
    category: "Performance",
    mode: "url",
    summary: "Estimate total transfer size signals from resource hints and response size where available.",
    metaDescription: "Estimate total transfer size signals from resource hints and response size where available.",
    primaryEntity: "page weight",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "image-weight-hint-checker",
    name: "Image Weight Hint Checker",
    category: "Performance",
    mode: "url",
    summary: "List large image candidates and missing modern format or dimension hints.",
    metaDescription: "List large image candidates and missing modern format or dimension hints.",
    primaryEntity: "image weight",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "render-blocking-hint-checker",
    name: "Render-Blocking Hint Checker",
    category: "Performance",
    mode: "url",
    summary: "Flag scripts and styles that often block first render when loaded in the head.",
    metaDescription: "Flag scripts and styles that often block first render when loaded in the head.",
    primaryEntity: "render-blocking resources",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "lazy-load-image-checker",
    name: "Lazy Load Image Checker",
    category: "Performance",
    mode: "url",
    summary: "Check whether below-the-fold images use loading=lazy or similar patterns.",
    metaDescription: "Check whether below-the-fold images use loading=lazy or similar patterns.",
    primaryEntity: "lazy loading",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "core-web-vitals-guide",
    name: "Core Web Vitals Guide Checker",
    category: "Performance",
    mode: "url",
    summary: "Summarize on-page factors that commonly affect LCP, INP and CLS for a URL.",
    metaDescription: "Summarize on-page factors that commonly affect LCP, INP and CLS for a URL.",
    primaryEntity: "Core Web Vitals",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "font-loading-checker",
    name: "Font Loading Checker",
    category: "Performance",
    mode: "url",
    summary: "Inspect font-related link and CSS patterns that can delay text rendering.",
    metaDescription: "Inspect font-related link and CSS patterns that can delay text rendering.",
    primaryEntity: "font loading",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "third-party-script-checker",
    name: "Third-Party Script Checker",
    category: "Performance",
    mode: "url",
    summary: "List third-party script hosts that may impact performance and privacy.",
    metaDescription: "List third-party script hosts that may impact performance and privacy.",
    primaryEntity: "third-party scripts",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "caching-header-checker",
    name: "Caching Header Checker",
    category: "Performance",
    mode: "url",
    summary: "Review cache-control and related headers for static asset caching opportunities.",
    metaDescription: "Review cache-control and related headers for static asset caching opportunities.",
    primaryEntity: "caching headers",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "compression-hint-checker",
    name: "Compression Hint Checker",
    category: "Performance",
    mode: "url",
    summary: "Check content-encoding headers for gzip or brotli compression on the main document.",
    metaDescription: "Check content-encoding headers for gzip or brotli compression on the main document.",
    primaryEntity: "compression",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "critical-css-hint-checker",
    name: "Critical CSS Hint Checker",
    category: "Performance",
    mode: "url",
    summary: "Identify large CSS footprints and inline critical CSS opportunities at a high level.",
    metaDescription: "Identify large CSS footprints and inline critical CSS opportunities at a high level.",
    primaryEntity: "critical CSS",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "preconnect-hint-checker",
    name: "Preconnect Hint Checker",
    category: "Performance",
    mode: "url",
    summary: "Detect preconnect and dns-prefetch resource hints for third-party origins.",
    metaDescription: "Detect preconnect and dns-prefetch resource hints for third-party origins.",
    primaryEntity: "preconnect hints",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "mobile-performance-checklist",
    name: "Mobile Performance Checklist",
    category: "Performance",
    mode: "generator",
    summary: "Generate a mobile-first performance checklist tailored to a page type.",
    metaDescription: "Generate a mobile-first performance checklist tailored to a page type.",
    primaryEntity: "mobile performance",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Generate",
    inputLabel: "Topic or details",
    placeholder: "Describe business or page type",
    related: [],
  },
  {
    slug: "lcp-element-hint-checker",
    name: "LCP Element Hint Checker",
    category: "Performance",
    mode: "url",
    summary: "Highlight likely LCP candidates such as hero images and large text blocks.",
    metaDescription: "Highlight likely LCP candidates such as hero images and large text blocks.",
    primaryEntity: "LCP",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "cls-risk-checker",
    name: "CLS Risk Checker",
    category: "Performance",
    mode: "url",
    summary: "Flag missing image dimensions and embeds that often cause layout shift.",
    metaDescription: "Flag missing image dimensions and embeds that often cause layout shift.",
    primaryEntity: "CLS",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Analyze",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "performance-budget-generator",
    name: "Performance Budget Generator",
    category: "Performance",
    mode: "generator",
    summary: "Create a simple performance budget for HTML, CSS, JS and image weight.",
    metaDescription: "Create a simple performance budget for HTML, CSS, JS and image weight.",
    primaryEntity: "performance budget",
    relatedEntities: ["performance", "semantic SEO", "user experience"],
    actionLabel: "Generate",
    inputLabel: "Topic or details",
    placeholder: "Describe business or page type",
    related: [],
  },
];
