export const EXTRA_SEO_TOOLS_3 = [
  {
    slug: "https-checker",
    name: "HTTPS Checker",
    category: "Security & HTTPS",
    mode: "url",
    summary: "Check whether a URL uses HTTPS, mixed content risk signals and secure transport basics.",
    metaDescription: "Check whether a URL uses HTTPS, mixed content risk signals and secure transport basics.",
    primaryEntity: "HTTPS",
    relatedEntities: ["HTTPS", "SEO"],
    actionLabel: "Check HTTPS",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "mixed-content-checker",
    name: "Mixed Content Checker",
    category: "Security & HTTPS",
    mode: "url",
    summary: "Scan a page for http:// asset references that can trigger mixed content warnings on HTTPS pages.",
    metaDescription: "Scan a page for http:// asset references that can trigger mixed content warnings on HTTPS pages.",
    primaryEntity: "mixed content",
    relatedEntities: ["mixed content", "SEO"],
    actionLabel: "Check mixed content",
    inputLabel: "Page URL",
    placeholder: "https://example.com/page",
    related: [],
  },
  {
    slug: "security-headers-checker",
    name: "Security Headers Checker",
    category: "Security & HTTPS",
    mode: "url",
    summary: "Inspect common security-related response headers such as HSTS, CSP and X-Content-Type-Options.",
    metaDescription: "Inspect common security-related response headers such as HSTS, CSP and X-Content-Type-Options.",
    primaryEntity: "security headers",
    relatedEntities: ["security headers", "SEO"],
    actionLabel: "Check headers",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "hsts-checker",
    name: "HSTS Checker",
    category: "Security & HTTPS",
    mode: "url",
    summary: "Check for Strict-Transport-Security response headers and report basic HSTS configuration signals.",
    metaDescription: "Check for Strict-Transport-Security response headers and report basic HSTS configuration signals.",
    primaryEntity: "HSTS",
    relatedEntities: ["HSTS", "SEO"],
    actionLabel: "Check HSTS",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "ssl-certificate-hint-checker",
    name: "SSL Certificate Hint Checker",
    category: "Security & HTTPS",
    mode: "url",
    summary: "Fetch a page over HTTPS and report whether the secure request completed successfully for SEO-safe transport checks.",
    metaDescription: "Fetch a page over HTTPS and report whether the secure request completed successfully for SEO-safe transport checks.",
    primaryEntity: "SSL",
    relatedEntities: ["SSL", "SEO"],
    actionLabel: "Check SSL response",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "viewport-meta-checker",
    name: "Viewport Meta Checker",
    category: "Mobile & Accessibility",
    mode: "url",
    summary: "Detect the viewport meta tag used for mobile rendering and flag missing or unusual configurations.",
    metaDescription: "Detect the viewport meta tag used for mobile rendering and flag missing or unusual configurations.",
    primaryEntity: "viewport meta",
    relatedEntities: ["viewport meta", "SEO"],
    actionLabel: "Check viewport",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "mobile-friendly-signals-checker",
    name: "Mobile-Friendly Signals Checker",
    category: "Mobile & Accessibility",
    mode: "url",
    summary: "Review basic mobile signals including viewport, tap-friendly layout hints and responsive meta configuration.",
    metaDescription: "Review basic mobile signals including viewport, tap-friendly layout hints and responsive meta configuration.",
    primaryEntity: "mobile SEO",
    relatedEntities: ["mobile SEO", "SEO"],
    actionLabel: "Check mobile signals",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "lang-attribute-checker",
    name: "HTML Lang Attribute Checker",
    category: "Mobile & Accessibility",
    mode: "url",
    summary: "Check the HTML lang attribute on a page for presence and basic language code formatting.",
    metaDescription: "Check the HTML lang attribute on a page for presence and basic language code formatting.",
    primaryEntity: "lang attribute",
    relatedEntities: ["lang attribute", "SEO"],
    actionLabel: "Check lang",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "aria-label-hint-checker",
    name: "ARIA Label Hint Checker",
    category: "Mobile & Accessibility",
    mode: "url",
    summary: "Sample interactive elements for missing accessible names that can affect usability and accessibility quality.",
    metaDescription: "Sample interactive elements for missing accessible names that can affect usability and accessibility quality.",
    primaryEntity: "ARIA labels",
    relatedEntities: ["ARIA labels", "SEO"],
    actionLabel: "Check ARIA hints",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "prefers-color-scheme-hint-checker",
    name: "Color Scheme Meta Checker",
    category: "Mobile & Accessibility",
    mode: "url",
    summary: "Inspect color-scheme related meta tags and theme-color signals that affect browser chrome presentation.",
    metaDescription: "Inspect color-scheme related meta tags and theme-color signals that affect browser chrome presentation.",
    primaryEntity: "theme-color",
    relatedEntities: ["theme-color", "SEO"],
    actionLabel: "Check theme meta",
    inputLabel: "Page URL",
    placeholder: "https://example.com",
    related: [],
  },
  {
    slug: "product-schema-presence-checker",
    name: "Product Schema Presence Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Detect Product structured data on a page and report whether core fields appear present.",
    metaDescription: "Detect Product structured data on a page and report whether core fields appear present.",
    primaryEntity: "Product schema",
    relatedEntities: ["Product schema", "SEO"],
    actionLabel: "Check product schema",
    inputLabel: "Product URL",
    placeholder: "https://example.com/product",
    related: [],
  },
  {
    slug: "offer-schema-checker",
    name: "Offer Schema Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Inspect Offer-related structured data fields such as price and availability when present.",
    metaDescription: "Inspect Offer-related structured data fields such as price and availability when present.",
    primaryEntity: "Offer schema",
    relatedEntities: ["Offer schema", "SEO"],
    actionLabel: "Check offer schema",
    inputLabel: "Product URL",
    placeholder: "https://example.com/product",
    related: [],
  },
  {
    slug: "breadcrumb-presence-checker",
    name: "Breadcrumb Presence Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Check for breadcrumb navigation markup or BreadcrumbList structured data on a page.",
    metaDescription: "Check for breadcrumb navigation markup or BreadcrumbList structured data on a page.",
    primaryEntity: "breadcrumbs",
    relatedEntities: ["breadcrumbs", "SEO"],
    actionLabel: "Check breadcrumbs",
    inputLabel: "Page URL",
    placeholder: "https://example.com/category/product",
    related: [],
  },
  {
    slug: "pagination-rel-checker",
    name: "Pagination Rel Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Detect rel=next and rel=prev link tags historically used for paginated series.",
    metaDescription: "Detect rel=next and rel=prev link tags historically used for paginated series.",
    primaryEntity: "pagination",
    relatedEntities: ["pagination", "SEO"],
    actionLabel: "Check pagination tags",
    inputLabel: "Page URL",
    placeholder: "https://example.com/category?page=2",
    related: [],
  },
  {
    slug: "product-title-length-checker",
    name: "Product Title Length Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Measure product page title length and flag very short or very long titles.",
    metaDescription: "Measure product page title length and flag very short or very long titles.",
    primaryEntity: "product title",
    relatedEntities: ["product title", "SEO"],
    actionLabel: "Check title length",
    inputLabel: "Product URL",
    placeholder: "https://example.com/product",
    related: [],
  },
  {
    slug: "out-of-stock-signal-checker",
    name: "Out of Stock Signal Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Look for common out-of-stock phrases and availability schema signals on a product page.",
    metaDescription: "Look for common out-of-stock phrases and availability schema signals on a product page.",
    primaryEntity: "availability",
    relatedEntities: ["availability", "SEO"],
    actionLabel: "Check stock signals",
    inputLabel: "Product URL",
    placeholder: "https://example.com/product",
    related: [],
  },
  {
    slug: "review-schema-checker",
    name: "Review Schema Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Detect Review or AggregateRating structured data on a page.",
    metaDescription: "Detect Review or AggregateRating structured data on a page.",
    primaryEntity: "review schema",
    relatedEntities: ["review schema", "SEO"],
    actionLabel: "Check review schema",
    inputLabel: "Page URL",
    placeholder: "https://example.com/product",
    related: [],
  },
  {
    slug: "price-in-schema-checker",
    name: "Price In Schema Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Check whether structured data includes price-related fields for commercial pages.",
    metaDescription: "Check whether structured data includes price-related fields for commercial pages.",
    primaryEntity: "price schema",
    relatedEntities: ["price schema", "SEO"],
    actionLabel: "Check price fields",
    inputLabel: "Product URL",
    placeholder: "https://example.com/product",
    related: [],
  },
  {
    slug: "sku-presence-checker",
    name: "SKU Presence Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Search page content and structured data for SKU-like product identifiers.",
    metaDescription: "Search page content and structured data for SKU-like product identifiers.",
    primaryEntity: "SKU",
    relatedEntities: ["SKU", "SEO"],
    actionLabel: "Check SKU",
    inputLabel: "Product URL",
    placeholder: "https://example.com/product",
    related: [],
  },
  {
    slug: "add-to-cart-button-checker",
    name: "Add To Cart Button Checker",
    category: "E-commerce SEO",
    mode: "url",
    summary: "Detect common add-to-cart button text and form signals on a product page.",
    metaDescription: "Detect common add-to-cart button text and form signals on a product page.",
    primaryEntity: "add to cart",
    relatedEntities: ["add to cart", "SEO"],
    actionLabel: "Check cart CTA",
    inputLabel: "Product URL",
    placeholder: "https://example.com/product",
    related: [],
  },
];
