// Core SEO tools part B
export const SEO_TOOLS_CORE_B = [
  {
    slug: "url-structure-checker",
    name: "URL Structure Checker",
    category: "Technical SEO",
    mode: "url",
    summary: "Review URL length, readability, parameters, path depth and characters that can make addresses harder to understand or maintain.",
    metaDescription: "Analyze URL structure for readability, length, parameters, path depth and common SEO or usability issues.",
    primaryEntity: "URL structure",
    relatedEntities: ["URL slug", "query parameter", "path depth", "HTTPS", "readability", "percent encoding"],
    actionLabel: "Analyze URL",
    inputLabel: "URL",
    placeholder: "https://example.com/category/product?ref=123",
    related: ["seo-slug-checker", "canonical-url-checker", "redirect-checker"],
  },
  {
    slug: "sitemap-validator",
    name: "XML Sitemap Validator",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Fetch an XML sitemap, verify its root structure and inspect loc entries for common formatting and protocol mistakes.",
    metaDescription: "Validate an XML sitemap's structure, namespace, URL entries and common formatting problems with clear error messages.",
    primaryEntity: "XML sitemap",
    relatedEntities: ["urlset", "loc", "lastmod", "XML namespace", "sitemap protocol", "indexing discovery"],
    actionLabel: "Validate sitemap",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-url-checker", "sitemap-index-checker", "sitemap-lastmod-checker", "sitemap-generator"],
  },
  {
    slug: "sitemap-url-checker",
    name: "Sitemap URL Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Inspect URLs listed in a sitemap and sample their HTTP responses to surface broken or redirected entries.",
    metaDescription: "Check URLs contained in an XML sitemap and review sampled HTTP status, redirects and indexability-related signals.",
    primaryEntity: "sitemap URLs",
    relatedEntities: ["XML sitemap", "loc", "HTTP status", "redirect", "indexable URL", "crawl discovery"],
    actionLabel: "Check sitemap URLs",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-validator", "http-status-code-checker", "indexability-checker"],
  },
  {
    slug: "sitemap-index-checker",
    name: "Sitemap Index Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Analyze a sitemap index file, list referenced child sitemaps and identify malformed or duplicate sitemap entries.",
    metaDescription: "Check XML sitemap index files, referenced child sitemaps, duplicate entries and structural issues.",
    primaryEntity: "sitemap index",
    relatedEntities: ["sitemapindex", "sitemap", "loc", "lastmod", "child sitemap", "XML"],
    actionLabel: "Check sitemap index",
    inputLabel: "Sitemap index URL",
    placeholder: "https://example.com/sitemap_index.xml",
    related: ["sitemap-validator", "sitemap-url-checker", "sitemap-lastmod-checker"],
  },
  {
    slug: "sitemap-lastmod-checker",
    name: "Sitemap Lastmod Checker",
    category: "XML Sitemaps",
    mode: "url",
    summary: "Review lastmod values inside a sitemap and flag missing, invalid, future-dated or inconsistent timestamps.",
    metaDescription: "Analyze XML sitemap lastmod dates for valid ISO formatting, future dates and consistency issues.",
    primaryEntity: "sitemap lastmod",
    relatedEntities: ["lastmod", "ISO 8601", "XML sitemap", "modification date", "crawl scheduling"],
    actionLabel: "Check lastmod values",
    inputLabel: "Sitemap URL",
    placeholder: "https://example.com/sitemap.xml",
    related: ["sitemap-validator", "sitemap-index-checker", "sitemap-generator"],
  },
  {
    slug: "sitemap-generator",
    name: "XML Sitemap Generator",
    category: "XML Sitemaps",
    mode: "generator",
    summary: "Turn a list of absolute URLs into a standards-compliant XML sitemap that you can download or host on your site.",
    metaDescription: "Generate a valid XML sitemap from a list of URLs with optional lastmod values and clear formatting.",
    primaryEntity: "XML sitemap generation",
    relatedEntities: ["urlset", "loc", "lastmod", "sitemap protocol", "crawl discovery"],
    actionLabel: "Generate sitemap",
    inputLabel: "URLs (one per line)",
    placeholder: "https://example.com/\nhttps://example.com/about",
    related: ["sitemap-validator", "sitemap-url-checker", "robots-txt-generator"],
  },
  {
    slug: "schema-validator",
    name: "Schema Markup Validator",
    category: "Structured Data",
    mode: "url",
    summary: "Fetch a page and inspect structured data blocks for presence, basic validity and common implementation issues.",
    metaDescription: "Validate schema markup and structured data on a live page with practical SEO interpretation.",
    primaryEntity: "schema markup",
    relatedEntities: ["JSON-LD", "Microdata", "structured data", "Schema.org", "rich results"],
    actionLabel: "Validate schema",
    inputLabel: "Page URL",
    placeholder: "https://example.com/article",
    related: ["json-ld-validator", "schema-markup-generator", "faq-schema-generator"],
  },
  {
    slug: "json-ld-validator",
    name: "JSON-LD Validator",
    category: "Structured Data",
    mode: "url",
    summary: "Extract JSON-LD scripts from a page and check for parse errors, missing required fields and type issues.",
    metaDescription: "Validate JSON-LD structured data on a webpage for syntax and common Schema.org issues.",
    primaryEntity: "JSON-LD",
    relatedEntities: ["JSON-LD", "@type", "@context", "Schema.org", "structured data"],
    actionLabel: "Validate JSON-LD",
    inputLabel: "Page URL",
    placeholder: "https://example.com/article",
    related: ["schema-validator", "schema-markup-generator"],
  },
  {
    slug: "schema-markup-generator",
    name: "Schema Markup Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate basic Schema.org JSON-LD for common types such as WebPage, Article and Organization.",
    metaDescription: "Create Schema.org JSON-LD markup for common page types with clean formatting.",
    primaryEntity: "Schema.org JSON-LD",
    relatedEntities: ["JSON-LD", "@type", "WebPage", "Article", "Organization"],
    actionLabel: "Generate schema",
    inputLabel: "Schema fields",
    placeholder: "Type, name, URL, description",
    related: ["schema-validator", "json-ld-validator"],
  },
  {
    slug: "faq-schema-generator",
    name: "FAQ Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Create FAQPage JSON-LD from question and answer pairs for FAQ structured data.",
    metaDescription: "Generate FAQPage schema markup from question and answer pairs.",
    primaryEntity: "FAQ schema",
    relatedEntities: ["FAQPage", "Question", "Answer", "JSON-LD"],
    actionLabel: "Generate FAQ schema",
    inputLabel: "Questions and answers",
    placeholder: "Question | Answer",
    related: ["schema-validator", "article-schema-generator"],
  },
  {
    slug: "article-schema-generator",
    name: "Article Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate Article JSON-LD with headline, author and date fields for editorial pages.",
    metaDescription: "Create Article schema markup for blog posts and editorial content.",
    primaryEntity: "Article schema",
    relatedEntities: ["Article", "headline", "author", "datePublished", "JSON-LD"],
    actionLabel: "Generate Article schema",
    inputLabel: "Article fields",
    placeholder: "Headline, URL, author, dates",
    related: ["faq-schema-generator", "schema-validator"],
  },
  {
    slug: "organization-schema-generator",
    name: "Organization Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate Organization JSON-LD for sitewide entity markup including name, URL and logo.",
    metaDescription: "Create Organization schema markup for brand and publisher entity signals.",
    primaryEntity: "Organization schema",
    relatedEntities: ["Organization", "logo", "sameAs", "JSON-LD"],
    actionLabel: "Generate Organization schema",
    inputLabel: "Organization details",
    placeholder: "Name, URL, logo URL",
    related: ["schema-validator", "breadcrumb-schema-generator"],
  },
  {
    slug: "breadcrumb-schema-generator",
    name: "Breadcrumb Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Create BreadcrumbList JSON-LD from a path of labels and URLs for navigation markup.",
    metaDescription: "Generate BreadcrumbList schema from navigation hierarchy for structured data.",
    primaryEntity: "BreadcrumbList",
    relatedEntities: ["BreadcrumbList", "ListItem", "JSON-LD", "navigation"],
    actionLabel: "Generate breadcrumb schema",
    inputLabel: "Breadcrumb path",
    placeholder: "Home > Category > Page",
    related: ["organization-schema-generator", "schema-validator"],
  },
  {
    slug: "local-business-schema-generator",
    name: "Local Business Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate LocalBusiness JSON-LD with name, address, phone and opening hours for local SEO.",
    metaDescription: "Create LocalBusiness schema markup for local search and entity signals.",
    primaryEntity: "LocalBusiness schema",
    relatedEntities: ["LocalBusiness", "PostalAddress", "JSON-LD", "local SEO"],
    actionLabel: "Generate LocalBusiness schema",
    inputLabel: "Business details",
    placeholder: "Name, address, phone",
    related: ["organization-schema-generator", "schema-validator"],
  },
  {
    slug: "website-schema-generator",
    name: "WebSite Schema Generator",
    category: "Structured Data",
    mode: "generator",
    summary: "Generate WebSite JSON-LD with name, URL and optional SearchAction for sitewide markup.",
    metaDescription: "Create WebSite schema markup for homepage and sitewide entity understanding.",
    primaryEntity: "WebSite schema",
    relatedEntities: ["WebSite", "SearchAction", "JSON-LD", "Schema.org"],
    actionLabel: "Generate WebSite schema",
    inputLabel: "Site details",
    placeholder: "Site name and homepage URL",
    related: ["organization-schema-generator", "schema-validator"],
  },
];
