import type { ToolEditorial } from "@/lib/seo-tools/content";

export const KEYWORD_BATCH_TOOL_EDITORIAL: Record<string, ToolEditorial> = {
  "keyword-density-checker": {
    definition: "A Keyword Density Checker counts how many times a target phrase appears in a block of text and expresses it as a percentage of total words. It is a mechanical frequency measurement, not a quality judgment. Google does not use keyword density as a ranking factor, so the number describes your writing habits rather than your SEO strength.",
    whyItMatters: "Unnaturally repeated keywords make content awkward for readers and can signal low-quality writing to anyone reviewing the page. Checking density helps you spot accidental stuffing, such as a product name repeated in every sentence, before publishing. The goal is natural topical coverage, not hitting a percentage.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to count total words and keyword occurrences.", "Review the density percentage for each target phrase.", "Judge the result against how the text reads, not against a magic number.", "Revise phrasing where repetition feels forced, then re-run the analysis."],
    interpretation: ["Density under roughly 2% usually indicates natural usage for most topics.", "A high percentage does not automatically mean over-optimization; short pages and brand names inflate the figure.", "Zero mentions of a core topic phrase may mean the draft drifted off subject.", "Single-word counts can mislead; check multi-word phrases that match real search language."],
    commonProblems: ["Chasing a target percentage and rewriting until the number looks right.", "Counting density on pages where synonyms and related terms do the real work.", "Testing a page template instead of the article body, so navigation labels inflate the count.", "Treating density as a ranking factor while ignoring topical completeness."],
    fixes: ["Rewrite repeated phrases with natural synonyms and pronouns.", "Expand the section so the topic is covered in depth instead of repeated in shorthand.", "Remove template text from the pasted sample before analyzing.", "Answer related sub-questions rather than repeating one phrase."],
    bestPractices: ["Use the tool as a writing-quality check, not an optimization target.", "Write for the topic first, then verify the language sounds natural.", "Let your own editorial standards beat any percentage.", "Combine density review with a topical coverage check for related terms."],
    example: "A 600-word article about sourdough starter that mentions the exact phrase 25 times reads as stuffed; replacing several mentions with \"the culture\" or \"your starter\" keeps the topic clear while removing mechanical repetition.",
    limitations: "The tool counts literal string matches in pasted text. It does not understand synonyms, stemming nuances, page context, or how search engines interpret topical relevance.",
    faqs: [
      { question: "What is a good keyword density percentage?", answer: "There is no official target. Google has never published one; write naturally and use the figure only to catch accidental repetition." },
      { question: "Can high keyword density get my page penalized?", answer: "Blatant stuffing can contribute to a low-quality assessment, but the problem is the poor writing itself, not the percentage." },
      { question: "Does keyword density include headings and alt text?", answer: "This tool measures the text you paste. If you want headings included, paste them in as well." },
      { question: "Why is my density high for a brand name?", answer: "Short texts and repeated brand mentions inflate percentages mechanically; judge by readability instead." },
      { question: "Should I check density before or after editing?", answer: "After. Write the draft first, then use the check to spot repetition you missed." },
    ],
  },
  "readability-score-checker": {
    definition: "A Readability Score Checker estimates how easy a passage is to read using formulas such as Flesch Reading Ease or Flesch-Kincaid Grade Level, which weigh sentence length and syllable counts. It produces a score or grade band, not a direct measure of comprehension. These formulas are heuristics from print-era research, so they reward short sentences and familiar words.",
    whyItMatters: "Content that is hard to parse gets skimmed, abandoned, or misunderstood, and no ranking can compensate for readers who leave confused. Readability scores give writers an objective nudge when sentences have grown tangled. They are especially useful for technical topics where experts unconsciously write for other experts.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to generate the readability score and grade level.", "Identify the longest or most complex sentences the results highlight.", "Rewrite those passages for clarity, then re-run the analysis.", "Compare the final score against the reading level your audience expects."],
    interpretation: ["A Flesch Reading Ease score of 60-70 is typical for general web content; higher means easier.", "A grade level of 8-10 suits most consumer audiences.", "Technical audiences tolerate higher grade levels when terminology is necessary.", "One very long sentence can drag down the whole score, so look at distribution, not just the average."],
    commonProblems: ["Dumbing down expert content until it loses precision.", "Chasing a score by chopping sentences without improving clarity.", "Ignoring that formulas penalize necessary technical terms.", "Testing marketing copy and body content together, blending two styles."],
    fixes: ["Split sentences over 25 words at natural clause boundaries.", "Replace nominalizations like \"make a decision\" with verbs like \"decide\".", "Keep technical terms but explain them on first use.", "Use lists for sequences the reader must follow in order."],
    bestPractices: ["Match the reading level to the audience, not to the formula.", "Use scores to find problem passages, not to grade whole articles.", "Read flagged sentences aloud; the ear catches what formulas miss.", "Combine with paragraph-length review for a fuller picture."],
    example: "A B2B security guide scoring at grade 16 might keep its terminology but split 40-word sentences and define acronyms on first use, landing near grade 11 without losing authority.",
    limitations: "Formulas measure sentence length and syllables, not logic, accuracy, or layout. A short, wrong sentence can score very well.",
    faqs: [
      { question: "Does Google use readability scores in ranking?", answer: "Google has not confirmed any readability formula as a ranking factor; the value is in user comprehension." },
      { question: "What Flesch score should I aim for?", answer: "60-70 for general audiences; adjust up or down for children or specialists." },
      { question: "Why does my technical article score poorly?", answer: "Long domain terms raise syllable counts; keep the terms but shorten the sentences around them." },
      { question: "Do bullet lists affect the score?", answer: "They can, since fragments alter sentence counts; treat list-heavy sections separately." },
      { question: "Is a higher score always better?", answer: "No. Oversimplified expert content can lose credibility with its real audience." },
    ],
  },
  "word-count-analyzer": {
    definition: "A Word Count Analyzer counts the words in pasted text and summarizes length context for blog posts, product pages, and guides. It reports totals and sometimes reading-time estimates. It measures quantity only; it says nothing about whether those words earn their place.",
    whyItMatters: "Length expectations differ by page type: a product page that answers everything in 150 words beats a 2,000-word guide that says nothing, and vice versa. Knowing your word count helps you compare drafts against the depth a topic actually needs. It also keeps briefs honest, so writers know whether they delivered the agreed scope.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to get the total word count and reading-time estimate.", "Compare the count against your brief or the depth competing pages offer.", "Decide whether the draft needs expansion or trimming.", "Re-run after revisions to confirm the change landed as intended."],
    interpretation: ["There is no ideal word count; match the depth the query deserves.", "Reading-time estimates assume average adult speed; technical content reads slower.", "A big gap between draft and brief usually means missing sections, not padding.", "Very short counts on guide-type pages often correlate with thin coverage."],
    commonProblems: ["Padding articles to hit an arbitrary word target.", "Comparing word counts across different page types.", "Counting template boilerplate as article content.", "Assuming longer always outranks shorter."],
    fixes: ["Add missing subtopics instead of stretching existing sentences.", "Cut repetition and throat-clearing introductions.", "Separate content counts from template counts before comparing.", "Let the outline, not a number, decide when the draft is done."],
    bestPractices: ["Set length ranges in briefs based on topic complexity.", "Review the thinnest and longest pages first during audits.", "Pair word count with a coverage check of subtopics.", "Track counts across revisions to catch accidental truncation."],
    example: "A product category page at 120 words may be fine if filters and products do the work, while a how-to-choose guide at 120 words almost certainly needs expansion.",
    limitations: "The tool counts words in what you paste. It cannot judge relevance, accuracy, duplication, or whether the words match search intent.",
    faqs: [
      { question: "How many words should a blog post be?", answer: "As many as the topic needs; many strong posts fall between 1,000 and 2,500 words, but intent matters more than the number." },
      { question: "Does Google prefer long content?", answer: "No. Google rewards satisfying the query; padding hurts more than it helps." },
      { question: "Does the count include headings?", answer: "It counts whatever text you paste, so include or exclude headings deliberately." },
      { question: "How accurate is the reading-time estimate?", answer: "Estimates assume roughly 200-250 words per minute; adjust downward for technical material." },
      { question: "Should product pages be long?", answer: "Only as long as needed to answer buying questions; specs and reviews often matter more than prose." },
    ],
  },
  "content-length-checker": {
    definition: "A Content Length Checker fetches a page URL and compares its visible text length against practical ranges for its page type. It looks at rendered main content rather than raw HTML. The comparison is advisory: page type and intent set the bar, not a universal number.",
    whyItMatters: "Pages that are dramatically shorter than competing results often fail to satisfy the query, while bloated pages bury answers. A quick length comparison during an audit flags both extremes. It is a triage signal that tells you which pages deserve a deeper content review.",
    howToUse: ["Enter the page address in the \"Page URL\" field.", "Click \"Analyze\" to fetch the page and measure its visible text.", "Compare the result against the practical range for that page type.", "Shortlist pages that fall far outside the expected range.", "Open the weakest pages for a manual content review."],
    interpretation: ["Below-range length on informational pages suggests missing coverage.", "Above-range length is only a problem if the extra text is filler.", "E-commerce and tool pages legitimately run short.", "Compare against the same page type, not site-wide averages."],
    commonProblems: ["Judging a checkout or tool page by article standards.", "Counting hidden tab content as missing.", "Expanding pages that already answer the query.", "Using length as a proxy for quality."],
    fixes: ["Brief expansions around missing subtopics the results page shows.", "Consolidate thin near-duplicate pages instead of padding each one.", "Move key answers above long introductions.", "Let user questions, not word targets, drive additions."],
    bestPractices: ["Audit length by template: guides, products, and categories separately.", "Pair length data with engagement metrics.", "Re-check after redesigns that move content into tabs.", "Document page-type ranges so audits stay consistent."],
    example: "A best-CRM-software guide at 400 visible words against competitors averaging 3,000 is a clear expansion candidate; a pricing page at 150 words is probably fine.",
    limitations: "The tool measures fetched visible text at one moment. It cannot assess relevance, accuracy, or content loaded only after complex interactions.",
    faqs: [
      { question: "What is the minimum word count for SEO?", answer: "There is none; the requirement is satisfying the query." },
      { question: "Does the tool count hidden content?", answer: "It measures visible text in the fetched page; tabbed content handling varies." },
      { question: "Why do competitors rank with short pages?", answer: "Strong brands, links, or a perfect intent match can outweigh length." },
      { question: "Should I expand all short pages?", answer: "No. Expand pages where shortness means unsatisfied intent." },
      { question: "How often should I re-check?", answer: "After redesigns, migrations, or template changes that alter visible text." },
    ],
  },
  "heading-keyword-alignment-checker": {
    definition: "A Heading Keyword Alignment Checker fetches a page and checks whether its primary topics appear naturally in the H1 and supporting H2 and H3 headings. It maps heading text against the page's target terms. The check is about topical signaling and scannability, not keyword repetition quotas.",
    whyItMatters: "Headings structure the page for both readers and search engines: the H1 declares the topic, and subheads promise what each section delivers. Misaligned headings confuse scanners and weaken topical clarity. A quick alignment check catches pages where the H1 targets one thing while the content discusses another.",
    howToUse: ["Enter the page address in the \"Page URL\" field.", "Click \"Analyze\" to extract the heading hierarchy.", "Check whether the H1 plainly states the page's primary topic.", "Scan the H2 and H3 headings for coverage of the topic's key sub-questions.", "Rewrite headings that are clever, stuffed, or disconnected from their sections."],
    interpretation: ["An H1 closely matching the page's primary topic is a good sign.", "Subheads should cover the topic's key sub-questions.", "Headings stuffed with keyword variants read as spammy.", "A missing H1 or multiple competing H1s are structural issues first."],
    commonProblems: ["Clever H1s that hide the topic, such as \"Unlock Your Potential\".", "Every H2 repeating the exact target phrase.", "Heading hierarchy skipping levels, jumping from H1 to H4.", "Headings that promise content the section does not deliver."],
    fixes: ["Rewrite the H1 to state the topic plainly.", "Vary subhead phrasing with synonyms and question forms.", "Fix the hierarchy so levels nest logically.", "Align each heading with its section's actual content."],
    bestPractices: ["Use one clear H1 per page stating the topic.", "Write headings for scanners first and keywords second.", "Mirror the language searchers use, without stuffing.", "Audit headings after content rewrites."],
    example: "A page targeting project management software with the H1 \"Work Smarter\" and H2s about company news fails alignment; an H1 like \"Project Management Software for Remote Teams\" with H2s on features, pricing, and integrations passes.",
    limitations: "The tool reads heading tags in fetched HTML. It cannot judge heading quality beyond text matching, nor see headings injected only after user interaction.",
    faqs: [
      { question: "Should the keyword be in the H1?", answer: "Usually yes, phrased naturally; the H1 should plainly state the topic." },
      { question: "How many keywords belong in one heading?", answer: "One natural mention; avoid stuffing variants into a single heading." },
      { question: "Do H2s matter as much as the H1?", answer: "The H1 carries the most weight; H2s support topical breadth." },
      { question: "Can I have multiple H1s?", answer: "HTML5 allows it, but one clear H1 remains the safer convention." },
      { question: "Should headings match the title tag?", answer: "They can differ; the title targets the search results page while the H1 targets the on-page reader." },
    ],
  },
  "keyword-in-title-checker": {
    definition: "A Keyword in Title Checker fetches a page and verifies whether its target topic appears in the title tag. The title tag is the page's headline in search results and a core relevance signal. The check confirms presence and placement, not the quality of the title as ad copy.",
    whyItMatters: "The title tag is often the first relevance cue a search engine sees and the first thing a searcher reads. A missing or vague title weakens both ranking relevance and click-through. Checking it catches template errors, such as every page sharing the site name as its title.",
    howToUse: ["Enter the page address in the \"Page URL\" field.", "Click \"Analyze\" to read the page's title tag.", "Check whether the target topic appears, ideally near the front.", "Flag duplicate, missing, or truncated titles.", "Rewrite weak titles as clear, compelling headlines."],
    interpretation: ["A topic near the front of the title is the strongest pattern.", "Titles over roughly 60 characters risk truncation in results.", "Duplicate titles across pages signal template problems.", "Brand suffixes are fine but should not crowd out the topic."],
    commonProblems: ["The homepage title reused on every page.", "Keyword-stuffed titles with comma-separated variants.", "Titles written in internal jargon instead of search language.", "Missing titles on template-generated pages."],
    fixes: ["Front-load the primary topic naturally.", "Make each page's title unique.", "Keep titles within truncation-safe length.", "Write titles as compelling headlines, not keyword lists."],
    bestPractices: ["Give every page one unique, descriptive title.", "Match title language to the query's language.", "Include a value proposition where space allows.", "Audit titles after migrations and template changes."],
    example: "A product page titled \"Acme Corp | Home\" tells searchers nothing; \"Wireless Noise-Cancelling Headphones | Acme\" states the topic and the brand.",
    limitations: "The tool reads the title tag in fetched HTML. Search engines may rewrite titles in results; the check covers your tag, not their display choice.",
    faqs: [
      { question: "Does the keyword have to be first in the title?", answer: "Front placement helps, but natural phrasing matters more than exact position." },
      { question: "Why does Google show a different title?", answer: "Google rewrites titles it considers poor; improving your tag usually fixes it." },
      { question: "How long should titles be?", answer: "Aim under about 60 characters to avoid truncation." },
      { question: "Should every page include the brand?", answer: "It is optional; keep it short and place it at the end." },
      { question: "Do keywords in titles still matter?", answer: "Yes, as a relevance signal and for click-through, though less dominantly than a decade ago." },
    ],
  },
  "keyword-in-url-checker": {
    definition: "A Keyword in URL Checker examines a page's URL slug for the presence of its target topic words. Descriptive slugs help users and search engines understand the page before it loads. The signal is minor compared to titles and content, but clean URLs compound across a site.",
    whyItMatters: "URLs appear in search results, get shared, and persist for years; a readable slug reinforces the topic at every touchpoint. Parameter-heavy or cryptic URLs hide the topic and complicate migrations. Checking slugs during audits catches legacy patterns worth cleaning up.",
    howToUse: ["Enter the page address in the \"Page URL\" field.", "Click \"Analyze\" to inspect the slug structure.", "Check that topic words appear in readable form.", "Flag IDs, parameters, and inconsistent conventions.", "Plan redirect-safe slug changes only where the benefit is clear."],
    interpretation: ["Short, readable slugs with topic words are ideal.", "IDs and parameters in slugs add noise.", "Excessively long slugs dilute readability.", "Changed slugs need redirects; the check informs but does not fix."],
    commonProblems: ["Date-based or ID-only slugs with no topic words.", "Keyword-stuffed slugs repeating variants.", "Inconsistent slug conventions across sections.", "Changing slugs without setting up redirects."],
    fixes: ["Use concise topic-based slugs for new pages.", "Redirect old URLs whenever slugs change.", "Standardize on lowercase with hyphens.", "Leave ranking old URLs alone unless the benefit is clear."],
    bestPractices: ["Keep slugs short, descriptive, and stable.", "Avoid dates in slugs for evergreen content.", "Use hyphens, not underscores.", "Do not rewrite slugs purely to insert keywords on ranking pages."],
    example: "A slug like /blog/post-48291 says nothing, while /blog/keyword-density-guide states the topic and survives sharing intact.",
    limitations: "The tool analyzes the URL string. It cannot assess redirect chains, canonicalization, or the ranking impact of a slug change.",
    faqs: [
      { question: "Do keywords in URLs help rankings?", answer: "Slightly, as a minor relevance signal; user clarity is the bigger win." },
      { question: "Should I change old URLs to add keywords?", answer: "Rarely worth the risk; redirects leak some equity and invite errors." },
      { question: "Underscores or hyphens?", answer: "Hyphens; search engines treat them as word separators." },
      { question: "How long should a slug be?", answer: "As short as clarity allows, usually three to five words." },
      { question: "Do stop words matter in URLs?", answer: "Not much; keep or drop them based on readability." },
    ],
  },
  "content-to-html-ratio-checker": {
    definition: "A Content-to-HTML Ratio Checker compares the bytes of visible text on a page against the total HTML transferred. A low ratio means heavy markup, scripts, and styles relative to actual content. It is a code-efficiency diagnostic, not a ranking factor.",
    whyItMatters: "Bloated markup slows parsing and rendering, especially on weak devices, and can indicate template problems like nested tables or excessive inline scripts. While search engines do not rank by this ratio, the bloat it reveals often correlates with performance issues that do matter. It points developers at pages worth slimming down.",
    howToUse: ["Enter the page address in the \"Page URL\" field.", "Click \"Analyze\" to measure text versus HTML bytes.", "Compare the ratio across pages sharing a template.", "Investigate pages with unusually low text share.", "Hand findings to developers with the worst offenders first."],
    interpretation: ["Ratios vary widely by template; compare like with like.", "Very low text share often means script-heavy pages.", "High-ratio pages are usually simple article templates.", "Trends over time matter more than absolute numbers."],
    commonProblems: ["Treating the ratio as a ranking factor.", "Comparing article pages against app-like pages.", "Ignoring that images and fonts are not part of the ratio.", "Optimizing the number instead of the underlying bloat."],
    fixes: ["Remove unused CSS and JavaScript.", "Defer non-critical scripts.", "Simplify deeply nested template markup.", "Move inline styles to stylesheets."],
    bestPractices: ["Track ratios per template over time.", "Investigate sudden drops after deployments.", "Pair the data with Core Web Vitals measurements.", "Focus on user-perceived speed, not the ratio itself."],
    example: "A blog post with a 2% text ratio likely loads megabytes of unused theme JavaScript; trimming it improves both the ratio and actual load time.",
    limitations: "The tool measures fetched HTML bytes. It does not run JavaScript, measure render time, or account for cached assets.",
    faqs: [
      { question: "What is a good content-to-HTML ratio?", answer: "There is no official benchmark; compare within your own templates." },
      { question: "Do search engines use this ratio?", answer: "No, it has never been a confirmed ranking factor." },
      { question: "Why is my ratio so low?", answer: "Usually heavy scripts, inline styles, or page-builder markup." },
      { question: "Will improving it boost rankings?", answer: "Only indirectly, if the cleanup improves page speed." },
      { question: "Does it count images?", answer: "No, only text versus HTML bytes." },
    ],
  },
  "paragraph-length-analyzer": {
    definition: "A Paragraph Length Analyzer breaks pasted text into paragraphs and reports their word and sentence counts. It highlights overlong blocks that strain readers on screens. Paragraphing is a readability and scannability aid; the analyzer makes invisible walls of text visible.",
    whyItMatters: "Online readers scan before they commit, and a 200-word paragraph looks like work. Short paragraphs create entry points and rhythm that keep people reading. The analyzer catches the dense blocks that authors stop noticing in their own drafts.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to see each paragraph's length.", "Identify paragraphs far longer than the rest.", "Split long blocks at natural topic shifts.", "Re-run the analysis to confirm the rhythm improved."],
    interpretation: ["Paragraphs over about 100 words deserve a second look.", "Single-sentence paragraphs are fine for emphasis when used sparingly.", "Consistent medium paragraphs suit guides; varied lengths suit stories.", "Mobile readers feel long paragraphs more acutely."],
    commonProblems: ["One-paragraph sections pasted straight from documents.", "Breaking paragraphs mid-thought purely for appearance.", "Uniform paragraph length creating monotony.", "Confusing paragraph breaks with simple line breaks."],
    fixes: ["Split at topic shifts inside long paragraphs.", "Move examples into their own paragraphs.", "Use subheadings to break very long sections.", "Keep one idea per paragraph."],
    bestPractices: ["Aim for visual variety in paragraph length.", "Front-load the point in each paragraph.", "Check paragraphs on a phone screen.", "Pair with sentence-complexity review for a fuller picture."],
    example: "A 180-word product description paragraph becomes three scannable blocks: what it is, who it is for, and the key specifications.",
    limitations: "The tool counts paragraphs in pasted plain text. It cannot judge whether a break helps comprehension or how CMS formatting renders the result.",
    faqs: [
      { question: "What is the ideal paragraph length?", answer: "No fixed rule; 40-80 words works well for web reading." },
      { question: "Are one-sentence paragraphs okay?", answer: "Yes, for emphasis, but not as a habit." },
      { question: "Does this affect SEO directly?", answer: "Indirectly, through readability and engagement." },
      { question: "Should dialogue be counted separately?", answer: "Dialogue naturally creates short paragraphs; that is fine." },
      { question: "Do lists count as paragraphs?", answer: "The tool treats list items by line breaks; review them separately." },
    ],
  },
  "sentence-complexity-checker": {
    definition: "A Sentence Complexity Checker measures sentence length and clause density in pasted text. It flags sentences likely to overload working memory. Complex sentences are not wrong, but unexamined complexity hides the point.",
    whyItMatters: "Readers abandon sentences they must re-read, and each re-read is a small exit opportunity. Complexity analysis finds the sentences where meaning gets buried under clauses. Simplifying them raises the odds the reader reaches your conclusion.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to flag long or clause-heavy sentences.", "Read each flagged sentence and locate its main point.", "Rewrite by splitting or front-loading the main clause.", "Re-run the check to confirm the worst offenders are resolved."],
    interpretation: ["Sentences over 25-30 words warrant review.", "Multiple subordinate clauses increase load faster than length alone.", "A mix of lengths reads better than uniform simplicity.", "Technical terms add complexity beyond word count."],
    commonProblems: ["Stacking three ideas into one sentence.", "Burying the main verb twenty words deep.", "Overusing semicolons to splice thoughts together.", "Simplifying until nuance disappears."],
    fixes: ["Split compound ideas into separate sentences.", "Move the main clause to the front.", "Replace nested clauses with short follow-up sentences.", "Keep complexity where precision genuinely requires it."],
    bestPractices: ["Vary sentence length deliberately.", "Put the point early in key sentences.", "Read complex passages aloud.", "Simplify the sentences surrounding technical terms."],
    example: "A 45-word sentence about a platform's history becomes two sentences with the current capability stated first and the background second.",
    limitations: "The tool measures structural complexity, not meaning. A short sentence can still confuse, and a long one can be perfectly clear.",
    faqs: [
      { question: "What sentence length is too long?", answer: "Above 25-30 words, review the sentence for splittability." },
      { question: "Are long sentences bad for SEO?", answer: "Only through readability; there is no direct penalty." },
      { question: "Should all sentences be short?", answer: "No; rhythm needs variety to hold attention." },
      { question: "Does it detect passive voice?", answer: "That is the Passive Voice Detector's job; the two tools complement each other." },
      { question: "What about legal or academic writing?", answer: "Precision can justify complexity; still trim the gratuitous kind." },
    ],
  },
  "passive-voice-detector": {
    definition: "A Passive Voice Detector scans pasted text for passive constructions, where the subject receives the action, as in \"the report was written\". It reports frequency and locations. Passive voice is not an error, but heavy use makes writing feel distant and harder to follow.",
    whyItMatters: "Active voice puts the actor first, which readers parse faster and remember better. Marketing and instructional content especially suffers when everything \"was done\" by nobody. The detector quantifies a habit most writers cannot feel in their own drafts.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to flag passive constructions.", "Review each flagged sentence in context.", "Rewrite the high-visibility ones in active voice.", "Re-run the analysis to confirm the balance improved."],
    interpretation: ["Occasional passive voice is normal, especially in methods sections.", "High percentages suggest systematic avoidance of naming actors.", "Some flagged sentences may be false positives.", "Focus on headlines, introductions, and calls to action first."],
    commonProblems: ["Rewriting every passive sentence mechanically.", "Forcing active voice where the actor is genuinely unknown.", "Trusting every flag without reading context.", "Ignoring that some style guides prefer passive in places."],
    fixes: ["Name the actor: \"we shipped\" instead of \"was shipped\".", "Keep passive voice when the receiver matters most.", "Rewrite instructions actively, such as \"click X\" rather than \"X should be clicked\".", "Vary voice deliberately instead of banning one form."],
    bestPractices: ["Favor active voice in headlines and calls to action.", "Accept passive voice in scientific methods and formal reports.", "Review introductions and conclusions first.", "Combine with readability scoring for a fuller edit."],
    example: "\"Mistakes were made in the migration process\" becomes \"Our team made migration errors\" — clearer and more accountable.",
    limitations: "Detection is pattern-based; it can misflag adjectives and complex tenses. It does not judge whether a passive construction is appropriate in context.",
    faqs: [
      { question: "Is passive voice bad for SEO?", answer: "No direct effect; it matters for clarity, not rankings." },
      { question: "What percentage of passive voice is acceptable?", answer: "There is no rule; under roughly 10-15% is typical for web content." },
      { question: "Why are some flags wrong?", answer: "Pattern matching cannot fully parse English grammar." },
      { question: "Should academic writing avoid passive voice?", answer: "Many conventions accept it; follow your style guide." },
      { question: "Does active voice rank better?", answer: "There is no evidence of that; readers simply prefer it." },
    ],
  },
  "transition-words-checker": {
    definition: "A Transition Words Checker counts connecting words and phrases — however, therefore, for example, meanwhile — in pasted text. Transitions signal relationships between ideas: contrast, cause, sequence, and example. The count indicates how explicitly a draft guides readers through its logic.",
    whyItMatters: "Ideas without transitions read as a list of disconnected claims, forcing readers to infer relationships themselves. Explicit connectors reduce cognitive load and make arguments feel coherent. The checker reveals drafts that state facts but never link them together.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to count transitions and show variety.", "Look for sections where the logic jumps without connectors.", "Add appropriate transitions where relationships are implicit.", "Re-run to confirm variety, not just higher counts."],
    interpretation: ["Low counts suggest choppy, disconnected prose.", "Repeating one transition everywhere is its own problem.", "Different sections need different connector types.", "Zero transitions in instructions may be fine; in arguments, rarely."],
    commonProblems: ["Overusing \"however\" and \"moreover\".", "Adding transitions without real logical relationships.", "Starting consecutive sentences with informal \"And\" or \"But\".", "Confusing transition stuffing with genuine coherence."],
    fixes: ["Vary connectors across contrast, cause, example, and sequence.", "Add missing links between paragraphs, not just sentences.", "Remove transitions that do not match the actual relationship.", "Use subheadings alongside transitions for structure."],
    bestPractices: ["Match the connector to the real relationship.", "Build a personal list of go-to transitions per type.", "Check transitions at paragraph boundaries especially.", "Read the draft without transitions to test the underlying logic."],
    example: "Two paragraphs, one on costs and one on benefits, gain coherence with an opening like \"Against these costs, the benefits compound over time...\"",
    limitations: "The tool matches a word list; it cannot verify that a connector fits the logic or detect coherence achieved through structure alone.",
    faqs: [
      { question: "How many transition words should I use?", answer: "Enough that relationships are explicit; a few per paragraph is typical in argumentative writing." },
      { question: "Do transitions help SEO?", answer: "Indirectly, through readability; some readability plugins score them." },
      { question: "Which transitions matter most?", answer: "Those marking contrast and causation, where misreading is costliest." },
      { question: "Can you overuse them?", answer: "Yes; forced connectors feel mechanical and distract." },
      { question: "Are \"and\" and \"but\" transitions?", answer: "They connect ideas, but varied connectors signal relationships more precisely." },
    ],
  },
  "thin-content-signals-checker": {
    definition: "A Thin Content Signals Checker fetches a page URL and looks for hallmarks of low-value content: very short text, a high boilerplate ratio, missing headings, or placeholder-like patterns. It reports risk signals, not a verdict; only human review decides whether a page truly lacks value.",
    whyItMatters: "Pages with little unique value waste crawl budget, dilute site quality signals, and rarely satisfy queries. Search engines' helpful-content systems target exactly this class of page. The checker triages large sites, surfacing the pages most likely to need improvement, consolidation, or removal.",
    howToUse: ["Enter the page address in the \"Page URL\" field.", "Click \"Analyze\" to scan for thin-content signals.", "Review each flagged signal against the live page.", "Manually inspect the page's actual usefulness.", "Decide per page: improve, merge, noindex, or remove."],
    interpretation: ["Multiple signals together indicate higher risk.", "Short text alone does not prove thinness; a tool page can be complete.", "Boilerplate-heavy pages look thinner than they are.", "One signal on an otherwise solid page is usually noise."],
    commonProblems: ["Auto-deleting every flagged page.", "Padding thin pages instead of adding real value.", "Ignoring that the tool cannot read images or video value.", "Treating pagination and archive pages as thin content."],
    fixes: ["Add original analysis, data, or examples.", "Merge overlapping thin pages into one strong page.", "Noindex pages that must exist but should not rank.", "Remove pages with no audience and no links."],
    bestPractices: ["Review flagged pages manually before acting.", "Prioritize pages with traffic or inbound links.", "Document each decision: improve, merge, noindex, or delete.", "Re-run the check after content refreshes."],
    example: "A 60-word location page duplicated across 50 cities with only the city name swapped is a classic thin-content pattern; merging into regional guides with unique detail fixes it.",
    limitations: "The tool analyzes fetched text signals. It cannot evaluate images, video, interactive tools, or genuine usefulness — human judgment is required.",
    faqs: [
      { question: "What counts as thin content?", answer: "Pages with little or no added value: auto-generated, scraped, doorway, or extremely shallow pages." },
      { question: "Is there a word-count threshold?", answer: "No official one; value determines thinness, not length." },
      { question: "Can thin pages cause penalties?", answer: "Site-wide quality assessments can suppress rankings; individual thin pages usually just fail to rank." },
      { question: "Should I delete thin pages?", answer: "Improve or merge first; delete only when there is no value and no links." },
      { question: "Do tag pages count as thin?", answer: "They can, if they add nothing beyond post lists; noindex them when that is the case." },
    ],
  },
  "content-structure-analyzer": {
    definition: "A Content Structure Analyzer fetches a page URL and maps its structural elements: heading hierarchy, section order, list usage, and content blocks. It shows how the page is organized rather than what it says. Good structure lets readers and crawlers parse the page's logic at a glance.",
    whyItMatters: "Structure determines whether a page can be scanned, whether sections flow logically, and whether key questions get dedicated space. Many underperforming pages hold adequate information in poor order. The analyzer exposes the skeleton so you can fix organization without rewriting everything.",
    howToUse: ["Enter the page address in the \"Page URL\" field.", "Click \"Analyze\" to map the heading outline and section sequence.", "Compare the order against what the query's searcher needs first.", "Identify buried answers, skipped levels, and overlong sections.", "Restructure the page and re-run to verify the new outline."],
    interpretation: ["A logical H1 to H2 to H3 cascade is the baseline.", "Key questions should map to dedicated sections.", "Long unbroken sections suggest missing subheads.", "Conclusions and summaries placed early often serve readers better."],
    commonProblems: ["Skipped heading levels breaking the outline.", "Important answers buried at the bottom.", "Sections arranged in illogical order.", "No summary or takeaway for scanners."],
    fixes: ["Reorder sections to match the reader's decision journey.", "Add subheads to long sections.", "Move the direct answer near the top.", "Close with a concise summary."],
    bestPractices: ["Outline before writing, then verify with the analyzer.", "Mirror the structure of the query's intent.", "Keep parallel sections parallel in format.", "Re-check structure after major edits."],
    example: "A buying guide ordered as history, then specs, then price, then \"what is X\" serves readers better as: what it is, who needs it, comparison, price, FAQ.",
    limitations: "The tool maps HTML structure. It cannot judge writing quality, factual accuracy, or whether the structure truly fits the audience.",
    faqs: [
      { question: "Does structure affect rankings?", answer: "Indirectly, through user experience and topical clarity." },
      { question: "How many H2s should a page have?", answer: "As many as the topic's sub-questions require." },
      { question: "Should the conclusion come first?", answer: "A summary up top helps scanners; details follow." },
      { question: "Do lists help structure?", answer: "Yes, for parallel items and step sequences." },
      { question: "Can structure alone fix a page?", answer: "It fixes findability of answers, not missing answers." },
    ],
  },
  "duplicate-content-text-checker": {
    definition: "A Duplicate Content Text Checker compares pasted text samples to find repeated passages. It highlights matching blocks so you can see where content echoes itself or another draft. It detects textual duplication in what you provide, not the cross-site duplication that search engines handle.",
    whyItMatters: "Internal repetition bores readers and dilutes the unique value of each page; duplication across pages confuses crawlers about which version to rank. Catching it before publishing keeps each page's contribution distinct. It is also a quick self-check for teams reusing briefs and templates.",
    howToUse: ["Paste your text into the \"Text\" field.", "Click \"Analyze\" to scan for repeated passages.", "Review each highlighted match in context.", "Rewrite substantive duplicates or mark quotes properly.", "For intentional duplicates, plan canonical tags instead of rewrites."],
    interpretation: ["Boilerplate matches such as disclaimers are usually harmless.", "Large body-text matches between pages need attention.", "Quoted material should be marked as quotes.", "Near-duplicates with swapped words still count as duplication."],
    commonProblems: ["Flagging standard legal boilerplate as a problem.", "Ignoring duplication across paginated series.", "Rewriting duplicates into awkwardly different phrasing.", "Confusing this check with search engines' cross-site duplicate handling."],
    fixes: ["Differentiate pages with unique angles and examples.", "Use canonical tags for intentional duplicates.", "Consolidate near-duplicate pages into one.", "Quote and attribute external excerpts."],
    bestPractices: ["Check drafts against existing site content.", "Keep boilerplate minimal and consistent.", "Write unique introductions for similar pages.", "Monitor syndication with canonical tags."],
    example: "Two service pages sharing 80% of their text should be differentiated — one with case details, the other with process specifics — or merged into a single stronger page.",
    limitations: "The tool compares text you provide. It does not crawl the web or replicate how search engines cluster duplicate content.",
    faqs: [
      { question: "Does Google penalize duplicate content?", answer: "Rarely as a penalty; usually Google filters results down to one version." },
      { question: "How much duplication is too much?", answer: "Substantial body-text overlap between pages that are each intended to rank." },
      { question: "What about quoted content?", answer: "Attribute it; small quoted excerpts are fine." },
      { question: "Do canonical tags fix duplication?", answer: "They consolidate ranking signals to your preferred version." },
      { question: "Is boilerplate duplicate content?", answer: "Search engines generally recognize site-wide boilerplate for what it is." },
    ],
  },
  "content-outline-generator": {
    definition: "A Content Outline Generator produces a structured article skeleton — a working title, H2 sections, and key points — from a topic or keywords you enter. It gives writers a starting framework aligned with common search intent. The outline is a draft to refine, not a publishable plan.",
    whyItMatters: "Weak outlines produce rambling drafts that miss the query's real questions. A generated skeleton ensures standard subtopics are not forgotten and gives writers a logical spine. It compresses the blank-page phase so effort goes into insight rather than structure.",
    howToUse: ["Enter your topic in the \"Topic or keywords\" field.", "Click \"Generate\" to produce the outline.", "Review the suggested sections against the query's intent.", "Add your unique angles, data, and examples.", "Finalize the outline as a writer's brief before drafting."],
    interpretation: ["Standard sections confirm baseline coverage.", "Missing angles are your differentiation opportunity.", "Generic outlines need your expertise injected.", "The order of sections suggests reader priority."],
    commonProblems: ["Publishing the outline structure verbatim.", "Accepting generic sections without unique insight.", "Skipping results-page review because the outline looks complete.", "Outlines that ignore the query's actual intent type."],
    fixes: ["Add original data, examples, or opinions to each section.", "Reorder sections to match your audience's journey.", "Cut sections that do not serve the specific query.", "Validate coverage against top-ranking pages."],
    bestPractices: ["Treat the output as a brief, not a template.", "Inject first-hand experience into every section.", "Check intent: guide, comparison, or definition.", "Iterate the outline before any writing begins."],
    example: "For email deliverability, the generated outline covers authentication, list hygiene, and content; the writer adds a section on their own inbox-placement test results.",
    limitations: "The generator works from patterns, not expertise. It cannot know your unique data, audience nuances, or the latest developments in the topic.",
    faqs: [
      { question: "Will following the outline guarantee rankings?", answer: "No; execution quality and site authority decide that." },
      { question: "Should I use the generated headings exactly?", answer: "Adapt them; verbatim use creates sameness across sites." },
      { question: "How detailed should the outline be?", answer: "Detailed enough that a writer cannot miss key subtopics." },
      { question: "Can it outline non-article pages?", answer: "It is tuned for articles; adapt the structure for other formats." },
      { question: "Does AI-generated structure hurt SEO?", answer: "Structure is not the issue; thin, undifferentiated content is." },
    ],
  },
  "faq-section-generator": {
    definition: "An FAQ Section Generator drafts a set of questions and answers for a topic you enter. It produces reader-style Q&As covering common doubts about the subject. The draft needs fact-checking and voice-matching before it belongs on a page.",
    whyItMatters: "FAQ sections capture long-tail questions, address objections near conversion points, and give scanners quick answers. A generated starting set ensures you do not forget the obvious questions. Well-crafted FAQs also serve voice-search style queries phrased as full questions.",
    howToUse: ["Enter your topic in the \"Topic or keywords\" field.", "Click \"Generate\" to draft the Q&A set.", "Verify every answer against your own sources.", "Rewrite the survivors in your brand's voice.", "Place the finished FAQs near the relevant section or page end."],
    interpretation: ["The suggested questions reveal a model of user intent worth sanity-checking.", "Missing questions point to gaps in your own understanding.", "Overlapping answers suggest merging two entries.", "Overly salesy answers need neutralizing before publishing."],
    commonProblems: ["Publishing generated answers without verification.", "Including questions nobody actually asks.", "Answers that merely repeat the page instead of adding.", "Keyword-stuffed question phrasing."],
    fixes: ["Fact-check every answer against reliable sources.", "Replace invented questions with real customer queries.", "Trim answers to what the question actually asked.", "Add FAQ structured data where your site is eligible."],
    bestPractices: ["Source questions from support tickets and search data.", "Keep answers concise and direct.", "Update FAQs when facts change.", "Avoid duplicating the main content verbatim."],
    example: "A pricing page FAQ gains \"Do you offer annual billing?\" from support logs — a question the generator suggested and the team confirmed was real.",
    limitations: "The generator cannot verify facts or know your policies. Note that search engines now limit FAQ rich results to select authoritative sites, so the value is mainly in the content itself.",
    faqs: [
      { question: "Should I publish AI-generated FAQs as they are?", answer: "No; verify accuracy and match your brand voice first." },
      { question: "How many FAQs belong on a page?", answer: "As many as real questions exist; four to eight is typical." },
      { question: "Do FAQs help rankings?", answer: "They help satisfy queries; FAQ rich results themselves are now limited." },
      { question: "Where should FAQs go?", answer: "Near the relevant section or at the page end, not dumped randomly." },
      { question: "Can FAQs target keywords?", answer: "Write for real questions; keyword benefits follow naturally." },
    ],
  },
  "howto-outline-generator": {
    definition: "A HowTo Outline Generator builds a step-by-step framework — prerequisites, ordered steps, tips, and troubleshooting — from a topic you enter. It structures procedural content so readers can follow it from start to finish. The outline needs your domain accuracy before it guides anyone.",
    whyItMatters: "How-to content fails when steps are missing, out of order, or assume knowledge readers lack. A generated framework enforces the discipline of prerequisites and sequencing. It turns scattered knowledge into a followable procedure.",
    howToUse: ["Enter the task in the \"Topic or keywords\" field.", "Click \"Generate\" to build the step framework.", "Verify each step's accuracy against reality.", "Add prerequisites, specifics, and screenshots.", "Test the procedure yourself before finalizing."],
    interpretation: ["Missing prerequisites are the most common gap in generated outlines.", "Steps should be atomic: one action each.", "Troubleshooting sections signal real-world testing.", "Vague steps need concrete details added."],
    commonProblems: ["Publishing steps you have not tested.", "Skipping prerequisites readers need.", "Steps that combine multiple actions.", "No troubleshooting for likely failures."],
    fixes: ["Test the procedure yourself end to end.", "List tools and access requirements up front.", "Split compound steps into single actions.", "Add failure recovery for each risky step."],
    bestPractices: ["Number steps; use bullets for options within a step.", "State the expected outcome of each step.", "Keep steps in strict chronological order.", "Update the guide when interfaces change."],
    example: "A setup-SPF-records outline becomes reliable only after the writer tests each DNS step and adds the 48-hour propagation warning.",
    limitations: "The generator does not test procedures. Also note that search engines discontinued HowTo rich results for most sites, so the value lies in the content itself.",
    faqs: [
      { question: "Do HowTo pages get rich results?", answer: "Search engines discontinued HowTo rich results for general sites; the content still serves users well." },
      { question: "How many steps is too many?", answer: "As many as the task needs; group long procedures into phases." },
      { question: "Should I include videos?", answer: "Yes, for physical or visual tasks where text falls short." },
      { question: "What if steps differ by platform?", answer: "Branch clearly within the guide or write separate guides." },
      { question: "Can I trust generated steps?", answer: "Verify each one; generators do not test procedures." },
    ],
  },
  "comparison-page-outline-generator": {
    definition: "A Comparison Page Outline Generator creates a framework for versus-style content — evaluation criteria, side-by-side sections, and a verdict structure — from the topics you enter. Comparison pages serve high-intent shoppers choosing between options. The outline needs your honest evaluation to be trustworthy.",
    whyItMatters: "Comparison queries convert well because the searcher is near a decision, but thin versus pages that declare a winner without evidence erode trust. A structured outline forces fair criteria and evidence behind each claim. It turns opinion into a genuinely useful buying aid.",
    howToUse: ["Enter the compared items in the \"Topic or keywords\" field.", "Click \"Generate\" to build the comparison framework.", "Define fair criteria buyers actually use.", "Fill in tested facts for each criterion.", "Write a verdict justified by the evidence, framed by use case."],
    interpretation: ["The chosen criteria reveal what the comparison values.", "Missing criteria are where bias hides.", "Symmetric sections suggest fairness.", "A verdict without trade-offs reads as an advertisement."],
    commonProblems: ["Declaring a winner to favor an affiliate relationship.", "Comparing on criteria buyers do not care about.", "No hands-on basis for the claims made.", "Ignoring the \"who should choose X\" framing."],
    fixes: ["Disclose testing methods and commercial relationships.", "Choose criteria buyers actually use.", "Present trade-offs honestly.", "Recommend by use case rather than universally."],
    bestPractices: ["Test products yourself when possible.", "Use tables for scannable specifications.", "Update the page when products change.", "Link to full reviews for depth."],
    example: "A Tool A versus Tool B page earns trust with a criteria table covering price, limits, and support, tested notes per row, and choose-A-if versus choose-B-if guidance.",
    limitations: "The generator provides structure, not product knowledge. It cannot test products or detect your commercial bias.",
    faqs: [
      { question: "Do comparison pages rank well?", answer: "Yes, when thorough and honest; thin ones do not." },
      { question: "Should I always pick a winner?", answer: "Recommend by use case; forced winners hurt credibility." },
      { question: "How do I handle affiliate bias?", answer: "Disclose relationships and keep the criteria fair." },
      { question: "Should I use comparison tables?", answer: "Yes; tables are excellent for scanners comparing options." },
      { question: "How often should I update?", answer: "Whenever products, prices, or features change." },
    ],
  },
  "semantic-entity-checklist": {
    definition: "A Semantic Entity Checklist analyzes pasted text and reports which relevant entities — people, places, products, and concepts — the content mentions. Entities help search engines understand what a page is about beyond raw keywords. The checklist shows topical breadth: whether the draft covers the subject's key components.",
    whyItMatters: "Modern search interprets meaning, not just strings; pages that naturally mention the right entities demonstrate genuine topical coverage. A checklist reveals blind spots — a camera review that never names sensor types, for instance. It guides expansion toward completeness rather than repetition.",
    howToUse: ["Paste your draft into the \"Text\" field.", "Click \"Analyze\" to extract the mentioned entities.", "Compare the list against the entities an expert would cover.", "Expand sections where key entities are absent.", "Re-run after expanding to confirm broader coverage."],
    interpretation: ["Missing core entities suggest shallow coverage.", "Entity variety matters more than raw counts.", "Irrelevant entities dilute topical focus.", "Brand and product entities anchor commercial topics."],
    commonProblems: ["Name-dropping entities without real discussion.", "Treating the checklist as a quota to fill.", "Adding entities that do not serve the reader.", "Ignoring how entities relate to each other in context."],
    fixes: ["Expand sections where key entities are absent.", "Discuss entities substantively, not in passing.", "Remove forced mentions that confuse the topic.", "Use entities to structure subtopics."],
    bestPractices: ["Research the topic's entity landscape before drafting.", "Cover the entities readers expect experts to know.", "Link entities to authoritative sources where useful.", "Re-check the draft after expanding it."],
    example: "An electric bike guide that discusses motors, batteries, and torque sensors in dedicated sections signals deeper coverage than one repeating the phrase electric bike alone.",
    limitations: "Entity extraction is heuristic. It cannot judge depth of discussion or distinguish meaningful mentions from passing name-drops.",
    faqs: [
      { question: "What is a semantic entity?", answer: "A distinct thing or concept — a person, place, product, or idea — that search engines recognize." },
      { question: "Do entities affect rankings?", answer: "They help search engines understand topical depth; strong coverage correlates with quality." },
      { question: "How many entities should I include?", answer: "Cover what the topic genuinely involves; there is no quota." },
      { question: "Is this the same as LSI keywords?", answer: "LSI is an outdated concept; entities are about real-world things, not keyword variants." },
      { question: "Can I just list entities?", answer: "No; discuss them meaningfully in context." },
    ],
  },
};
