import type { ToolEditorial } from "@/lib/seo-tools/content";

export const STRUCTURED_TOOL_EDITORIAL: Record<string, ToolEditorial> = {
  "schema-validator": {
    definition: "A Schema Markup Validator checks structured data for machine-readable problems before you publish or troubleshoot a page. On this site, the validator focuses on JSON-LD because it is widely used and easier to inspect safely than trying to infer every possible microdata or RDFa relationship from arbitrary HTML. It checks JSON syntax, looks for linked-data fields such as `@context` and `@type`, and exposes the parsed structure so you can review what the markup actually says.",
    whyItMatters: "Structured data is easy to break with one missing comma, an incorrectly nested object or a field copied from an unrelated example. A page can render perfectly for users while its JSON-LD silently fails to parse. Validation catches those structural problems early, but it should not be confused with search-engine rich-result eligibility, which has additional product-specific requirements.",
    howToUse: ["Copy the JSON-LD object from your page source or implementation code.", "Paste the JSON-LD into the validator without the surrounding `<script>` tag if possible.", "Run validation and resolve JSON syntax errors first.", "Review detected `@context` and `@type` values to make sure they describe the visible page honestly.", "After structural validation, use the relevant search-engine testing tool if your goal is a specific rich result."],
    interpretation: ["Valid JSON means the text is syntactically parseable; it does not mean every Schema.org property is semantically correct.", "A missing `@context` warning indicates the object may not clearly declare the vocabulary it uses.", "A detected `@type` tells you which entity the object claims to represent.", "Nested objects should mirror real relationships on the page rather than exist only because a sample template included them."],
    commonProblems: ["Trailing commas copied from JavaScript objects into strict JSON.", "Smart quotes pasted from a rich-text editor.", "Using a schema type that does not match the page's main entity.", "Adding ratings, reviews, prices or authors that are not visible or real.", "Publishing duplicate JSON-LD blocks from both a plugin and custom code."],
    fixes: ["Convert JavaScript-style objects into strict JSON before embedding them.", "Remove unsupported or fictional properties instead of filling them with placeholder values.", "Keep one authoritative source of structured data for each entity where possible.", "Validate after deployment because templates, escaping and minification can change the final output."],
    bestPractices: ["Describe real entities and visible facts.", "Prefer the most specific appropriate Schema.org type without forcing an unrelated subtype.", "Use absolute URLs for important identifiers and page references.", "Treat structured data as a representation of the page, not a separate SEO story."],
    example: "A product page should not publish AggregateRating markup merely because a generator supports it. If the page has no real review data, omit the rating rather than inventing `4.9` to make the schema look complete.",
    limitations: "This validator checks syntax and basic linked-data structure. It does not guarantee that Google, Bing or another platform will use the markup, and it does not replace product-specific rich result documentation.",
    faqs: [
      { question: "Is valid schema guaranteed to produce rich results?", answer: "No. Valid syntax is only one requirement. Search engines apply feature-specific policies and decide whether to show enhanced results." },
      { question: "Does the validator support microdata?", answer: "This implementation focuses on pasted JSON-LD. Use a browser or search-engine testing tool when you need to inspect microdata rendered in HTML." },
      { question: "What is `@context`?", answer: "It identifies the vocabulary used by the JSON-LD, commonly `https://schema.org`." },
      { question: "Can one page have several schema types?", answer: "Yes, when the page genuinely contains multiple related entities. They should be connected logically rather than dumped into unrelated blocks." },
      { question: "Should schema include hidden information?", answer: "Structured data should accurately represent page content and real facts, not hidden promotional claims created only for crawlers." },
    ],
  },
  "json-ld-validator": {
    definition: "A JSON-LD Validator focuses on the JSON layer of linked data. It answers a foundational question: can the structured data be parsed consistently as JSON, and does the object expose expected linked-data keys such as `@context` and `@type`? This is useful before debugging higher-level Schema.org semantics.",
    whyItMatters: "JSON-LD is often generated dynamically from CMS fields, TypeScript objects or template variables. A missing quote, unescaped line break or undefined value can break the entire block. Because users never see the script content directly, these failures can survive for weeks unless validation is part of QA.",
    howToUse: ["Paste only the JSON-LD payload or a clean JSON object.", "Run validation and fix parsing errors at the exact character or line reported by the browser parser.", "Confirm `@context` and `@type` are present where your implementation requires them.", "Inspect nested arrays and objects for accidental strings or null placeholders.", "Retest the final rendered JSON-LD from production, not only the source object in your codebase."],
    interpretation: ["Valid JSON means braces, arrays, strings, commas and values follow JSON syntax.", "A parsed object can still contain wrong Schema.org properties.", "Arrays are valid JSON-LD containers when multiple entities are intentionally represented.", "The safest troubleshooting order is JSON syntax first, linked-data structure second, rich-result rules last."],
    commonProblems: ["Using single quotes instead of JSON double quotes.", "Leaving comments inside JSON.", "Trailing commas after the final property.", "Serializing HTML entities or escaped strings incorrectly.", "Passing a JavaScript `undefined` value into output that expects strict JSON."],
    fixes: ["Serialize structured data with `JSON.stringify` or an equivalent safe serializer instead of hand-concatenating strings.", "Escape user-entered text before it reaches a script context.", "Remove comments and JavaScript-only syntax.", "Use automated tests that parse generated JSON-LD during builds."],
    bestPractices: ["Keep structured-data generation close to the real content model.", "Do not duplicate business facts in several places unless the same source of truth feeds them.", "Review rendered output after framework upgrades.", "Validate representative templates, including pages with optional fields missing."],
    example: "A developer may create `{ '@context': 'https://schema.org', '@type': 'Article', }` in JavaScript and assume it is valid JSON. It is not: strict JSON requires double-quoted property names and does not allow the trailing comma.",
    limitations: "The validator cannot determine whether every Schema.org property is appropriate for your business or whether a search engine considers the page eligible for a feature.",
    faqs: [
      { question: "Is JSON-LD the same as JSON?", answer: "JSON-LD uses JSON syntax plus linked-data conventions such as @context and @type." },
      { question: "Can JSON-LD contain arrays?", answer: "Yes. Arrays are commonly used for multiple items or property values." },
      { question: "Can I include comments in JSON-LD?", answer: "Standard JSON does not support comments, so avoid them in the embedded payload." },
      { question: "Should I minify JSON-LD?", answer: "Minification is optional. Readability during development often matters more than saving a tiny amount of markup." },
      { question: "Why does my framework output escaped characters?", answer: "Safe serialization may escape characters to protect the script context. What matters is that the final script remains valid JSON-LD." },
    ],
  },
  "schema-markup-generator": {
    definition: "A general Schema Markup Generator creates a clean JSON-LD starting object from the entity type and factual fields you provide. It is intentionally conservative: rather than inventing dozens of optional properties, it gives you a valid base that can be extended only with information your page genuinely contains.",
    whyItMatters: "Most schema errors do not come from a lack of properties; they come from copied templates that include irrelevant or fictional values. A minimal generator helps developers and editors begin with correct JSON structure while keeping responsibility for the underlying facts with the site owner.",
    howToUse: ["Choose or type the Schema.org type that matches the page entity.", "Enter the real name, canonical URL and description when relevant.", "Generate the JSON-LD and review each field before publishing.", "Add extra properties only after checking the official Schema.org definition or search-feature documentation.", "Validate the completed object before deployment."],
    interpretation: ["`@context` identifies Schema.org as the vocabulary.", "`@type` identifies the entity type you selected.", "Name, URL and description are generic properties supported by many types, but not every page needs every field.", "A simple correct object is better than a large object filled with guesses."],
    commonProblems: ["Selecting Product for a service page simply because both involve prices.", "Using Organization markup for every article as though it were the page's main entity.", "Copying review properties without actual review data.", "Using relative URLs for identifiers that should remain stable across contexts."],
    fixes: ["Read the definition of the chosen type before adding specialized properties.", "Separate page entities when necessary instead of forcing everything into one flat object.", "Use real URLs and content values generated from the same data source as the page."],
    bestPractices: ["Keep schema truthful and maintainable.", "Use IDs or canonical URLs consistently when connecting entities.", "Do not mark up content that users cannot access.", "Review changes whenever page templates gain or lose important visible fields."],
    example: "For a software documentation page, a WebPage or TechArticle may be more suitable than Product if the page is primarily educational. The generator should reflect what the page is, not what the company sells elsewhere.",
    limitations: "The generator does not automatically know the correct Schema.org subtype, required rich-result fields or your search engine's current feature policies. Use it as a structured starting point.",
    faqs: [
      { question: "Which schema type should I choose?", answer: "Choose the type that most accurately describes the main entity or content on the page." },
      { question: "Is more schema always better?", answer: "No. Extra markup adds maintenance cost and can create misleading claims if the properties are not real." },
      { question: "Can I edit the generated JSON-LD?", answer: "Yes. The output is a starting point and can be extended with valid properties." },
      { question: "Do I need a separate schema block for every entity?", answer: "Not always. Related entities can be nested or connected, but the structure should remain understandable and factual." },
      { question: "Where should JSON-LD be placed?", answer: "It can be embedded in a script element on the page. Many implementations place it in the head, though placement can vary by framework." },
    ],
  },
  "faq-schema-generator": {
    definition: "An FAQ Schema Generator converts real, visible questions and answers into an FAQPage JSON-LD structure. It does not write the answers for you because the structured data should mirror the actual FAQ content users can read on the page.",
    whyItMatters: "FAQ markup became widely copied as an SEO tactic, which led to pages containing structured questions that were hidden, duplicated or unrelated to the page. A generator should help with syntax while keeping the content requirement explicit: use real questions and accurate answers first, then mark them up.",
    howToUse: ["Prepare the questions and answers that are visibly published on the page.", "Enter one `Question | Answer` pair per line.", "Generate the FAQPage JSON-LD.", "Compare the generated text with the visible FAQ section to ensure they match.", "Validate the final JSON-LD after publishing."],
    interpretation: ["FAQPage is the container type for a page presenting questions and answers controlled by the publisher.", "Each Question contains a `name` and an `acceptedAnswer` object.", "Structured data does not guarantee an enhanced search display.", "The value of the FAQ remains the usefulness of the answers even when no rich treatment appears."],
    commonProblems: ["Creating schema for questions that are not visible on the page.", "Using FAQPage for user-generated discussion where QAPage may be conceptually different.", "Repeating keyword variations as separate questions with nearly identical answers.", "Embedding promotional claims into every answer."],
    fixes: ["Make the visible FAQ the source of truth and generate markup from it.", "Remove duplicate questions that do not add new information.", "Keep answers direct, accurate and useful without padding them for word count."],
    bestPractices: ["Use FAQs to address real objections, definitions and process questions.", "Maintain answers when policies or product behavior changes.", "Avoid schema-only FAQ content.", "Check current search-engine documentation before assuming FAQ markup will receive a specific visual treatment."],
    example: "A canonical checker page can include a visible question such as 'Can a canonical point to another domain?' with a concise answer. The schema should repeat that same answer, not a longer hidden marketing version.",
    limitations: "The generator only creates JSON-LD from your input. It cannot determine whether a search engine will display FAQ enhancements or whether your page qualifies under current policies.",
    faqs: [
      { question: "Do FAQ answers need to be visible?", answer: "Yes, structured data should represent content users can actually access on the page." },
      { question: "Can I use FAQ schema on every page?", answer: "Only where a genuine FAQ section is useful and appropriate. Adding it mechanically to every page is unnecessary." },
      { question: "Will FAQ schema make my page rank higher?", answer: "There is no ranking guarantee. Its main purpose is machine-readable representation of real FAQ content." },
      { question: "Can I include HTML inside an answer?", answer: "Keep the data straightforward and check consumer support before relying on complex HTML strings." },
      { question: "What if my FAQ changes?", answer: "Update both the visible answer and the structured data so they remain consistent." },
    ],
  },
  "article-schema-generator": {
    definition: "An Article Schema Generator creates JSON-LD describing an editorial article: its headline, canonical page, author and publication or modification dates. It is useful for blogs, news-style resources and other editorial pages when the site already has accurate byline and date information.",
    whyItMatters: "Article metadata is often assembled from several CMS fields, which can lead to mismatches between visible bylines, Open Graph data and structured data. Generating from known fields helps teams see exactly what they are declaring and avoid invented authors or dates.",
    howToUse: ["Enter the visible article headline and canonical URL.", "Add the real author name exactly as the page presents it.", "Use the actual publication date and modification date if the content was materially updated.", "Generate the JSON-LD and compare it with the page metadata.", "Validate after deployment and keep dates synchronized with editorial updates."],
    interpretation: ["`headline` describes the article title.", "`mainEntityOfPage` identifies the canonical page being described.", "`author` should represent a real person or organization responsible for the content.", "`dateModified` should change when the article meaningfully changes, not on every render."],
    commonProblems: ["Using a fictional expert name for credibility.", "Resetting dateModified every day.", "Schema headline differs from the visible H1 because fields are maintained separately.", "Article URL points to a tracking or preview version."],
    fixes: ["Feed schema from the same content record that renders the visible article.", "Use organization authorship honestly when an editorial team writes collectively.", "Keep canonical URL generation centralized.", "Only update modification dates for substantive editorial changes."],
    bestPractices: ["Make authorship transparent.", "Connect publisher or organization data consistently if you add those fields.", "Use image properties only for real representative images.", "Avoid adding review or rating fields that do not belong to the article."],
    example: "A guide published on September 1 and substantially rewritten on September 18 can preserve `datePublished` as September 1 while setting `dateModified` to September 18. That tells a clearer story than pretending the article was newly published.",
    limitations: "The generator covers a practical base set of Article fields. Specific search features may expect additional properties such as images or publisher details, and those should be added only when accurate.",
    faqs: [
      { question: "Should author be a Person or Organization?", answer: "Use the type that reflects real authorship. Editorial-team content can legitimately use an organization when that is how the page is published." },
      { question: "Is dateModified required?", answer: "Not always, but it is useful when you can maintain it accurately." },
      { question: "Can Article schema be used for product pages?", answer: "Not as a substitute for the page's actual entity type. Article markup is for editorial article content." },
      { question: "Should the schema headline match the H1?", answer: "They should normally describe the same article and remain closely aligned." },
      { question: "Does Article schema create a news result automatically?", answer: "No. Search-engine features have additional eligibility and editorial requirements." },
    ],
  },
  "organization-schema-generator": {
    definition: "Organization schema represents a real company, nonprofit, publisher or other organization in machine-readable form. This generator builds a conservative JSON-LD object from the name, canonical website, logo and optional telephone you provide.",
    whyItMatters: "Organization data is often copied across a site and can become inconsistent after rebrands, domain moves or logo updates. A single factual object can help applications understand the entity, but only when it reflects information the business actually uses publicly.",
    howToUse: ["Enter the official public organization name.", "Use the canonical homepage URL.", "Add a stable logo URL if the image is publicly accessible.", "Add a real contact telephone only if it is genuinely part of your public organization data.", "Generate and validate the JSON-LD before adding optional fields such as sameAs profiles."],
    interpretation: ["The Organization object represents the business entity, not every individual webpage.", "The URL should identify the organization's primary website.", "Logo should be a real brand image and not a placeholder.", "Optional social profile relationships should only reference official profiles."],
    commonProblems: ["Invented legal names or addresses that do not match the business.", "Old logos cached in structured data after a redesign.", "Adding social profiles the organization does not control.", "Creating several conflicting Organization objects from different plugins."],
    fixes: ["Use one canonical business data source.", "Remove fields you cannot verify.", "Update schema at the same time as visible rebrand information.", "Connect page-specific schema to the organization rather than duplicating inconsistent copies."],
    bestPractices: ["Keep organization facts stable and factual.", "Use absolute HTTPS URLs.", "Avoid filling optional fields simply because a generator supports them.", "Review organization schema after domain or ownership changes."],
    example: "If a brand trades publicly as 'Example Studio' but no legal entity name is shown or relevant on the website, the structured data should not invent 'Example Studio International Holdings Ltd.' just to look more complete.",
    limitations: "This generator does not verify legal registration, phone ownership or social profile ownership. It formats the facts you provide.",
    faqs: [
      { question: "Do I need Organization schema on every page?", answer: "Not necessarily. Site-wide generation is common, but the implementation should avoid conflicting duplicates." },
      { question: "Should I add an address?", answer: "Only when the organization genuinely has and publishes an appropriate address." },
      { question: "Can I add social profiles?", answer: "Yes, when they are official profiles and you use the appropriate property." },
      { question: "Can a person use Organization schema?", answer: "A person should generally be represented with Person when the entity is an individual rather than an organization." },
      { question: "Does Organization schema verify my business with Google?", answer: "No. It is structured data, not a business-verification mechanism." },
    ],
  },
  "breadcrumb-schema-generator": {
    definition: "BreadcrumbList schema represents the visible navigation path from broader sections to the current page. This generator converts ordered label-and-URL pairs into ListItem objects with explicit positions, which is less error-prone than hand-numbering JSON-LD.",
    whyItMatters: "Breadcrumbs help users understand location in a site hierarchy and create useful internal links. When structured data is added, the markup should describe the same path users see rather than inventing a second SEO-only hierarchy.",
    howToUse: ["Write the breadcrumb path in display order, one `Label | URL` pair per line.", "Include the homepage if it appears in the visible breadcrumb.", "Use final canonical URLs rather than redirected addresses.", "Generate the JSON-LD and compare item names with the visible breadcrumb labels.", "Keep the positions sequential when the path changes."],
    interpretation: ["BreadcrumbList is the container.", "Each ListItem has a position, label and destination.", "Positions begin at one and follow the visible hierarchy.", "The final item can describe the current page, depending on your visible breadcrumb implementation."],
    commonProblems: ["Schema path differs from the breadcrumb users see.", "Positions skip numbers after a template change.", "Items point to redirected or parameterized URLs.", "Breadcrumb hierarchy is created only for schema and has no user-facing equivalent."],
    fixes: ["Generate visible breadcrumbs and JSON-LD from the same route hierarchy.", "Use canonical destinations.", "Remove obsolete parent sections after site architecture changes.", "Test deep pages, not only top-level categories."],
    bestPractices: ["Keep labels concise and understandable.", "Use breadcrumbs as real navigation, especially on deep content structures.", "Do not force artificial hierarchy onto pages that do not belong to one.", "Review breadcrumb markup after taxonomy changes."],
    example: "A page at `/guides/technical-seo/canonicals/` might show Home → Guides → Technical SEO → Canonical URLs. The structured data should reflect that visible path rather than a keyword-stuffed alternative.",
    limitations: "The generator formats the sequence you provide. It cannot determine whether your information architecture is sensible or whether the breadcrumb is visible to users.",
    faqs: [
      { question: "Does every breadcrumb item need a URL?", answer: "Common implementations provide destinations for navigable items. Keep the structured path consistent with the visible UI." },
      { question: "Should the current page be included?", answer: "It can be, particularly if the visible breadcrumb includes it. Keep implementation consistent." },
      { question: "Can breadcrumbs improve crawling?", answer: "Visible breadcrumb links can strengthen internal navigation and discovery, separate from the structured data itself." },
      { question: "Can I use categories that are not clickable?", answer: "You can model a visible hierarchy, but avoid inventing destinations that do not exist." },
      { question: "Why use positions?", answer: "Positions tell consumers the order of items in the breadcrumb path." },
    ],
  },
  "local-business-schema-generator": {
    definition: "LocalBusiness structured data describes a real physical or locally serving business using properties such as name, website, telephone and postal address. This generator creates a factual base object without inventing opening hours, coordinates, ratings or price ranges.",
    whyItMatters: "Local business markup becomes risky when generators encourage users to fill every possible field whether or not the information is accurate. A smaller object based on verified contact data is easier to maintain and less likely to contradict visible location pages or business profiles.",
    howToUse: ["Enter the business name exactly as customers see it.", "Add the canonical business or location URL.", "Provide a real telephone number if publicly used.", "Enter the physical address components that belong to the location.", "Generate the JSON-LD and compare it with the visible contact details before publishing."],
    interpretation: ["LocalBusiness identifies a business with local presence or service context.", "PostalAddress nests the location fields in a standard structure.", "Telephone and URL should match the public business identity.", "More specific LocalBusiness subtypes can be used later when they accurately describe the business."],
    commonProblems: ["Using a virtual mailbox as though it were a customer-facing location.", "Schema address differs from the website footer or location page.", "Fake ratings or price ranges added for perceived SEO benefit.", "One location's schema copied unchanged across multiple branches."],
    fixes: ["Create location-specific data from real branch records.", "Remove unsupported claims and unverified coordinates.", "Keep NAP information synchronized with visible pages and major business profiles.", "Use an appropriate subtype only when it truly fits the business."],
    bestPractices: ["Treat local structured data as entity information, not keyword space.", "Use one clear canonical URL for each important location page.", "Update address and telephone data immediately after a move.", "Do not mark up locations that do not genuinely exist."],
    example: "A dental clinic with one real office can describe that office's name, URL, phone and postal address. It should not create five LocalBusiness objects for nearby cities simply because the clinic wants to rank in those places.",
    limitations: "The generator does not verify the address, phone number, licensing or business eligibility for local search products. It only formats supplied data.",
    faqs: [
      { question: "Does LocalBusiness schema create a map listing?", answer: "No. Structured data is separate from business-profile verification and local listing platforms." },
      { question: "Can service-area businesses use LocalBusiness?", answer: "Potentially, but location and service-area representation should match the real business model and current platform guidance." },
      { question: "Should I add latitude and longitude?", answer: "Only when you have accurate coordinates and a reason to include them." },
      { question: "Can each branch have its own schema?", answer: "Yes, location-specific pages can represent real branches with their own factual details." },
      { question: "Should I add reviews?", answer: "Only when the markup is eligible, visible and based on genuine review data. Never invent ratings." },
    ],
  },
  "website-schema-generator": {
    definition: "WebSite schema describes the website as an entity rather than a single page or business location. This generator creates a simple object with the site name and canonical homepage URL, plus an optional SearchAction when the website has a real internal search URL pattern.",
    whyItMatters: "WebSite markup is often confused with Organization or WebPage markup. Keeping those concepts separate produces cleaner structured data: the organization owns or publishes the site, the WebSite represents the overall property, and individual WebPage entities represent specific URLs.",
    howToUse: ["Enter the public website name and canonical homepage URL.", "If the site has a functional search feature, optionally enter its real query URL template.", "Generate the JSON-LD and verify the search template actually returns useful results.", "Connect the WebSite entity with other structured data only when the relationships are accurate."],
    interpretation: ["WebSite represents the overall web property.", "Name should match the site's public brand or site title.", "A SearchAction describes a real site-search function, not an invented search endpoint.", "The homepage URL should be the canonical production address."],
    commonProblems: ["Using WebSite to describe an individual article.", "Adding a SearchAction when the site has no working search page.", "Using a temporary preview domain as the URL.", "Duplicating several inconsistent WebSite objects from different plugins."],
    fixes: ["Use one stable site name and production homepage.", "Remove SearchAction if internal search is unavailable or private.", "Generate structured data from shared site configuration.", "Audit duplicates after adding SEO plugins or framework metadata modules."],
    bestPractices: ["Keep site-level structured data minimal and stable.", "Use the same canonical base URL throughout metadata and schema.", "Do not stuff alternate names with keywords.", "Revalidate after domain migrations."],
    example: "A site called Linkslo can use a WebSite object for `https://www.linkslo.com/`, while a technical SEO article on the same domain can separately use Article and WebPage markup.",
    limitations: "The generator cannot confirm that search engines will use WebSite data for any specific feature, and SearchAction behavior depends on the real site search implementation.",
    faqs: [
      { question: "What is the difference between WebSite and WebPage?", answer: "WebSite represents the overall website; WebPage represents one specific page within it." },
      { question: "Do I need SearchAction?", answer: "No. Add it only if the site has a real search URL pattern you want to describe." },
      { question: "Can I add alternateName?", answer: "Yes when there is a genuine alternate brand or site name, not as a place to add keywords." },
      { question: "Should WebSite schema appear on every page?", answer: "It can be generated site-wide, but avoid conflicting duplicates and keep the entity consistent." },
      { question: "Does WebSite schema control sitelinks?", answer: "No. Search engines choose sitelinks algorithmically." },
    ],
  },
  "video-schema-generator": {
    definition: "VideoObject schema describes a real video with fields such as name, description, thumbnail, upload date and a content or embed URL. This generator creates a focused JSON-LD object from information you already have, rather than fabricating duration, interaction counts or publisher metrics.",
    whyItMatters: "Video pages often depend on JavaScript players, which can make metadata inconsistent between the visible player and page source. Structured data gives a machine-readable description, but only when the URLs and dates remain synchronized with the real media asset.",
    howToUse: ["Enter the exact visible video title and description.", "Provide a crawlable thumbnail URL.", "Use the real upload date.", "Add the direct content or embed URL used by the page.", "Generate the JSON-LD and validate it alongside the rendered player page."],
    interpretation: ["`name` and `description` describe the video content.", "`thumbnailUrl` points to an image representing the video.", "`uploadDate` records when the video was originally published.", "`contentUrl` can identify the media file, while `embedUrl` is often used for a player URL in more advanced implementations."],
    commonProblems: ["Thumbnail URL blocked by authentication or hotlink rules.", "Upload date changes on every page update.", "Schema describes a video that is not actually present on the page.", "Title in schema differs from the player title and page heading."],
    fixes: ["Use stable public media and thumbnail URLs.", "Keep upload date separate from page modification date.", "Generate video fields from the same media record used by the player.", "Remove video markup when the video is removed from the page."],
    bestPractices: ["Use high-quality representative thumbnails.", "Keep descriptions specific rather than promotional filler.", "Add duration only when you have the real duration value.", "Do not invent view counts or engagement statistics."],
    example: "A tutorial page with a real embedded canonical-tag walkthrough can describe that specific video. A page containing only a static image with a play icon should not publish VideoObject schema unless an actual video is available.",
    limitations: "The generator creates a base VideoObject. Search-engine video features may require additional properties, crawlable media and technical playback conditions outside the JSON-LD itself.",
    faqs: [
      { question: "Do I need a thumbnail URL?", answer: "Video structured data commonly relies on a representative thumbnail. Use a real accessible image." },
      { question: "What is the difference between contentUrl and embedUrl?", answer: "contentUrl points to the media resource; embedUrl points to a player URL. Use the property that matches your implementation." },
      { question: "Should uploadDate change when I edit the page?", answer: "No. It should represent the video's publication date, not routine page edits." },
      { question: "Can I use VideoObject for a GIF?", answer: "Use the type for actual video content rather than stretching it to unrelated media formats." },
      { question: "Does VideoObject guarantee a video result?", answer: "No. Search engines evaluate additional content and technical signals before showing video features." },
    ],
  },
};
