import type { SeoToolDefinition } from "@/lib/seo-tools/catalog";

export type ToolFaq = { question: string; answer: string };
export type ToolEditorial = {
  definition: string;
  whyItMatters: string;
  howToUse: string[];
  interpretation: string[];
  commonProblems: string[];
  fixes: string[];
  bestPractices: string[];
  example: string;
  limitations: string;
  faqs: ToolFaq[];
};

const E: Record<string, ToolEditorial> = {
  "robots-txt-tester": {
    definition: "A robots.txt tester evaluates whether a crawler is permitted to request a particular path according to the rules published at the site's /robots.txt location. It is a crawl-control check, not an indexing check. A URL can be allowed by robots.txt and still carry a noindex directive, canonicalize elsewhere, return an error, or remain unindexed for other reasons.",
    whyItMatters: "Robots rules are easy to misread because matching depends on user-agent groups, path prefixes and the most specific applicable rule. A single broad Disallow can prevent search crawlers from fetching templates, sections or resources that the site owner expected to be accessible. Testing the exact URL and crawler is safer than scanning the file by eye.",
    howToUse: ["Enter the full URL you want to test, not only the domain.", "Choose or enter the crawler name that matters to your audit, such as Googlebot.", "Run the test and review the fetched robots.txt file, matching group and winning Allow or Disallow rule.", "If no rule matches, remember that the default outcome is normally allowed."],
    interpretation: ["Allowed means the tested crawler is not blocked by the applicable robots.txt rules for that path.", "Blocked means a matching Disallow rule wins for the selected crawler and path.", "No robots.txt or a fetch failure is different from an explicit Allow. Read the fetch message before drawing a conclusion."],
    commonProblems: ["Blocking an entire directory when only one private path was intended.", "Testing Googlebot while the file contains a more specific Googlebot-News or AdsBot group.", "Assuming robots.txt removes a URL from search results.", "Using robots.txt to protect confidential content."],
    fixes: ["Narrow broad Disallow patterns and retest the exact affected paths.", "Use meta robots or X-Robots-Tag when the requirement is about indexing rather than crawling.", "Use authentication for private content; robots.txt is publicly readable and is not an access-control system."],
    bestPractices: ["Keep rules as simple as the site architecture allows.", "Retest after migrations, CMS changes and staging-to-production releases.", "Link your sitemap from robots.txt when useful, but do not assume that makes every sitemap URL indexable."],
    example: "If /admin/ is disallowed for User-agent: * but /admin/help/ is explicitly allowed, a tester should evaluate the exact requested path rather than declaring the whole /admin/ tree blocked.",
    limitations: "This tool evaluates published robots rules and the requested crawler. It does not prove that Google has crawled, indexed or ranked the URL, and it cannot override server-side bot blocking that happens outside robots.txt.",
    faqs: [
      { question: "Does robots.txt prevent indexing?", answer: "Not reliably. Robots.txt primarily controls crawling. A blocked URL can still be known from links and may appear without a normal fetched snippet." },
      { question: "What happens when there is no matching rule?", answer: "The crawler is generally allowed to request the path, assuming no separate network or server restriction blocks it." },
      { question: "Can robots.txt block CSS and JavaScript?", answer: "Yes. That can interfere with rendering and should be intentional rather than inherited from an old configuration." },
      { question: "Is robots.txt case-sensitive?", answer: "Path matching can be case-sensitive because URLs themselves may be case-sensitive on the server. Test the exact URL used by the site." },
      { question: "Can I use robots.txt for private pages?", answer: "No. Use authentication or access controls for private content." },
    ],
  },
  "robots-txt-validator": {
    definition: "A robots.txt validator checks the file as a configuration document: whether crawler groups are understandable, directives are written in useful locations and common unsupported or malformed lines are present. Validation is different from testing one URL because it reviews the file's overall structure rather than one matching decision.",
    whyItMatters: "A robots file is often edited during redesigns, migrations and emergency deindexing work. Old sitemap paths, misplaced directives and copied syntax from unrelated products can linger for years. A validation pass helps separate valid crawler instructions from lines that search engines may ignore.",
    howToUse: ["Enter the site's homepage or robots.txt URL.", "Run validation and inspect the retrieved file before the issue list.", "Check each user-agent group, sitemap declaration and unknown directive.", "Resolve syntax problems first, then use the Robots.txt Tester on important URLs."],
    interpretation: ["Errors indicate syntax or structural patterns likely to be ignored or misunderstood.", "Warnings identify patterns that can be valid but deserve manual confirmation.", "Information items describe detected groups and sitemap declarations without treating them as problems."],
    commonProblems: ["Writing Noindex in robots.txt and expecting modern search engines to honor it.", "Placing an Allow or Disallow line before any User-agent group.", "Referencing an old HTTP or staging sitemap.", "Using full URLs where a path pattern is expected."],
    fixes: ["Move crawl rules inside a clear user-agent group.", "Remove obsolete non-standard indexing directives and use page-level robots controls instead.", "Update Sitemap entries to the canonical production sitemap URL."],
    bestPractices: ["Prefer a short file that humans can review quickly.", "Keep comments useful and avoid generated clutter.", "Validate again after CDN, framework or CMS changes because robots files are sometimes generated outside the application repository."],
    example: "A line such as `Disallow: https://example.com/private/` is a common mistake. The directive normally expects a path such as `/private/`, not an absolute URL.",
    limitations: "Syntax validation cannot tell you whether every rule supports your business intent. A technically valid Disallow can still block a section you wanted indexed.",
    faqs: [
      { question: "Is an empty robots.txt valid?", answer: "An empty reachable file effectively blocks nothing and can be valid, though many sites include sitemap references for convenience." },
      { question: "Does Crawl-delay work for Googlebot?", answer: "Google does not use Crawl-delay in robots.txt in the same way some other crawlers do. Treat crawler-specific directives separately." },
      { question: "Can robots.txt contain more than one Sitemap line?", answer: "Yes. Multiple sitemap declarations can be used when a site publishes several sitemap files." },
      { question: "Should robots.txt return 200?", answer: "A normal published robots file should generally be directly retrievable. Different failure status codes can be interpreted differently by crawlers." },
      { question: "Do comments change matching?", answer: "Comments beginning with # are for humans and are not crawl directives." },
    ],
  },
  "robots-txt-generator": {
    definition: "A robots.txt generator turns explicit crawl choices into a plain-text file that can be served from the root of a host. It is useful when you know which crawler groups and paths should be allowed or disallowed but want to avoid formatting mistakes.",
    whyItMatters: "Small syntax mistakes can make a crawl-control rule ineffective, while an overly broad rule can hide an important section from crawlers. Generating a minimal file from deliberate choices makes review easier than copying a large example from another website.",
    howToUse: ["Choose the user-agent group you want to control.", "Add blocked or allowed path prefixes one per line.", "Add the absolute sitemap URL if the site has one.", "Generate the file, review it manually and publish it as /robots.txt on the correct host."],
    interpretation: ["User-agent selects the crawler group the following rules apply to.", "Disallow defines paths the group should not request.", "Allow can create a more specific exception within a broader blocked path.", "Sitemap points crawlers to an XML sitemap and uses an absolute URL."],
    commonProblems: ["Copying rules from staging into production.", "Blocking /wp-content/ or asset directories without checking rendering effects.", "Trying to create noindex behavior through robots.txt.", "Publishing the file on a subdirectory instead of the host root."],
    fixes: ["Test representative public, blocked and exception URLs before deployment.", "Pair indexing requirements with meta robots or X-Robots-Tag rather than crawl blocks.", "Keep separate robots files for different hosts when subdomains have different crawl policies."],
    bestPractices: ["Start permissive and add only rules you can explain.", "Document unusual blocks with short comments.", "Keep a version-controlled copy when possible."],
    example: "A simple file can allow all crawlers, block `/internal-search/`, and declare `Sitemap: https://example.com/sitemap.xml` without adding dozens of unnecessary directives.",
    limitations: "The generator cannot know which application routes are private, low-value or important to your SEO strategy. Review every rule against the actual site before publishing.",
    faqs: [
      { question: "Where should robots.txt be uploaded?", answer: "At the root of the host, for example https://example.com/robots.txt." },
      { question: "Should I block admin pages?", answer: "Only if crawl control is appropriate. Sensitive admin areas should also have real authentication." },
      { question: "Can one robots file control another subdomain?", answer: "No. Robots rules apply to the host where the file is served." },
      { question: "Should I add a Sitemap directive?", answer: "It can be useful for discovery and is common practice, though sitemaps can also be submitted through search engine tools." },
      { question: "Can I block query parameters?", answer: "Path patterns can target parameter-containing URLs, but test carefully because broad patterns can catch valid pages." },
    ],
  },
  "canonical-url-checker": {
    definition: "A canonical URL checker reads the rel=canonical declaration from a page and compares it with the fetched URL, redirect outcome and basic URL details. The canonical element is a hint about the preferred version of duplicate or near-duplicate content; it is not a redirect and does not prevent users from loading the current page.",
    whyItMatters: "Canonical mistakes can consolidate signals toward the wrong page, point to non-200 destinations or create mixed signals with redirects and internal links. They are especially common after protocol changes, faceted navigation, ecommerce filtering and migrations.",
    howToUse: ["Enter the exact page URL you want to audit.", "Review the final fetched URL in case the request redirects.", "Compare the declared canonical with the page you expect search engines to treat as preferred.", "Open the canonical destination and confirm it is live, indexable and semantically equivalent."],
    interpretation: ["Self-referencing means the declared canonical resolves to the same preferred URL as the page being checked.", "Cross-URL means the page points to another URL as preferred and should be reviewed for intentional duplication.", "Missing canonical is not automatically an error; some pages can be indexed correctly without one."],
    commonProblems: ["Canonical pointing to HTTP while the site uses HTTPS.", "Every paginated or filtered page canonicalizing to a category root even when content differs.", "Canonical URL returning 404, redirecting repeatedly or carrying noindex.", "Relative or malformed canonical values generated by templates."],
    fixes: ["Use an absolute preferred URL that resolves cleanly.", "Align internal links, sitemap URLs and redirects with the canonical version when appropriate.", "Remove contradictory noindex/canonical combinations unless the behavior is deliberate and understood."],
    bestPractices: ["Use canonicals to consolidate genuinely duplicate or substantially similar URLs.", "Keep canonical destinations stable and indexable.", "Audit canonicals during migrations and parameter-handling changes."],
    example: "If `https://example.com/product?color=blue` is only a filtered presentation of the main product page, a canonical to the clean product URL may be appropriate. If the blue variant has unique content and demand, that decision deserves separate analysis.",
    limitations: "The tool can report the declared canonical and technical conflicts, but it cannot guarantee which URL Google will select as canonical because search engines evaluate additional signals.",
    faqs: [
      { question: "What does a canonical URL tell search engines?", answer: "It indicates the URL you prefer for consolidation when duplicate or very similar versions exist." },
      { question: "What if a page has multiple canonical tags?", answer: "Conflicting canonical declarations are a serious implementation problem because they create ambiguity and may be ignored." },
      { question: "Should a canonical use HTTPS?", answer: "If HTTPS is the site's preferred protocol, the canonical should normally use the HTTPS version." },
      { question: "Can a canonical point to another domain?", answer: "Cross-domain canonicals are supported in appropriate duplicate-content situations, but they should be deliberate and verifiable." },
      { question: "Canonical or redirect: which should I use?", answer: "Use a redirect when users and crawlers should move to another URL. Use canonical when the current URL remains accessible but another version is preferred for consolidation." },
    ],
  },
  "canonical-tag-generator": {
    definition: "A canonical tag generator creates the HTML `<link rel=\"canonical\">` element for a preferred absolute URL. The element belongs in the document head and communicates canonical preference without changing the URL users see in their browser.",
    whyItMatters: "Hand-written canonical markup is simple, but copying an old domain, dropping HTTPS or generating relative values can create large-scale errors when the tag is applied through a shared template.",
    howToUse: ["Enter the complete preferred URL including protocol.", "Generate the tag and confirm the URL is exactly the version you want indexed.", "Place one canonical link element in the HTML head.", "After deployment, use the Canonical URL Checker to verify the rendered output."],
    interpretation: ["The generated href should be an absolute URL.", "One clear canonical declaration is preferable to conflicting duplicates.", "The destination should normally return a successful response and represent equivalent content."],
    commonProblems: ["Using a relative href when deployment environments can change base URLs.", "Canonicalizing all pages to the homepage.", "Leaving a staging hostname in production markup.", "Generating both framework metadata and a second manual canonical tag."],
    fixes: ["Centralize canonical logic in one rendering layer.", "Use environment-safe production base URLs.", "Test representative templates rather than checking only the homepage."],
    bestPractices: ["Generate canonicals from stable route data rather than the raw request URL when tracking parameters are present.", "Keep URL casing, trailing-slash convention and protocol consistent.", "Combine canonical QA with sitemap and internal-link checks."],
    example: "For a preferred page at `https://example.com/guides/canonical-tags/`, the generated element should point to that exact URL rather than a campaign-parameter version of it.",
    limitations: "Generating valid markup does not prove the canonical strategy is correct. Search engines can choose a different canonical when stronger signals conflict.",
    faqs: [
      { question: "Where does the canonical tag go?", answer: "Inside the HTML head of the page." },
      { question: "Can I have two canonical tags?", answer: "Avoid conflicting canonical declarations. A page should communicate one clear preferred canonical URL." },
      { question: "Should the canonical be self-referencing?", answer: "Self-referencing canonicals are common and useful on indexable pages, though strategy depends on the page type." },
      { question: "Can canonical URLs contain parameters?", answer: "They can, but only if the parameterized URL is intentionally the preferred version." },
      { question: "Does canonical pass all ranking signals?", answer: "Canonicalization is a consolidation signal, not a contractual transfer of a fixed amount of ranking value." },
    ],
  },
  "hreflang-checker": {
    definition: "An hreflang checker inspects alternate-language annotations that connect equivalent pages for different languages or regions. It looks for declared language-region values, duplicate annotations and the URLs referenced by each alternate.",
    whyItMatters: "Hreflang errors rarely break a page for users, which means they can go unnoticed while search engines receive incomplete or contradictory international targeting signals. Missing return links, invalid codes and canonicals pointing outside the language cluster are frequent causes.",
    howToUse: ["Enter one URL from the international page set.", "Review every detected hreflang value and destination.", "Confirm language codes are ISO-style values and optional regions are appropriate.", "Check reciprocal annotations on alternate pages and confirm canonicals remain inside the intended cluster."],
    interpretation: ["A language-only value such as `en` targets English generally.", "A language-region value such as `en-GB` narrows the intended audience to English users in the UK.", "x-default can identify a fallback page when no listed language or region matches."],
    commonProblems: ["Using country codes without a language component.", "Linking from page A to page B when B does not reference A.", "Mixing canonical URLs and hreflang URLs from different clusters.", "Pointing hreflang to redirected or non-indexable pages."],
    fixes: ["Normalize codes and URLs across every page in the set.", "Generate reciprocal annotations from the same source of truth.", "Remove stale alternates when localized pages are deleted or redirected."],
    bestPractices: ["Use absolute canonical URLs.", "Keep each alternate indexable when it is intended to appear in search.", "Test several page families because homepage hreflang can work while deeper templates fail."],
    example: "An English UK page can reference `en-GB`, an English US page `en-US`, a French page `fr-FR`, and an x-default selector page. Each participating page should normally list the same cluster.",
    limitations: "The checker can inspect annotations available from the fetched page. It cannot prove that a search engine has accepted the international targeting or that every remote alternate remains unchanged later.",
    faqs: [
      { question: "Do hreflang pages need reciprocal links?", answer: "Reciprocal annotations are an important part of a valid hreflang cluster and help confirm the relationship between alternates." },
      { question: "Can hreflang and canonical point to different URLs?", answer: "They can, but careless combinations often break the intended cluster. Each localized page usually canonicals to its own preferred localized URL." },
      { question: "What is x-default?", answer: "It identifies a fallback page for users whose language or region is not represented by a more specific hreflang value." },
      { question: "Should I use `uk` in hreflang?", answer: "Use the ISO region code GB, as in en-GB, rather than UK." },
      { question: "Can hreflang be placed in a sitemap?", answer: "Yes. Hreflang can be implemented in HTML, HTTP headers for some formats, or XML sitemaps when done correctly." },
    ],
  },
  "hreflang-generator": {
    definition: "An hreflang generator creates alternate link elements from language or language-region codes and their equivalent absolute URLs. It is most useful when teams already know the correct localization map but want consistent markup.",
    whyItMatters: "International sites often maintain dozens of language-market combinations. A consistent generator reduces typing errors and makes it easier to review whether every member of a cluster is represented.",
    howToUse: ["Enter one language or language-region code and URL per line.", "Add x-default only when you have a genuine fallback destination.", "Generate the link elements.", "Deploy the same complete cluster on each equivalent page and then verify it with the Hreflang Checker."],
    interpretation: ["Each generated tag describes one alternate version of substantially equivalent content.", "Language values should follow recognized two-letter language codes, with optional region codes where regional targeting is necessary.", "x-default is a fallback, not a substitute for a missing language version."],
    commonProblems: ["Translating codes incorrectly, such as using a country where a language is required.", "Adding hreflang between pages that are not equivalent.", "Forgetting to update all pages when one localized URL changes."],
    fixes: ["Keep localization URLs in a centralized data structure.", "Validate codes before generating tags.", "Retest reciprocal references after every international release."],
    bestPractices: ["Prefer only the granularity you actually need; `es` can be better than many regional variants when content is identical.", "Keep canonical and hreflang URLs aligned with final, redirect-free destinations.", "Do not generate placeholder alternates for translations that do not exist."],
    example: "A product available in English US and French France can use two alternate tags if those pages contain equivalent localized product content. Add x-default only if there is a meaningful fallback such as a market selector.",
    limitations: "The generator validates formatting, not business equivalence. You are responsible for ensuring each URL is a real localized counterpart.",
    faqs: [
      { question: "Can two hreflang tags use the same URL?", answer: "Sometimes one URL can serve more than one audience, but repeated mappings deserve careful review because they can obscure the intended localization strategy." },
      { question: "Do I need x-default?", answer: "No. Use it only when a fallback page genuinely serves users outside your listed language or region options." },
      { question: "Should URLs be absolute?", answer: "Yes, absolute URLs are the safest and standard form for hreflang annotations." },
      { question: "Can I generate hreflang for PDFs?", answer: "For non-HTML resources, hreflang relationships can be delivered with HTTP headers rather than HTML link elements." },
      { question: "Does hreflang translate content?", answer: "No. It only describes relationships between existing localized pages." },
    ],
  },
  "redirect-checker": {
    definition: "A redirect checker requests a URL without automatically hiding the intermediate responses, records each redirect status and follows the Location header until a final response is reached or a safety limit is hit.",
    whyItMatters: "Browsers make redirects look instant, but crawlers, analytics and caching layers still process each hop. Old migrations can leave chains that waste requests, slow users and obscure the true canonical destination.",
    howToUse: ["Enter the exact source URL including protocol.", "Run the check and read the sequence from first request to final destination.", "Confirm the status code matches the redirect's intent.", "Update internal links to point directly to the stable final URL when possible."],
    interpretation: ["301 and 308 indicate permanent redirection semantics.", "302 and 307 indicate temporary semantics.", "A final 200 usually means the destination responded successfully, while 4xx or 5xx final responses need investigation."],
    commonProblems: ["HTTP to HTTPS redirect followed by a second www/non-www redirect.", "Old URL redirecting to another old URL before reaching the current page.", "Redirecting removed content to an unrelated homepage.", "Mixing temporary and permanent redirects without intent."],
    fixes: ["Collapse chains so old URLs point directly to the best current destination.", "Update internal navigation, canonicals and sitemap entries to final URLs.", "Use relevant replacement pages rather than blanket homepage redirects."],
    bestPractices: ["Test redirects after platform migrations and domain changes.", "Preserve query parameters only when they are required.", "Monitor high-value externally linked legacy URLs."],
    example: "A legacy URL that goes HTTP → HTTPS → www → new path has three hops. A cleaner rule can often send the original URL directly to the final HTTPS canonical page.",
    limitations: "The checker sees the network path from this service at the time of the request. Geo-targeted, cookie-based or bot-specific redirect behavior can differ for other users.",
    faqs: [
      { question: "Is a 301 always better than a 302?", answer: "No. Use permanent or temporary semantics according to the actual change. The correct status depends on intent." },
      { question: "How many redirect hops are too many?", answer: "Fewer is generally better. Long chains add latency and failure points even when crawlers can follow them." },
      { question: "Do redirects transfer all SEO value?", answer: "Search engines use redirects as strong canonicalization signals, but it is better to think in terms of consolidation than a guaranteed percentage transfer." },
      { question: "Should internal links point through redirects?", answer: "Usually no. Internal links should generally point directly to the preferred final URL." },
      { question: "Can redirects cause loops?", answer: "Yes. Conflicting application, CDN or web-server rules can send URLs back and forth indefinitely." },
    ],
  },
  "redirect-chain-checker": {
    definition: "A redirect chain checker focuses on sequences where one redirected URL leads to another redirected URL before reaching a final resource. It records each hop so the chain can be shortened intentionally rather than guessed from the browser address bar.",
    whyItMatters: "Chains accumulate during repeated redesigns. They add network latency, complicate debugging and can send crawlers through old URL generations that no longer serve a purpose.",
    howToUse: ["Enter the oldest or suspect URL.", "Review every hop and status code in order.", "Identify which intermediate URLs exist only because of historical migrations.", "Replace source redirects and internal references with a direct path to the current destination."],
    interpretation: ["One intentional redirect can be normal.", "Multiple consecutive redirects indicate a chain worth reviewing.", "A chain ending in an error is both a redirect and destination problem."],
    commonProblems: ["Protocol and hostname normalization handled in separate rules.", "CMS slug changes layered on top of previous redirects.", "Redirect plugins retaining old rules after a second migration."],
    fixes: ["Consolidate rules at the layer that owns canonical URL behavior.", "Test old backlinks and bookmarked URLs after changing rules.", "Remove obsolete intermediates only after confirming no application feature depends on them."],
    bestPractices: ["Maintain a redirect map during migrations.", "Audit top linked legacy URLs, not only current navigation.", "Keep sitemap and canonical URLs free of redirects."],
    example: "A chain `/services/seo` → `/seo-services` → `/services/search-engine-optimization` should usually be replaced by direct redirects from both older URLs to the final current page.",
    limitations: "Some redirects depend on device, location, cookies or authentication. A server-side check cannot reproduce every personalized path.",
    faqs: [
      { question: "Does a two-hop chain break SEO?", answer: "Not necessarily, but unnecessary hops add complexity and should usually be simplified when you control them." },
      { question: "Can a canonical point through a redirect chain?", answer: "It can technically, but canonicals should normally point directly to the stable final URL." },
      { question: "Should sitemap URLs redirect?", answer: "Sitemaps should ideally list final canonical URLs rather than redirecting addresses." },
      { question: "Can chains slow a site?", answer: "Yes. Every network hop adds latency before the final resource is retrieved." },
      { question: "Are redirect chains the same as loops?", answer: "No. A chain eventually resolves; a loop repeats URLs without reaching a stable final resource." },
    ],
  },
  "redirect-loop-checker": {
    definition: "A redirect loop occurs when redirect rules send a request back to a URL already visited in the same path. Browsers eventually stop with a too-many-redirects error; search crawlers also cannot reach useful content through the loop.",
    whyItMatters: "Loops can take important pages completely offline even though the application itself is healthy. They often appear after changing HTTPS, reverse-proxy settings, trailing slashes, locale routing or authentication rules.",
    howToUse: ["Enter the URL producing a redirect error.", "Run the check and inspect repeated URLs in the recorded path.", "Identify which infrastructure layer owns each redirect.", "Change the conflicting rule and retest from the original URL."],
    interpretation: ["A repeated normalized URL indicates circular behavior.", "A safety-limit stop without an exact repeat can still indicate an abnormally long redirect path.", "A normal final 200 means no loop was observed during this request."],
    commonProblems: ["CDN forces HTTPS while the origin redirects HTTPS back to HTTP.", "Locale middleware redirects `/` to `/en/` while another rule strips `/en/`.", "Trailing-slash rules disagree between framework and server."],
    fixes: ["Choose one canonical protocol, host and path style.", "Remove duplicate redirect ownership where possible.", "Test with cookies cleared when authentication middleware is involved."],
    bestPractices: ["Document which layer controls redirects.", "Add automated smoke tests for canonical host and protocol behavior.", "Retest both desktop and bot-like requests after infrastructure changes."],
    example: "If nginx redirects `/page` to `/page/` but an application middleware redirects `/page/` back to `/page`, neither URL can load until the rules are aligned.",
    limitations: "The tool detects the loop visible from its request context. Conditional redirects based on login state, geography or headers may behave differently elsewhere.",
    faqs: [
      { question: "What causes ERR_TOO_MANY_REDIRECTS?", answer: "Usually circular or excessively repeated redirect rules, though cookies and authentication state can also contribute." },
      { question: "Can a redirect loop affect only bots?", answer: "Yes. User-agent-specific middleware or CDN rules can create crawler-only behavior." },
      { question: "How do I fix HTTP/HTTPS loops?", answer: "Make the proxy and origin agree about the original protocol and configure one consistent HTTPS canonicalization path." },
      { question: "Can cookies cause loops?", answer: "Yes. Authentication or preference cookies can repeatedly trigger conflicting redirect logic." },
      { question: "Will search engines index a looping URL?", answer: "A crawler cannot fetch stable content through a loop, so the issue should be fixed rather than treated as an indexing strategy." },
    ],
  },
  "http-status-code-checker": {
    definition: "An HTTP status code checker requests a resource and reports the response class returned by the server. Status codes describe request outcomes: successful responses, redirects, client errors and server errors all have different operational and SEO implications.",
    whyItMatters: "A page can look fine in a browser while automated systems receive a different status, especially behind CDNs, security products or soft-error templates. Checking the real response helps distinguish content problems from transport problems.",
    howToUse: ["Enter a complete HTTP or HTTPS URL.", "Run the request and review both the first and final response when redirects occur.", "Compare the status with what the page is supposed to do.", "Investigate unexpected 4xx, 5xx or redirect responses at the application or infrastructure layer."],
    interpretation: ["2xx indicates the request was handled successfully.", "3xx indicates redirection or related resource movement.", "4xx indicates the request cannot be fulfilled as sent, such as 404 Not Found.", "5xx indicates a server-side failure."],
    commonProblems: ["Custom error page returning 200 instead of 404.", "Deleted URL returning 302 to the homepage.", "Intermittent 503 responses during deployment.", "Security layer returning 403 only to crawlers."],
    fixes: ["Return meaningful status codes that match the content state.", "Use 404 or 410 for genuinely unavailable content when no replacement exists.", "Use redirects only when there is a real replacement or intentional temporary destination."],
    bestPractices: ["Monitor important templates and endpoints automatically.", "Check both canonical and legacy URLs after releases.", "Investigate recurring 5xx errors through server logs rather than masking them with redirects."],
    example: "A deleted product can return 404 with a useful navigation template. The helpful design does not require a 200 status; the status should still communicate that the requested resource no longer exists.",
    limitations: "One request is a snapshot. Intermittent outages, rate limits and geo-specific behavior can require repeated monitoring from multiple locations.",
    faqs: [
      { question: "Is 404 bad for SEO?", answer: "A legitimate 404 is normal for a missing URL. The problem is broken internal links, valuable lost URLs or large unexpected error patterns." },
      { question: "What is a soft 404?", answer: "It is a page that technically returns success or redirect behavior but appears to search engines like missing or empty content." },
      { question: "What is the difference between 301 and 308?", answer: "Both indicate permanent redirection semantics; 308 also preserves the request method and body according to HTTP semantics." },
      { question: "Should maintenance use 503?", answer: "A temporary 503 can accurately signal service unavailability when used intentionally and briefly." },
      { question: "Can a page return different statuses to bots?", answer: "Yes, through security, CDN or application logic. That behavior should be audited carefully." },
    ],
  },
  "indexability-checker": {
    definition: "An indexability checker combines observable page signals that influence eligibility for indexing: HTTP response, robots directives, canonical declaration and crawl accessibility. It should not claim to know whether a search engine has actually indexed the page unless it has a reliable index-status source.",
    whyItMatters: "Indexing problems are often caused by combinations rather than one obvious tag. A page may return 200 but carry noindex, or be indexable in HTML while canonicalizing to another URL. Reviewing the signals together prevents narrow diagnoses.",
    howToUse: ["Enter the exact page URL.", "Review response status and final URL first.", "Check meta robots and X-Robots-Tag directives.", "Compare canonical URL and robots.txt crawlability.", "Treat the result as technical eligibility, then use Search Console or equivalent first-party data for actual index status."],
    interpretation: ["Indexable signals means no obvious technical exclusion was detected in the fetched response.", "Noindex is an explicit indexing directive and should be intentional.", "Canonical to another URL is a consolidation signal, not necessarily an error.", "Blocked crawling can prevent search engines from seeing page-level directives."],
    commonProblems: ["Production templates inheriting staging noindex.", "Canonical pointing to a different page family.", "X-Robots-Tag noindex added at CDN or server level.", "Robots.txt blocking a page whose noindex tag needs to be seen."],
    fixes: ["Remove accidental noindex controls from pages intended for search.", "Make canonical, sitemap and internal links agree on the preferred URL.", "Allow crawling long enough for search engines to observe page-level removal directives when appropriate."],
    bestPractices: ["Audit indexability before and after launches.", "Use first-party search engine tools to confirm actual indexing rather than extrapolating from HTML alone.", "Keep staging protections separate from production configuration."],
    example: "A category page returning 200 with `meta name=robots content=noindex` is technically available to users but explicitly asks compliant search engines not to index it.",
    limitations: "This tool reports signals available in the response. It does not query Google's private index and cannot promise that an eligible page will be indexed or ranked.",
    faqs: [
      { question: "Does indexable mean indexed?", answer: "No. Indexable means the observed technical signals do not obviously exclude the page. Actual indexing depends on crawling and search-engine decisions." },
      { question: "Can a noindex page be crawled?", answer: "Yes. Crawling and indexing are separate concepts, and crawlers often need to fetch a page to see its noindex directive." },
      { question: "Can canonical make a page non-indexable?", answer: "Canonical is a consolidation hint, not a noindex directive, but it can lead search engines to prefer another URL." },
      { question: "Should indexable pages be in the sitemap?", answer: "Sitemaps should generally contain canonical URLs you want search engines to discover and index." },
      { question: "Why does Search Console disagree with a checker?", answer: "Search Console has first-party crawl and index data, while a checker sees the current public response at one moment." },
    ],
  },
  "noindex-checker": {
    definition: "A noindex checker looks specifically for indexing exclusion directives in HTML meta robots tags and X-Robots-Tag HTTP headers. It narrows the audit to one high-impact question: is this response explicitly asking compliant search engines not to index the resource?",
    whyItMatters: "Accidental noindex is one of the easiest ways to remove otherwise healthy pages from search. It commonly survives from staging environments, template experiments and temporary campaign settings.",
    howToUse: ["Enter the exact URL.", "Run the check and review both HTML and response-header directives.", "Confirm whether noindex is intentional for that page type.", "If removed, request recrawling through first-party search tools where appropriate."],
    interpretation: ["Noindex detected means an explicit exclusion directive was found.", "No noindex detected means this specific exclusion was not observed; it does not guarantee indexing.", "Header-based noindex can affect non-HTML resources as well as webpages."],
    commonProblems: ["CMS checkbox applied to an entire template.", "Staging environment variable leaking into production.", "CDN rule injecting X-Robots-Tag noindex.", "Robots.txt blocking the page before crawlers can see the noindex directive."],
    fixes: ["Remove unintended meta or header directives at their source.", "Verify rendered HTML and response headers after deployment.", "Do not try to reverse noindex by adding an `index` tag while another layer still sends noindex."],
    bestPractices: ["Treat noindex as a deliberate page-level policy.", "Monitor key commercial and content templates after releases.", "Use authentication rather than noindex for genuinely private information."],
    example: "A landing-page template may include `<meta name=\"robots\" content=\"noindex,follow\">` for paid campaigns. Reusing that template for an organic page without removing the tag can prevent indexing.",
    limitations: "Absence of noindex is only one eligibility signal. Canonicalization, crawl blocks, response status, content quality and search-engine decisions still matter.",
    faqs: [
      { question: "Is noindex the same as Disallow?", answer: "No. Noindex is about indexing; Disallow in robots.txt is about crawling." },
      { question: "Can noindex be sent in an HTTP header?", answer: "Yes, with X-Robots-Tag, which is especially useful for non-HTML resources." },
      { question: "What does noindex,follow mean?", answer: "It asks the crawler not to index the page while still allowing links on the fetched page to be followed." },
      { question: "How long until a removed noindex page returns to search?", answer: "There is no fixed time. Search engines need to recrawl and reevaluate the page." },
      { question: "Can I noindex a PDF?", answer: "Yes, typically with an X-Robots-Tag response header." },
    ],
  },
  "meta-robots-checker": {
    definition: "A meta robots checker reads robots directives embedded in HTML meta elements and translates them into plain language. It can surface index/noindex, follow/nofollow and snippet controls declared for general robots or named crawlers.",
    whyItMatters: "Robots directives are compact but powerful. Templates can emit contradictory tags, duplicate crawler-specific tags or old snippet restrictions that no one remembers adding.",
    howToUse: ["Enter a webpage URL.", "Review every detected robots meta element rather than only the first one.", "Compare general robots directives with crawler-specific tags if present.", "Resolve contradictions at the template or CMS layer."],
    interpretation: ["index permits indexing but does not guarantee it.", "noindex asks compliant engines not to index the page.", "nofollow changes how links on the page are treated by compliant crawlers.", "Snippet directives can limit preview text or image previews."],
    commonProblems: ["Two tags declaring conflicting index and noindex instructions.", "Crawler-specific noindex hidden alongside a general index tag.", "Global nofollow applied when only one link needed qualification."],
    fixes: ["Emit one deliberate robots policy per crawler context.", "Use link-level rel attributes for individual sponsored, UGC or nofollow links.", "Remove old snippet restrictions when they no longer support the content strategy."],
    bestPractices: ["Keep robots logic centralized.", "Test rendered production HTML, not only CMS settings.", "Audit important templates after SEO plugins or framework metadata changes."],
    example: "A page with `<meta name=\"robots\" content=\"index,follow\">` and `<meta name=\"googlebot\" content=\"noindex\">` gives Googlebot a more specific exclusion that deserves immediate review.",
    limitations: "The checker reads meta markup from the fetched HTML. Header-based X-Robots-Tag directives require a header check as well.",
    faqs: [
      { question: "Is `index,follow` required?", answer: "No. Those behaviors are commonly defaults when no restrictive directive is present." },
      { question: "Can I target Googlebot separately?", answer: "Yes, crawler-specific robots meta names can be used, though complexity should be justified." },
      { question: "What does max-snippet do?", answer: "It can limit the amount of text search engines may use for a snippet, subject to engine support." },
      { question: "Does meta nofollow block crawling of the page?", answer: "No. It relates to following links found on the fetched page, not whether the page itself can be requested." },
      { question: "Can multiple meta robots tags exist?", answer: "They can, but conflicting values create avoidable ambiguity and should be cleaned up." },
    ],
  },
  "x-robots-tag-checker": {
    definition: "The X-Robots-Tag is an HTTP response header that can carry indexing and snippet directives outside HTML. A checker reads the header exactly as delivered by the server or CDN and explains detected values.",
    whyItMatters: "Header-level directives are easy to miss in source-code reviews. They are commonly used for PDFs, files and server-wide policies, and a broad server rule can accidentally noindex entire asset classes or page sections.",
    howToUse: ["Enter the resource URL, including non-HTML files if relevant.", "Run the request and review all X-Robots-Tag header values.", "Compare the header with HTML meta robots when checking webpages.", "Trace unexpected directives to CDN, web-server or application configuration."],
    interpretation: ["noindex in the header is an explicit indexing exclusion.", "Crawler-specific forms can scope a directive to a named bot.", "Multiple header lines may combine into one effective policy."],
    commonProblems: ["Server configuration adds noindex to every PDF when only one directory should be excluded.", "CDN rule persists after application tags are fixed.", "Conflicting header and HTML directives make debugging difficult."],
    fixes: ["Remove or narrow the server/CDN rule that injects unwanted directives.", "Keep one authoritative policy where possible.", "Retest the raw response after cache purge."],
    bestPractices: ["Use X-Robots-Tag when controlling non-HTML indexing.", "Document header policies in infrastructure code.", "Include response-header checks in launch QA."],
    example: "A PDF can return `X-Robots-Tag: noindex` even though it has no HTML head. That is a valid way to prevent the document itself from being indexed.",
    limitations: "The checker reports current headers from one request. Cached, geo-specific or authenticated responses can differ.",
    faqs: [
      { question: "Can X-Robots-Tag control PDFs?", answer: "Yes. That is one of its common uses because PDFs do not contain HTML meta tags." },
      { question: "Which wins, meta robots or X-Robots-Tag?", answer: "Restrictive directives across supported sources can affect indexing. Avoid conflicting policies instead of relying on precedence tricks." },
      { question: "Where is X-Robots-Tag configured?", answer: "It can be emitted by the application, web server, reverse proxy or CDN." },
      { question: "Can it be crawler-specific?", answer: "Yes, implementations can target named crawlers using supported syntax." },
      { question: "Does no X-Robots-Tag mean indexable?", answer: "No. It only means this header-based exclusion was not detected." },
    ],
  },
  "url-structure-checker": {
    definition: "A URL structure checker evaluates the address itself: protocol, hostname, path depth, slug readability, query parameters, encoded characters and overall length. It does not judge content quality from the URL alone.",
    whyItMatters: "URLs become part of internal links, analytics, sharing, redirects and long-term site architecture. Unnecessarily complex addresses are harder to maintain and can create duplicate variants when parameters or casing are inconsistent.",
    howToUse: ["Enter a complete URL.", "Review protocol, path segments and parameter count.", "Check whether the path describes the resource in a stable way.", "Decide whether any parameter or segment exists only because of implementation history."],
    interpretation: ["A short readable path is easier to understand but there is no universal ideal character count.", "Parameters can be legitimate for filtering and tracking but need canonical and crawl planning.", "Deep paths are not automatically bad; the information architecture matters more than the number of slashes."],
    commonProblems: ["Session IDs or tracking parameters baked into internal links.", "Mixed uppercase and lowercase variants.", "Long numeric identifiers with no stable descriptive path.", "Multiple URL forms for the same content."],
    fixes: ["Standardize internal links on one canonical URL form.", "Remove parameters that are not required for content state.", "Use redirects when permanently changing public URLs."],
    bestPractices: ["Choose stable slugs that survive minor title edits.", "Use HTTPS and one hostname convention.", "Coordinate URL changes with redirects, canonical tags and sitemap updates."],
    example: "`/products/red-running-shoes/` is easier to interpret than `/index.php?id=88271&cat=14`, but ecommerce filters may still require parameters when they represent useful state.",
    limitations: "A clean URL can host poor content and a parameterized URL can rank well. This tool highlights maintainability and clarity signals, not a ranking score.",
    faqs: [
      { question: "Are shorter URLs always better?", answer: "No. Clarity and stability matter more than forcing every URL to be minimal." },
      { question: "Should URLs contain keywords?", answer: "Descriptive words can help users understand the page, but stuffing variants into the slug is unnecessary." },
      { question: "Are underscores bad?", answer: "Hyphens are the conventional word separator for readable web URLs. Existing underscore URLs do not always justify migration by themselves." },
      { question: "How many folders are too many?", answer: "There is no fixed SEO limit. Use a path depth that reflects a sensible site structure." },
      { question: "Should tracking parameters be canonicalized?", answer: "Often yes when they do not change core content, but parameter strategy depends on how the site uses each value." },
    ],
  },
};

/**
 * For tools whose editorial copy lives in later category files, provide a safe
 * fallback only during development. Production pages should have an explicit
 * entry before they are considered editorially complete.
 */
export function getToolEditorial(tool: SeoToolDefinition): ToolEditorial | null {
  return E[tool.slug] ?? null;
}

export const TECHNICAL_TOOL_EDITORIAL = E;
