import type { ToolEditorial } from "@/lib/seo-tools/content";

export const SOCIAL_TOOL_EDITORIAL: Record<string, ToolEditorial> = {
  "og-tag-checker": {
    definition: "An Open Graph Tag Checker reads the Open Graph metadata declared by a webpage and presents the values that social platforms may use when someone shares the URL. The key fields are usually `og:title`, `og:description`, `og:image` and `og:url`, but the practical goal is not to maximize tag count; it is to make sure the shared preview represents the page accurately.",
    whyItMatters: "A technically healthy article can still look poor when shared if the image is missing, the title is stale or the description comes from the wrong template. Social previews influence whether people recognize and trust a link, especially when content is distributed through messaging apps, social networks or internal team channels.",
    howToUse: ["Enter the public page URL.", "Run the check and review the detected Open Graph fields.", "Compare the title and description with the current page content.", "Open the image URL manually and confirm it is public, stable and visually appropriate.", "Use platform-specific debuggers when you need to refresh a cached social preview."],
    interpretation: ["`og:title` is the social-sharing title candidate.", "`og:description` provides summary copy for platforms that use it.", "`og:image` should point to an accessible representative image.", "`og:url` should normally reflect the canonical public URL rather than a tracking or preview address."],
    commonProblems: ["Old brand image remains after a redesign.", "Relative image URL is rendered instead of an absolute URL.", "Every page inherits the homepage social title.", "Open Graph URL disagrees with canonical metadata.", "Image is blocked by authentication, robots or hotlink protection."],
    fixes: ["Generate social metadata from the same page record that supplies title and canonical URL.", "Use stable absolute image URLs.", "Replace template fallbacks that erase page-specific titles.", "Purge platform caches after correcting important shared pages."],
    bestPractices: ["Write social titles for recognition and clarity rather than keyword density.", "Choose images that remain legible when cropped.", "Keep canonical and Open Graph URLs aligned when they represent the same page.", "Test representative templates after CMS or framework changes."],
    example: "A technical guide about redirect chains should share with a title and image related to that guide, not the generic homepage card. If `og:url` points to a staging host, social platforms can cache the wrong identity even while the visible page works normally.",
    limitations: "The checker reports metadata from the current HTML response. Social platforms can cache older values or apply their own formatting and image-cropping rules.",
    faqs: [
      { question: "Do Open Graph tags affect Google rankings?", answer: "They primarily control social sharing metadata rather than standard search rankings." },
      { question: "What size should og:image be?", answer: "Platforms publish their own recommendations and can change them. Use a high-quality landscape image that remains clear when cropped." },
      { question: "Can og:title differ from the SEO title?", answer: "Yes. It can be adapted for social sharing as long as it still accurately represents the page." },
      { question: "Why does Facebook show an old image?", answer: "Social platforms cache preview data. Use their debugging or rescraping tools after fixing the page." },
      { question: "Is og:url required?", answer: "It is commonly used to identify the preferred shared URL, but the overall implementation should remain consistent with canonical metadata." },
    ],
  },
  "twitter-card-checker": {
    definition: "A Twitter/X Card Checker inspects metadata such as `twitter:card`, `twitter:title`, `twitter:description` and `twitter:image`. These fields describe how a shared URL may be presented on X and compatible consumers, although the platform can apply its own rendering, caching and fallback behavior.",
    whyItMatters: "Sites frequently configure Open Graph metadata but forget the Twitter/X layer, leaving old handles, missing card types or broken image URLs. A dedicated check makes those differences visible rather than assuming one platform will always reuse Open Graph fields exactly as expected.",
    howToUse: ["Enter the page URL.", "Review the card type and text fields.", "Check the image URL directly.", "Compare Twitter/X metadata with Open Graph data for consistency where appropriate.", "Update cached previews through platform tools when the live page is correct but sharing still looks outdated."],
    interpretation: ["`twitter:card` describes the presentation type, such as summary or summary_large_image.", "Title and description should identify the page clearly.", "Image should be accessible without login or temporary signed URLs.", "Missing Twitter-specific fields can sometimes fall back to Open Graph, but explicit metadata gives you clearer control."],
    commonProblems: ["twitter:site references an account the brand no longer controls.", "Card type expects an image but the image URL is empty.", "Metadata is copied from another template.", "Image CDN blocks social crawlers.", "Preview title contains internal campaign labels."],
    fixes: ["Remove stale account references.", "Use stable public image assets.", "Generate page-specific titles and descriptions.", "Test sharing from the production hostname rather than preview deployments."],
    bestPractices: ["Keep metadata factual and concise.", "Use the large-image card only when you have an appropriate image.", "Avoid embedding tracking parameters in the declared page URL.", "Review metadata after brand or social-account changes."],
    example: "A blog article can use `summary_large_image` with a real editorial hero image. If the image is a temporary Vercel preview asset that expires, the card will become unreliable even though the metadata syntax remains valid.",
    limitations: "This tool checks declared metadata, not the platform's live cache. X can change card rendering or fallback behavior independently of your HTML.",
    faqs: [
      { question: "What is summary_large_image?", answer: "It is a card type designed to feature a large image alongside the page's title and description." },
      { question: "Can Twitter/X use Open Graph tags?", answer: "Platforms may use fallbacks, but dedicated Twitter/X fields provide clearer intent." },
      { question: "Do I need twitter:site?", answer: "No. Add it only if it accurately represents an official account you want associated with the page." },
      { question: "Why is my image missing?", answer: "The URL may be inaccessible, cached incorrectly, use an unsupported response or be blocked by the CDN." },
      { question: "Does card metadata affect indexing?", answer: "It is mainly for sharing presentation rather than ordinary search indexing." },
    ],
  },
  "meta-robots-generator": {
    definition: "A Meta Robots Generator creates the HTML meta element used to communicate page-level crawler directives such as index, noindex, follow, nofollow and supported snippet controls. The important part is choosing a policy that matches the page purpose before generating the syntax.",
    whyItMatters: "Robots directives are frequently added through checkboxes and plugins, which can hide the actual HTML from editors. A generator makes the resulting tag explicit and helps teams discuss what the directive means before they paste it into a template.",
    howToUse: ["Decide whether the page should be eligible for indexing.", "Decide whether crawler link-following behavior needs an explicit directive.", "Add optional supported preview controls only when you understand their effect.", "Generate the tag and place it in the page head.", "Verify the live output with the Meta Robots Checker and confirm no X-Robots-Tag header conflicts."],
    interpretation: ["`noindex` is an explicit request not to index the page.", "`index` is often unnecessary because indexing eligibility is the default when no restrictive directive exists.", "`nofollow` applies to links discovered on the page, not whether the current page can be crawled.", "Snippet directives can limit how much text or imagery is shown in search previews."],
    commonProblems: ["Adding both index and noindex in different tags.", "Using noindex as a security mechanism for private pages.", "Applying nofollow to an entire site because a few sponsored links exist.", "Forgetting a temporary campaign noindex after the page becomes evergreen."],
    fixes: ["Keep one clear robots policy in the rendered head.", "Use authentication for private content.", "Qualify individual sponsored or UGC links at link level rather than using global page nofollow unnecessarily.", "Audit template defaults during launch QA."],
    bestPractices: ["Use noindex deliberately and document why a page is excluded.", "Keep staging and production robots policies separate.", "Retest after SEO plugin changes.", "Remember that robots.txt crawl blocking and meta robots indexing directives solve different problems."],
    example: "A post-checkout thank-you page may reasonably use `noindex, follow` because it should remain accessible to customers but has little value as a search result. A public product category page normally should not inherit that directive.",
    limitations: "The generator only formats the directives you choose. It does not determine the correct indexing strategy for your page or resolve conflicts added by HTTP headers.",
    faqs: [
      { question: "Do I need `index, follow` on normal pages?", answer: "No. Those are commonly default behaviors when restrictive directives are absent." },
      { question: "Can noindex protect confidential content?", answer: "No. Use real access controls or authentication." },
      { question: "What is the difference between nofollow and rel=nofollow?", answer: "Meta nofollow applies at page level; rel=nofollow qualifies an individual link." },
      { question: "Can I use noindex with a canonical?", answer: "You can technically output both, but the signals serve different purposes and contradictory strategies should be reviewed carefully." },
      { question: "Where does the meta robots tag go?", answer: "Inside the HTML head of the page." },
    ],
  },
  "seo-snippet-preview": {
    definition: "An SEO Search Snippet Preview places a title, URL and description into a search-style layout so editors can judge clarity before publishing. It is deliberately described as a preview rather than a simulator because real search engines can rewrite titles, choose different snippet text and vary layouts by query, device and feature set.",
    whyItMatters: "Metadata is often edited in plain CMS fields without seeing how the title and description read together. A preview makes repetition, weak wording and awkward truncation risk easier to spot before the page goes live.",
    howToUse: ["Enter the title you plan to publish.", "Enter the canonical page URL.", "Write a description that summarizes the page rather than repeating the title.", "Update the preview and read the result as a searcher would.", "Use the pixel tools for a rough width estimate, then prioritize clarity over squeezing text into an exact limit."],
    interpretation: ["The blue title area is a visual approximation, not a guaranteed displayed title link.", "The URL line helps you spot messy paths or tracking parameters.", "The description can be replaced by search engines with query-relevant page text.", "A preview that looks good still depends on the underlying page matching the promise."],
    commonProblems: ["Title and description repeat the same phrase twice.", "Brand boilerplate leaves little room for the page topic.", "Description contains unsupported claims or calls the tool 'best' without evidence.", "URL shown in the preview is a staging or parameterized address."],
    fixes: ["Lead with the clearest page topic.", "Use the description to add benefit, scope or context rather than duplicating the title.", "Remove promotional filler.", "Keep the preview URL aligned with the canonical production route."],
    bestPractices: ["Write metadata that accurately sets expectations.", "Consider the user's query and the page's real purpose.", "Treat length as a readability constraint rather than a ranking factor.", "Review actual search performance after indexing instead of assuming the preview predicts every query."],
    example: "A useful snippet for a Redirect Chain Checker can say that it reveals each HTTP hop and final destination. That tells the user what the tool does. A description such as 'Best free SEO tool for SEO experts and beginners' says almost nothing about the actual task.",
    limitations: "The preview cannot reproduce every font, SERP feature, device width or search-engine rewrite. It is an editorial aid, not a guaranteed rendering engine.",
    faqs: [
      { question: "Will Google display this exact snippet?", answer: "No guarantee. Google can rewrite both title links and description snippets." },
      { question: "Why preview the URL?", answer: "It helps catch staging hosts, tracking parameters or confusing paths before publication." },
      { question: "Does the description need keywords?", answer: "Use natural language that matches the page. Do not force repeated terms purely for density." },
      { question: "Can I use emojis in titles?", answer: "They may render inconsistently or be rewritten. Use them only when they suit the brand and content." },
      { question: "Should every title end with the brand?", answer: "Not necessarily. Branding can help recognition, but it should not overwhelm the page topic." },
    ],
  },
  "serp-title-pixel-checker": {
    definition: "A SERP Title Pixel Checker estimates how wide a title would render using browser canvas text measurement. Pixel width is more informative than character count because letters occupy different amounts of space, but it is still only an estimate: search engines can use different fonts, device widths and rewritten titles.",
    whyItMatters: "Two titles with the same number of characters can have very different visual widths. A title full of wide capital letters may consume much more space than one using narrow lowercase characters. Pixel measurement gives editors another way to identify titles that are likely to feel crowded.",
    howToUse: ["Paste the exact title text.", "Run the width estimate.", "Treat a wide result as a prompt to review the wording rather than a hard failure.", "Remove low-value boilerplate before cutting useful page terms.", "Use the snippet preview to read the title in context with the URL and description."],
    interpretation: ["The reported pixels come from a browser text-measurement approximation.", "A warning means the title is relatively wide compared with a common desktop working range.", "A passed width does not guarantee the title will be displayed unchanged.", "Search engines can rewrite title links even when the original fits comfortably."],
    commonProblems: ["Teams optimize to an exact pixel number and produce unnatural titles.", "Brand suffixes consume most of the available width.", "All-uppercase wording becomes wider and harder to scan.", "Titles are shortened so aggressively that the page topic becomes vague."],
    fixes: ["Remove duplicated words and promotional filler first.", "Keep the main entity or task easy to identify.", "Use concise brand treatment where branding is helpful.", "Accept that some long precise titles are better than vague short ones."],
    bestPractices: ["Use pixel width as one editorial signal.", "Prioritize accuracy and intent.", "Check mobile search appearance separately when it matters.", "Monitor real title rewrites in Search Console or SERP observation rather than relying only on pre-publication estimates."],
    example: "`XML Sitemap Validator - Check Sitemap Errors` may fit more comfortably than `The Best Completely Free Online XML Sitemap Validation Checker Tool`, while communicating the task more clearly at the same time.",
    limitations: "The tool does not use Google's private rendering system and cannot predict query-specific title rewrites, fonts or device layouts.",
    faqs: [
      { question: "What pixel width does Google allow?", answer: "There is no guaranteed fixed limit. Display width varies by device, font and result treatment." },
      { question: "Is pixel width better than character count?", answer: "It adds useful context because characters have different widths, but neither method predicts every SERP." },
      { question: "Will a wide title be penalized?", answer: "There is no simple width penalty. The practical issue is truncation, rewriting and clarity." },
      { question: "Why did Google rewrite a short title?", answer: "Title rewriting can happen for relevance or page-quality reasons unrelated to width." },
      { question: "Should I remove my brand to save pixels?", answer: "Only if the brand suffix adds less value than the page topic. Make the decision editorially." },
    ],
  },
  "meta-description-pixel-checker": {
    definition: "A Meta Description Pixel Checker estimates the visual width of description text using browser canvas measurement. It complements character count by showing that a line of narrow characters and a line of wide characters can occupy different space, while clearly acknowledging that search engines often rewrite snippets.",
    whyItMatters: "Editors sometimes chase a universal 155-character rule even though snippet layouts vary across devices and queries. Pixel estimation encourages a more realistic approach: write a useful description, then review whether it is excessively wide or repetitive.",
    howToUse: ["Paste the proposed meta description.", "Run the estimate.", "Review any width warning in the context of the actual message.", "Cut redundant phrases before removing important benefit or scope information.", "Preview the full search-style snippet to check title-description repetition."],
    interpretation: ["Pixel width is an approximation based on browser text metrics.", "A relatively narrow description can still be rewritten.", "A wide description may be shortened visually but can still contain useful source text.", "The best description communicates the page honestly rather than filling a target width."],
    commonProblems: ["Writing descriptions to an exact number and ending sentences awkwardly.", "Repeating the title phrase several times.", "Adding long lists of keywords.", "Trying to guarantee that Google uses the supplied description."],
    fixes: ["Rewrite for natural language first.", "Remove filler such as 'best', 'ultimate' and 'all-in-one' when unsupported.", "Put the most useful information earlier without making the sentence robotic.", "Accept search-engine rewriting as normal behavior."],
    bestPractices: ["Describe the page's actual task or answer.", "Use width estimates as an editing aid.", "Keep metadata synchronized with content changes.", "Evaluate click-through behavior with real search data after indexing."],
    example: "A description for an Hreflang Checker can explain that it checks language-region codes, duplicates and alternate URLs. That is more useful than padding the text with repeated 'international SEO tool' phrases to reach a target length.",
    limitations: "The estimate cannot reproduce every search-results layout. Search engines may generate a different snippet from page content regardless of the supplied description width.",
    faqs: [
      { question: "Is there a fixed meta description pixel limit?", answer: "No guaranteed universal limit exists because layouts and devices vary." },
      { question: "Why use pixels instead of characters?", answer: "Characters have different visual widths, so pixel estimates provide another editing perspective." },
      { question: "Can a long description hurt rankings?", answer: "There is no simple length penalty. The main concern is usefulness and how the snippet may be displayed or rewritten." },
      { question: "Does Google always use the meta description?", answer: "No. It often selects page text that better matches a particular query." },
      { question: "Should I put a CTA in the description?", answer: "A natural reason to visit can help, but avoid exaggerated or generic marketing language." },
    ],
  },
  "seo-page-analyzer": {
    definition: "An SEO Page Analyzer combines several observable on-page and technical signals into one report: HTTP response, title, meta description, canonical, robots directives, H1 count, link counts, image alt coverage and social metadata. It deliberately avoids an arbitrary 0-100 score because different findings carry different weight and depend on page intent.",
    whyItMatters: "Individual checkers are useful when you know the suspected problem. A consolidated analyzer is better for first-pass QA because it can reveal that a page has several small issues at once: a missing description, multiple H1s and an accidental noindex header, for example.",
    howToUse: ["Enter the exact public page URL.", "Review errors first, especially HTTP failures and noindex directives.", "Check warnings such as missing description, unusual H1 count or missing image alt attributes.", "Open technical details for canonical, robots and social metadata.", "Use the specialized tool linked from each topic when you need a deeper diagnosis."],
    interpretation: ["Passed means the specific transparent rule did not detect an issue; it is not a quality guarantee.", "Warning means the finding deserves human review rather than automatic correction.", "Error is reserved for stronger technical problems such as explicit noindex or failed response states.", "Information items provide context without claiming optimization value."],
    commonProblems: ["Teams fix easy metadata warnings while ignoring an actual noindex problem.", "SEO scores encourage chasing points instead of user value.", "One-page analysis is mistaken for a full technical crawl.", "Dynamic content loaded only after interaction is absent from server HTML.", "Page quality and search intent are reduced to checklist completion."],
    fixes: ["Prioritize exclusion and response issues before editorial refinements.", "Use the relevant specialist checker for canonical, heading, image or link problems.", "Test representative page templates after fixes.", "Combine tool output with Search Console, analytics, crawl data and human content review."],
    bestPractices: ["Use consolidated analysis as triage, not a final verdict.", "Keep page intent central when interpreting warnings.", "Avoid changing correct content solely to satisfy generic thresholds.", "Run the check before and after major releases to catch regressions."],
    example: "If an article returns 200, has a strong title and clean H1 but also carries `X-Robots-Tag: noindex`, the noindex finding matters far more than whether the description is 10 characters shorter than a common guideline. A useful analyzer should make that distinction visible rather than average everything into 87/100.",
    limitations: "The analyzer sees the current public response from one URL. It does not measure rankings, backlinks, search volume, Core Web Vitals, actual index status or full-site architecture, and it does not pretend those data exist when they are unavailable.",
    faqs: [
      { question: "Why is there no SEO score?", answer: "A single score hides context and encourages arbitrary weighting. This tool reports transparent checks instead." },
      { question: "Can it tell whether Google indexed my page?", answer: "No. It reports indexability signals, not Google's private index state." },
      { question: "Does it check backlinks?", answer: "No. Backlink data requires an external data source and is outside this page-level analyzer." },
      { question: "Can it replace a full site crawl?", answer: "No. It analyzes one supplied URL at a time and is best used for page-level QA." },
      { question: "What should I fix first?", answer: "Start with failed responses, accidental noindex and major canonical problems, then move to structural and editorial warnings." },
      { question: "Does a passed report guarantee rankings?", answer: "No. Technical correctness is only one part of search performance." },
    ],
  },
};
