import type { Metadata } from "next";
import { ScoutPanel } from "@/components/marketing/ScoutPanel";
import { PageHero } from "@/components/site/PageHero";
import { Icon } from "@/components/ui/Icon";
import { Reveal } from "@/components/ui/motion";
import { Button, SectionHeading } from "@/components/ui/primitives";

export const metadata: Metadata = {
  alternates: { canonical: "/tools/link-gap-scout" },
  title: "Link Gap Scout Demo",
  description:
    "Explore a representative backlink-gap workflow using demonstration figures. Results are illustrative and are not live SEO measurements.",
  robots: { index: false, follow: true },
  openGraph: {
    title: "Link Gap Scout Demo | Linkslo",
    description:
      "Explore a representative backlink-gap workflow using demonstration figures rather than live SEO measurements.",
    type: "website",
  },
};

const STEPS = [
  {
    icon: "globe" as const,
    title: "Enter a domain and keyword",
    body: "The public demo uses your inputs to illustrate how a backlink-gap workflow can be structured.",
  },
  {
    icon: "target" as const,
    title: "Review an illustrative gap",
    body: "Representative competitor and referring-domain figures show the type of comparison a live analysis would require.",
  },
  {
    icon: "link" as const,
    title: "Move to real marketplace research",
    body: "Use the marketplace and service pages to compare actual listed packages, markets, prices and delivery details.",
  },
];

export default function LinkGapScoutPage() {
  return (
    <>
      <PageHero
        eyebrow="Demonstration tool"
        eyebrowIcon="compass"
        breadcrumbs={[{ label: "Home", href: "/" }, { label: "Link Gap Scout Demo" }]}
        title="Link Gap Scout"
        description="A demonstration of the questions a backlink-gap review can help organise. Figures shown by the public tool are representative rather than live third-party SEO measurements."
      />

      <section className="bg-canvas py-12 sm:py-16">
        <div className="container-x">
          <ScoutPanel />

          <div className="mt-6 rounded-xl border border-line bg-white p-4 text-[0.84rem] leading-relaxed text-ink-500">
            <strong className="text-ink-900">Demo notice:</strong> values generated by this public tool are illustrative. Validate real competitors, referring domains, traffic and authority metrics with current data before making campaign decisions.
          </div>

          <div className="mt-12 grid gap-5 sm:grid-cols-3">
            {STEPS.map((step, index) => (
              <Reveal key={step.title} delay={index * 80}>
                <div className="card-hover h-full rounded-2xl border border-line bg-white p-6">
                  <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-700">
                    <Icon name={step.icon} size={19} />
                  </span>
                  <p className="mt-4 font-display text-[1.02rem] font-semibold text-ink-950">
                    {step.title}
                  </p>
                  <p className="mt-2 text-[0.87rem] leading-relaxed text-ink-500">{step.body}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      <section className="border-t border-line bg-white py-20 sm:py-24">
        <div className="container-x grid gap-10 lg:grid-cols-2 lg:gap-16">
          <Reveal>
            <SectionHeading
              eyebrow="Planning framework"
              eyebrowIcon="shield"
              title="What a real backlink-gap review should check"
              description="A useful gap analysis needs live competitive data plus context about the target page, search intent and realistic publisher availability."
            />
            <ul className="mt-7 space-y-4">
              {[
                { label: "Topical relevance", body: "How closely the target page and surrounding content match the subject where links are being sought." },
                { label: "Competitive link profile", body: "Current referring domains, link quality, placement types and how consistently competitors have earned links over time." },
                { label: "Authority and traffic context", body: "Third-party metrics can help compare domains, but should be checked alongside indexing, relevance and real traffic patterns." },
                { label: "Publisher feasibility", body: "Whether relevant websites and service options are actually available for the target market, niche and budget." },
              ].map((item) => (
                <li key={item.label} className="rounded-xl border border-line bg-canvas p-4">
                  <p className="text-[0.9rem] font-semibold text-ink-950">{item.label}</p>
                  <p className="mt-1 text-[0.85rem] leading-relaxed text-ink-500">{item.body}</p>
                </li>
              ))}
            </ul>
          </Reveal>

          <Reveal delay={120}>
            <div className="rounded-2xl border border-line bg-canvas p-7">
              <h2 className="font-display text-[1.2rem] font-semibold text-ink-950">
                Need a campaign recommendation?
              </h2>
              <p className="mt-3 text-[0.92rem] leading-relaxed text-ink-500">
                Share your target page, market and campaign constraints. Linkslo can help narrow the relevant service type and marketplace options without treating the demo figures above as live measurements.
              </p>
              <ul className="mt-6 space-y-3">
                {[
                  "Target-page and anchor requirements",
                  "Relevant service and market options",
                  "Package scope and delivery comparison",
                  "Publisher availability confirmation where applicable",
                ].map((item) => (
                  <li key={item} className="flex gap-2.5 text-[0.88rem] text-ink-600">
                    <Icon name="check" size={17} className="mt-0.5 shrink-0 text-brand-600" />
                    {item}
                  </li>
                ))}
              </ul>
              <div className="mt-7 flex flex-wrap gap-3">
                <Button href="/marketplace" icon="arrow-right">Browse marketplace</Button>
                <Button href="/contact" variant="outline">Discuss a brief</Button>
              </div>
            </div>
          </Reveal>
        </div>
      </section>
    </>
  );
}
